app/services/geographical_area_memberships_import_service.rb
app/services/geographical_areas_import_service.rb
db/migrate/20210108162807_add_hjid_to_geographical_areas_oplog.rb
db/migrate/20210108163822_add_hjid_to_geographical_area_memberships_oplog.rb
db/migrate/20210108165416_add_hjid_to_geographical_areas_view.rb
db/migrate/20210108170325_add_hjid_to_geographical_area_memberships_view.rb
db/migrate/20210112135615_add_new_fields_to_geographical_area_memberships_oplog.rb
db/migrate/20210112160504_add_fields_to_geographical_area_memberships_view.rb
db/structure.sql
lib/cds_importer/entity_mapper.rb
lib/cds_importer/entity_mapper/geographical_area_mapper.rb
lib/cds_importer/entity_mapper/geographical_area_membership_mapper.rb
lib/tasks/data_import/import_hjid_to_geographical_area_memberships.rake
lib/tasks/data_import/import_hjid_to_geographical_areas.rake
spec/fixtures/files/hjid_member_map.csv
spec/fixtures/files/hjid_to_sid_map.csv
spec/integration/cds_importer/entity_mapper_spec.rb
spec/integration/cds_importer/entity_mappers_spec.rb
spec/services/geographical_area_import_service_spec.rb
spec/services/geographical_area_memberships_import_service_spec.rb

HOTT-274
HOTT-277
HOTT-335
I have:
a) geographicalAreaGroupSid key points to sid value in the node,
instead of the child member hjid (as it is now)
b) it adds a new geographicalAreaSid key that points to the
geographical_area_sid which is retrieved from Geographical Areas
table, using the hjid as lookup key.
Details behind the changes can be found at:
- https://transformuk.atlassian.net/browse/HOTT-274
- https://transformuk.atlassian.net/browse/HOTT-277
- https://transformuk.atlassian.net/browse/HOTT-335
- Contains migrations that drop and recreate some views

Add required hjid field to the db, create the data importers and add the data transform step for CDS importer

---

.github/workflows/deploy_dev.yml
.github/workflows/deploy_production.yml
.github/workflows/deploy_staging.yml

n/A
- We re-imported the repos, and workflows need to be repushed to be picked up.

Repush workflows following repo import

---

app/models/goods_nomenclature.rb
spec/models/goods_nomenclature_spec.rb

HOTT-268
Replace the existing dynamic bti_url value with a
static as a result of Brexit.
The existing bti_url value no longer serves the purpose of post Brexit.

Update the bti_url value for API V1 & V2

---

lib/tariff_synchronizer/file_service.rb

HOTT-NA
Files should be looked for inside the S3 bucket on production.
If we want to enable the CDS flag, without this change the importer would never check the S3 bucket, where the increments are being downloaded.

Remove useless blocking condition

---

Gemfile
Gemfile.lock

HOTT-<TODO>
Add newrelic gem for APM monitoring.
Ability to debug easier and track performance spikes.

Add newrelic gem for monitoring

---

Gemfile
app/controllers/application_controller.rb
config/environments/production.rb

HOTT-<TODO>
- This is noisy and distracting

Removes noisy output from scout in dev/test

---

config/sidekiq.yml

HOTT-<TODO>
Change the time the CDS importer runs.
We want to make sure the importer runs after HMRC has
produced their CDS/CHEIF/TARIC files.

Update CDS importer scheduler

---

.rubocop.yml
app/services/geographical_area_memberships_import_service.rb
app/services/geographical_areas_import_service.rb
spec/services/geographical_area_import_service_spec.rb
spec/services/geographical_area_memberships_import_service_spec.rb

HOTT-<TODO>
- It's frustrating getting all of this distracting output in the tests

Fix more test noise

---

app/models/concerns/clearable.rb
spec/models/concerns/clearable_spec.rb
spec/rails_helper.rb

https://transformuk.atlassian.net/browse/HOTT-359
If a client of a model wants to clear the association cache there is
currently no public api that enables this behaviour.
We typically want to clear it in the tests because we run the same
queries (at least as they appear to Sequel) multiple times and expect different results to be returned from the cache.
This has been specifically highlighted in the tests around the
TimeMachine which doesn't update the cache key and therefore looks like
the same query.
We can get around this by adding behaviour to Sequel::Model classes
which clears the cache after every example and by making sure that we
don't have multiple TimeMachine expectations in the same example (see
subsequent commit for this change).
- Our TimeMachine …

[HOTT-359] Adds Clearable concern to all Sequel::Model classes

---

spec/models/additional_code_spec.rb
spec/models/certificate_spec.rb
spec/models/export_refund_nomenclature_spec.rb
spec/models/footnote_spec.rb
spec/models/geographical_area_spec.rb
spec/models/goods_nomenclature_spec.rb
spec/models/measure_spec.rb
spec/rails_helper.rb
spec/support/shared_examples/association_shared_examples.rb

https://transformuk.atlassian.net/browse/HOTT-359
These tests duplicate a test of the same behaviour.
These tests were leading to the false assumption that we needed to disable the benefits of eager loading/caching associations and forcibly reload all subsequent associations - causing a significantly diminished performance of our apis (760 queries instead of a normal 60).
What's actually happening is the cache inside of each of the AssociationReflection classes that are pegged to each model didn't recognise TimeMachine filters as needing to create a unique key.
I suspect we could rework the TimeMachine in future so this was enabled - I'd need to investigate this.

[HOTT-359] Remove misleading duplicate tests

---

app/models/goods_nomenclature_description.rb
spec/models/goods_nomenclature_description_spec.rb

https://transformuk.atlassian.net/browse/HOTT-281
- The data is broken slightly in production

[HOTT-281] Fixes chained <br> tags in GoodsNomenclatureDescription

---

lib/cds_importer/entity_mapper.rb
lib/sequel/plugins/oplog.rb
spec/integration/cds_importer/entity_mapper_spec.rb

HOTT-416
- when we have Measures coming through, we delete all
corresponding geographical areas exclusions
- if the XML increment file contains any exclusions they
will be recreated
CDS no longer sends exclusions with operation type D, instead, the records will be completely missing.

Adjust ETL logic as follows

---

app/controllers/api/v2/commodities_controller.rb
app/services/chemical_search_service.rb
app/services/heading_service/heading_serialization_service.rb
app/workers/clear_cache_worker.rb
config/sidekiq.yml
lib/trade_tariff_backend.rb

HOTT-<TODO>
- We invalidate the redis cache on a schedule way before this time so this is completely redundant.
- The logic and naming of this method were just wrong, too.
- The combination of performance enhancements and the fact that these caches get invalidated every night anyway diminish the risk around this change

Force ttl of headings, chemical search and commodities to 24 hours

---

.rubocop.yml
app/views/tariff_synchronizer/mailer/applied.html.erb
lib/cds_importer/entity_mapper.rb
lib/tariff_synchronizer.rb
lib/tariff_synchronizer/logger.rb
lib/tariff_synchronizer/mailer.rb
spec/integration/cds_importer/entity_mapper_spec.rb
spec/unit/tariff_synchronizer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-351
- We want to have some way of knowing when we've skipped a transform or
exclusion clobbering due to missing references.
- This should be super rare but we want to know about it because it could
indicate data issues upstream

[HOTT-351] Warn on guard clauses in cds importer flow

---

app/controllers/application_controller.rb
lib/trade_tariff_backend.rb
spec/rails_helper.rb

https://transformuk.atlassian.net/browse/HOTT-426
We know that association queries get cached and don't recognise that the
time machine should represent a change in the stored query.
Weirdly this affects only a subset of models that are invoked with the
TimeMachine.
I'd need to further dig into the specifics to understand why this is but
I know for a fact that the class level cache needs invalidating when we
want to change the actual date.
It's important to know that data gets stored in lexical scope under an
instance of a Sequel query result not in the class cache that we're
clearing here. What we're clearing is explicitly the query itself which
is reused between runs to (I suspect) save Sequel a smidge of time in
generating the output SQL as driven by …

[HOTT-426] Clears association cache on all known problem models before a request

---

app/serializers/api/v2/measures/measure_component_serializer.rb
spec/serializers/api/v2/measure_component_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-422
- This is needed for the measurement unit work as part of the duty calculator app

[HOTT-422] Adds measurement_unit_qualifier_code to the V2 MeasureComponentSerializer

---

app/controllers/api/v2/geographical_areas_controller.rb
spec/controllers/api/v2/geographical_areas_controller_spec.rb

https://transformuk.atlassian.net/browse/HOTT-477
- We want to know the members of the European Union in the Duty Calculator and this is currently not possible

[HOTT-477] Surface contained geographical areas

---

app/models/measure.rb
app/models/measure_component.rb
app/models/measure_type.rb
app/presenters/api/v2/commodities/commodity_presenter.rb
app/serializers/api/v2/commodities/commodity_serializer.rb
spec/controllers/api/v2/commodities_controller_spec.rb
spec/factories/measure_factory.rb
spec/models/measure_spec.rb
spec/models/measure_type_spec.rb
spec/services/cached_commodity_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-356
- We need this question answered for the duty calculator flow

[HOTT-356] Decorate zero duties for third countries on commodity response

---

app/models/measure.rb
app/models/measure_type.rb
app/presenters/api/v2/commodities/commodity_presenter.rb
app/serializers/api/v2/commodities/commodity_serializer.rb
spec/models/measure_type_spec.rb

https://transformuk.atlassian.net/browse/HOTT-355
- This is needed to make decisions in the duty calculator

[HOTT-355] Surface trade remedies in commodity response meta

---

app/models/duty_expression.rb
app/models/duty_expression_description.rb
app/models/measure.rb
app/models/measure_component.rb
app/models/measure_condition.rb
app/models/measure_condition_component.rb
app/models/measure_type.rb
app/models/measurement_unit.rb
app/presenters/api/v2/commodities/commodity_presenter.rb
app/serializers/api/v2/commodities/commodity_serializer.rb
app/services/measure_unit_service.rb
db/measurement_units.json
spec/factories/measure_component_factory.rb
spec/factories/measure_factory.rb
spec/models/measure_component_spec.rb
spec/models/measure_condition_component_spec.rb
spec/models/measure_spec.rb
spec/models/measure_type_spec.rb
spec/services/measure_unit_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-410
- In order to more simply iterate through a given set of measure units and present them as simplified components in the duty calculator
- To make it possible for any user of the api to be able to use this information

[HOTT-410] Surface measurement units for the duty calculator

---

app/controllers/api/v2/exchange_rates_controller.rb
app/models/exchange_rate.rb
app/serializers/api/v2/exchange_rate_serializer.rb
app/services/exchange_rate_service.rb
config/routes.rb
lib/trade_tariff_backend.rb
spec/controllers/api/v2/exchange_rates_controller_spec.rb
spec/factories/exchange_rate_factory.rb
spec/rails_helper.rb
spec/serializers/api/v2/exchange_rate_serializer_spec.rb
spec/services/exchange_rate_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-463
- This is needed for the duty calculator and (we expect) other things in the backend.
- Must be encapsulated and portable
- Must refresh when the api data refreshes

[HOTT-463] Surface exchange rates for the duty calculator

---

.circleci/config.yml
app/controllers/api/v2/geographical_areas_controller.rb
spec/controllers/api/v2/geographical_areas_controller_spec.rb

HOTT-<TODO>
- There are quite a few geographical areas and fetching/serializing them over the wire is quite slow.

Cache geographical areas for 24 hours

---

app/controllers/api/v2/geographical_areas_controller.rb
app/services/cached_commodity_service.rb
app/services/cached_geographical_area_service.rb
spec/controllers/api/v2/geographical_areas_controller_spec.rb
spec/services/cached_geographical_area_service_spec.rb

HOTT-<TODO>
- These areas aren't needed in each of these services.
- This avoids duplication in both of our frontends

Exclude geographical areas by service

---

Gemfile.lock

HOTT-<TODO>
- The existing version has been yanked. Whole explanation here:
https://www.altusintel.com/public-yy2r88/
https://github.com/mimemagicrb/mimemagic/commit/c0f7b6b21a192629839db87612794d08f9ff7e88
- Other gov projects have opted out from mimemagic - it has licensing issues:
https://ukgovernmentdfe.slack.com/archives/CAGBHB4JV/p1616668662022200
Rationale for rails dep changes here: rails/rails#41750 (comment)
Relevant govuk-component changes: DFE-Digital/govuk-components#124
However, we explicitly need this in our importers (CDS importer):
```ruby
def import
handler = XmlProcessor.new(@cds_update.filename)
gzip_file = TariffSynchronizer::FileService.file_as_stringio(@cds_update)
if MimeMagic.by_magic(gzip_file).subtype == 'gzip'
xml_stream = …
```

Bump mimemagic

---

app/serializers/api/v2/exchange_rate_serializer.rb
spec/controllers/api/v2/exchange_rates_controller_spec.rb
spec/serializers/api/v2/exchange_rate_serializer_spec.rb

HOTT-<TODO>
- This is because the jsonapi parser relies on ids being in the attributes not in the id field :facepalm:

Adds id to attributes

---

app/controllers/api/v2/exchange_rates_controller.rb
spec/controllers/api/v2/exchange_rates_controller_spec.rb

HOTT-<TODO>
- Removes an additional layer of caching that really isn't needed

Set Cache-Control to no-cache in ExchangeRateController

---

app/models/duty_expression.rb
app/models/measure_component.rb
app/models/measure_condition_component.rb
spec/factories/measure_component_factory.rb

HOTT-<TODO>
- We only care about the id for sequencing duty expressions that we need to evaluate

Ignore duty expression ids for ad valorem

---

app/services/cached_geographical_area_service.rb
spec/services/cached_geographical_area_service_spec.rb

HOTT-<TODO>
- There are some places you just won't import from and that aren't useful in both the frontend and the duty calculator

Extend list of globally-excluded geographical area ids

---

.circleci/config.yml

n/a
- We don't want the request to go in and out via the public internet (and CDN)

Allow duty-calculator to reach backend internal endpoint

---

app/models/measure.rb
app/models/measure_condition.rb
app/models/measure_condition_code.rb
app/presenters/api/v2/commodities/commodity_presenter.rb
app/serializers/api/v2/commodities/commodity_serializer.rb
spec/controllers/api/v2/commodities_controller_spec.rb
spec/models/measure_condition_spec.rb

https://transformuk.atlassian.net/browse/HOTT-358
I'm ignoring the fact that we aren't interested in UK measure conditions
for now and short circuiting an iteration over the import measures in UK
commodities. This is because we plan to push for UK EPS measures in the
future
We also eager load all of the related resources and don't have issues with N+1 by iterating through the measure conditions
- This is needed for business logic in the Duty Calculator

Surface whether there are any entry price measures.

---

README.md

none
This PR adds a note in the `README.md` file regarding the required versions for PostgreSQL and ElasticSearch.
During a first setup of the application, I've been informed that the backend only works with PostgreSQL 10, and the error I was experiencing were due to the fact that I was using a more recent version.
Adding the information in the `README.md`  will hopefully make things easier for the next person that needs to set up the application.

Add a note about the PostgreSQL version in README

---

app/models/quota_blocking_period.rb
app/models/quota_definition.rb
app/models/quota_order_number.rb
app/models/quota_suspension_period.rb
app/serializers/api/v2/quotas/order_number/quota_definition_serializer.rb
app/serializers/api/v2/quotas/order_number/quota_order_number_serializer.rb
spec/models/quota_order_number_spec.rb

https://transformuk.atlassian.net/browse/HOTT-428
- The ID currently surfaced for quota definitions is in fact the `quota_order_number_sid`. 
This makes some sense as the above is the join key, but the correct ID for quota definition is in fact the `quota_definition_sid`
- This changes the ID used to link the order number with the definition in the JSON API. 
This doesn't seem to be breaking the frontend as the ID is changed consistently, but a thorough test is still required.

Hott 428 - change displayed id for quota definitions

---

app/services/applicable_additional_code_service.rb
spec/factories/measure_factory.rb
spec/services/applicable_additional_code_service_spec.rb

HOTT-<TODO>
- This is needed for richer information in the duty calculator

Adds measure type descriptions to the applicable additional codes

---

app/controllers/api/v2/goods_nomenclatures_controller.rb

HOTT-<TODO>
- /goods_nomenclatures/chapter/:chapter_id
- /goods_nomenclatures/heading/:heading_id
- Remove the DoS attack risk
Used https://www.diffchecker.com/diff to compare the JSON responses before and after and they match perfectly.

Fix brakeman HIGH level violations

---

lib/trade_tariff_backend.rb

HOTT-<TODO>
- We think this might cause some issues when returning certificate descriptions

Clear CertificateDescription and CertificateDescriptionPeriods

---

.circleci/config.yml
.rubocop.yml
app/controllers/api/api_controller.rb
app/controllers/api/v2/quotas_controller.rb
app/controllers/application_controller.rb
app/models/quota_balance_event.rb
app/models/quota_definition.rb
app/models/quota_event.rb
app/serializers/api/v2/quotas/definition/quota_balance_event_serializer.rb
app/serializers/api/v2/quotas/definition/quota_definition_serializer.rb
app/services/quota_search_service.rb
config/brakeman.ignore
spec/controllers/api/v2/quotas_controller_spec.rb
spec/factories/quota_factory.rb
spec/models/quota_balance_event_spec.rb
spec/models/quota_definition_spec.rb
spec/serializers/api/v2/quotas/definition/quota_balance_event_serializer_spec.rb
spec/serializers/api/v2/quotas/definition/quota_definition_serializer_spec.rb
spec/services/quota_search_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-716
Mainly this PR enables calls to fetch quota balance events with:
```
GET /api/v2/quotas/search?order_number=058063&include=quota_balance_events,measures,measures.geographical_area_id
```
This doesn't affect the existing functionality in any way but does make
some optimisations to what queries get executed based on what's being
passed to the api endpoint.
Some other things that are happening in this PR are:
- Move to lazy loading quota definition relationships (only load them if
they're specified)
- Enable people to specify the includes in the quotas controller
- Default to the original includes that are required so we don't affect
existing functionality
- Surface quota balance events and add corresponding serializer and
specs on a quota …

Surface quota balance events

---

.circleci/config.yml
app/controllers/healthcheck_controller.rb
config/initializers/revision.rb
config/initializers/sha.rb

https://transformuk.atlassian.net/browse/HOTT-717
- We use this to debug
```shell
cf ssh tariff-xi-backend-dev  -t -c "/tmp/lifecycle/launcher /home/vcap/app 'curl http://localhost:8080/healthcheck' ''"
{"git_sha1":"539635e0"}
```

Reenable current git revision healthcheck

---

lib/tariff_synchronizer.rb
spec/integration/tariff_synchronizer_spec.rb
spec/unit/tariff_synchronizer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-740
CHIEF endpoints return Excise and VAT measures and related resources in CSV format. We ETL these into the database via thei ChiefUpdate mechanism. This PR disables CHIEF ETL
- The measures a related resources created by this ETL process are no longer used - UK measures are the source of truth for VAT/Excise duties

Disable chief synchronizer

---

app/serializers/api/v2/commodities/commodity_serializer.rb
app/serializers/api/v2/measures/measure_serializer.rb
spec/controllers/api/v2/commodities_controller_spec.rb
spec/serializers/api/v2/commodities/commodity_serializer_spec.rb
spec/serializers/api/v2/measures/measure_serializer_spec.rb
spec/services/cached_commodity_service_spec.rb

HOTT-<TODO>
- These are needed for the duty calculator
**XI**
**UK**

Surface the source of the commodity and measure resources

---

.circleci/config.yml
app/presenters/api/v2/commodities/commodity_presenter.rb
spec/factories/goods_nomenclature_factory.rb
spec/presenters/api/v2/commodities/commodity_presenter_spec.rb

https://transformuk.atlassian.net/browse/HOTT-784
In the situation where we have multiple third country duties with additional codes (e.g. covid-related commodities) we want the backend to flag the commodity as having a non-zero amount on the third country duty if and only if _all_ the third country duties have components that are 0.
- We need to make sure we're returning true only when all the mfn measures are zero in the xi service for the duty calculator

Make sure all MFN measures are zero duty

---

app/controllers/api/v2/quotas_controller.rb
app/models/measure.rb
app/services/quota_search_service.rb
spec/services/quota_search_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-689
actual_date that is used around the action
the time machine - this is more idiomatic with the rest of the
application - this may break integrations (but we believe we're the
only ones using this. We need to investigate api usage to see before
we go live with this change.
- Remove duplication
- Fix naming of contexts and examples
- Use subject and filter with lets properly
- Remove redundant specs (especially of day, month, year and years
filtering)
- Tests necessary and sufficient behaviour
validity_start_date (this is an overlap with the TimeMachine
functionality and excludes the wrong records). These start dates are
handled by different processes and needed removing
- The service …

Refactor quota search service

---

app/serializers/api/v2/measures/measure_serializer.rb
spec/factories/measure_factory.rb
spec/serializers/api/v2/measures/measure_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-781
I am doing this because it's required in order to properly calculate Meursing duties on the commodity code page

HOTT-781: Add reduction indicator to the commodities API

---

app/controllers/api/v1/chapters/chapter_notes_controller.rb

https://transformuk.atlassian.net/browse/HOTT-844
I am doing this because of this error:
https://sentry.io/organizations/engine-le/issues/2515546107/?project=5557005
In this specific case (chapter "732"), the chapter itself doesn't exist, so when trying to fetch the chapter note, the controller used to throw an exception instead of answering with a more reasonable 404 - not found.

HOTT-844: 

---

app/models/additional_code.rb
app/services/applicable_additional_code_service.rb
spec/models/additional_code_spec.rb
spec/services/applicable_additional_code_service_spec.rb

HOTT-<TODO>
We have plumbed together a list of applicable additional codes via the ApplicableAdditionalCodeService that we use to enumerate the additional codes the trader might select for a given measure type id. This has a filtering effect on the measures with additional codes that match the trader's answer in the duty calculation.
This PR extends this functionality to also return the excise type of additional codes so we can plumb together a step for excise.
- We need to extend the list of the additional code types we return so we can build the additional code step for excise.

Adds excise type to the applicable additional codes

---

db/additional_codes.json

https://transformuk.atlassian.net/browse/HOTT-832
- The current descriptions that would automatically come back via the ApplicableAdditionalCodeService class isn't sufficient/doesn't look nice or make any sense

Adds excise overlays

---

app/models/measurement_unit.rb
app/services/measure_unit_service.rb
spec/models/measurement_unit_spec.rb

https://transformuk.atlassian.net/jira/software/projects/HOTT/boards/96?selectedIssue=HOTT-854
I have added a fallback for when a Measurement Unit is requested which is not listed in the YML:
- The commodities listed in ticket `HOTT-825` were triggering a key error because whilst they were valid and present in the database, they had no corresponding entries in the YML file of questions (`db/measurement_units.yml`)
- I've left the existing `#measurement_units` method public _but_ there are no consumers of this method now and it would make sense to make it private since that will force consumers down the path with fallback handling (ie `MeasurementUnit#measurement_unit`)

Hott 854 add fallback for missing measurement units

---

app/services/cached_commodity_service.rb
app/services/cached_geographical_area_service.rb
config/environments/development.rb

[HOTT-720](https://transformuk.atlassian.net/jira/software/projects/HOTT/boards/96?selectedIssue=HOTT-720)
- We were generating a lot of N+1 queries on the `/commodities/:id` endpoint on the frontend - this is a common end point and this code path will be used frequently

Hott 720 eager loading fixes

---

app/formatters/duty_expression_formatter.rb
app/formatters/requirement_duty_expression_formatter.rb
app/models/measure_component.rb
app/models/measure_condition_component.rb
lib/trade_tariff_backend.rb
spec/formatters/duty_expression_formatter_spec.rb

https://transformuk.atlassian.net/browse/HOTT-879
- The currency conversion feature isn't being used.
- The n + 1 inverse load was creating a ton of SQL queries that are slowing down calls to the commodity api

Fix n + 1 issue due to inverse load of measure via the measure condition

---

.circleci/config.yml
app/models/measure.rb
app/models/measure_condition.rb
app/models/measure_condition_component.rb
spec/factories/measure_condition_factory.rb
spec/factories/measure_factory.rb
spec/models/measure_condition_component_spec.rb
spec/models/measure_condition_spec.rb
spec/models/measure_type_spec.rb

HOTT-<TODO>
condition components
- This is needed when generating duty calculations against measure condition components

Handle units that belong to measure condition components

---

.rubocop.yml
app/presenters/api/v2/measures/measure_legal_act_presenter.rb
app/presenters/api/v2/measures/measure_presenter.rb
app/serializers/api/v2/measures/measure_legal_act_serializer.rb
lib/uk_regulation_parser.rb
spec/factories/base_regulation_factory.rb
spec/lib/uk_regulation_parser_spec.rb
spec/presenters/api/v2/measures/measure_legal_act_presenter_spec.rb
spec/presenters/api/v2/measures/measure_presenter_spec.rb
spec/serializers/api/v2/measures/measure_legal_act_serializer_spec.rb

[HOTT-866](https://transformuk.atlassian.net/jira/software/projects/HOTT/boards/96?selectedIssue=HOTT-866)
- Uk regulations after 01 Jan 2021 will be holding their regulation code, regulation url and description in a concatenated format inside of the `information_text` field instead of using the existing fields
This changes the format of the legal act API nodes in 3 ways
- for uk regulations after 01 Jan 2021 changes from the existing fields, to extracting regulation code/url/description from the information text
- it hides the code/url/description for all regulations with an id of `IYY99990` or measure type id of 305 or 306
- it adds a description attribute for all other regulations with the contents of the information text database …

HOTT-866 extend legal act node

---

app/workers/clear_cache_worker.rb
config/sidekiq.yml

https://transformuk.atlassian.net/browse/HOTT-889
- We only want to recache after a UpdateSynchronizerWorker has triggered but I felt that was too much of a change (affecting both sets of workers)
- This reduces the number of schedules we have to manage

Updates schedule and triggers reindexing of es models after clearing redis

---

Gemfile
Gemfile.lock
lib/cds_importer.rb

HOTT-<TODO>
- This was only required to magically handle/understand gzipped annual files. We never download these and can manually gunzip them if necessary by passing the correct flags
- mimemagic was requiring extra files to be provided as part of dockerising this application

Removes mimemagic

---

spec/factories/measure_factory.rb

???
Parts of the code special case behaviour depending upon the measure.measure_type_id. 
If an autogenerated id matches one of the ids expected by these special cases, then behaviour can change causing unexpected failures.
The sequence of the randomised tests will determine whether this failure occurs. This is reproduceable at commit e800e5d6 with seed 36099.

Fix some flaky tests

---

spec/rails_helper.rb

????
- This doesn't appear to be serving any purpose and slows down starting the test suite when testing individual specs - I assume its a fix for an old autoloading issue thats now resolved. I've run every spec individually and they all still pass.

Removed eager loading of models in specs

---

.circleci/config.yml
.github/dependabot.yml

???
- We can get automatic PRs for gem updates and this avoids gems becoming stale when developers are busy
- repo only change

Added dependabot config

---

.circleci/config.yml

HOTT-<TODO>
- We don't want to spam dev with deploys of dependabot upgrades

Fixes filter for stopping deploys on dependabot branches

---

app/models/measure_component.rb
app/models/measure_condition_component.rb
app/services/measure_unit_service.rb
spec/models/measure_condition_spec.rb
spec/models/measure_spec.rb
spec/services/measure_unit_service_spec.rb
spec/support/shared_examples/a_component.rb

HOTT-<TODO>
- These aren't needed anymore

Refactor the applicable_measure_units returned for the Duty Calculator

---

app/models/measurement_unit.rb
app/services/measure_unit_service.rb
spec/models/measurement_unit_spec.rb

HOTT-<TODO>
In the wild we retrieve the unit from the measure units file using the
code and the qualifier concatenated. This enables us to enrich the
descriptions a bit as they relate to the specific measure
component/measure condition component.
Our specific example `Factor` exists in the database but does not match
because it's code is FC1 and we were passing in the full key FC1X
```
"500 - Internal Server Error: Requested invalid measurement unit: FC1X"
```
There are only **18** measure condition components active in the database that have the unit key `FC1X`
code in fallback scenarios to exclude the qualifier
- This is needed for us to be able to present commodities with unsupported units

Handle extra qualifier in unit code key.

---

app/workers/taric_sequence_check_worker.rb
lib/tariff_synchronizer/taric_file_name_generator.rb
lib/tariff_synchronizer/taric_sequence_checker.rb
spec/rails_helper.rb
spec/unit/tariff_synchronizer/taric_sequence_checker_spec.rb
spec/workers/taric_sequence_check_worker_spec.rb

HOTT-<TODO>
- That this is happening was noticed because we failed to do a deploy when a queued worker was getting failed responses from the Taric api
- It seemed simple enough to just stop this from running

Handle generation of missing taric updates on the uk service

---

app/models/rules_of_origin/data_set.rb
app/models/rules_of_origin/explainer.rb
app/models/rules_of_origin/heading_mappings.rb
app/models/rules_of_origin/link.rb
app/models/rules_of_origin/query.rb
app/models/rules_of_origin/rule.rb
app/models/rules_of_origin/rule_set.rb
app/models/rules_of_origin/scheme.rb
config/initializers/rules_of_origin.rb
lib/trade_tariff_backend.rb
spec/factories/rules_of_origin/data_set_factory.rb
spec/factories/rules_of_origin/heading_mappings_factory.rb
spec/factories/rules_of_origin/link_factory.rb
spec/factories/rules_of_origin/rule_set_factory.rb
spec/factories/rules_of_origin/scheme_set_factory.rb
spec/models/rules_of_origin/data_set_spec.rb
spec/models/rules_of_origin/heading_mappings_spec.rb
spec/models/rules_of_origin/query_spec.rb
spec/models/rules_of_origin/rule_spec.rb
spec/models/rules_of_origin/scheme_spec.rb

[HOTT-868](https://transformuk.atlassian.net/browse/HOTT-868)
- We need a way to query our file based data so that we can return the Rules of Origin data in the API

HOTT-868 - Rules of origin queries

---

spec/serializers/api/v2/headings/declarable_heading_serializer_spec.rb

HOTT-???
- Deploys rely on passing specs

Fix for failing spec with hard coded date

---

app/models/hidden_goods_nomenclature.rb

This PR remove the cache for hidden_goods_nomenclature_codes,
which do no provide any valuable performance improvement (the number of entries are very low),
and is cause of a nasty bug that was hard to spot.
No ticket for this, but that is to prevent a bug spotted working on the HOTT-811
This PR remove the cache for hidden_goods_nomenclature_codes,
which do no provide any valuable performance improvement (the number of entries are very low),
and is cause of a nasty bug that was hard to spot.

Remove the cache for hidden_goods_nomenclature_codes

---

Gemfile
config/initializers/rack_timeout.rb

HOTT-<TODO>
No Jira ticket.
Disable rack-timeout in Dev environment, to allow to pry the BE server.
To simplify debugging in local dev env.

Disable rack-timeout in Dev environment

---

config/application.rb

Requires Env var setting - will only be set on DEV environment
[HOTT-943](https://transformuk.atlassian.net/browse/HOTT-943)
- the DEV environment flip flops between different branches so sometimes migration files will 'disappear' but we don't want this to prevent the `rake db:migrate` task from running

HOTT-943: Allow missing migration files

---

app/serializers/api/v2/measures/measure_serializer.rb
spec/serializers/api/v2/measures/measure_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-801
- This change means that other users of the serializer do not have to load the entire world of un-eager loaded resources just to return a subset of the targeted relationships.
- This will make the meursing index endpoints which serialize meursing measures as measures signficantly faster and should not affect existing implementations

Lazy load all measure v2 relationships

---

app/models/chapter.rb
app/models/goods_nomenclature.rb
app/services/find_ancestors_service.rb
app/services/quota_search_service.rb
spec/services/find_ancestors_service_spec.rb
spec/services/quota_search_service_spec.rb

This PR Fixes and extends the Search for quotas
The search is smarter now, it supports:
- Chapter
- Heading
- Commodity
using the ancestries,
otherwise - in case the term does not look one of those - it uses a ilike search.
To allow users to find easily quotas.
https://transformuk.atlassian.net/browse/HOTT-940

HOTT-940 Fix and extend the Search for quotas

---

app/models/goods_nomenclature.rb
app/services/find_ancestors_service.rb

Make use of sti_load to constantize the good nomenclature class name.
Why?
The method String#constantize is considered unsafe by Brakeman.

Replacing constantize with sti_load

---

lib/api_constraints.rb

HOTT-<TODO>
- This is required to enable using the dev .env file to specify the right api version we default to

Fix api constraints

---

.circleci/config.yml

[HOTT-988](https://transformuk.atlassian.net/browse/HOTT-988)
- I _think_ this is failing because flaky network means curl is creating an empty file and then deb is trying to install it
- The retry will hopefully solve the issue
- If it doesn't the `file cf.deb` should mean we can see what `cf.deb` is and why its not installable

HOTT-988: Retry downloads of cf.deb file

---

.circleci/config.yml

[HOTT-997](https://transformuk.atlassian.net/browse/HOTT-997)
- So we get early warning if a backend change is incompatible with the frontend

HOTT-997: Run smoketests on DEV after deploy

---

app/models/additional_code_description.rb
app/models/certificate_description.rb
app/models/concerns/declarable.rb
app/models/concerns/formatter.rb
app/models/footnote_description.rb
app/models/goods_nomenclature_description.rb
app/models/measure_component.rb
app/models/measure_condition.rb
app/models/measurement_unit_qualifier_description.rb

HOTT-<TODO>
- We don't want to override a ruby or rails core methods that aren't attached clearly
to a constant (e.g. DescriptionFormatter.format)

Rename format -> custom_format

---

app/models/measure.rb
app/models/measure_type.rb
spec/models/measure_spec.rb
spec/models/measure_type_spec.rb

https://transformuk.atlassian.net/browse/HOTT-801
- We have meursing measures that are erga omnes and the business logic around whether the measure is relevant only applies to national measures

Handle meursing measures that are erga omnes

---

config/autoscaling/development-policy.json
config/autoscaling/production-policy.json
config/autoscaling/staging-policy.json

HOTT-957
In general the changes were:
-  scale up aggressively, and scale down in a softer way after the spike is gone.
- Drop the `throughput` metric, as it was useless (no data for it)
- This morning's [blip](https://transformuk.atlassian.net/browse/HOTT-957) was likely caused but lack of resources on a flash spike in traffic. 
- This prompted an investigation, amongst other things, on the scaling policy. 
We also want to adjust the memory footprint of each instance as we have it oversized. We want to be able to have more discrete instances with less memory each, and re-balance toward CPU usage instead. 
**Note: The autoscaler was actually already enabled for the backend in all environments, so this PR just adjusts it's settings.**

Adjust autoscaling policy for all environments

---

spec/integration/cds_importer/entity_mapper_spec.rb

Failure was caused by missing load of entities by entity mapper. Check to ensure the list of MAPPERS is not empty.
[HOTT-930](https://transformuk.atlassian.net/browse/HOTT-930)
- When the zeitwerk autoloader was enabled it broke autoloading of the entity mappers. This was not picked up because the specs mocked the list of entity mappers to use.
- So I've added a spec to ensure when the list isn't mocked, it is still not empty.

HOTT-930: Spec to catch when the CDS import failed

---

Gemfile.lock

[HOTT-1034](https://transformuk.atlassian.net/browse/HOTT-1034)
- we currently have 5.5.0 which has a minor security issue in it

HOTT-1034: Upgrade puma to 5.5.2

---

.circleci/config.yml

[HOTT-1049](https://transformuk.atlassian.net/browse/HOTT-1049)
- we are currently using the wrong smoke test

HOTT-1049: Use smokeTestCI.spec for smoketest runs

---

lib/goods_nomenclature_mapper.rb

[HOTT-1036](https://transformuk.atlassian.net/browse/HOTT-1036)
- It is breaking the eager loading and triggering N+1's when calling Commodity#children - this affects all Commodity pages plus the headings pages
This was introduced in 20dd0bdf (PR 259) but it causes an N+1 whenever Commodity#children is requested
It was introduced as part of the Changes work _but_ I can't find
anything to suggest that its ever used as part of that work. Specs
still pass fine without the reloads and we didn't previously have
those reloads so I'm working on the assumption it was accidentally
introduced as part of the development process.
- This removes a previously added `.reload` - I can't find a reason for this to be added but can find problems caused …

HOTT-1036: Don't reload database records in mapper

---

.circleci/config.yml

[HOTT-1060](https://transformuk.atlassian.net/browse/HOTT-1060)
- It should reduce the time spent installing node packages
This will slow things down for the odd occasions the lock file changes but this is exceedingly rare, with the benefit of 30 - 60 secs speed up the rest of the time

Cache node modules for smoketest runs

---

app/controllers/api/v2/commodities_controller.rb
app/models/measure.rb
app/models/measure_component.rb
app/presenters/api/v2/measures/measure_presenter.rb
app/serializers/api/v2/measures/measure_serializer.rb
app/services/cached_commodity_service.rb
spec/controllers/api/v2/commodities_controller_spec.rb
spec/factories/measure_component_factory.rb
spec/models/measure_spec.rb
spec/serializers/api/v2/measures/measure_serializer_spec.rb
spec/services/cached_commodity_service_spec.rb
spec/support/shared_contexts/with_meursing_additional_code_id.rb

https://transformuk.atlassian.net/browse/HOTT-1082
- This is required to make sure the user is asked the proper questions about resolved measure component units in the duty calculator

HOTT-1082: Expose resolved measure component units

---

config/environments/test.rb

Currently using :memory_store which _may_ result in data leaking between tests. Tests probably still pass because we use factories so are generating new IDs but this could trip someone up in the future.
Using :null_store brings this inline with rails defaults.

Use :null_store for caching when Rails.env.test?

---

app/controllers/api/v2/news_items_controller.rb
app/models/news_item.rb
app/serializers/api/v2/news_item_serializer.rb
config/routes.rb
spec/models/news_item_spec.rb
spec/requests/api/v2/news_items_controller_spec.rb
spec/requests/api/v2/rules_of_origin_controller_spec.rb
spec/serializers/api/v2/news_item_serializer_spec.rb
spec/support/shared_examples/api_request_examples.rb

[HOTT-1080](https://transformuk.atlassian.net/browse/HOTT-1080)
- We wish to show news items on the frontend

HOTT-1080 Add frontend news api

---

app/models/measure.rb
spec/models/measure_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1011
- This makes for a cleaner user experience when there is no meursing measures for the meursing additional code specified by the user

Handle invalid/missing meursing additional code id

---

lib/cds_importer/entity_mapper.rb
lib/cds_importer/entity_mapper/base_mapper.rb
lib/cds_importer/entity_mapper/geographical_area_membership_mapper.rb
lib/cds_importer/entity_mapper/measure_mapper.rb

https://transformuk.atlassian.net/browse/HOTT-1084
We are in a situation where, because of CDS non-compliance with
taric data structure and processing standards we need to special
snowflake a bunch of behaviour when specific kinds of entity are
imported.
This change makes this whole process a bit neater by supplying a before
insert callback mechanism which (as the name suggests) enables us to
implement root- and branch- specific behaviour before a given entity  has an operation row created.
Following this specific change will be more changes to the MeasureMapper
around FootnoteAssociationMeasures
- This is significantly neater than putting the callback code inline with the orchestrating layer and requires less logic

HOTT-1084: Migrate to using callbacks for specific behaviours on specific mappers

---

app/lib/cds_importer/entity_mapper/measure_mapper.rb
config/brakeman.ignore
spec/factories/footnote_factory.rb
spec/integration/cds_importer/entity_mapper_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1084
- This is required to handle the fact that CDS are not compliant with Taric processing standards and have decided that every Measure node is now a source of truth for all relationships.

HOTT-1084: Remove footnote associations for every measure

---

Rakefile
app/lib/tariff_synchronizer.rb
app/lib/tasks/data_migrations.rake

HOTT-<TODO>
We depend on a bunch of models being loaded and haven't got explicit
requires that do this to enable doing various things with these models.
This includes things like unrestricting the primary key of each model so
the import process can update them or enumerating the models that are backed by oplogs
so we can clean oplog tables of rolled back files.
I've also updated a rake task not to try and load a constant and assign
a class variable to it before we've had a chance to load the environment
- So we can follow the common rails/zeitwerk idioms and not get confusing behaviour around rollbacks (I was getting confusing behaviour)
- So we can list rake tasks that - a bug I introduced when we moved to making lib work with …

Fix rake tasks

---

app/services/base_suggestions_service.rb

[HOTT-334](https://transformuk.atlassian.net/browse/HOTT-334)
- These are caused by multiple current goods nomenclature records with the same commodity code but with different product line suffixes. We do not want these showing up multiple times in the search results on the frontend.
This does change the output from `/search/suggestions` previously with multiple production line suffixes we would return all the commodity codes, each with a different OID. Now we only return 1 commodity code with the last matched OID.

HOTT-334 Avoid duplicates in comm code suggestions

---

app/models/rules_of_origin/query.rb
config/routes.rb
spec/factories/rules_of_origin/data_set_factory.rb
spec/models/rules_of_origin/query_spec.rb
spec/requests/api/v2/rules_of_origin_controller_spec.rb

[HOTT-1001](https://transformuk.atlassian.net/browse/HOTT-1001)
- Because we are going to publicly expose the Rules of Origin api

Tighten validation on Rules of Origin query

---

app/services/measure_service/council_regulation_url_generator.rb

[HOTT-1184](https://transformuk.atlassian.net/browse/HOTT-1184)
- We now have other regulation types without published dates

HOTT-1184 Handle when no published date

---

app/models/rules_of_origin/query.rb
spec/models/rules_of_origin/query_spec.rb

[HOTT-1001](https://transformuk.atlassian.net/browse/HOTT-1001)
- whilst internally the lookups occur using subheadings, the ticket specifies using commodity codes
- this is a definite trade off between user convenience and a more optimal API - if users query using 6 digit subheadings, then _any_ commodity under that subheading hits the same CDN cached api endpoint - when using 10 digit codes - this means separate endpoints for every commodity, even though commodities under the same subheadng always end up returning the same JSON payload

HOTT-1001 Allow 10 digit comm codes in RoO api

---

app/lib/tariff_synchronizer.rb
app/workers/updates_synchronizer_worker.rb
config/sidekiq.yml
spec/unit/tariff_synchronizer_spec.rb
spec/workers/updates_synchronizer_worker_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1203
- The extra 30 minutes enables us to better capture slow to drop api files on the cds files
- Only running when all updates are applied  and there are no failed updates will catch extra work which doesn't add value
- Chaining the Update and Cache workers will reduce the arbitrary latency/schedules we have setup for these two related jobs and should speed up the process overall

Push updates back a bit and chain the reindex when the updates actually happen

---

config/sidekiq.yml

https://transformuk.atlassian.net/browse/HOTT-1233
- The update files are available later than we currently think they should be there so we need to push back a bit

HOTT-1233: Updates cron schedule for synchronizer worker

---

.circleci/config.yml

[HOTT-1230](https://transformuk.atlassian.net/browse/HOTT-1230)
- When a new backend dev PR is pushed - the old app is removed and a new one is created in its place. This new backend will lack the necessary network policies to allow review apps to connect to the new backend.
- This fixes the issue where pushing a backend PR breaks the frontend review apps
- This changes the CI pipeline so is probably one to merge in the New Year - I've tested the `when:`  clause with both 'development' and 'ignore' - the step skips when its 'ignore' as expected. There will also be an opportunity to verify that step does not get run for staging when the PR is merged.

HOTT-1230 Fix backend PRs breaking review apps

---

config/environments/development.rb

HOTT-????
- So that I can have query logging on by default without requiring other developers to do so

Allow developers to assign log_levels locally

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/lib/tariff_synchronizer/cds_update.rb
app/models/measurement_unit.rb
config/initializers/raven.rb
config/initializers/sentry.rb
lib/sentry/rails/background_worker.rb
spec/models/measurement_unit_spec.rb
spec/unit/tariff_synchronizer/cds_update_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1143
- sentry-raven is out of support

HOTT-1143-sentry-rails: Migrate to sentry-rails and sentry-sidekiq

---

Gemfile
app/models/news_item.rb
config/routes.rb
spec/models/news_item_spec.rb
spec/requests/api/v2/news_items_controller_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1225
- We need to be able to return all of the target and service options
- We don't need to be defensive for this internal api

HOTT-1225: Make news item target and service optional parameters

---

db/migrate/20220107134210_add_productline_suffix_to_search_references.rb
db/structure.sql

https://transformuk.atlassian.net/browse/HOTT-1240
- This is required to differentiate commodity subheadings

HOTT-1240: Adds productline suffix to search references

---

app/lib/cds_importer/entity_mapper.rb
app/lib/cds_importer/entity_mapper/base_mapper.rb
app/lib/cds_importer/entity_mapper/geographical_area_membership_mapper.rb
spec/integration/cds_importer/entity_mapper_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1261
- When we moved to callbacks I missed the sequencing mattered and broke imports of memberships from CDS
- We want to make sure there's coverage to avoid this happening in future

HOTT-1261: Fix sequencing of transforms during CDS ETL

---

app/controllers/api/admin/commodities/search_references_controller.rb
app/controllers/api/admin/commodities_controller.rb
app/controllers/api/admin/search_references_base_controller.rb
app/models/commodity.rb
app/models/search_reference.rb
app/serializers/api/admin/commodities/commodity_serializer.rb
app/serializers/api/admin/headings/commodity_serializer.rb
app/serializers/api/admin/headings/heading_serializer.rb
config/routes.rb
spec/controllers/api/admin/commodities/search_references_controller_spec.rb
spec/models/commodity_spec.rb
spec/models/search_reference_spec.rb
spec/serializers/api/admin/commodities/commodity_serializer_spec.rb
spec/serializers/api/admin/headings/commodity_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1240
- The productline suffix enables us to differentiate different subheading commodities

HOTT-1240: Populate search references with productline suffix

---

app/lib/tariff_synchronizer.rb
app/lib/tariff_synchronizer/base_update.rb
app/lib/tariff_synchronizer/cds_update.rb
app/lib/tariff_synchronizer/taric_update.rb
spec/factories/cds_update_factory.rb
spec/factories/taric_update_factory.rb
spec/integration/tariff_synchronizer_spec.rb
spec/unit/tariff_synchronizer/cds_update_spec.rb
spec/unit/tariff_synchronizer/logger_spec.rb
spec/unit/tariff_synchronizer/taric_update_spec.rb
spec/unit/tariff_synchronizer_spec.rb

[HOTT-1252](https://transformuk.atlassian.net/browse/HOTT-1252)
We want to identify whether the current update is the next increment for the sequence based on its filename. In case it is not the expected update in sequence, it should not be run, and an alert must be sent to an appropriate channel.
To avoid data inconsistency.

HOTT-1252 Check the correctness of sequence for the CDS and Taric updates.

---

app/elastic_search_indexes/search/search_reference_index.rb
app/models/search_reference.rb
app/serializers/cache/heading_serializer.rb
app/services/heading_service/cached_heading_service.rb

https://transformuk.atlassian.net/browse/HOTT-1276
- The cached headings do not even serialize the commodity search references and this is just overhead: https://github.com/trade-tariff/trade-tariff-backend/blob/main/app/serializers/cache/heading_serializer.rb#L73-L123. I believe these were put in place as part of the V2 api previously being used for admin ui purposes before the separation: https://github.com/trade-tariff/trade-tariff-backend/commit/0c9f7a120a75c4cf31be6f7649372733ae93f602.
- The scope filtering methods just are not used
- The eager loading is also not used - I suspect it would have been part of enabling eager loading of search references as part of the CachedHeadingService

HOTT-1276: Tidy up search references

---

.circleci/config.yml

HOTT-???
- We're defining how to download and retrieve the cf command in multiple places - this removes the duplication

Split cf install into separate command for reuse

---

app/lib/tariff_synchronizer/base_update.rb
spec/factories/cds_update_factory.rb
spec/factories/taric_update_factory.rb
spec/unit/tariff_synchronizer/base_update_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1286
- Now that we've removed the missing files functionality and we know that the files can come out of order we need to try and download previously unavailable files which now exist. Our tolerance is set to the last 20 days just as a starting point.
- I've applied this behaviour to the CdsUpdate type to keep things
consistent between the implementations.

HOTT-1286: Extend download date range logic to be 20 days ago

---

app/lib/tariff_synchronizer/taric_update_downloader.rb
spec/unit/tariff_synchronizer/logger_spec.rb
spec/unit/tariff_synchronizer/taric_update_downloader_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1286
- This isn't helpful and in fact creates noise in the process of
reviewing files which haven't been downloaded correctly.

HOTT-1286: Remove creation of missing updates

---

app/lib/tariff_synchronizer.rb
app/lib/tariff_synchronizer/base_update.rb
app/lib/tariff_synchronizer/cds_update.rb
spec/unit/tariff_synchronizer/base_update_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1252
- These break the cds sequence checker and therefore are holding up applies

HOTT-1252: Fix new scopes for update model

---

.circleci/config.yml

[HOTT-1206](https://transformuk.atlassian.net/browse/HOTT-1206)
- CI does not queue and concurrent downloads can result in the deletion of the server being deployed to

HOTT-1206 Fix queueing in CI deploy step

---

.rubocop.yml
app/lib/tariff_synchronizer.rb
app/lib/tariff_synchronizer/cds_update.rb
app/workers/updates_synchronizer_worker.rb
spec/unit/tariff_synchronizer/cds_update_spec.rb
spec/unit/tariff_synchronizer_spec.rb
spec/workers/updates_synchronizer_worker_spec.rb

[HOTT-1260](https://transformuk.atlassian.net/browse/HOTT-1260)
- Sometimes the CDS update file arrives later then when our synchronizer is scheduled to run. If that is the case - re-schedule every 20 minutes until the cut off time is reached. Once the cut off time is reached, if there still isn't a file for today, the job will continue as per normal.
- Changes the behaviour of the overnight sync job

HOTT-1260 Retry data loads

---

app/lib/hashie/tariff_mash.rb
app/lib/trade_tariff_backend/search_client.rb
app/services/heading_service/cached_heading_service.rb
spec/controllers/api/v2/headings_controller_spec.rb
spec/lib/hashie/tariff_mash_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1305
When the heading hasn't been preloaded, we try to serialize using the
json api fast serializer a Mash which calls Array(our_mash) on the
intermediate serialized result. We have an intermediate result because
we use a different structure for the ES cache DDL to the JSON API
schema.
We have a special snowflake Mash implementation that was nested in the
SearchClient and generically named Response. This was implemented
because of an incompatibility with the JSON API gem we're using where
Array() implicitly calls to to_a on the Hashie::Mash and creates the
wrong result for includes.
I've moved this Mash implementation, added specs for it and made sure
that we can properly serialize all Mashes we instantiate.
I am …

HOTT-1250: Fixes broken heading api

---

app/helpers/application_helper.rb
spec/controllers/api/v2/additional_codes_controller_spec.rb
spec/controllers/api/v2/footnotes_controller_spec.rb
spec/factories/measure_factory.rb
spec/helpers/application_helper_spec.rb
spec/models/commodity_spec.rb
spec/models/heading_spec.rb
spec/models/meursing_measure_spec.rb
spec/presenters/api/v2/measures/measure_presenter_spec.rb
spec/serializers/cache/heading_serializer_spec.rb
spec/services/cached_commodity_service_spec.rb
spec/services/heading_service/cached_heading_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1318
- To avoid coupling
- To enable tests of the base regulation filtering on a measure

HOTT-1318: Adds a trait for base regulation and avoid forced coupling

---

app/models/measure.rb
spec/models/commodity_spec.rb
spec/models/measure_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1318
The distinct measure regulation query needs to take account of the
regulation role in order to uniquely identify the modification or the
base regulation measures.
This is then used downstream to pull out the correct measures that are
applicable based on the TimeMachine as applied to a worked-out effective end
date.
This was subtle and unnoticed because for the most part regulation ids
are unique between the base_regulations and modification_regulations
views and we were getting the correct joined measures bac.
- Fixes some presentational issues where the regulation id is the same between two regulations with different validity periods

HOTT-1318: Fix broken measure filtering

---

Gemfile.lock

HOTT-<TODO>
- The current version uses an old api of the redis gem and is spitting out deprecation warnings

Bump sidekiq - fix redis deprecation warnings

---

app/lib/tariff_synchronizer.rb
app/lib/tariff_synchronizer/taric_update.rb
app/lib/tariff_synchronizer/taric_update_downloader_patched.rb
app/lib/tariff_synchronizer/tariff_downloader.rb
spec/unit/tariff_synchronizer/taric_update_downloader_patched_spec.rb
spec/unit/tariff_synchronizer/taric_update_spec.rb
spec/unit/tariff_synchronizer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1244
- We are about to do a long rollback and whilst we can't distinguish between an actual 404 and a new year/or a genuinely non present file we can bail at the point the next increment isn't there. This will enable me to rollback a long way and bring us up-to-date with the patched downloader a year at a time.

HOTT-1244: Update downloads to handle long rollbacks in XI

---

app/models/footnote.rb
app/serializers/api/v2/subheadings/footnote_serializer.rb
app/serializers/cache/heading_serializer.rb
spec/serializers/api/v2/subheadings/footnote_serializer_spec.rb
spec/serializers/cache/heading_serializer_spec.rb

HOTT-<TODO>
When there are footnotes for a subheading we want to present them under the footnotes in the UI. In the current implementation we were returning footnotes but the ids were never matching up/were using the wrong id.
- We were getting a garbled jsonapi result which was breaking the frontend integration on subheadings with their own footnotes

Fix subheading footnotes

---

app/lib/goods_nomenclature_mapper.rb

https://transformuk.atlassian.net/browse/HOTT-1332
See https://sentry.io/organizations/engine-le/issues/3015912710/?project=5557005&referrer=slac
- See linked open sentry issue

HOTT-1332: Reload stale goods nomenclature

---

spec/controllers/api/v2/geographical_areas_controller_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1313
- We seem to get the wrong response from the cache intermittently

HOTT-1313: Fix intermittent geographical area failures

---

app/models/quota_definition.rb
spec/factories/quota_factory.rb
spec/models/quota_definition_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1342
- This is the correct behaviour

HOTT-1342: Adjust balance to initial volume when no balance events

---

app/controllers/api/v2/commodities_controller.rb
spec/controllers/api/v2/commodities_controller_spec.rb
spec/factories/goods_nomenclature_factory.rb

https://transformuk.atlassian.net/browse/HOTT-1341
- This is required to avoid colliding meursing additional code behaviour

HOTT-1341: Avoid collisions in meursing additional code values

---

.circleci/config.yml
app/lib/paas_config.rb
docker-compose.yml

In order to migrate our elasticsearch nodes to opensearch we need to move the connection information to the newly created opensearch nodes. They work correctly with the current elasticsearch gem and have been tested. I will be providing a follow up PR to normalize some of the references of 'elasticsearch' where possible and provide some comment around the move from an infrastructure perspective in confluence.
- Removed disabling of xpack plugin and added `plugins.security.disabled` which disables TLS that's enabled by default (ES did not have this feature enabled by default). We require this in CI.
- Corrected issues with rubocop linting.
- Moved docker-compose to use opensearch.
- Disabled Style/HashSyntax due to a problem with ruby_parser and 3.1 syntax when interacting with Brakeman
- …

[HOTT-1312] Elasticsearch migration

---

app/models/concerns/declarable.rb
app/models/measure.rb
spec/models/commodity_spec.rb
spec/models/measure_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1343
- We currently show measures that should be end dated because we're not filtering on regulation role and are picking the wrong regulation effective end date
- We need to make sure the base regulation filter includes all possible role ids (this caught us out recently)

HOTT-1343: Filter regulation measures correctly

---

app/services/search_service/exact_search.rb
spec/services/search_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1316
Currently, if we have a title value that has any capitals in it we cannot
match the result with an ExactSearch because the input query gets
downcased in the constructor of BaseSearch.
The net effect of this is to prevent us from being able to query search
references until the ES index for search references is repopulated the
following morning. We see the reference in search suggestions but cannot
fetch the result.
After this change we can pull out search results without needing to
touch the ES index rows.
- This is a broken implementation
- This is a bad user experience
- This forces us to always do an ES AND a psql query

HOTT-1316: Fixes broken ExactSearch behaviour

---

app/controllers/api/v2/quota_order_numbers_controller.rb
app/models/quota_order_number.rb
app/serializers/api/v2/quota_definition_serializer.rb
app/serializers/api/v2/quota_order_number_serializer.rb
config/routes.rb
spec/controllers/api/v2/quota_order_numbers_controller_spec.rb
spec/factories/quota_factory.rb
spec/models/quota_order_number_spec.rb
spec/serializers/api/v2/quota_definition_serializer_spec.rb
spec/serializers/api/v2/quota_order_number_serializer_spec.rb
spec/serializers/api/v2/quotas/definition/quota_definition_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1298
- This is a feature request that will be used by Defra https://www.gov.uk/government/organisations/department-for-environment-food-rural-affairs
corresponding quota definition for the given time machine specified
date.
be fetched using a different api (to come later)

HOTT-1298: Surface quota order numbers.

---

Gemfile
Gemfile.lock
config/initializers/redis_lock_db.rb

[HOTT-1270](https://transformuk.atlassian.net/browse/HOTT-1270)
Whilst working on the CDS rollback and reapply a few weeks ago we observed that scheduling a rollback didn't work, but did then subsequently ran much later on. I had observed similar behaviour whilst dealing with another CDS rollback some months prior but I'd only just started on the project and assumed I was doing something wrong.
The issue turns out to be redlock hanging waiting to acquire a lock - I can reliably reproduce this by scheduling a rollback, then a roll forward. This will result in hang between 1 and 3 iterations - killing sidekiq then causes the job to run on shutdown. Potentially much later then expected.
I believe this is caused by our Redlock …

HOTT-1270 Use a connection pool for RedLock

---

.circleci/config.yml

[HOTT-1104](https://transformuk.atlassian.net/browse/HOTT-1104)
This avoids the current 'race' scenario triggered by a newly deployed app reading the database structure on boot.
In order to perform database migrations, we need an 'app' running the latest image. _BUT_ if that app starts, it will start with the old database structure because migration has not yet happened. Best case scenario is sidekiq boots but with an old structure, worst case is we've added a new db model and the missing table prevents sidekiq from booting.
This change introduces a new app, the same size as the sidekiq worker app but without it ever starting (the `--task` option to cf push). This app can be updated, then used to migrate the database before updating the worker and web apps …

HOTT-1104 Run database migrations on own tasks app

---

spec/spec_helper.rb

Useful for debugging flaky specs (this is why using rspec --seed doesn't work at the moment)

Changed spec_helper to allow assigning seed

---

.rubocop.yml
app/lib/tariff_synchronizer.rb
app/lib/tariff_synchronizer/cds_update.rb
app/workers/updates_synchronizer_worker.rb
config/sidekiq.yml
spec/unit/tariff_synchronizer/cds_update_spec.rb
spec/unit/tariff_synchronizer_spec.rb
spec/workers/updates_synchronizer_worker_spec.rb

[HOTT-1260](https://transformuk.atlassian.net/browse/HOTT-1260)
- We want to try and import as early as possible but if the files are arriving later, then we should still be importing them
- Changes behaviour of overnight sync

HOTT-1260 Retry downloading CDS

---

app/lib/tariff_synchronizer/cds_update.rb
app/serializers/api/admin/tariff_update_serializer.rb
spec/controllers/api/admin/updates_controller_spec.rb
spec/unit/tariff_synchronizer/cds_update_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1364
- This will be used for the admin UI
https://github.com/trade-tariff/trade-tariff-backend/pull/434
https://github.com/trade-tariff/trade-tariff-admin/pull/125

HOTT-1364: Populate oplog inserts in tariff update table

---

.circleci/config.yml

HOTT-<TODO>
- Deploying is unnecessary when just running migrations

Update staging db refresh migrations to not require a deploy

---

.circleci/config.yml

HOTT-1104
- We currently upgrade sidekiq, then migrate, then upgrade the web apps - this can leave sidekiq with the wrong schema loaded if adding/changing columns. This does not resolve the problem but is step 1
- Changes our deployment process - well tested in Staging in earlier PR but does change a 'critical path'

Revised PR - only deploys the tasks app

---

Dockerfile
Gemfile
Gemfile.lock
app/lib/tariff_synchronizer/tariff_updates_requester.rb
spec/unit/tariff_synchronizer/tariff_updates_requester_spec.rb
spec/unit/tariff_synchronizer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1357
- This is an additional dependency that adds no value beyond being a bit interesting to developers.

HOTT-1357: Remove curb and replace it with Faraday

---

.circleci/config.yml

Instead of worker
HOTT-1104
- It will resolve the out-of-order execution of migrations we have on deploy at present
- Changes deployment behaviour for the migrations

HOTT-1104 Run migrations on the tasks app

---

app/controllers/application_controller.rb
config/environments/test.rb
spec/requests/application_controller_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1337
- We were missing coverage of this
- We need to make sure that internal details of the service do not leak to clients

HOTT-1337: Obfuscate errors to clients of the backend apis

---

.circleci/config.yml

HOTT-<TODO>
- ruby 6 syntax brakes the brakeman sexpression tokeniser and propagates errors since brakeman 4

Exit brakeman gracefully after parser errors

---

app/lib/tariff_synchronizer/tariff_updates_requester.rb
spec/unit/tariff_synchronizer/tariff_updates_requester_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1357
- We need to make sure the downloads on XI are working

Fixes deprecated basic auth api usage

---

.circleci/config.yml

[HOTT-1396](https://transformuk.atlassian.net/browse/HOTT-1396)
- The wrong service value was being passed into the migrations command, preventing the weekly staging refresh from running the migrations

HOTT-1396 Fix migrations on staging refresh

---

app/services/base_suggestions_service.rb
spec/services/api/v2/suggestions_service_spec.rb

HOTT-1400
- they should not be showing up in search suggestions

HOTT-1400 Exclude hidden commodities from suggestions

---

docker-compose.yml

For some reason I'd excluded a change which disabled security for
opensearch as opensearch is 'better' than elasticsearch when it comes to
defaults choices. However, this gets in the way when we want to run
something locally quickly without messing about too much.
I've updated the file so that we can run the backend with docker-compose
without too much faffing around.
Signed-off-by: Chris Mills <7100370+chriscoffee@users.noreply.github.com>

hotfix docker-compose config

---

app/services/meursing_measure_finder_service.rb
spec/services/meursing_measure_finder_service_spec.rb

[HOTT-1393](https://transformuk.atlassian.net/browse/HOTT-1393)
This solves a flaky spec (and possible real world bug) - it is fairly frequently reproducible (maybe 2 in 3 runs) at 17858ab8 using
`bundle exec rspec --seed=8725 spec/services/meursing_measure_finder_service_spec.rb`
The underlying issue is if reduction_indicator is nil, the finder produces an incorrect SQL query, using `reduction_indicator = NULL` instead of `reduction_indicator IS NULL`
This is triggered intermittently because we are using `.sample` in the `Measure` factory for `reduction_indicator` and one of the possible values is `nil`. When this value (nil) is chosen, the spec fails.
Currently this is derived from an older commit (`17858ab8`) to demonstrate it …

HOTT-1393 Fixed SQL when nil reduction_indicator

---

app/lib/hashie/tariff_mash.rb
spec/lib/hashie/tariff_mash_spec.rb

The relationship method calls map for a TariffMash for non-static serializers: https://github.com/jsonapi-serializer/jsonapi-serializer/blob/master/lib/fast_jsonapi/relationship.rb#L110-L114. We want Mash to be treated like a non-enumerable object.
- This is required so we can serialize ES-backed search results polymorphically
- This does not affect when An Array/Hashie::Mash::Array is encountered by the jsonapi-serializer.

HOTT-1414: Tweak tariff mash to work with polymorphic serializers

---

app/serializers/cache/additional_code_serializer.rb
app/serializers/cache/certificate_serializer.rb
app/serializers/cache/footnote_serializer.rb
app/serializers/cache/search_cache_methods.rb
spec/serializers/cache/search_cache_methods_spec.rb
spec/services/additional_code_search_service_spec.rb
spec/services/certificate_search_service_spec.rb

- This is required so that ES-backed search results can be serialized using the new shared serializers
- We were missing coverage

HOTT-1414: Adds necessary attributes to ES-backed goods nomenclature

---

app/models/commodity.rb
app/models/goods_nomenclature_indent.rb
spec/factories/goods_nomenclature_factory.rb
spec/models/commodity_spec.rb

- This method is called a lot and is very expensive (we have to enumerate children and related indents. This will optimise other places we ask this question.

HOTT-1414: Cache Commodity#declarable? result

---

config/autoscaling/staging-policy.json

HOTT-???
- Max DB connections allowed in Staging is 200
- Previously we were running with a max of 12 instances, 6 process per instance, 6 connections per process = 432
- Now its max 8 processes, 4 processes per instance, 6 connections per process = 192

Drop the max autoscale value for Staging

---

app/serializers/cache/footnote_serializer.rb

HOTT-<TODO>
- This fails to update some footnotes in ES

Handle when a measure has no matching goods nomenclature

---

app/lib/paas_config.rb
spec/rails_helper.rb

HOTT-???
- The tests run flushdb before and after the suite, this means you can run the tests at the same time as meaningfully using Redis in development, eg running a re-cache.
- The separate db for RedLockDb should no longer be necessary because we handle connection pooling correctly - it looks like this was a historical attempt to solve the test suite from locking up.

Use separate Redis database for tests

---

app/services/quota_search_service.rb
spec/services/quota_search_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1432
- We use the measure model to find applicable measures and we do not need these to be distinct on the validity start date.
- Its possible/happens in the wild for 2 measures to have a different validity start dates despite having the same order number.
- The order number and definition are one-to-one and we only ever need one active order number measure returned to get the active definition.

HOTT-1432: Adjust quotas query to remove duplicate definitions

---

app/serializers/api/v2/shared/measure_serializer.rb
spec/serializers/api/v2/shared/measure_serializer_spec.rb

- This is causing failures for users that are scraping certain additional codes in production

HOTT-1414: Handle nil goods nomenclature in polymorphic serializer

---

app/serializers/cache/additional_code_serializer.rb
app/services/additional_code_search_service.rb
spec/controllers/api/v2/additional_codes_controller_spec.rb
spec/serializers/cache/additional_code_serializer_spec.rb

- This is required so we filter out broken measures from the additional code search

HOTT-1414: Exclude measures without goods nomenclature code search

---

.circleci/config.yml
.rubocop.yml
app/controllers/api/v2/quotas_controller.rb
app/lib/paas_config.rb
app/lib/trade_tariff_backend.rb
app/models/goods_nomenclature.rb
app/models/measure_condition.rb
spec/factories/measure_factory.rb
spec/factories/quota_factory.rb
spec/models/measure_action_spec.rb
spec/models/measure_spec.rb
spec/models/measure_type_spec.rb
spec/models/quota_critical_event_spec.rb
spec/presenters/api/v2/measures/measure_presenter_spec.rb
spec/serializers/api/v2/shared/measure_serializer_spec.rb
spec/services/meursing_measure_finder_service_spec.rb
spec/support/shared_examples/a_serialized_goods_nomenclature.rb
spec/unit/tariff_synchronizer/cds_update_spec.rb

HOTT-???
- Brakeman is more important than utilising Ruby 3.1 hash syntax
- its trivial to convert back at a future point
- for now it reduces noise in PRs because rubocop isn't insisting on an syntax change to existing code

Rubocop match brakeman

---

app/controllers/api/admin/news_items_controller.rb
app/models/news_item.rb
app/serializers/api/admin/news_item_serializer.rb
app/serializers/api/v2/news_item_serializer.rb
db/migrate/20220328091515_add_show_on_banner_to_news_items.rb
db/structure.sql
spec/factories/news_item_factory.rb
spec/models/news_item_spec.rb
spec/serializers/api/admin/news_item_serializer_spec.rb
spec/serializers/api/v2/news_item_serializer_spec.rb

[HOTT-1381](https://transformuk.atlassian.net/browse/HOTT-1381)
- We want to content manage the banner on the frontend site
- Database change included along side code dependency on database change - this should be a non-issue now with the migration fixes

HOTT-1381 Add Banner news items

---

app/serializers/api/v2/footnotes/footnote_serializer.rb
app/serializers/cache/footnote_serializer.rb
app/services/footnote_search_service.rb
spec/controllers/api/v2/footnotes_controller_spec.rb
spec/factories/footnote_factory.rb
spec/serializers/api/v2/footnotes/footnote_serializer_spec.rb
spec/serializers/cache/footnote_serializer_spec.rb

- This is required to avoid sentry failures for people scraping footnotes from the api when goods nomenclature associations are broken (see https://sentry.io/organizations/engine-le/issues/3139630294/?project=5557005&query=is%3Aunresolved)

HOTT-1414: Handle missing goods nomenclature in footnote search

---

app/serializers/cache/certificate_serializer.rb
spec/controllers/api/v2/certificates_controller_search_spec.rb
spec/factories/certificate_factory.rb
spec/serializers/cache/certificate_serializer_spec.rb

- This is in anticipation of the certificate search api returning broken goods nomenclature

HOTT-1414: Handle certificate search goods nomenclature

---

app/controllers/api/v2/certificates_controller.rb
app/serializers/api/v2/certificates/certificate_list_serializer.rb
spec/controllers/api/v2/certificate_types_controller_spec.rb
spec/controllers/api/v2/certificates_controller_index_spec.rb
spec/factories/certificate_factory.rb
spec/serializers/api/v2/certificate/certificate_list_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1466
- This is currently returning certificates and saying they're a certificate_type

HOTT-1466: Fixes type on certificate list serializer

---

app/models/measure_condition.rb
app/serializers/api/v2/certificates/certificate_list_serializer.rb
app/serializers/api/v2/certificates/certificates_serializer.rb
spec/models/measure_condition_spec.rb
spec/serializers/api/v2/certificates/certificate_list_serializer_spec.rb
spec/serializers/api/v2/certificates/certificates_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1468
- CDS and CHIEF guidance is never relevant on European data

HOTT-1468: Disable guidance on XI

---

app/serializers/api/v2/quotas/quota_definition_serializer.rb
spec/serializers/api/v2/quotas/quota_definition_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1492
- This has been broken for quite a while and has only recently been noticed

HOTT-1492: Fix bug in last_allocation_date

---

app/serializers/api/v2/headings/commodity_serializer.rb
app/serializers/cache/heading_serializer.rb
spec/serializers/cache/heading_serializer_spec.rb

HOTT-<TODO>
- Heading commodities are missing this field which makes determining declarability different for headings (see https://github.com/trade-tariff/trade-tariff-frontend/pull/772)

Surface declarable on heading commodity

---

config/routes.rb
spec/requests/api/v2/chapters_controller_spec.rb
spec/requests/api/v2/sections_controller_spec.rb
spec/support/shared_examples/api_request_examples.rb

https://transformuk.atlassian.net/browse/HOTT-1518
- This is required so we can support the text/csv mimetype in the ACCEPT header
- We should run a full regression and leave this on staging for a bit

HOTT-1518: Support text/csv in ACCEPT header

---

.circleci/config.yml
spec/models/rules_of_origin/scheme_set_spec.rb

[HOTT-1519](https://transformuk.atlassian.net/browse/HOTT-1519)
- Orbs follow semantic versioning, so it should be safe to upgrade minor and patch releases automatically since they wont include
breaking changes.
- There are known problems with specs not being run for the old v1.4.0 version of the ruby orb we currently use.

HOTT-1519 Always use latest v1 Ruby orb

---

app/controllers/api/v2/headings_controller.rb
app/serializers/api/v2/csv/commodity_serializer.rb
config/routes.rb
spec/requests/api/v2/headings_controller_spec.rb
spec/serializers/api/v2/csv/commodity_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1491
- This is part of a wider rollout of csv apis that are useful to HMRC and our stakeholders generally

HOTT-1491: Adds heading commodties csv api endpoint

---

app/controllers/api/v2/chapters_controller.rb
app/controllers/api/v2/headings_controller.rb
app/controllers/api/v2/sections_controller.rb
app/models/section.rb
spec/requests/api/v2/chapters_controller_spec.rb
spec/requests/api/v2/headings_controller_spec.rb
spec/requests/api/v2/sections_controller_chapters_spec.rb
spec/requests/api/v2/sections_controller_spec.rb
spec/support/shared_examples/api_request_examples.rb

https://transformuk.atlassian.net/browse/HOTT-1544
- This is required for the user to distinguish between files from the two backends

HOTT-1544: Add service to csv endpoint filenames

---

app/controllers/api/v2/chapters_controller.rb
app/models/heading.rb
app/serializers/api/v2/csv/heading_serializer.rb
config/routes.rb
spec/requests/api/v2/chapters_controller_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1490
This PR adds a new endpoint 
`/chapters/:id/headings on V2`
and supports the JSON and CSV formats.
It is using the existing serializer for Json: `Api::V2::Headings::HeadingSerializer`
and a new serializer for CSV: `Csv::HeadingSerializer`

HOTT-1490: Add new endpoint /chapters/:id/headings on V2

---

app/services/search_service/exact_search.rb
spec/services/search_service_spec.rb

[HOTT-1379](https://transformuk.atlassian.net/browse/HOTT-1379)
- I am trying to ensure the search behaves according to the 'scenarios' document attached to the ticket
This supercedes #500

HOTT-1379 Search improvements

---

app/services/search_service/exact_search.rb
spec/services/search_service_spec.rb

Previously search would return the heading for the missing commodity,
but this places behavioural logic in the backend and removes our ability
to handle empty searches differently on the frontend.
[HOTT-1379](https://transformuk.atlassian.net/browse/HOTT-1379)
- Currently we return an exact match, even though its not. 
- The frontend cannot differentiate between an exact match that it should treat as canonical and redirect the user to, and an exact match that actually wasn't and the user should be given options (ie the 404 history page)
- Returning no result makes it clear we didn't find a match for that commodity
- Includes behavioural changes to the search api - this isn't a documented API but is publicly accesible so may affect …

HOTT-1379 Return empty result for unknown commodities

---

app/serializers/api/v2/search_reference_serializer.rb
spec/controllers/api/v2/search_references_controller_spec.rb
spec/serializers/api/v2/search_reference_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1549
This PR exposes productline_suffix on the api /search_references
To provide a way for the FE to understand if the entries are subheadings.

HOTT-1549 Expose productline_suffix on the api /search_references

---

config/sidekiq.yml

[HOTT-1568](https://transformuk.atlassian.net/browse/HOTT-1568)
- The Sidekiq Healthcheck worker is currently being starved out on the Sidekiq queues and not firing whilst we are rebuilding the cache
- Changes priority levels of job queues

HOTT-1568 increase priority of healthcheck queue

---

app/lib/tariff_synchronizer.rb
app/workers/updates_synchronizer_worker.rb
lib/tasks/tariff.rake
spec/factories/cds_update_factory.rb
spec/support/sidekiq.rb
spec/unit/tariff_synchronizer_spec.rb
spec/workers/rollback_worker_spec.rb
spec/workers/updates_synchronizer_worker_spec.rb

[HOTT-1505](https://transformuk.atlassian.net/browse/HOTT-1505)
- I want to add another step to the ETL process before the cache invalidation (subsequent PR)
- This new step doesn't relate to the TariffSynchronizer itself
- The ETL process is more then just the TariffSynchronizer, currently its Synchronizer + Cache Invalidation + Index rebuild + Cache rebuild
- As it stands changes to the broader ETL process order potentially require the model for `TariffSynchronizer` to be changed, even if its unrelated
- Changes the critical TariffSynchronizer process - should run overnight in Dev environment prior to merge, and checks should be made that cache invalidation and reindex were run

HOTT-1505 Refactor Updates Synchronize Worker

---

app/lib/cds_importer/entity_mapper/measure_partial_temporary_stop_mapper.rb
app/lib/cds_importer/entity_mapper/quota_reopening_event_mapper.rb
app/lib/cds_importer/entity_mapper/quota_unsuspension_event_mapper.rb

https://transformuk.atlassian.net/browse/HOTT-1581
- This is required so we can properly import these entities in future

HOTT-1581: Adds mapping root to unimportable entities for CDS

---

spec/models/healthcheck_spec.rb

HOTT-1565
- flaky specs result in false negatives for the whole team

HOTT-1565 Fix for flaky spec on Healthcheck model

---

app/serializers/api/v2/subheadings/commodity_serializer.rb
spec/serializers/api/v2/subheadings/commodity_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1557
Add declarable to Subheading.
To fix the subheading formatting.
The issue with the FE, is not having a `declarable` attribute for the subheading provided by the API.

HOTT-1557 Expose declarable for Subheading.

---

db/data_migrations/20220425110310_footnote_808_description_html_fix.rb

Re-instate data migration and include fix for `LongJump` error
Reverts trade-tariff/trade-tariff-backend#576
This was caused by attemptinging to `return` from a proc when on XI

Revert "Revert "HOTT-1413 Fix the description on Footnote 808""

---

app/lib/tariff_synchronizer.rb
app/workers/updates_synchronizer_worker.rb
lib/tasks/tariff.rake
spec/workers/updates_synchronizer_worker_spec.rb

[HOTT-1505](https://transformuk.atlassian.net/browse/HOTT-1505)
- If an ETL rollback has been performed, we will potentially have Data Migrations needing to be reapplied
- These should be reapplied before the cache invalidation and reindex process occurs
- This doesn't need to impact the nightly process but its useful for the 'manual roll forward' scenario
- The rollback's _keep_ the data from the chosen data, _but_ the data migration rollback was removing that days migrations - instead in now only removes data migrations from the following day to keep it inline with where data is being rolled back to
- The `rake tariff:sync` task would reasonably be expected to sync the tariff data - previously only did part of the process (apply) …

HOTT-1505 Reapply data migrations on ETL sync

---

Gemfile
Gemfile.lock
config/initializers/redis_lock_db.rb

HOTT-1620
- You can get to the Redis connection pool directly, so we don't need to create our own
- Open connections to Redis turn READONLY when the Redis instance failsover - this in effect leaves open connections broken. Redis ElasticCache makes the READONLY responses look like connection errors, triggering reconnects which will connect to the new master, resolving the problem.
This gem uses is marked as deprecated because there is now a config option for the Redis instance.
Due to limits in how we deploy our services we cannot set this config option in a persisted manner - if Redis gets recreated (ie we upgrade to a larger instance) we will loose this option re-introducing the problem.
Hence why I'm relying on a deprecated gem - I …

HOTT-1620 Handle Redis connections go READONLY

---

.circleci/config.yml

HOTT-???
- It will take 3 minutes out the pipeline

Build docker image concurrently with running tests

---

spec/factories_spec.rb
spec/spec_helper.rb
spec/support/shared_examples/a_component.rb
spec/support/shared_examples/a_serialized_goods_nomenclature.rb
spec/support/shared_examples/association_shared_examples.rb
spec/support/shared_examples/base_update_shared_examples.rb
spec/support/shared_examples/v2_search_reference_controller_examples.rb

HOTT-<TODO>
- This is consistent with the rails generators and it is generally more desirable to do things in one way, only: https://github.com/rspec/rspec-rails/commit/ca0d249858903949052e06884e8e7f9d596cdc79

 Disable RSpec dsl in main

---

app/models/data_migration.rb
app/models/section.rb
db/data_migrations/20220513092532_update_section_title.rb
spec/models/data_migration_spec.rb
spec/models/section_spec.rb

[HOTT-1619](https://transformuk.atlassian.net/browse/HOTT-1619)
- We want to amend the title of Section III
- Previously API returned sections in the order of 'least recently modified' first - which meant the newly modified Section III was at the end, not between Section II and Section IV as it should be
- The DataMigrations also have a natural order, so we should follow that in retrieval to avoid confusing future developers - note this model isn't used by the migration system itself, its just a convenience model I've added for working with records from the Data Migrator

HOTT-1619 Update Section title

---

app/serializers/api/v2/subheadings/subheading_serializer.rb
app/services/cached_subheading_service.rb
spec/services/cached_subheading_service_spec.rb

[HOTT-1483](https://transformuk.atlassian.net/browse/HOTT-1483)
- The frontend wants to show the list of ancestors for a subheading so we duplicate the commodity references in the API to avoid the frontend computing the ancestors

HOTT-1483 Include the ancestors tree in the Subheadings API

---

Gemfile
Gemfile.lock
config/environments/production.rb

Update Rails cache to use the Redis cache store.
The reason of this PR is because Rails 5.2.0 (and following versions) includes a Redis cache store out of the box, so you don't need this gem anymore if you just need to store the cache in Redis.
https://transformuk.atlassian.net/browse/HOTT-1567

HOTT-1567 Update Rails cache to use the redis cache store.

---

app/lib/cds_importer/entity_mapper/base_mapper.rb
app/lib/cds_importer/entity_mapper/footnote_description_period_mapper.rb
app/lib/cds_importer/entity_mapper/footnote_mapper.rb
spec/lib/cds_importer/entity_mapper/base_mapper_spec.rb
spec/lib/cds_importer/entity_mapper/footnote_mapper_spec.rb
spec/support/shared_examples/an_entity_mapper_missing_entity_destroy_operation.rb

https://transformuk.atlassian.net/browse/HOTT-1599
- This is required to support other more complex/dynamic relationships as part of measure missing secondary node soft deletion

HOTT-1599: Handle composite primary keys during missing secondary node deletion

---

app/lib/cds_importer/entity_mapper.rb
app/lib/cds_importer/entity_mapper/base_mapper.rb
spec/lib/cds_importer/entity_mapper/base_mapper_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1585
- When applicable mappers are sorted by their sort key the primary
comes first. Rather than relying on this heuristic rely on the primary? method to
pull out the first primary that matches in the applicable_mappers_for
method just to avoid any ambiguity/potential for regression.

HOTT-1585: Rely on primary method rather than heuristic

---

app/models/additional_code_type_description.rb
db/migrate/20220526155444_add_language_to_additional_code_type_description_view.rb
db/structure.sql
spec/controllers/api/v2/additional_code_types_controller_spec.rb
spec/factories/additional_code_factory.rb

https://transformuk.atlassian.net/browse/HOTT-1586
- This is how we uniquely identify the additional code type description when there are more than one languages we might pull out
- This was noticed as I was adding coverage for clearing missing versions of these from an additional code description type primary

HOTT-1585: Adds migration for additional code type description view language

---

config/autoscaling/staging-policy.json

https://transformuk.atlassian.net/browse/HOTT-1665
- This reflects the fact that we get connection issues at 100 connections
despite the govuk documentation saying this should be at 200.
- 4 processes per worker at 6 connections in each pool at 4 workers is 96 and just under the amount that caused issues on staging
- See initial change here: https://github.com/trade-tariff/trade-tariff-backend/pull/496

HOTT-1665: Tweak autoscale rule for maximum nodes on staging to 4

---

app/models/goods_nomenclature.rb
spec/models/goods_nomenclature_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1628
- This is the correct ordering

HOTT-1628: Fixes ordering of goods nomenclature

---

.rubocop.yml
app/models/chapter.rb
app/models/goods_nomenclature.rb
app/models/heading.rb
app/services/materialized_path_updater_service.rb
app/workers/generate_materialized_paths_worker.rb
app/workers/updates_synchronizer_worker.rb
config/application.rb
db/migrate/20220609140555_add_path_to_goods_nomenclatures_oplog.rb
db/structure.sql
spec/factories/goods_nomenclature_factory.rb
spec/models/chapter_spec.rb
spec/models/goods_nomenclature_spec.rb
spec/services/materialized_path_updater_service_spec.rb
spec/workers/generate_materialized_paths_worker_spec.rb
spec/workers/updates_synchronizer_worker_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1628
- This is required to make for a speedier hierarchy generation and was driven by upcoming changes to search indexes

HOTT-1628: Generate materialized paths for all goods nomenclature

---

app/elastic_search_indexes/search_index.rb
app/lib/trade_tariff_backend.rb
app/lib/trade_tariff_backend/search_client.rb
app/serializers/search/search_reference_serializer.rb
app/workers/build_index_page_worker.rb
spec/elastic_search_indexes/cache/additional_code_index_spec.rb
spec/elastic_search_indexes/cache/certificate_index_spec.rb
spec/elastic_search_indexes/cache/footnote_index_spec.rb
spec/elastic_search_indexes/cache/heading_index_spec.rb
spec/elastic_search_indexes/search/chapter_index_spec.rb
spec/elastic_search_indexes/search/commodity_index_spec.rb
spec/elastic_search_indexes/search/heading_index_spec.rb
spec/elastic_search_indexes/search/search_reference_index_spec.rb
spec/elastic_search_indexes/search/section_index_spec.rb

HOTT-1676
- We want to add/extend our search indexes and this is necessary to have different behaviours in new vs old indexes
- Changes the Search Indexing behaviour so needs to run in Dev overnight prior to any merge

HOTT-1676 move responsibilities to indexes

---

app/elastic_search_indexes/search_index.rb
app/lib/trade_tariff_backend.rb
app/lib/trade_tariff_backend/search_client.rb
app/services/additional_code_search_service.rb
app/services/certificate_search_service.rb
app/services/footnote_search_service.rb
app/services/heading_service/cached_heading_service.rb
app/services/search_service/fuzzy_search/fuzzy_search_result.rb
app/services/search_service/fuzzy_search/reference_query.rb
config/environments/test.rb
spec/lib/trade_tariff_backend/search_client_spec.rb

HOTT-1676
- Previously these options lacked context for which class they impacted, -locating them on the class they relate to clarifies that
- Affects search index generation, should be run overnight on Dev first

HOTT-1676 Moved ES options to SearchClient

---

app/models/commodity.rb
app/models/measure_type.rb
spec/factories/measure_factory.rb
spec/models/commodity_spec.rb
spec/models/measure_type_spec.rb
spec/serializers/cache/heading_serializer_spec.rb
spec/services/heading_service/cached_heading_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1698
- We need to make sure that country-specific measures aren't part of the
overview of a commodity on the subheading and heading pages in the
frontend. It doesn't make sense to show these for all users on an
overview

HOTT-1698: Filter in only erga omnes third country overview measures

---

app/elastic_search_indexes/search_index.rb
app/lib/sequel/plugins/elasticsearch.rb
app/lib/trade_tariff_backend.rb
app/lib/trade_tariff_backend/search_client.rb
app/services/search_service/fuzzy_search/fuzzy_search_result.rb
app/workers/build_index_page_worker.rb
config/environments/test.rb
spec/controllers/api/v2/additional_codes_controller_spec.rb
spec/controllers/api/v2/certificates_controller_search_spec.rb
spec/controllers/api/v2/footnotes_controller_spec.rb
spec/elastic_search_indexes/cache/additional_code_index_spec.rb
spec/elastic_search_indexes/cache/certificate_index_spec.rb
spec/elastic_search_indexes/cache/footnote_index_spec.rb
spec/elastic_search_indexes/cache/heading_index_spec.rb
spec/elastic_search_indexes/search/chapter_index_spec.rb
spec/elastic_search_indexes/search/commodity_index_spec.rb
spec/elastic_search_indexes/search/heading_index_spec.rb
spec/elastic_search_indexes/search/search_reference_index_spec.rb
spec/elastic_search_indexes/search/section_index_spec.rb
spec/lib/trade_tariff_backend/search_client_spec.rb
spec/services/additional_code_search_service_spec.rb
spec/services/certificate_search_service_spec.rb
spec/workers/build_index_page_worker_spec.rb

[HOTT-1676](https://transformuk.atlassian.net/browse/HOTT-1676)
- This allows us to have multiple indexes for a given model class within the new search namespace
- Those indexes can exclude themselves from Search lookups
- This will allow us to 'evolve' the index definitions by just adding additional V2/V3/V4 indexes and then dropping the old ones in subsequent PRs - the new ones will get created automatically in the overnight sync
- Changes the parameters contents (but not count) of the BuildIndexPageWorker, there is still compatibility with the old syntax though so any queued jobs will still complete sucessfully.

HOTT-1676 allow multiple indexes per model

---

app/models/chapter.rb
app/models/heading.rb

https://transformuk.atlassian.net/browse/HOTT-1719
- This is required to make sure the goods nomenclature mapper returns the correct root headings of a chapter and is the only correct implementation

HOTT-1628: Fixes ordering of headings and chapters

---

.circleci/config.yml

HOTT-???
- it creates unnecessary noise
- Changes an production deployment pipeline

Fixed double notification of backend release

---

.circleci/config.yml

HOTT-1687
- It avoids the need to choose between no release, reverting changes that have not yet been QAd, or requiring urgent QA decisions. 
- Changes production deployment path

HOTT-1687 Create releases from hotfix PRs

---

app/lib/trade_tariff_backend.rb
app/models/measurement_unit.rb

HOTT-<TODO>
- This feature has been switched on for a long time in production and has gone through rigorous testing by @madviv and by me.

Removes the normalize measure unit feature flag

---

app/elastic_search_indexes/search/goods_nomenclature_index.rb
app/elastic_search_indexes/search_index.rb
app/lib/trade_tariff_backend.rb
app/models/goods_nomenclature.rb
app/serializers/search/goods_nomenclature_serializer.rb
app/workers/build_index_page_worker.rb
app/workers/reindex_models_worker.rb
spec/elastic_search_indexes/search/goods_nomenclature_index_spec.rb
spec/factories/commodity_factory.rb
spec/models/goods_nomenclature_spec.rb
spec/serializers/search/goods_nomenclature_serializer_spec.rb
spec/workers/reindex_models_worker_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1702
- This is required so we can do some more intelligent querying of the goods nomenclature and their ancestors and is part of a wider rollout of improvements to search

HOTT-1702: Adds v2 search index

---

app/models/goods_nomenclature.rb
app/models/goods_nomenclature_description.rb
app/serializers/search/goods_nomenclature_serializer.rb
spec/factories/commodity_factory.rb
spec/models/goods_nomenclature_description_spec.rb
spec/serializers/search/goods_nomenclature_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1703
- This is required since when we search for a specific term we do not want
it to be included in the results if the term is technically negated.

HOTT-1703: Adds negation term removal to description indexed

---

.circleci/config.yml

https://transformuk.atlassian.net/browse/HOTT-1740
- This is required to enable configurable smoketests for the staging space

HOTT-1740: Adds support for backend smoketests on staging

---

app/formatters/requirement_duty_expression_formatter.rb
spec/formatters/requirement_duty_expression_formatter_spec.rb

HOTT-1747
- It wasn't being displayed when monetary unit was present

HOTT-1747: Display monetary unit if present

---

app/models/beta/search/open_search_result.rb
app/models/goods_nomenclature.rb
app/serializers/api/beta/chapter_statistics_serializer.rb
app/serializers/api/beta/heading_statistics_serializer.rb
app/serializers/api/beta/search_result_serializer.rb
app/services/api/beta/search_result_statistics_service.rb
app/services/api/beta/search_service.rb
spec/factories/search_result_factory.rb
spec/fixtures/beta/search/goods_nomenclatures/serialized_result.json
spec/models/beta/search/open_search_result_spec.rb
spec/models/goods_nomenclature_spec.rb
spec/serializers/api/beta/chapter_statistics_serializer_spec.rb
spec/serializers/api/beta/heading_statistics_serializer_spec.rb
spec/serializers/api/beta/search_result_serializer_spec.rb
spec/services/api/beta/search_result_statistics_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1743
We need to return statistics for unique headings and chapters that were returned by the beta
search functionality.
This will ultimately enable us to know which headings and chapters got the best results and also
to know which headings we can filter on in the frontend UI.
- This is required for some of the beta search functionality in the frontend

HOTT-1743: Adds heading and chapter statistics to search results

---

app/workers/reindex_models_worker.rb
spec/workers/reindex_models_worker_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1757
- This makes working with these indexes easier whilst we're quickly iterating on them
- These indexes are very quick to recreate and are frequently changing at the moment. 
- If the promotion out of beta/rate-of-change reduces moving forward I can always go back to repopulate, only

HOTT-1757: Drop and completely recreate beta search indexes

---

db/rules_of_origin/roo_schemes_uk/articles/cariforum/wholly-obtained.md
db/rules_of_origin/roo_schemes_uk/articles/central-america/wholly-obtained.md
db/rules_of_origin/roo_schemes_uk/articles/cotedivoire/wholly-obtained.md
db/rules_of_origin/roo_schemes_uk/articles/esa/wholly-obtained.md
db/rules_of_origin/roo_schemes_uk/articles/ghana/wholly-obtained.md
db/rules_of_origin/roo_schemes_uk/articles/kenya/wholly-obtained.md
db/rules_of_origin/roo_schemes_uk/articles/pacific/wholly-obtained.md
db/rules_of_origin/roo_schemes_uk/articles/sacum/wholly-obtained.md
db/rules_of_origin/roo_schemes_uk/articles/south-korea/wholly-obtained.md
spec/features/rules_of_origin_data_spec.rb

[HOTT-1765](https://transformuk.atlassian.net/browse/HOTT-1765)
- of font inconsistencies in the frontend

HOTT 1765 inconsistent font on wholly obtained definition page

---

app/models/rules_of_origin/v2/rule_set.rb
app/serializers/api/v2/rules_of_origin/v2/rule_serializer.rb
spec/models/rules_of_origin/v2/rule_set_spec.rb
spec/serializers/api/v2/rules_of_origin/v2/rule_serializer_spec.rb

HOTT-1701
- A blank string is different from an absence of value and I believe this is an error in the source JSON file
- The original field is not currently required so minimising the API surface we need to support
- Changes an api that is used in production, but undocumented sections of that API which have only recently been deployed so there should be no impact

HOTT-1701 tweaks to roo api additions

---

app/models/goods_nomenclature_description.rb
spec/models/goods_nomenclature_description_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1777
- This is required so we can safely tokenise/match tokens to classifications in beta search

HOTT-1777: Replace non-breaking spaces in indexable descriptions

---

.circleci/config.yml

https://transformuk.atlassian.net/browse/HOTT-1718
- This has been running on a weekly schedule for several weeks now and each job succeeds.
- It is a feature requirement

HOTT-1718: Promote search reference refresh to production

---

.rspec

HOTT-1790
- They are taking too long to run

HOTT-1790 Disable the data specs because they are slow

---

app/models/beta/search/open_search_result.rb
spec/fixtures/beta/search/goods_nomenclatures/serialized_result.json
spec/models/beta/search/open_search_result_spec.rb
spec/serializers/api/beta/chapter_statistics_serializer_spec.rb
spec/serializers/api/beta/heading_statistics_serializer_spec.rb
spec/services/api/beta/search_result_statistics_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1830
- This is required for human understanding of chapter/heading stats

HOTT-1830: Fix missing descriptions in search

---

app/controllers/api/beta/search_controller.rb
app/models/beta/search/intercept_message.rb
app/models/beta/search/open_search_result.rb
app/serializers/api/beta/intercept_message_serializer.rb
app/serializers/api/beta/search_result_serializer.rb
config/locales/en.yml
spec/fixtures/beta/search/goods_nomenclatures/serialized_result.json
spec/models/beta/search/intercept_message_spec.rb
spec/models/beta/search/open_search_result_spec.rb
spec/serializers/api/beta/search_result_serializer_spec.rb

[HOTT-1759](https://transformuk.atlassian.net/browse/HOTT-1759)
- To cater ticket requirements

HOTT-1759 - Permit intercept messages to be used on search terms

---

db/data_migrations/20220815120205_quota_data_fix.rb

[HOTT-1898](https://transformuk.atlassian.net/browse/HOTT-1898)
- Fixes quotas for following codes
Quota | Country | Comm code  URL
-- | -- | --
052012 | AU (Australia) | https://www.trade-tariff.service.gov.uk/commodities/0204221010?country=AU
052105 | AU (Australia) | https://www.trade-tariff.service.gov.uk/commodities/0204230091?country=AU
052106 | AU (Australia) | https://www.trade-tariff.service.gov.uk/commodities/0204230099?country=AU
058020 | Countries subject to UK safeguard measures (5050) | https://www.trade-tariff.service.gov.uk/commodities/7214200010#quotas

HOTT-1898 Adds migration for quota data fix

---

app/controllers/api/v2/rules_of_origin_controller.rb
app/models/rules_of_origin/origin_reference_document.rb
app/models/rules_of_origin/scheme.rb
app/presenters/api/v2/rules_of_origin/scheme_presenter.rb
app/serializers/api/v2/rules_of_origin/origin_reference_document_serializer.rb
app/serializers/api/v2/rules_of_origin/scheme_serializer.rb
db/rules_of_origin/roo_schemes_uk.json
spec/factories/rules_of_origin/origin_reference_document_factory.rb
spec/factories/rules_of_origin/scheme_factory.rb
spec/models/rules_of_origin/origin_reference_document_spec.rb
spec/models/rules_of_origin/scheme_spec.rb
spec/presenters/api/v2/rules_of_origin/scheme_presenter_spec.rb
spec/serializers/api/v2/rules_of_origin/origin_reference_document_serializer_spec.rb
spec/serializers/api/v2/rules_of_origin/scheme_serializer_spec.rb

[HOTT-1870](https://transformuk.atlassian.net/browse/HOTT-1870)
- We need to access Origin reference document attributes on the front end

HOTT-1870: Expose Origin reference document attributes on ROO API

---

db/measurement_units_20220428.json
spec/models/measurement_unit_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1909
- This more clearly indicates that BRX is the unit being used on the confirmation page of the duty calculator

HOTT-1909: Update unit label for BRX measure unit

---

app/lib/tariff_synchronizer/taric_update.rb
app/lib/tariff_synchronizer/taric_update_downloader_patched.rb
spec/unit/tariff_synchronizer/taric_update_downloader_patched_spec.rb
spec/unit/tariff_synchronizer/taric_update_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1928
The initial (and correct) version of the taric file downloader would determine what file to download for a given date (we call this the issue date) by calling an api with the current days date string.
Sadly this date → file api started giving false negative responses (404s). Calling the file api with the expected next sequence of filename worked but asking for the filename on a given issue date didn’t meaning the ETL process for taric was just blocked.
We fixed this by just checking the next sequence we can expect against the filename api using a patched version of the downloader module using a simple factory pattern.
The patched downloader is not aware of the standard of resetting the sequence when the year changes and sadly we don’t …

HOTT-1928: Handle rollover in patched taric downloader

---

app/services/quota_search_service.rb
spec/services/quota_search_service_spec.rb

HOTT-1832
- If a Measure references a QuotaDefinition, and the Measure is not end dated but the quota definition is - then the scope will still include those quota definitions. Subsequent retrieval via association will return `nil` results for these quota definitions which were previously then being excluded via `.compact`
- This works but leaves a `COUNT(*)` on the original scope returning a different value to the number of records the service will actually return - leading to incorrect pagination
- By excluding these end-dated quota definitions from the original query and removing the use of `.compact` the `COUNT(*)` on the scope is correct, and so is the pagination. There shouldn't be any actual change to the quota definitions …

HOTT-1832 Fix quota search pagination

---

app/elastic_search_indexes/cache/heading_index.rb
app/lib/cds_importer/record_inserter.rb
app/lib/sequel/plugins/oplog.rb
app/lib/trade_tariff_backend.rb
app/models/chapter.rb
app/models/commodity.rb
app/models/goods_nomenclature.rb
app/models/heading.rb
app/serializers/cache/heading_serializer.rb
db/migrate/20220908105343_adds_heading_and_chapter_id_to_goods_nomenclatures_view.rb
db/structure.sql
spec/models/commodity_spec.rb
spec/models/goods_nomenclature_spec.rb
spec/models/heading_spec.rb

- Building the heading indexes currently takes days (totally unnacceptable from a team responsiveness perspective).
- Devs validating changes to endpoints that use the heading cache are also massively affected by the slowness
- Faster ETL finish would mean we could push the ETL process later without affecting live users

HOTT-1658: Optimise heading cache performance

---

app/elastic_search_indexes/cache/heading_index.rb
app/lib/sequel/plugins/time_machine.rb
app/lib/trade_tariff_backend.rb
app/models/commodity.rb
app/serializers/cache/heading_serializer.rb
spec/factories/commodity_factory.rb
spec/models/commodity_spec.rb

- This means we can take advantage of the materialized path to work out whether or not a commodity is declarable

HOTT-1658: Adds fast_declarable?

---

app/models/concerns/declarable.rb
spec/models/commodity_spec.rb

- This hasn't been supported functionality since the end of 2016 and complicates the measures association

HOTT-1658: Removes export refund nomenclature query

---

db/data_migrations/20220909093819_fix_description_for_coffins.rb

HOTT-1947
- The description is missing from the original data
- Includes changes to production data

HOTT-1947 Fix description for coffins

---

db/data_migrations/20220909113745_fix_chemical_mixtures_description.rb

HOTT-1948
- The description in the upstream data was blank
- Includes migratory actions which will affect commodity data

HOTT-1948 Fixed description of chemical mixtures

---

app/lib/trade_tariff_backend.rb

- Getting documents that are bigger than what is support by ES

HOTT-1658: Reduce batch size

---

app/controllers/api/v2/validity_periods_controller.rb
app/presenters/api/v2/validity_period_presenter.rb
app/serializers/api/v2/validity_period_serializer.rb
config/routes.rb
spec/presenters/api/v2/validity_period_presenter_spec.rb
spec/requests/api/v2/validity_periods_controller_spec.rb
spec/serializers/api/v2/validity_period_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1617
- This is required for consistency of experience in the subheading UI and enables users to review the history of subheadings when there is no current subheading

HOTT-1617: Adds subheading validity periods

---

app/services/heading_service/heading_serialization_service.rb
spec/controllers/api/v2/headings_controller_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1970
- This change includes the md5 sum of the geographical area id filter
so we distinguish responses between different declarable headings and
their expected measures. Without this we do not recognise changes in the are that's being filtered.

HOTT-1970: Fixes the heading cache key

---

app/models/beta/search/intercept_message.rb
app/serializers/api/beta/intercept_message_serializer.rb
config/locales/en.yml
spec/factories/intercept_message_factory.rb
spec/factories/search_query_parser_result_factory.rb
spec/factories/search_result_factory.rb
spec/fixtures/beta/search/goods_nomenclatures/serialized_result.json
spec/models/beta/search/intercept_message_spec.rb
spec/models/beta/search/open_search_result_spec.rb
spec/serializers/api/beta/intercept_message_serializer_spec.rb
spec/serializers/api/beta/search_result_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1968
- This is required so HMRC can arbitrarily specify goods nomenclature in intercept messages and we generate links for them

HOTT-1968: Generate intercept message links

---

app/lib/trade_tariff_backend.rb
config/sidekiq.yml

https://transformuk.atlassian.net/browse/HOTT-1368
- This has been a long-standing requirement but was made important by the fact that we need to make sure that we can merge the UK/XI clusters which requires the two runs to not exhaust write limits by running at similar times.

HOTT-1368: Separate UK and XI ETL runs

---

.circleci/config.yml

HOTT-<TODO>
- To avoid collisions in the now-moved XI ETL job refresh. The refresh normally takes about 12 minutes so is well within the hour of the ETL job

Avoid staging refresh collisions with xi

---

app/controllers/api/v2/geographical_areas_controller.rb
app/serializers/api/v2/geographical_area_tree_serializer.rb
app/services/cached_geographical_area_service.rb
spec/controllers/api/v2/geographical_areas_controller_spec.rb
spec/factories/geographical_area_factory.rb
spec/serializers/api/v2/geographical_area_tree_serializer_spec.rb
spec/services/cached_geographical_area_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2087
We need this to automate the pipeline for providing XLSX files for HMRC (amongst other people).
- When the file includes a membership in the UK CDS file we need to be able to look up the description by the hjid.
- When the file includes memberships for excluded geographical areas we still want to show these in the file

HOTT-2087: Surface hjid for all geographical areas

---

config/initializers/sentry.rb

HOTT-2006
- Previously we were not reporting any exceptions which resulted in the user seeing the branded 500 page

HOTT-2006 Report exceptions to sentry

---

app/models/beta/search/open_search_result.rb
app/models/beta/search/search_query_parser_result.rb
app/serializers/api/beta/search_query_parser_result_serializer.rb
app/services/api/beta/search_query_parser_service.rb
app/services/api/beta/search_service.rb
spec/factories/search_query_parser_result_factory.rb
spec/factories/search_result_factory.rb
spec/fixtures/beta/search/goods_nomenclatures/serialized_result.json
spec/models/beta/search/open_search_result/no_hits_spec.rb
spec/models/beta/search/open_search_result/with_hits_spec.rb
spec/models/beta/search/open_search_result_spec.rb
spec/models/beta/search/search_query_parser_result/null_spec.rb
spec/serializers/api/beta/search_query_parser_result_serializer_spec.rb
spec/services/api/beta/search_query_parser_service_spec.rb
spec/services/api/beta/search_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2043
- This is required to avoid doing a large uncapped query against the cluster

HOTT-2043: Handle empty search query

---

db/rules_of_origin/roo_schemes_uk.json

HOTT-2127
- Solomon islands is party to that treaty and rules of origin should reflect that
- Low risk

HOTT-2127 Added Solomon Islands to Pacific treaty

---

.circleci/config.yml

HOTT-2120
- We have data specs but they are slow to run so are disabled by default.
- The data specs are hidden behind a RSpec tag which makes them quite undiscoverable and a developer just updating the files might not realise they should be run when the data changes
- Automating this solves both problems
- None - only affects CI runs

HOTT-2120 Run RoO data specs in CI if data changes

---

app/models/beta/search/intercept_message.rb
config/locales/en.yml
spec/models/beta/search/intercept_message_spec.rb
spec/serializers/api/beta/intercept_message_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2139
- Otherwise we can't render these lives with GovSpeak

HOTT-2139: Fixes broken intercept message links

---

app/controllers/api/v2/measure_types_controller.rb
app/controllers/api/v2/preference_codes_controller.rb
config/routes.rb
spec/controllers/api/v2/measure_types_controller_spec.rb
spec/requests/api/v2/preference_codes_controller_spec.rb

[HOTT-<2048>](https://transformuk.atlassian.net/browse/HOTT-2048)
- We need access to measure_type and preference_code on the frontend

HOTT-2048: Exposed API endpoints needed for measure_type page

---

app/controllers/api/admin/quota_order_numbers/quota_definitions_controller.rb
app/models/quota_order_number.rb
app/serializers/api/admin/quota_order_numbers/quota_balance_event_serializer.rb
app/serializers/api/admin/quota_order_numbers/quota_definition_serializer.rb
app/serializers/api/admin/quota_order_numbers/quota_order_number_serializer.rb
config/routes.rb
spec/factories/commodity_factory.rb
spec/factories/quota_factory.rb
spec/models/quota_order_number_spec.rb
spec/requests/api/admin/quota_order_numbers/quota_definitions_controller_spec.rb
spec/serializers/api/admin/quota_order_numbers/quota_balance_event_serializer_spec.rb
spec/serializers/api/admin/quota_order_numbers/quota_definition_serializer_spec.rb
spec/serializers/api/admin/quota_order_numbers/quota_order_number_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2167
- This is required so we can find a specific quota and render its balance events in a graph in the admin UI

HOTT-2167: Adds admin quotas endpoint

---

app/controllers/api/admin/news/items_controller.rb
app/controllers/api/v2/news_items_controller.rb
app/models/news/item.rb
app/serializers/api/admin/news/item_serializer.rb
app/serializers/api/v2/news/collection_serializer.rb
app/serializers/api/v2/news/item_serializer.rb
db/migrate/20221020121609_add_precis_and_slug_to_news_items.rb
db/structure.sql
spec/factories/news_factory.rb
spec/models/news/item_spec.rb
spec/serializers/api/admin/news/item_serializer_spec.rb
spec/serializers/api/v2/news/collection_serializer_spec.rb
spec/serializers/api/v2/news/item_serializer_spec.rb

HOTT-2128
- We will want to use these attributes on the frontend
- We will want to edit these attributes in the admin area
- Significant: Changes `news_items` database table and news items api which is used on _all_ pages

HOTT-2128 Extend news apis

---

app/models/beta/search/open_search_result.rb
app/services/api/beta/search_query_parser_service.rb
app/services/api/beta/search_service.rb
spec/models/beta/search/open_search_result_spec.rb
spec/services/api/beta/search_query_parser_service_spec.rb
spec/services/api/beta/search_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2173
We need to make sure we can redirect to the correct chapter, heading, subheading or commodity depending on what the user searches for.
The rules for this are generally:
- If a chapter/heading short code is searched for, then redirect to the chapter/heading
- If a subheading 6, 8 or 13 code is used then redirect to the subheading
- Redirect to the commodity when 10 digits are passed
- For any other number redirect to the heading 
- The original requirement https://transformuk.atlassian.net/browse/HOTT-1632 asked that no hit results would redirect to the history page. A more consistent approach is to redirect to the relevant goods nomenclature page regardless of the specific search …

HOTT-2173: Move to redirecting for all matched goods nomenclature

---

app/controllers/api/admin/chapters/chapter_notes_controller.rb
app/controllers/api/admin/footnotes_controller.rb
app/controllers/api/admin/news/items_controller.rb
app/controllers/api/admin/rollbacks_controller.rb
app/controllers/api/admin/search_references_base_controller.rb
app/controllers/api/admin/sections/section_notes_controller.rb
app/serializers/api/admin/chapters/chapter_note_serializer.rb
app/serializers/api/admin/sections/section_note_serializer.rb
app/services/api/admin/error_serialization_service.rb
spec/services/api/admin/error_serialization_service_spec.rb
spec/support/shared_examples/v2_search_reference_controller_examples.rb

HOTT-2130
- We can now show backend validation errors in the admin area so we should expose the errors in the appropriate format
- Changes admin api error responses but these should be internal only

HOTT-2130 Model error serialization

---

app/serializers/api/v2/validity_period_serializer.rb
spec/serializers/api/v2/validity_period_serializer_spec.rb

HOTT-<TODO>
- This creates a dependency on heading commodities and doesn't work with expired headings

Remove unused validity periods attribute

---

app/models/measure.rb
spec/factories/geographical_area_factory.rb
spec/factories/measure_excluded_geographical_area_factory.rb
spec/models/measure_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2189
- The CDS team seem to be making extensive use of this referenced area so we need to support filtering it in the declarable responses

Support using referenced geographical areas for applicability of a measure geo area

---

app/models/measure_action.rb
spec/models/measure_action_spec.rb

HOTT-2234
- DIT have changed how the are utilising this measure action code and we are now out of alignment
- Changes how historical pages utilising that code are rendered

HOTT-2234 Treat 07 measure actions codes as positive

---

db/data_migrations/20221115112502_remove_old_measure_components.rb

HOTT-2235
- There were not marked as removed in the CDS extract

HOTT-2235 Remove old measure components

---

app/models/complete_abrogation_regulation.rb
app/models/explicit_abrogation_regulation.rb
spec/factories/explicit_abrogation_regulation_factory.rb
spec/models/complete_abrogation_regulation_spec.rb
spec/models/explicit_abrogation_regulation_spec.rb

Add method role for complete_abrogation_regulation and explicit_abrogation_regulation
To fulfil the interface implemented in all kinds of regulation.

Add more role to abrogation regulations

---

app/controllers/api/v2/news/collections_controller.rb
config/routes.rb
spec/requests/api/v2/news/collections_controller_spec.rb

HOTT-2246
- We will want to list the available collections on the new news UX
- Low, new internal only API

HOTT-2246 add collections api

---

app/controllers/api/v2/news/items_controller.rb
app/models/news/item.rb
config/routes.rb
spec/models/news/item_spec.rb
spec/requests/api/v2/news/items_controller_spec.rb

HOTT-2132
- The replacement news UX needs these features
- The N+1 is caused a stupid implementation detail in the sequel paginate plugin
- Changes in use APIs but they are internal only and should maintain the existing API

HOTT-2132 updated news items api

---

app/formatters/duty_expression_formatter.rb
app/models/measure.rb
spec/models/measure_spec.rb

[HOTT-<2270>](https://transformuk.atlassian.net/browse/HOTT-2270)
- verbose_duty output was incorrect

HOTT-2270: Fixed missing percent symbol in verbose duty

---

spec/controllers/api/v2/certificates_controller_index_spec.rb
spec/controllers/api/v2/measure_actions_controller_spec.rb
spec/controllers/api/v2/measure_condition_codes_controller_spec.rb
spec/controllers/api/v2/measure_types_controller_spec.rb
spec/controllers/api/v2/quota_order_numbers_controller_spec.rb

Removed specs related to the TimeMachine in the controlles: they are not effective, even removing `.actual` from the queries in the controller, specs continue to pass.
- Add specs that actually test when the validity_end_date is set to a past date.
No Jira

Clean up/Refactor spec using TimeMachine

---

app/controllers/api/admin/commodities_controller.rb
spec/requests/api/admin/commodities_controller_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2275
- This is required so we can properly manage search references

HOTT-2275: Fixes copy/paste error in the admin commodities controller

---

db/data_migrations/20221130132800_add_all_of_chapter98_to_hidden_goods_nomenclature_table.rb

[HOTT-<2263>](https://transformuk.atlassian.net/browse/HOTT-2263)
- We need to hide these pages

HOTT-2263: Hide all commodities in chapter 98

---

db/data_migrations/20221130144331_remove_commodity9919000030_from_hidden_goods_nomenclature_table.rb

[HOTT-<2268>](https://transformuk.atlassian.net/browse/HOTT-2268)
- We want to display this commodity

HOTT-2268: Unhide commodity code 9919000030

---

app/controllers/api/v2/news/items_controller.rb
app/models/news/item.rb
spec/models/news/item_spec.rb
spec/requests/api/v2/news/items_controller_spec.rb

We should return an empty list instead of 404
HOTT-2278
- Previously an invalid collection id would return a 404 rather then no news items
- Changes behaviour of the key news item api but in a manner which should make its usage safer

HOTT-2278 dont 404 for news items for unknown collection

---

app/models/news/importer.rb
lib/tasks/news.rake
spec/models/news/importer_spec.rb

HOTT-2314
- We will want nice urls when we switch to the new UX
- None but when running the rake task it will change production data

HOTT-2314 assign slugs to existing stories

---

app/models/beta/search/open_search_result.rb
spec/models/beta/search/open_search_result_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2322
- Its simple enough to handle this here even if technically the short code is in the wrong format
- Discovered as part of performance testing here: https://sentry.io/organizations/engine-le/issues/3790300560/?project=5557002&referrer=slack

HOTT-2322: Redirect single digit searches to chapter

---

app/models/beta/search/goods_nomenclature_query.rb
spec/models/beta/search/goods_nomenclature_query_spec.rb
spec/serializers/api/beta/goods_nomenclature_query_serializer_spec.rb
spec/services/api/beta/search_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2302
- Chapters are too broad and include lots of semantically different adjacent concepts

HOTT-2302: Exclude chapter descriptions from search

---

app/lib/cds_importer/entity_mapper.rb
app/lib/cds_importer/entity_mapper/quota_balance_event_mapper.rb
app/lib/cds_importer/entity_mapper/quota_closed_and_transferred_event_mapper.rb
app/lib/sequel/plugins/oplog.rb
app/models/quota_closed_and_transferred_event.rb
app/models/quota_definition.rb
lib/generators/data_migration_generator.rb
spec/integration/cds_importer/entity_mapper_spec.rb
spec/lib/cds_importer/entity_mapper/quota_closed_and_transferred_event_mapper_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2233
- This is required to make sure that transfer events are getting imported

HOTT-2233: Import quota_closed_and_transferred_events

---

app/serializers/api/v2/quota_order_numbers/quota_definition_serializer.rb
spec/serializers/api/v2/quota_order_numbers/quota_definition_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2297
- This is required for serializing definitions in the frontend

HOTT-2297: Adds missing measurement unit

---

app/models/news/item.rb
spec/models/news/item_spec.rb

HOTT-2241
- All stories belong to collections, so no stories could be removed
- Low, bugfix

HOTT-2241 Fixed removing stories belonging to a collection

---

app/models/news/item.rb
spec/factories/news_factory.rb
spec/models/news/item_spec.rb
spec/presenters/api/v2/news/item_presenter_spec.rb
spec/requests/api/v2/news/items_controller_spec.rb
spec/serializers/api/admin/news/item_serializer_spec.rb
spec/serializers/api/v2/news/item_serializer_spec.rb

HOTT-2164
- We will ultimately want to show all news items in the news area of the frontend within collections
- Changes logic for creation of news items
- Modifies data of existing news items

HOTT-2164 Add validations to news attributes

---

app/models/beta/search/open_search_result.rb
app/models/search_reference.rb
app/serializers/search/goods_nomenclature_serializer.rb
app/services/api/beta/search_service.rb
spec/factories/commodity_factory.rb
spec/factories/search_reference_factory.rb
spec/factories/search_result_factory.rb
spec/models/beta/search/open_search_result/no_hits_spec.rb
spec/models/beta/search/open_search_result/with_hits_spec.rb
spec/models/beta/search/open_search_result_spec.rb
spec/models/search_reference_spec.rb
spec/serializers/search/goods_nomenclature_serializer_spec.rb
spec/services/api/beta/search_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2329
https://transformuk.atlassian.net/browse/HOTT-2358
https://transformuk.atlassian.net/browse/HOTT-2364
- This is required to advance the beta search to support legacy features around search references
- This is required make sure we can promote search reference tokens for partial search reference matches in the with hit search results

HOTT-2329: Search reference handling improvements in beta search

---

app/controllers/api/admin/headings_controller.rb
app/models/goods_nomenclature.rb
app/models/search_reference.rb
app/presenters/api/admin/headings/commodity_presenter.rb
app/presenters/api/admin/headings/heading_presenter.rb
app/serializers/api/admin/headings/commodity_serializer.rb
app/serializers/api/admin/headings/heading_serializer.rb
spec/models/goods_nomenclature_spec.rb
spec/models/search_reference_spec.rb
spec/presenters/api/admin/headings/commodity_presenter_spec.rb
spec/presenters/api/admin/headings/heading_presenter_spec.rb
spec/requests/api/admin/headings_controller_spec.rb
spec/serializers/api/admin/headings/commodity_serializer_spec.rb
spec/serializers/api/admin/headings/heading_serializer_spec.rb

HOTT-2361
There are 2 key sources of N+1 on the admin headings API - inclusion of declarable field for child commodities, and inclusion of counts for those commodities. 
- declarable is cached so will hopefully avoid those queries in production
- counting the search refs for the commodities
By using a grouped count 1300 queries are removed from api requests for large headings
- Low, only affects admin API

HOTT-2361 timeouts from search references reduce counts

---

app/formatters/description_formatter.rb
spec/formatters/description_formatter_spec.rb

[HOTT-<2310>](https://transformuk.atlassian.net/browse/HOTT-2310)
- XI and UK need to display different text

HOTT-2310: Used regex to change text on UK version

---

app/lib/cds_importer.rb
app/lib/cds_importer/entity_mapper.rb
app/lib/cds_importer/entity_mapper/quota_closed_and_transferred_event_mapper.rb
app/lib/cds_importer/record_inserter.rb
spec/integration/cds_importer/cds_importer_spec.rb
spec/integration/tariff_synchronizer/cds_update_spec.rb
spec/lib/cds_importer/entity_mapper/quota_closed_and_transferred_event_mapper_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2390
- The daily files can include transfer out and transfer in events. I didn't notice this until this morning since most files only have one event per quota definition primary node.
- I wanted the skipped feedback just for development purposes the ability to review skipped transfer nodes

HOTT-2390: Add support for multiple transfer events

---

app/services/api/beta/search_query_parser_service.rb
app/services/api/beta/search_service.rb
spec/requests/api/beta/search_controller_spec.rb
spec/services/api/beta/search_query_parser_service_spec.rb
spec/services/api/beta/search_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2392
- This is required as part of the beta search functionality

HOTT-2392: Fixes bug with redirecting search references

---

app/elastic_search_indexes/search/goods_nomenclature_index.rb
app/models/beta/search/goods_nomenclature_query.rb
app/models/beta/search/intercept_message.rb
app/models/beta/search/open_search_result.rb
app/models/goods_nomenclature.rb
app/serializers/api/beta/goods_nomenclature_serializer.rb
app/serializers/search/goods_nomenclature_serializer.rb
data/intercept-messages.yml
spec/factories/intercept_message_factory.rb
spec/models/beta/search/goods_nomenclature_query_spec.rb
spec/models/beta/search/intercept_message_spec.rb
spec/models/goods_nomenclature_spec.rb
spec/serializers/api/beta/goods_nomenclature_query_serializer_spec.rb
spec/serializers/api/beta/search_result_serializer_spec.rb
spec/serializers/search/goods_nomenclature_serializer_spec.rb
spec/services/api/beta/search_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2373
- This is required so that we can use the intercept messages as part of search at the subheading and commodity levels.
- Intercept messages have valuable hand-crafted meaning in them

HOTT-2373: Make intercept message search terms searchable 

---

db/data_migrations/20230103143452_remove_vanuatu_from_geographical_group.rb

HOTT-2408
- It should never have been in that geographical area group
- Data migration

HOTT-2408 Remove Vanuatu from Geographical Area 1400

---

app/services/slack_notifier_service.rb
config/initializers/slack_notifier.rb
spec/services/slack_notifier_service_spec.rb

HOTT-<TODO>
- This is not important information and is something a developer that is configuring the service should just be able to fix

Kill slack notifier noise

---

app/serializers/api/v2/quotas/order_number/quota_definition_serializer.rb
spec/serializers/api/v2/quotas/order_number/quota_definition_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2414
The commodity api response with the quota definition in it for the quota measures needs to actually return the correct allocation date and not just return the occurrence timestamp.
- These values are just wrong and were discovered by our users
- This has been wrong since this feature was implemented https://github.com/trade-tariff/trade-tariff-backend/commit/9bbad5984e459405b9697f573fea73049fc8949f

HOTT-2414: Fix bug in last allocation date

---

db/data_migrations/20230104093551_goods_description_fixes.rb

https://transformuk.atlassian.net/browse/HOTT-2396
- It is borked

HOTT-2396: Fixes borked subheading description

---

config/initializers/rack_timeout.rb

HOTT-2238
- This is spamming the logs in NewRelic generating 4 times as much 'noise' as useful logging data
- Should be low - just changing log levels

HOTT-2238 Remove rack timeout noise from logs

---

config/initializers/console_time_machine.rb

HOTT-????
- It is far far more likely you'll want it set to today rather then unset
- I often forget to set it in debugging sessions and just causes confusion
- New developers wont know to set the thread variable and will be equally confused
- Patches rails code

Set TimeMachine to today in console

---

app/lib/trade_tariff_backend.rb

HOTT-????
- Previously this was 5 seconds - this meant that we only avoided problems from multiple tariff syncs running concurrently for the first 5 seconds of the sync.
- If the job completes before the 10 minutes then the lock is released upon completion anyway.
- Impacts overnight sync

Increase max lifetime of the redis lock to 10 mins

---

.rubocop.yml
lib/tasks/tariff.rake

HOTT-????
- `rake tariff:sync` was broken
- download and apply doesn't convey that unlike other tariff tasks this is going to perform a very long running action
- linter was complaining
- linter was complaining
- Low

Fix tariff sync rake task

---

app/models/rollback.rb
config/initializers/sidekiq.rb

HOTT-2210
- The current value (a Date object) is raising errors, so instead I'm using a 'db formatted' date - this simple, easily readable in the logs, unambiguous and avoids including potentially incorrect time and zone information since this is subsequently ignored by the Rollback model.
- This is a preliminary fix for the other sidekiq 7 related changes
- Low - new jobs get serialized in a different format but the Rollback model understands both old and new formats anyway

HOTT-2210 Avoid serialization warnings from Sidekiq

---

app/serializers/api/admin/headings/commodity_serializer.rb

HOTT-2361
- Whilst it still has a high query count, the ruby processing over head is much less and this allows the search references pages to complete within the timeout
- Low, only impacts admin API

HOTT-2361 Use fast_declarable to speed up admin api

---

app/workers/spelling_file_uploader_worker.rb
config/sidekiq.yml
spec/workers/spelling_file_uploader_worker_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2372
- This is required to update the spelling model everyday as data changes

HOTT-2372: Adds sidekiq job for uploading new spelling model

---

.circleci/config.yml

https://transformuk.atlassian.net/browse/HOTT-2442
- This is required to keep us updated with search references on all environments and to make validation easier

HOTT-2442: Renew search references on staging and development

---

app/controllers/api/admin/quota_order_numbers/quota_definitions_controller.rb
spec/factories/quota_factory.rb

https://transformuk.atlassian.net/browse/HOTT-2226
- This occurs when the quota definition is non-current but the quota order number is current

HOTT-2226: Fix issue with non-current quota definition

---

app/lib/cds_importer/entity_mapper/footnote_association_goods_nomenclature_mapper.rb
app/lib/cds_importer/entity_mapper/goods_nomenclature_description_period_mapper.rb
app/lib/cds_importer/entity_mapper/goods_nomenclature_indent_mapper.rb
app/lib/cds_importer/entity_mapper/goods_nomenclature_mapper.rb
spec/factories/footnote_factory.rb
spec/factories/goods_nomenclature_factory.rb
spec/lib/cds_importer/entity_mapper/goods_nomenclature_mapper_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1596
- This is required to make sure we're clearing out indents that are no longer supplied at the end of the indent sequence (e.g. ironing boards being fixed by removal)

HOTT-1596: Adds implicit deletion to goods nomenclature primary

---

app/lib/cds_importer/entity_mapper/quota_order_number_origin_exclusion_mapper.rb
spec/lib/cds_importer/entity_mapper/quota_order_number_origin_exclusion_mapper_spec.rb

HOTT-2326
- The mapper was failing to import QuotaOrderNumberOriginExclusions
- Low, changes sync - should fix the problem

HOTT-2326 Fix CDS Importer for QuotaOrderNumberOriginExclusions

---

app/models/measure_collection.rb
app/presenters/api/v2/commodities/commodity_presenter.rb
app/presenters/api/v2/headings/declarable_heading_presenter.rb
spec/factories/measure_factory.rb
spec/models/measure_collection_spec.rb
spec/models/preference_code_spec.rb
spec/presenters/api/v2/commodities/commodity_presenter_spec.rb
spec/presenters/api/v2/headings/declarable_headings_presenter_spec.rb
spec/serializers/api/v2/commodities/commodity_serializer_spec.rb
spec/serializers/api/v2/headings/declarable_heading_serializer_spec.rb

HOTT-2447
- Measure type 464 is specific to a country, without knowing the country we cannot know whether it is an authorised_use_provisions_submission
- Low, does change the api values

HOTT-2447 Apply measure type 464 when filtering by country

---

app/models/measure_collection.rb
spec/models/measure_collection_spec.rb

HOTT-2491
- it the data requested does not exist and we should return an appropriate status code instead of erroring out
- Changes behaviour of an in use API

HOTT-2491 Return 404 when unknown country code

---

.circleci/config.yml

https://transformuk.atlassian.net/browse/HOTT-2487
- This is required by the DIT data engineers to make sure they've got the latest snapshot of the data

HOTT-2487: Adds database backup job and Sunday workflow

---

app/models/quota_definition.rb
app/serializers/api/v2/quotas/order_number/quota_definition_serializer.rb
app/serializers/api/v2/quotas/quota_definition_serializer.rb
spec/models/quota_definition_spec.rb
spec/serializers/api/v2/quotas/order_number/quota_definition_serializer_spec.rb
spec/serializers/api/v2/quotas/quota_definition_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2555
- This is required to reflect when HMRC started managing balance transfers

HOTT-2555: Hide past transfer events

---

app/lib/tariff_synchronizer/cds_update.rb
app/lib/tariff_synchronizer/taric_update.rb
app/lib/tariff_synchronizer/tariff_downloader.rb
spec/unit/tariff_synchronizer/tariff_downloader_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2573
- This was non-SAX parsing and undermining the whole point of using an
event driven parsing implementation
- We had no coverage of this behaviour and needed it

HOTT-2573: Remove insane duplicate XML validation

---

app/lib/spelling_corrector/loaders/origin_reference.rb
app/services/spelling_corrector/file_updater_service.rb
spec/fixtures/spelling_corrector/origin_reference/bar.txt
spec/fixtures/spelling_corrector/origin_reference/foo.txt
spec/lib/spelling_corrector/loaders/origin_reference_spec.rb
spec/services/spelling_corrector/file_updater_service_spec.rb
spec/support/shared_contexts/with_a_stubbed_s3_bucket.rb

https://transformuk.atlassian.net/browse/HOTT-2553
- This is required so that the spelling functionality can understand origin reference terms

HOTT-2553: Adds origin reference spelling model loader

---

app/lib/cds_importer/entity_mapper/quota_order_number_mapper.rb
app/lib/cds_importer/entity_mapper/quota_order_number_origin_exclusion_mapper.rb
app/lib/cds_importer/entity_mapper/quota_order_number_origin_mapper.rb
app/lib/cds_importer/xml_parser.rb
app/models/quota_order_number_origin.rb
spec/factories/quota_factory.rb
spec/lib/cds_importer/entity_mapper/quota_order_number_mapper_spec.rb
spec/lib/cds_importer/entity_mapper/quota_order_number_origin_mapper_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1613
- The excess content has no impact - it just looks weird in a console
- This will mean that when CDS/DIT/TAP produce a file which is missing some order number secondaries in it we will clear them out

HOTT-1613: Quota order number missing deletes

---

app/lib/cds_importer/entity_mapper/quota_association_mapper.rb
app/lib/cds_importer/entity_mapper/quota_critical_event_mapper.rb
app/lib/cds_importer/entity_mapper/quota_exhaustion_event_mapper.rb
app/lib/cds_importer/entity_mapper/quota_reopening_event_mapper.rb
app/lib/cds_importer/entity_mapper/quota_suspension_period_mapper.rb
app/lib/cds_importer/entity_mapper/quota_unsuspension_event_mapper.rb
app/models/quota_blocking_period.rb
app/models/quota_exhaustion_event.rb
app/models/quota_reopening_event.rb
app/models/quota_unblocking_event.rb
app/models/quota_unsuspension_event.rb

https://transformuk.atlassian.net/browse/HOTT-2590
- The current status of a quota definition can change multiple times (e.g. become exhausted, then critical and back again). This wouldn't be reflected if the exhausted could only exist once in the history of the quota definition. We may also want to plot these events on the graph in the admin UI at a later date.
- The blocking period model was not using its correct primary key

HOTT-1612: Update primary keys of quota definition secondaries

---

app/lib/cds_importer/entity_mapper/quota_closed_and_transferred_event_mapper.rb
spec/lib/cds_importer/entity_mapper/quota_closed_and_transferred_event_mapper_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2593
- Adds failing spec to capture transferred_amount issue
- Removes check on transferred amount to find equivalent node (making the test pass)
- This is required to make sure we can import transfer events that have a different string representation for their transferred amounts than what we would pull out of the model
```ruby
a = event.transferred_amount.to_s => "1444634.0"
b = xml_node_event['transferredAmount'] => "1444634"
a == b => false
```

HOTT-2593: Remove brittle check of transferred amount

---

app/lib/cds_importer/entity_mapper/geographical_area_description_mapper.rb
app/lib/cds_importer/entity_mapper/geographical_area_description_period_mapper.rb
app/lib/cds_importer/entity_mapper/geographical_area_mapper.rb
spec/controllers/api/v1/headings_controller_spec.rb
spec/factories/geographical_area_factory.rb
spec/factories/goods_nomenclature_factory.rb
spec/factories/measure_factory.rb
spec/factories/quota_factory.rb
spec/lib/cds_importer/entity_mapper/geographical_area_description_period_mapper_spec.rb
spec/lib/cds_importer/entity_mapper/geographical_area_mapper_spec.rb
spec/models/geographical_area_spec.rb
spec/serializers/api/v2/geographical_area_tree_serializer_spec.rb
spec/serializers/cache/search_cache_methods_spec.rb
spec/services/cached_commodity_service_spec.rb
spec/services/cached_geographical_area_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1595
- This is required because we can expect to receive instructions to delete entities implicitly by CDS

HOTT-1595: Handle missing geographical area entities

---

app/lib/cds_importer/entity_mapper.rb
app/lib/cds_importer/entity_mapper/base_mapper.rb
app/lib/cds_importer/entity_mapper/quota_closed_and_transferred_event_mapper.rb
spec/lib/cds_importer/entity_mapper/base_mapper_spec.rb
spec/support/shared_examples/an_entity_mapper.rb

https://transformuk.atlassian.net/browse/HOTT-2595
- This is required to simplify any reverse engineering of the attributes that are applicable for the current invocation of a before insert callback. Where before we tried to determine surrounding attributes of a given model instance, now we can just ask for them from the passed in expanded attributes

HOTT-2595: Fixes smelly design and reverse engineering attributes

---

.circleci/config.yml

HOTT-<TODO>
- This is to make sure we're aware of release day test failures

Notify regression channel when flaky tests fail before release

---

Gemfile
Gemfile.lock
app/lib/sequel/plugins/elasticsearch.rb
app/lib/trade_tariff_backend.rb
app/services/search_service/fuzzy_search.rb
app/workers/build_index_page_worker.rb
docker-compose.yml
spec/integration/tariff_synchronizer_spec.rb
spec/rails_helper.rb

https://transformuk.atlassian.net/browse/HOTT-2605
You can see that the maintainers are the same for both gems - the api is also exactly the same:
- We've been pinned to an older version of the elasticsearch gem (maintained by the same people and with the same api) for a long time now. I generally don't like not being able to upgrade gems and this solves that.
- In my local docker-compose I've been using 2.x for a while now - this reflects what we're using in aws, too

HOTT-2605: Migrate to opensearch client

---

app/controllers/api/v2/quota_order_numbers_controller.rb
app/services/cached_quota_order_number_service.rb
app/workers/clear_cache_worker.rb
app/workers/prewarm_quota_order_numbers_worker.rb
spec/controllers/api/v2/quota_order_numbers_controller_spec.rb
spec/services/cached_quota_order_number_service_spec.rb
spec/workers/clear_cache_worker_spec.rb
spec/workers/prewarm_quota_order_numbers_worker_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2577
- This is needed to make sure the change XLSX reports we generate for HMRC have the data they need ahead of a busy morning

HOTT-2577: Prewarm quota order numbers after sync

---

app/lib/trade_tariff_backend.rb
app/workers/build_index_page_worker.rb

https://transformuk.atlassian.net/browse/HOTT-2605
- This is required to make updating the client configuration simpler and to fix broken configuration I missed

HOTT-2605: Consolidate all opensearch client configuration

---

app/controllers/api/v2/footnotes_controller.rb
app/serializers/api/v2/footnotes/footnote_serializer.rb
spec/controllers/api/v2/footnotes_controller_spec.rb
spec/serializers/api/v2/footnotes/footnote_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2495
- This is a feature request

HOTT-2495: Adds start/end dates to footnote api

---

app/services/api/beta/search_service.rb
spec/services/api/beta/search_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2382
- This fixes: https://sentry.io/organizations/engine-le/issues/3812759750/?project=5557005&query=url%3A%22https%3A%2F%2Fwww.trade-tariff.service.gov.uk%2Fuk%2Fapi%2Fbeta%2Fsearch%22&referrer=issue-stream

HOTT-2382: Handle null query

---

spec/spec_helper.rb

This reverts commit 4ed74faabef2488cf7b661f807406546461ad2ec.
Standard RSpec feature - in use by developers

Revert "HOTT-2574: Kill totally unused/misleading tag"

---

app/lib/cds_importer/xml_parser.rb
app/lib/taric_importer/xml_parser.rb
spec/lib/cds_importer/xml_parser_spec.rb
spec/lib/taric_importer/xml_parser_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2631
- This is causing footnote descriptions to not be imported in the XI service.
- We would have been alerted to this not working on the UK service although I'm sure we will encounter it eventually

HOTT-2631: Fix bug in Taric importer

---

.rubocop.yml
app/controllers/api/admin/sections_controller.rb
app/models/chapter.rb
app/models/commodity.rb
app/models/concerns/search_referenceable.rb
app/models/heading.rb
app/models/search_reference.rb
app/models/section.rb
app/models/subheading.rb
app/serializers/api/admin/sections/section_list_serializer.rb
app/serializers/api/admin/sections/section_serializer.rb
app/serializers/search/goods_nomenclature_serializer.rb
app/services/search_service/exact_search.rb
app/views/api/v1/sections/index.json.rabl
app/views/api/v1/sections/show.json.rabl
spec/controllers/api/admin/chapters/search_references_controller_spec.rb
spec/controllers/api/admin/commodities/search_references_controller_spec.rb
spec/controllers/api/admin/headings/search_references_controller_spec.rb
spec/controllers/api/v1/sections_controller_spec.rb
spec/controllers/api/v2/search_controller_suggestions_spec.rb
spec/controllers/api/v2/search_references_controller_spec.rb
spec/models/search_reference_spec.rb
spec/serializers/search/search_reference_serializer_spec.rb
spec/services/search_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2381
- This reduces a lot of the complexity around search references and enables the eventual removal of the now-redundant referenced_id field

HOTT-2381: Tidy up search reference associations

---

app/models/goods_nomenclature.rb
app/models/goods_nomenclature_origin.rb

https://transformuk.atlassian.net/browse/HOTT-2622
- This enables us to ask the goods nomenclature whether it is an origin of
any other goods nomenclature and for their validity start/end dates

HOTT-2622: Adds succeeding/preceeding relationships for origins

---

app/models/goods_nomenclature.rb

https://transformuk.atlassian.net/browse/HOTT-2622
- This enables us to ask the goods nomenclature whether it is an origin of
any other goods nomenclature and for their validity start/end dates

HOTT-2622: Fix goods nomenclature origins relationship

---

app/controllers/api/v2/rules_of_origin_controller.rb
app/serializers/api/v2/rules_of_origin/scheme_serializer.rb
spec/factories/rules_of_origin/scheme_set_factory.rb
spec/requests/api/v2/rules_of_origin_controller_spec.rb
spec/serializers/api/v2/rules_of_origin/scheme_serializer_spec.rb

HOTT-2565
- we need to show all schemes plus their proofs on a single page on the frontend
- Low

HOTT-2565 Include proofs in all schemes api

---

app/controllers/api/v2/validity_periods_controller.rb
app/models/goods_nomenclature.rb
app/presenters/api/v2/validity_period_presenter.rb
app/serializers/api/v2/shared/goods_nomenclature_serializer.rb
app/serializers/api/v2/validity_period_serializer.rb
app/services/validity_period_serializer_service.rb
spec/controllers/api/v2/additional_codes_controller_spec.rb
spec/controllers/api/v2/certificates_controller_search_spec.rb
spec/controllers/api/v2/quotas_controller_spec.rb
spec/factories/goods_nomenclature_factory.rb
spec/presenters/api/v2/validity_period_presenter_spec.rb
spec/requests/api/v2/validity_periods_controller_spec.rb
spec/serializers/api/v2/validity_period_serializer_spec.rb
spec/services/validity_period_serializer_service_spec.rb
spec/support/shared_examples/a_serialized_goods_nomenclature.rb

https://transformuk.atlassian.net/browse/HOTT-2622
- This enables a full history review of where the goods nomenclatures have moved in the hierarchy

HOTT-2622: Surface deriving goods nomenclatures

---

app/presenters/api/v2/validity_period_presenter.rb
spec/presenters/api/v2/validity_period_presenter_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2622
- On day 0 we started from EU goods nomenclature, measures, etc. Most of this data just isn't pertinent to changes made by the CDS and DIT teams

HOTT-2622: Filter deriving goods nomenclatures that start after Brexit

---

app/lib/tariff_synchronizer/base_update.rb
app/lib/tariff_synchronizer/tariff_downloader.rb
spec/unit/tariff_synchronizer/tariff_downloader_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2576
- Rather than being specific about an error that will never be raised this moves us to more general handling of generally uncaught exceptions below StandardError and attaches their details to the specific update that we're failing to download. The idea is that this will give us more information about what has gone wrong with the downloader

HOTT-2576: Handle tariff downloader exceptions

---

app/workers/clear_invalid_search_references.rb
spec/workers/clear_invalid_search_references_spec.rb

Remove excess slack notifications on clearing search references

---

db/migrate/20230207114821_drop_referenced_id_on_search_references.rb
db/structure.sql

https://transformuk.atlassian.net/browse/HOTT-2381
- This is part of us migrating to a more sensible relationship layout for search references - next step involves renaming the goods_nomenclature_sid column to be referenced_id to conform to polymorphic standards of associations

HOTT-2381: Drop referenced_id column

---

spec/support/database_cleaner.rb

HOTT-2700
- It solves data being left around by specs if they created the data in an `around` block
If factories are created in an RSpec `around` hook, they continue to persist after the RSpec example completes and DatabaseCleaner has supposedly cleaned the database.
This is because DatabaseCleaner currently runs in the `before` and `after` RSpec hooks, which run after the `around` hook.
This means the database transaction is started after the data is created and so the transaction rollback doesn't actually remove it.
Moving the transaction start to an `around` hook (and hence higher priority) solves this problem.
- None - changes to testing infrastructure

HOTT-2700 Fix database cleaner with rspec `around` hook

---

app/controllers/api/v2/additional_codes_controller.rb
app/elastic_search_indexes/cache/additional_code_index.rb
app/serializers/cache/additional_code_serializer.rb
app/services/additional_code_search_service.rb
spec/controllers/api/v2/additional_codes_controller_spec.rb
spec/elastic_search_indexes/cache/additional_code_index_spec.rb
spec/serializers/cache/additional_code_serializer_spec.rb
spec/services/additional_code_search_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2699
- We get a lot of garbage in the search results and have a lot of special snowflaking around meursing goods nomenclatures
- This should also significantly speed up ETL in the am

HOTT-2699: Adds filtering to additional code dataset and serializer filter

---

spec/controllers/api/v1/commodities_controller_spec.rb
spec/controllers/api/v1/headings_controller_spec.rb
spec/controllers/api/v2/commodities_controller_spec.rb
spec/controllers/api/v2/goods_nomenclatures_controller_spec.rb
spec/controllers/api/v2/headings_controller_spec.rb
spec/factories/chapter_factory.rb
spec/factories/commodity_factory.rb
spec/factories/goods_nomenclature_factory.rb
spec/factories/heading_factory.rb
spec/lib/cds_importer/entity_mapper/goods_nomenclature_mapper_spec.rb
spec/models/goods_nomenclature_spec.rb
spec/presenters/api/v2/commodities/commodity_presenter_spec.rb
spec/rails_helper.rb
spec/serializers/api/v2/commodities/commodity_serializer_spec.rb
spec/services/cached_commodity_service_spec.rb

HOTT-2688
The Nested Set relies heavily on the ability to create multiple hierarchies reliably 
- as part of that work I was running into both outright collisions on sids
- factories obscuring data they'd just created due to how the oplog handles duplicate sids
- fixing up some of this hardcoding in term broke a lot of existing specs relating to materialized path because the factories were hardcoding a hierarchy which was no longer correct. Hence I've refactored it to use a transient parent attribute and use that for dynamic generation of materialized paths `path` column
- NestedSet will rely on correct generation of `item_id` to support its hierarchy logic - ie creating 2 commodities should result in 2 siblings, not the second …

HOTT-2688 Refactored GoodsNomenclature factories

---

app/controllers/api/admin/news/collections_controller.rb
app/serializers/api/admin/news/collection_serializer.rb
config/routes.rb
spec/requests/api/admin/news/collections_controller_spec.rb
spec/serializers/api/admin/news/collection_serializer_spec.rb

[HOTT-<TODO>](https://transformuk.atlassian.net/browse/HOTT-2305)
- We need access to this API so we can Display, create, update data on admin

HOTT-2305: Exposed news collection API endpoints

---

app/controllers/api/admin/headings_controller.rb
app/models/concerns/ten_digit_goods_nomenclature.rb
app/models/goods_nomenclature.rb
app/presenters/api/admin/headings/heading_presenter.rb
app/serializers/api/admin/csv/goods_nomenclature_serializer.rb
app/serializers/search/goods_nomenclature_serializer.rb
spec/models/goods_nomenclature_spec.rb
spec/presenters/api/admin/headings/heading_presenter_spec.rb

HOTT-2732
- It avoids them being shadowed by methods on on `Commodity` (which inherits from `GoodsNomenclature`)
- It unblocks fixing the single table inheritance loader
- Does change code in use in production AFAICT, but its new code so should be covered by specs

HOTT-2732 Rename materialised path relationships

---

app/serializers/api/admin/headings/commodity_serializer.rb

HOTT-2732
- The rename has broken the commodity search refs screens in the admin area

HOTT-2732 Fix for use of GoodsNomenclature#declarable?

---

app/lib/sequel/plugins/sti.rb
spec/controllers/api/v2/goods_nomenclatures_controller_spec.rb
spec/controllers/api/v2/quotas_controller_spec.rb
spec/models/goods_nomenclature_spec.rb

HOTT-2692
- It makes it much easier to use eager loadable methods if they can return the correct classes
- Changes anywhere relying on GoodsNomenclature being returned to instead return Chapter/Heading/Commodity
- I _think_ this should only affect components using materialised path - which already utilise an additional attribute to describe their 'type'
- Commodity CSV Report
- Admin Headings optimisations
- Beta search (not yet in use)

HOTT-2692 Fix single table inheritance

---

app/elastic_search_indexes/search/goods_nomenclature_index.rb

HOTT-2732
- it was broken by the rename from `ancestors` to `path_ancestors`
- Low

HOTT-2732 Fix missing eager load rename

---

spec/models/beta/search/direct_hit_spec.rb
spec/models/search_reference_spec.rb

HOTT-2736
- It gets immediately binned by the `TRUNCATE` at the start of the lifecycle
- It breaks the materialized view work
- None - spec changes

HOTT-2736 Avoid creation of data outside spec lifecycle

---

app/controllers/api/v2/search_controller.rb
app/models/search_suggestion.rb
app/serializers/api/v2/search_suggestion_serializer.rb
app/services/api/v2/suggestions_service.rb
app/services/base_suggestions_service.rb
app/services/search_suggestion_populator_service.rb
app/workers/populate_search_suggestions_worker.rb
config/sidekiq.yml
db/migrate/20230225194140_create_table_suggestions.rb
db/structure.sql
spec/controllers/api/v2/search_controller_search_spec.rb
spec/controllers/api/v2/search_controller_suggestions_spec.rb
spec/factories/search_suggestion_factory.rb
spec/models/search_suggestion_spec.rb
spec/serializers/api/v2/search_suggestion_serializer_spec.rb
spec/services/api/v2/suggestions_service_spec.rb
spec/services/search_suggestion_populator_service_spec.rb
spec/workers/populate_search_suggestions_worker_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2733
- This is required to enable a new implementation of the search suggestions UI

HOTT-2733: Adds fuzzy search suggestion capability

---

app/models/concerns/ten_digit_goods_nomenclature.rb
app/models/measure_type.rb
spec/factories/measure_factory.rb
spec/models/commodity_spec.rb
spec/models/measure_type_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2716
- This is a feature request that resulted from strange data

HOTT-2716: Filter out non-erga omnes overview VAT measures

---

app/models/quota_order_number.rb

https://transformuk.atlassian.net/browse/HOTT-2806
- This is required so that they are sensibly ordered for the admin UI

HOTT-2806: Order quota definitions

---

app/formatters/description_formatter.rb
spec/formatters/description_formatter_spec.rb

[HOTT-<TODO>](https://transformuk.atlassian.net/browse/HOTT-2750)
- the HTML is broken and we need to fix it on our end

HOTT-2750: Fixed footnotes HTML using regex

---

app/models/beta/search/search_facet_classifier_configuration.rb
spec/models/beta/search/search_facet_classifier_configuration_spec.rb
spec/services/api/beta/classification_converter_service_spec.rb
spec/services/api/beta/goods_nomenclature_filter_generator_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2812
- This classification category needs a bit of work/is misfiring a bit and could probably benefit from filtering on certain headings a bit more specifically

HOTT-2812: Filter out entity classifications

---

app/models/healthcheck.rb
spec/controllers/healthcheck_controller_spec.rb
spec/models/healthcheck_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2823
- This is required as part of our smoketesting of our infrastructure

HOTT-2823: Extend healthchecks to include additional checks

---

app/elastic_search_indexes/search/goods_nomenclature_index.rb
app/models/beta/search/goods_nomenclature_query.rb
app/models/beta/search/search_query_parser_result.rb
app/serializers/api/beta/search_query_parser_result_serializer.rb
app/serializers/search/goods_nomenclature_serializer.rb
spec/factories/goods_nomenclature_query_factory.rb
spec/factories/search_query_parser_result_factory.rb
spec/fixtures/beta/search/goods_nomenclatures/serialized_result.json
spec/models/beta/search/goods_nomenclature_query_spec.rb
spec/models/beta/search/search_query_parser_result/null_spec.rb
spec/models/beta/search/search_query_parser_result/standard_spec.rb
spec/serializers/api/beta/search_query_parser_result_serializer_spec.rb
spec/serializers/search/goods_nomenclature_serializer_spec.rb
spec/services/api/beta/search_query_parser_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2813
- This is actually a feature request from HMRC and allows them to bypass lemmatization, spelling correction and just do match phrase queries against the index

HOTT-2813: Support quoted search queries

---

app/services/appendix_5a_populator_service.rb
spec/services/appendix_5a_populator_service_spec.rb

HOTT-<TODO>
- The majority of days are no change days and this is just noise

Reduce noise around append 5a updates

---

app/models/quota_definition.rb

[HOTT-<2808>](https://transformuk.atlassian.net/browse/HOTT-2808)
- We need them in this order on the Admin app

HOTT-2808: Sort quota balance events by occurrence_timestamp

---

app/models/beta/search/goods_nomenclature_query.rb
spec/factories/goods_nomenclature_query_factory.rb
spec/models/beta/search/goods_nomenclature_query_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2835
- This is required to handle generally garbage content that might be thrown at spacy/textblob in the search query parser and have performance implications. The idea is, sometimes we might have some non-garbage content and we still want performant search results for these

HOTT-2835: Adds support for fallback queries

---

app/services/api/v2/suggestions_service.rb
app/services/search_suggestion_populator_service.rb
spec/services/search_suggestion_populator_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2840
- We have a bunch of expired search suggestions that are cluttering up the typeahead

HOTT-2840: Clear expired goods nomenclature from suggestions

---

app/models/goods_nomenclatures/tree_node.rb
app/workers/rollback_worker.rb
app/workers/updates_synchronizer_worker.rb
db/migrate/20230210140401_add_goods_nomenclature_tree_nodes.rb
db/seeds.rb
db/structure.sql
docs/adr/2023-02-07_goods-nomenclature-nested-set.md
docs/goods-nomenclature-nested-set.md
lib/tasks/data_migrations.rake
spec/factories/goods_nomenclature_factory.rb
spec/models/goods_nomenclatures/tree_node_spec.rb
spec/rails_helper.rb
spec/workers/rollback_worker_spec.rb
spec/workers/updates_synchronizer_worker_spec.rb

HOTT-2639
- tree nodes view is a 'better' indents table which allows for 'nested set' access to the tariff hierarchy
- maintenance of this view should be low, hence integrating refreshing it with anything which modify the data
- normally we want a concurrent refresh since that doesn't block other queries, but we cannot use a concurrent refresh on a newly create view, so specs need a 'non-concurrent' refresh done at the start
- Should be low, its just adding adding a view, the only behavioural change should be tariff sync and data migrations refresh that view

HOTT-2639 add `goods_nomenclature_tree_nodes` materialized view

---

app/models/search_suggestion.rb
spec/models/search_suggestion_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2852
- This is required to make sure we're returning results that make sense for goods nomenclature short codes and full item ids
- Using a similarity filter on the short codes made no sense from a user perspective

HOTT-2852: Support more sensible digit search suggestions

---

app/models/goods_nomenclatures/tree_node.rb

To avoid deadlocks
HOTT-2870
- If the refresh occurs under heavy read load (eg morning cache rebuild) it is causing dead locks in the workers
- Low, does mean page loads may pause for a couple of seconds during deploys and nightly syncs but we have plenty of pages loading slower then that anyway

HOTT-2870 Default to non-concurrent refreshes

---

app/controllers/api/v2/chapters_controller.rb
spec/requests/api/v2/chapters_controller_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2879
- This is a temporary fix just to diminish the impacts of users scripting concurrent requests to chapter endpoints

HOTT-2879: Cache chapter responses

---

app/lib/sequel/plugins/time_machine.rb
app/models/goods_nomenclature.rb
app/models/goods_nomenclatures/nested_set.rb
app/models/goods_nomenclatures/tree_node.rb
app/models/goods_nomenclatures/tree_node_alias.rb
spec/factories/chapter_factory.rb
spec/factories/goods_nomenclature_factory.rb
spec/factories/heading_factory.rb
spec/lib/sequel/plugins/time_machine_spec.rb
spec/models/goods_nomenclatures/nested_set_spec.rb
spec/models/goods_nomenclatures/tree_node_alias_spec.rb
spec/models/goods_nomenclatures/tree_node_spec.rb

HOTT-2640
- I want fast time machine compatible mechanisms to query the hierarchy
- Purely addition of unused relationships so should be safe

HOTT-2640 Add tree node relationships

---

app/models/goods_nomenclatures/nested_set.rb
spec/models/goods_nomenclatures/nested_set_spec.rb
spec/support/matchers/eq_pk.rb

HOTT-2690
- Objects returned via relationships have an additional `depth` value - and just fetching out SIDs to compare objects can be DRYed out
- This avoids unneeded relationship queries for objects we can already derive from the descendants we have already loaded
- This avoids unneeded relationship queries for objects we can already derive from the ancestors we have already loaded
- This version can operate without querying the database if children are already loaded (eg via an eager load of descendants)
- Low, shouldn't change any in use code

HOTT-2690 custom loader for descendants

---

app/models/concerns/declarable.rb
app/models/concerns/ten_digit_goods_nomenclature.rb
app/models/goods_nomenclatures/nested_set.rb
app/models/measure.rb
spec/models/goods_nomenclatures/nested_set_spec.rb
spec/models/measure_spec.rb

HOTT-2769
- building the relationship this way allows retrieving a particular measure from postgres once rather than once per commodity under the goods_nomenclature you are retrieving
- we similar interface to the existing `#measures` relationship which presents a list of all applicable measures
- we require equivalents for overview only measures
- we wish to reduce code duplication
- Relatively, this is mostly new code but does change the existing in-use `overview_measures` relationship to rely upon the new shared definition of an overview measure

HOTT-2769 Eager loadable measures and overview measures

---

app/models/goods_nomenclatures/nested_set.rb
spec/models/goods_nomenclatures/nested_set_spec.rb
spec/support/matchers/eq_pk.rb

HOTT-2912
- This can be inferred by them being either the parent or ancestor of another goods nomenclature and helps avoid N+1 db queries
- Low, only impacts nested set

HOTT-2912 Assign declarable for parent queries

---

app/models/goods_nomenclatures/nested_set.rb
app/models/measure.rb
spec/models/goods_nomenclatures/nested_set_spec.rb
spec/models/measure_spec.rb

HOTT-2915
- We want to maintain the same ordering for the new `#applicable_measures` as the existing `#measures` it replaces
- We want to maintain the same ordering for the new `#applicable_overview_measures` as the existing `#overview_measures` it replaces
- Low, impacts nested set which currently is not in use

HOTT-2915 Fix sorting for NestedSet#applicable_measures

---

.circleci/config.yml

https://transformuk.atlassian.net/browse/HOTT-2977
- We need to consolidate around a single approach to managing the database in all spaces otherwise we're fighting against ourselves
- The removed workflow was to try and make sure that staging had the same search references as production. We have since streamlined this so this is redundant

HOTT-2977: Disable database workflows until we're ready

---

app/serializers/api/v2/headings/commodity_serializer.rb
spec/serializers/api/v2/headings/commodity_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2985
- This is required because materialized path requires time machine is applied on the headings cache in order to determine declarability. We've opted to just use leaf over fast_declarable? to avoid this requirement

HOTT-2985: Use leaf to determine declarability of commodity

---

app/controllers/api/admin/quota_order_numbers/quota_definitions_controller.rb
app/models/quota_definition.rb
app/serializers/api/admin/quota_order_numbers/measurement_unit_serializer.rb
app/serializers/api/admin/quota_order_numbers/quota_definition_serializer.rb
spec/serializers/api/admin/quota_order_numbers/measurement_unit_serializer_spec.rb
spec/serializers/api/admin/quota_order_numbers/quota_definition_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2980
- This is required to show consistent abbreviations in the UI of the admin area

HOTT-2980: Surface measurement unit for quota definitions

---

app/models/additional_code.rb
app/services/applicable_additional_code_service.rb
db/additional_codes.json
spec/models/additional_code_spec.rb
spec/services/applicable_additional_code_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2989
- This enables the duty calculator to filter these if the user picks not to use one of the borked additional codes

HOTT-2989: Surface null additional codes

---

.circleci/config.yml

HOTT-<TODO>
- The original method of using a deb repo is now working since the User-Agent requirement is now skipped

Revert using self-hosted cf binary

---

app/lib/trade_tariff_backend.rb
app/presenters/api/v2/headings/chapter_presenter.rb
app/presenters/api/v2/headings/commodity_presenter.rb
app/presenters/api/v2/headings/heading_presenter.rb
app/presenters/api/v2/headings/section_presenter.rb
app/presenters/api/v2/subheadings/subheading_presenter.rb
app/services/heading_service/heading_serialization_service.rb
app/services/heading_service/serialization/ns_nondeclarable_service.rb
spec/controllers/api/v2/headings_controller_spec.rb
spec/factories/heading_factory.rb
spec/presenters/api/v2/headings/chapter_presenter_spec.rb
spec/presenters/api/v2/headings/commodity_presenter_spec.rb
spec/presenters/api/v2/headings/heading_presenter_spec.rb
spec/presenters/api/v2/headings/section_presenter_spec.rb
spec/presenters/api/v2/subheadings/subheading_presenter_spec.rb

HOTT-2643 Use Nested set for headings
- It removes the reliance upon the headings getting cached into opensearch everynight
- It will significantly ease working on headings api
- We can precache both headings and subheadings in a signle job (this will come in a later PR)
- Low, feature flagged but when the flag is on this is a significant change to the code base

HOTT-2643 Use nested set for headings

---

app/presenters/api/v2/commodities/commodity_presenter.rb
app/presenters/api/v2/headings/declarable_heading_presenter.rb
app/presenters/api/v2/headings/heading_presenter.rb
app/serializers/api/v2/headings/footnote_serializer.rb
spec/presenters/api/v2/headings/heading_presenter_spec.rb

HOTT-2992
- When using only the `Footnote#footnote_id` discreet footnotes which share a `footnote_id` but with a different `footnote_type_id` get deduplicated during serialization to jsonapi, eg so **PN001** and **TN001** will get deduplicated to a single foot note which is incorrect.
- The commodities endpoint actually used a mix of `Footnote#id` and `Footnote#footnote_id` for different footnotes further confusing things
- Changes the ids used for footnotes in the jsonapi response on major endpoints.

HOTT-2992 Fix footnote ids

---

app/models/goods_nomenclature.rb
app/models/goods_nomenclatures/nested_set.rb
app/presenters/api/v2/headings/commodity_presenter.rb
app/presenters/api/v2/subheadings/subheading_presenter.rb
app/serializers/api/admin/csv/goods_nomenclature_serializer.rb
spec/models/goods_nomenclatures/nested_set_spec.rb

HOTT-3029
- The existing mechanism didn't work for headings and their descendants if `number_indents != 0` which is the case for heading 9919
- Anything loaded via the nested set relationships will automatically benefit from the `number_indents` value being loaded and potentially fix N+1s on endpoints which should be eager loading `goods_nomenclature_indents` but aren't
- Changes core method but in quite a conservative manner - shouldn't have impact on any endpoints unless they are already converted to use nested set

HOTT-3029 Drop ns_number_indents

---

app/controllers/api/v2/goods_nomenclatures_controller.rb

HOTT-2941
- It maintains parity with prior implementation
- Low

HOTT-2941 Include grouping headings

---

app/models/measure_condition_permutations/calculator.rb
spec/models/measure_condition_permutations/calculator_spec.rb

HOTT-3040
- Whilst the data is invalid DBT would prefer that we expose it to our users
- Low, exposes addition measure conditions in permutation groups which is an internal api extension

HOTT-3040 Include negative measure conditions

---

app/controllers/api/v2/goods_nomenclatures_controller.rb
app/serializers/api/v2/csv/goods_nomenclature_serializer.rb
app/serializers/api/v2/goods_nomenclatures/goods_nomenclature_extended_serializer.rb
spec/controllers/api/v2/goods_nomenclatures_controller_spec.rb
spec/serializers/api/shared/csv_serializer_spec.rb
spec/serializers/api/v2/csv/goods_nomenclature_serializer_spec.rb
spec/serializers/api/v2/goods_nomenclatures/goods_nomenclature_extended_serializer_spec.rb
spec/serializers/api/v2/goods_nomenclatures/goods_nomenclature_list_serializer_spec.rb

HOTT-2943
- We want to expose these additional fields but the existing serializer was used in other locations
- The missing specs help avoid accidental regressions
- Low, changes format of CSV but only extends it

HOTT-2943 Add fields to Goods Nomenclature API

---

app/controllers/api/v2/goods_nomenclatures_controller.rb
app/serializers/api/v2/csv/goods_nomenclature_serializer.rb
app/serializers/api/v2/goods_nomenclatures/goods_nomenclature_extended_serializer.rb
spec/serializers/api/v2/csv/goods_nomenclature_serializer_spec.rb
spec/serializers/api/v2/goods_nomenclatures/goods_nomenclature_extended_serializer_spec.rb

HOTT-2940
- The current links are wrong

HOTT-2940 Use subheading links for subheadings

---

app/controllers/api/v2/goods_nomenclatures_controller.rb

HOTT-2940
- if the object is a commodity then `#to_param` excludes the producline_suffix
- Low, fixes bug

HOTT-2940 Fix for incorrect subheading url in GN API

---

app/controllers/api/v2/goods_nomenclatures_controller.rb
app/serializers/api/v2/csv/goods_nomenclature_serializer.rb
app/serializers/api/v2/goods_nomenclatures/goods_nomenclature_extended_serializer.rb
spec/serializers/api/v2/csv/goods_nomenclature_serializer_spec.rb
spec/serializers/api/v2/goods_nomenclatures/goods_nomenclature_extended_serializer_spec.rb

HOTT-2945
- It helps our users understand the relationship between different Goods Nomenclature within the hierarchy

HOTT-2945 add parent to goods nomenclature api

---

app/models/goods_nomenclature.rb
app/serializers/api/v2/commodities/commodity_serializer.rb
app/serializers/api/v2/full_chemical_serializer.rb
app/serializers/api/v2/headings/declarable_heading_serializer.rb
spec/models/goods_nomenclature_spec.rb
spec/serializers/api/v2/commodities/commodity_serializer_spec.rb
spec/serializers/api/v2/full_chemical_serializer_spec.rb
spec/serializers/api/v2/headings/declarable_heading_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2936
- This is needed to show/not show the chemicals tab in the OTT frontend

HOTT-2936: Surface whether a declarable has any chemicals

---

app/controllers/api/v2/subheadings_controller.rb
app/models/goods_nomenclature.rb
app/services/cached_subheading_service.rb
app/services/heading_service/heading_serialization_service.rb
app/services/heading_service/precache_service.rb
app/services/heading_service/serialization/ns_nondeclarable_service.rb
app/workers/clear_cache_worker.rb
app/workers/precache_headings_worker.rb
config/sidekiq.yml
spec/services/heading_service/precache_service_spec.rb
spec/workers/precache_headings_worker_spec.rb

HOTT-2987
- It should reduce load on postgres at the start of the day
- Footnotes order ensures consistency of presentation across pages, particularly when eager loading
- Low, if nested set headings/subheadings are used it will speed them up, if not it will just iterate through the chapters without caching anything

HOTT-2987 Precache headings and subheadings

---

.circleci/config.yml
Gemfile
Gemfile.lock
config/sidekiq.yml

HOTT-2210
- Redis-Elasticache is incompatible with the Redis 5 rubygem
- Its purpose is to reconnect on READONLY errors caused by a failover in the elasticache cluster
- That functionality is now provided by the redis-client (>= 0.11.2) and redis (>= 5.0.6) gems
- Upgraded sidekiq-scheduler to be compatible with Sidekiq 7 and Redis 5 gem
- Upgraded redlock to be compatible with Redis 5 gem
- Replaces a key component
- Removes the `redis-elasticache` gem which had solved our errors from the frequent failures from redis at weekends - my reading of the docs implies this should be a 'solved issue' now even without that gem

HOTT-2210 Sidekiq 7 upgrade

---

app/lib/tariff_synchronizer/tariff_downloader.rb
spec/factories/response_factory.rb
spec/unit/tariff_synchronizer/tariff_downloader_spec.rb

https://transformuk.atlassian.net/browse/HOTT-3075
- We have a repeating issue with CDS files which are not actually zip files. This reduces to burden to rollback/rollforward which can now just be done in the admin UI

HOTT-3075: Adds handling for non-zip content when downloading CDS files

---

app/presenters/api/v2/subheadings/subheading_presenter.rb
db/data_migrations/20230421152645_fix_heading_9905_tree_node.rb
db/migrate/20230419084212_add_tree_nodes_overrides.rb
db/structure.sql
spec/models/goods_nomenclatures/nested_set_spec.rb

HOTT-3025
- Whilst there is a lot of inconsistency in the code base, general conclusion is that grouping headings should be above their non-grouping equivalents rather then adjacent to them
- This is how GoodsNomenclatureMapper handles it _if_ given a full tree of nodes, which it only is for the chapters endpoint
- Tarics UI nests non-grouped headings under grouped
- It is easier to drop and replace the view now whilst it has limited usage rather then later when it has heavy usage
Technically this is incorrect! 
Prior to now the position in the tree of every node could be decided from the information provided by that indent record itself - this is necessary for time machine compatibility.
That is no longer possible, every node needs …

HOTT-3025 Grouping headings

---

app/controllers/api/v2/subheadings_controller.rb
app/services/cached_subheading_service.rb
app/services/heading_service/precache_service.rb
spec/services/cached_subheading_service_spec.rb
spec/services/heading_service/precache_service_spec.rb

HOTT-3093
- The PrewarmSubheadingsWorker should continue to operate 'as-is' even when the feature flag is turned on
- Low - fixes bug when feature flag is on, but flag is off at present

HOTT-3093 Ignore feature flag in PrewarmSubheadingsWorker

---

lib/tasks/data_migrations.rake

HOTT-2871
- It is a 'pause the app for 2 seconds' event, so can take a few seconds to acquire a lock
- It is unneeded on deploy unless we've actually changed the data via a data migration
- The view was already being refreshed as part of the `rake data:migrate` so no need to do it again straight afterward
- Low, just avoids an unneeded step on deploy

HOTT-2871 Only refresh view if applicable data migrations

---

spec/controllers/api/v2/additional_codes_controller_spec.rb
spec/elastic_search_indexes/cache/additional_code_index_spec.rb
spec/factories/additional_code_factory.rb
spec/factories/measure_factory.rb
spec/services/additional_code_search_service_spec.rb
spec/services/applicable_additional_code_service_spec.rb
spec/services/applicable_vat_options_service_spec.rb

HOTT-???
- It makes any spec using the AdditionalCode factory and relying on the behaviour of CacheAdditionalCodeIndex#dataset flaky
- None, spec only changes
Addresses these failures on CI Job 23062

Fix flaky additional code specs

---

db/data_migrations/20230502102427_kill_broken_balance_events.rb

https://transformuk.atlassian.net/browse/HOTT-3088
Before
After
- These shouldn't exist and show an increasing volume

HOTT-3087: Drop borked balance events

---

app/models/concerns/ten_digit_goods_nomenclature.rb
app/models/full_chemical.rb
app/models/goods_nomenclature.rb
app/models/search_reference.rb
app/serializers/cache/heading_serializer.rb
app/services/suggestions_service.rb
spec/models/commodity_spec.rb
spec/models/full_chemical_spec.rb
spec/models/goods_nomenclature_spec.rb
spec/models/search_reference_spec.rb
spec/models/search_suggestion_spec.rb
spec/services/suggestions_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-3048
- This should speed up the generation of the search suggestions
- Reverting ns until we're in a position to have this running in production for subheading/heading apis in earnest

HOTT-3095: Enhance search suggestions service

---

app/controllers/api/admin/headings_controller.rb
app/presenters/api/admin/headings/heading_presenter.rb
app/serializers/api/admin/headings/commodity_serializer.rb
spec/presenters/api/admin/headings/heading_presenter_spec.rb

HOTT-3065
- To reduce N+1s in the admin api
- To replace existing materialized path code with nested set which available for more scenarios
- Low
Running locally so no real network latency impact

HOTT-3065 Fixed N+1s in admin headings api

---

app/controllers/api/v2/chapters_controller.rb
app/presenters/api/admin/headings/heading_presenter.rb
app/presenters/api/v2/chapters/chapter_presenter.rb
app/presenters/api/v2/chapters/heading_presenter.rb
app/presenters/api/v2/headings/commodity_presenter.rb
app/presenters/api/v2/news/item_presenter.rb
app/presenters/wrap_delegator.rb
app/serializers/api/v2/chapters/chapter_serializer.rb
app/serializers/api/v2/chapters/heading_leaf_serializer.rb
app/serializers/api/v2/chapters/heading_serializer.rb
app/serializers/api/v2/chapters/section_serializer.rb
app/serializers/api/v2/csv/heading_serializer.rb
spec/presenters/api/v2/chapters/headings_presenter_spec.rb
spec/requests/api/v2/chapters_controller_spec.rb

HOTT-2904
- This is a good test bed for comparing nested set output
- We can further optimise the endpoint with nested set
- I keep adding `SomePresenter#wrap` everywhere, this standardises it
- Low, behaviour is the same
Old (prod) on the left and new (dev) on the right

HOTT-2904 Convert v2 chapters to use nested sets

---

app/models/rules_of_origin/scheme.rb
app/models/rules_of_origin/scheme_set.rb
db/rules_of_origin/roo_schemes_uk.json
spec/fixtures/rules_of_origin/invalid_dates.json
spec/models/rules_of_origin/scheme_set_spec.rb
spec/models/rules_of_origin/scheme_spec.rb

HOTT-2844
- We have some schemes that are only applicable up to or from certain dates
- Low

HOTT-2844 validity periods for schemes

---

config/environments/development.rb

HOTT-????
- It will help highlight when changes introduce N+1s
- It sets the 'default' developer experience to have increased visibility
- The developer can still easily control it via the env var using `.env.development.local`
- None

Change the default log level in development environment

---

app/models/goods_nomenclatures/nested_set.rb
app/models/goods_nomenclatures/tree_node.rb
spec/models/goods_nomenclatures/nested_set_spec.rb
spec/models/goods_nomenclatures/tree_node_spec.rb

HOTT-3118
- It allows `ns_declarable?` to determine whether a commodity is declarable without requiring a database lookup or retrieving all its children
- Low, not currently in use - will be used in following PRs
This is checking `ns_declarable?` for every GoodsNomenclature in our database

HOTT-3118 Add leaf virtual column

---

app/controllers/api/admin/headings_controller.rb
app/controllers/api/v2/goods_nomenclatures_controller.rb
app/lib/sequel/plugins/take.rb
app/services/cached_subheading_service.rb
app/services/heading_service/precache_service.rb
app/services/heading_service/serialization/ns_nondeclarable_service.rb

HOTT-3133
- We have quite a few locations in the code base which are using `.eager`  together with `.take` without the authors realising this has no effect. Its best to make it work with `.eager`
- change to a sequel plugin used in lots of places but should be a safe change

HOTT-3133 Eager loadable Sequel#take

---

.rubocop.yml
app/models/rules_of_origin/article.rb
app/models/rules_of_origin/explainer.rb
app/models/rules_of_origin/heading_mappings.rb
app/models/rules_of_origin/link.rb
app/models/rules_of_origin/query.rb
app/models/rules_of_origin/rule.rb
app/models/rules_of_origin/rule_set.rb
app/models/rules_of_origin/scheme.rb
app/models/rules_of_origin/scheme_set.rb
app/models/rules_of_origin/v2/rule.rb
app/models/rules_of_origin/v2/rule_set.rb

HOTT-????
- it drops mem usage by 20%

Revert "Removes dead frozen string literal instruction"

---

app/models/quota_definition.rb
app/models/quota_order_number.rb
app/services/cached_quota_order_number_service.rb

HOTT-3199
- Currently it generates 6000 queries on XI
- Low, changes sort order of returned data - content is identical

HOTT-3199 Use eager loading to speed up /quota_order_numbers

---

config/environments/development.rb

https://transformuk.atlassian.net/browse/HOTT-3204
**Before**
**After**
- These relate to Sequel working out the casting rules for table columns
-> model attributes but are never helpful when debugging n+1s and often
create many lines of additional output.

HOTT-3204: Filter out redundant logs in development

---

app/services/api/beta/search_service.rb
app/services/search_service/exact_search.rb
spec/services/search_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-3216
- This is required so that suggestions with matches to commodities can be submitted in their short form, too
- Low, it updates/augments existing behaviour which has good test coverage

HOTT-3216: Shorter comm code suggestion support

---

app/lib/reporting/differences.rb
app/lib/reporting/differences/goods_nomenclature.rb

https://transformuk.atlassian.net/browse/HOTT-3250
https://transformuk.atlassian.net/browse/HOTT-3251
This includes two of our first worksheets:
- This is required to kick off the work to produce the differences report
- Specs (once we're integrating with S3 and are actually emailing these reports we can add some integration tests)
- Persisting the reports to s3
- Emailing the reports to relevant stakeholders in Engine and HMRC

HOTT-3250: Adds initial differences report plumbing

---

app/lib/reporting/differences.rb
app/lib/reporting/differences/goods_nomenclature.rb
app/lib/reporting/differences/indentation.rb

https://transformuk.atlassian.net/browse/HOTT-3302
- This dramatically speeds up the reporting implementation

HOTT-3302: Enhance report generation performance

---

app/controllers/api/v1/commodities_controller.rb
app/controllers/api/v2/commodities_controller.rb
app/elastic_search_indexes/search/goods_nomenclature_index.rb
app/lib/reporting/basic.rb
app/models/chapter.rb
app/models/concerns/ten_digit_goods_nomenclature.rb
app/models/goods_nomenclatures/nested_set.rb
app/models/heading.rb
app/services/heading_service/heading_serialization_service.rb
docs/goods-nomenclature-nested-set.md
spec/models/goods_nomenclatures/nested_set_spec.rb

HOTT-2638
- It is able to return only declarable GNs, the old method only filtered on PLS - so subsequent filtering in Ruby was required to find if a GN was really declarable - this often involved other expensive db queries and was not eager loadable
- Drive by fix but this should potentially speed up `#by_code` for Chapter and Heading - it certainly shouldn't be slower then using `LIKE`
- This is necessary if we are joining on tree nodes because they also have a `goods_nomenclature_item_id` column
- Replace use of the old scope with the new one because it is faster
- Replaces existing code with nested set variants with differing behaviour

HOTT-2638 add NestedSet#ns_declarable scope

---

app/models/rules_of_origin/scheme_set.rb

Previously was done when the scheme set is loaded but that is cached at boot
HOTT-3283
- Previously it was done on first access but this ends up being cached when it is loaded at boot. 
- This in turn means the schemes list would always reflect the schemes list on the day the app was deployed
- Some, changes an endpoint used by our commodities page

HOTT-3283 Dynamically filter schemes list

---

app/lib/time_machine.rb
app/models/goods_nomenclatures/nested_set.rb
spec/models/commodity_spec.rb
spec/models/goods_nomenclatures/nested_set_spec.rb
spec/models/goods_nomenclatures/tree_node_spec.rb
spec/models/measure_spec.rb
spec/models/meursing_measure_spec.rb
spec/models/quota_definition_spec.rb
spec/rails_helper.rb
spec/services/search_service_spec.rb
spec/unit/time_machine_spec.rb

HOTT-3284
- There is not currently a known use case for querying the hiearchy outside of TimeMachine
- Doing so will return confusing results requiring additional filtering in Ruby
- The most likely scenario for the developer doing this is by mistake running outside of TimeMachine, so remove this source of confusion
- Almost all specs are written with an expectation they are running inside of TimeMachine, even though they are not. Change that behaviour globally and the user can disable TimeMachine on the specific specs thats required for
- Low

HOTT-3284 Raise if using NestedSet outside TimeMachine

---

app/models/goods_nomenclature.rb
spec/models/goods_nomenclature_spec.rb

HOTT-2638
- it is no longer in use, and ns_declarable is quick enough to act as a replacement
- Drops code which is believed to be orphaned

HOTT-2638 Drop legacy declarable scope

---

app/lib/reporting/differences/quota_missing_origin.rb

https://transformuk.atlassian.net/browse/HOTT-3265
- This now matches Matt's implementation and outputs

HOTT-3265: Filter origins by order number

---

app/models/healthcheck.rb

HOTT-????
- Previously we were just triggering the default 500 response
- Low, should improve our robustness in the face of problems

Handle connection failures to search query parser

---

app/workers/build_index_page_worker.rb

https://transformuk.atlassian.net/browse/HOTT-3372
- This is essential for optimising these index jobs

HOTT-3372: Fixes eager loading in build index worker

---

app/lib/query_count_job_logger.rb
app/workers/build_index_page_worker.rb
config/initializers/sidekiq.rb

HOTT-1658
- It will help identify jobs which can benefit from eager loading
- Limited, extends Sidekiq - works for me, if it breaks our background jobs wont run

HOTT-1658 List query counts for all Sidekiq jobs

---

app/elastic_search_indexes/search/goods_nomenclature_index.rb
app/serializers/search/goods_nomenclature_serializer.rb
spec/elastic_search_indexes/search/goods_nomenclature_index_spec.rb
spec/serializers/search/goods_nomenclature_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-3372
- Short codes come in 2, 4, 6, 8 and 10 digit forms for ancestors. The form is interesting to the bulk-search api as a point to accumulate scores across search results for.

HOTT-3372: Surface short code in beta search

---

app/services/suggestions_service.rb

HOTT-2642
- It can fetch the goods_nomenclature_class as part of the query
- It takes 2 minutes out the run time on my machine
- It removes a materialized path dependency
- Low

HOTT-2642 Use nested set for SearchSuggestions

---

db/rules_of_origin/roo_schemes_uk/proofs/australia/importers-knowledge.md
db/rules_of_origin/roo_schemes_uk/proofs/australia/origin-declaration.md
db/rules_of_origin/roo_schemes_uk/proofs/new-zealand/importers-knowledge.md
db/rules_of_origin/roo_schemes_uk/proofs/new-zealand/origin-declaration.md

HOTT-3426
- So that we can show the additional proofs information to users at the end of the wizard
- Low

HOTT-3426 Added proofs documents for NZ/AU schemes

---

app/models/concerns/ten_digit_goods_nomenclature.rb
app/models/full_chemical.rb
app/models/goods_nomenclature.rb
app/models/search_reference.rb
app/models/search_suggestion.rb
app/services/api/beta/search_service.rb
app/services/search_service/exact_search.rb
app/services/suggestions_service.rb
spec/models/commodity_spec.rb
spec/models/full_chemical_spec.rb
spec/models/goods_nomenclature_spec.rb
spec/models/search_reference_spec.rb
spec/models/search_suggestion_spec.rb
spec/workers/clear_invalid_search_references_spec.rb

HOTT-2642
- DRYing out code is good
- Low

HOTT-2642 Drop custom STI logic

---

.circleci/config.yml

https://transformuk.atlassian.net/browse/HOTT-3414
- This is consistent with all live environments

HOTT-3372: Make opensearch version consistent

---

app/services/bulk_search_result_answer_service.rb
spec/services/bulk_search_result_answer_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-3414
- This seems to be an internal quirk of opensearch that doesn't ever happen in real situations
- This is just a quick fix for making test scenarios pass

HOTT-3372: Handle nil hits

---

app/models/goods_nomenclatures/nested_set.rb
docs/goods-nomenclature-nested-set.md

HOTT-2642
- It greatly simplifies using this dataset method - previously if you were joining anything else, you would need to override the grouping rules
- Low
There is a 5-10% performance cost to this approach vs GROUPing but its still very quick and way quicker for alternatives when you want the leaf status for large numbers of goods nomenclatures.
```
~460ms = All GNs
~32ms = 1000 GNs by sid
~6ms = 100 GNs by sid
~1.8ms = 10 GNs by sid
```

HOTT-2642 Use distinct for `with_leaf_column`

---

db/rules_of_origin/roo_schemes_uk.json

HOTT-3452
HOTT-3453
- On the proofs screen on the frontend which lists proofs for all schemes, you cannot tell which scheme is which
- Vietnam was included in dcts-ldcs by mistake
- Low

HOTT-3453 - Update the UK RoO schemes definition

---

db/data_migrations/20230619123312_remove_duplicate_geo_area_memberships.rb

These were cause by bad data files from CDS
HOTT-3432
- There is a bug in CDS which particularly badly impacted two files and created hundreds of oplog updates for certain membership records. Because of the implementation of the oplog system this results in poor performance when querying affected memberships in the view above the table.
- We only require the last oplog entries from a given sync
- Removes oplog data

HOTT-3432 Remove duplicate oplogs for geo area memberships

---

db/data_migrations/20230619123312_remove_duplicate_geo_area_memberships.rb

HOTT-3432
- It wont work on prod

HOTT-3432 Fix migration for when non-merged databases

---

lib/tasks/tariff.rake

HOTT-2913
- When this feature is deployed we will want to recreate all data
- Low, just a rake task

HOTT-2913 Add rake task to recreate all changes data

---

db/data_migrations/20230614094504_remove_montenegro_from_quota_order_number_origins.rb

https://transformuk.atlassian.net/browse/HOTT-3388
- Removed Quota 051534 ME origins
- The data was incorrect

HOTT-3388: Quota 051534 origins data fix

---

app/elastic_search_indexes/concerns/point_in_time_index.rb
app/elastic_search_indexes/search_index.rb
app/workers/build_index_page_worker.rb

HOTT-3507
- Previously if data was excluded from an eager load (eg because of bad references, or because of a missing eager load) then the subsequent attempt to fetch the data at serialization time would either do a non-timemachine query or in the case of nested sets would actually raise an error because it was outside of time machine
- Changes reindexing but should improve consistency so lower risk of different behaviour under differing circumstances

HOTT-3507 Let indexer control reindexing environment

---

app/controllers/api/v2/bulk_searches_controller.rb
app/models/bulk_search/result_collection.rb
app/presenters/api/v2/bulk_search_result_presenter.rb
app/serializers/api/v2/csv/bulk_search_result_serializer.rb
spec/factories/bulk_search/search_ancestor_factory.rb
spec/factories/bulk_search/search_factory.rb
spec/presenters/api/v2/bulk_search_result_presenter_spec.rb
spec/requests/api/v2/bulk_searches_controller_spec.rb
spec/serializers/api/v2/csv/bulk_search_result_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-3447
- This is required for simple reporting from the results of this api

HOTT-3447: Adds support for csv to bulk search api

---

.env.development
.env.test
config/database.yml

HOTT-????
- developer nit - internal docker networks sometimes dont access via localhost
- Non - dev environment only, and the addition of `PGHOST` env vars should achieve the same goal but make it overrideable should the developer wish to

Allow overriding database host

---

.env.development
app/models/goods_nomenclature.rb
app/workers/build_index_by_heading_worker.rb
app/workers/build_index_by_headings_worker.rb
spec/factories/heading_factory.rb
spec/models/goods_nomenclature_spec.rb
spec/workers/build_index_by_heading_worker_spec.rb
spec/workers/build_index_by_headings_worker_spec.rb

https://transformuk.atlassian.net/browse/HOTT-3532
- This is required to enable bulk-search index population

HOTT-3547: Adds by headings index builder worker

---

app/models/search_suggestion.rb
app/services/search_suggestion_populator_service.rb

https://transformuk.atlassian.net/browse/HOTT-3571
- This is required because the search suggestions use values which change as the hierarchy reorganises but these changes were not being reflected by clearing out the no-longer-current values.

HOTT-3572: Handle hierarchy movements in search suggestions

---

app/elastic_search_indexes/search/bulk_search_index.rb
app/elastic_search_indexes/search_index.rb
app/lib/trade_tariff_backend.rb
app/lib/trade_tariff_backend/search_client.rb
app/models/bulk_search/result_collection.rb
app/models/bulk_search/search.rb
app/serializers/api/v2/bulk_search/search_serializer.rb
app/serializers/search/bulk_search_serializer.rb
app/serializers/serializer.rb
app/services/bulk_search/hit_ancestor_finder_service.rb
app/services/bulk_search/result_answer_service.rb
app/services/bulk_search_document_builder_service.rb
app/workers/build_index_by_heading_worker.rb
app/workers/clear_cache_worker.rb
app/workers/reindex_models_worker.rb
spec/elastic_search_indexes/search/bulk_search_index_spec.rb
spec/factories/bulk_search/search_factory.rb
spec/models/bulk_search/result_collection_spec.rb
spec/models/bulk_search/search_spec.rb
spec/serializers/api/v2/bulk_search/result_collection_serializer_spec.rb
spec/serializers/api/v2/bulk_search/search_serializer_spec.rb
spec/serializers/search/bulk_search_serializer_spec.rb
spec/services/bulk_search/result_answer_service_spec.rb
spec/services/bulk_search_document_builder_service_spec.rb
spec/workers/build_index_by_heading_worker_spec.rb
spec/workers/reindex_models_worker_spec.rb

https://transformuk.atlassian.net/browse/HOTT-3532
- This is required and reflects a consistent approach to the index creation between Keith, Matt and myself after recent discussions

HOTT-3547: Enable population of a bulk search index by heading

---

app/services/tree_integrity_checking_service.rb
app/workers/updates_synchronizer_worker.rb
config/sidekiq.yml
spec/services/tree_integrity_checking_service_spec.rb

HOTT-3509 
- Last week we didn't pick up when a sync was sent through removing the indents for several commodities - an alert  would have aided debugging
- We should alert immediately if we find something amiss rather then waiting for users to notice something
- Low, schedules a job during syncs

HOTT-3509 Check for missing tree nodes

---

db/rules_of_origin/roo_schemes_uk.json

HOTT-3566
- This was missing from the original data
- Low, changes the schemes which apply to Solomon Islands

HOTT-3566 Add solomon islands to pacific RoO scheme

---

app/models/goods_nomenclature.rb
app/presenters/api/v2/subheadings/subheading_presenter.rb
app/serializers/api/v2/csv/commodity_serializer.rb
spec/models/goods_nomenclatures/nested_set_spec.rb
spec/models/search_reference_spec.rb

This will not always work, if nothing is pulling in the tree nodes join then we cannot know leaf. And pulling it in is non-optimal if we are pulling a vertical slice of the tree
HOTT-3119
- It has been requested by other developers
- Changes how we load goods nomenclatures - GNs that were previously loaded as Commodities (but were actually Subheadings) will now be loaded as Subheadings
I've dithered on adding this because I am very aware it only works if something is setting the the `leaf` attribute for GNs with PLS=80. This is a potential source of confusion for future developers but can be resolved if needed by utilising the `with_leaf_column` scope. When looking up the tree this is set automatically.
In general I think it makes …

HOTT-3119 Make STI Subheading aware

---

db/migrate/20230706092636_adds_tradesets_descriptions.rb
db/structure.sql

https://transformuk.atlassian.net/browse/HOTT-3576
- This will be used to eager load associated tradeset descriptions for a given goods nomenclature and will end up in the bulk search index

HOTT-3576: Adds tradeset_descriptions table

---

app/models/goods_nomenclature.rb
app/presenters/api/v2/commodities/commodity_presenter.rb
app/presenters/api/v2/headings/commodity_presenter.rb
app/presenters/api/v2/subheadings/subheading_presenter.rb
app/serializers/api/v2/csv/commodity_serializer.rb
spec/models/goods_nomenclatures/nested_set_spec.rb
spec/models/search_reference_spec.rb
spec/presenters/api/v2/commodities/commodity_presenter_spec.rb

HOTT-3119
- The functionality is desirable but was reverted in a hotfix after discover of the bug
- Medium - its been deployed once already, and we know it doesn't trigger any outright problems. The origin of how the bug crept in has been established - multiple concurrent branches, and a new check for instances of `is_a?(Commodity)` has been done. Specs have also been introduced checking the ancestors behaviour from the problematic presenter.

HOTT-3119 Use leaf where available for Single Table Inheritance

---

app/controllers/api/v2/bulk_searches_controller.rb
app/models/bulk_search/result_collection.rb
app/models/bulk_search/search.rb
app/services/bulk_search/error_serialization_service.rb
spec/models/bulk_search/result_collection_spec.rb
spec/models/bulk_search/search_spec.rb
spec/requests/api/v2/bulk_searches_controller_spec.rb
spec/services/bulk_search/error_serialization_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-3587
- This is to avoid odd behaviour/people doing searches on digits we do not support

HOTT-3587: Adds validations to search model

---

.circleci/config.yml
bin/sync_opensearch_packages

[HOTT-3553](https://transformuk.atlassian.net/browse/HOTT-3553)
- Updated the `sync_opensearch_packages` script to take a `bucket` parameter.
- As S3 bucket names are globally unique across AWS, when we come to do this on the new accounts, we'll have to specify different bucket names.

HOTT-3553: Update OpenSearch Sync Script

---

app/models/concerns/componentable.rb
app/models/measure.rb
app/models/measure_condition.rb
app/models/measurement_unit.rb
db/measurement_units_20220825.json
spec/factories/measure_condition_component_factory.rb
spec/factories/measure_factory.rb
spec/models/measure_condition_spec.rb
spec/support/shared_examples/a_component.rb

https://transformuk.atlassian.net/browse/HOTT-3641
- This is required to enable asking for different units in the duty calculator
- Depending on the available units, we'll require different inputs from the user

HOTT-3641: Surface SPQ measure units

---

.env.development
.env.test
app/lib/trade_tariff_backend.rb
app/models/measure.rb
app/models/measure_condition.rb
app/presenters/api/v2/measures/measure_condition_component_presenter.rb
app/presenters/api/v2/measures/measure_condition_presenter.rb
app/presenters/api/v2/measures/measure_presenter.rb
app/serializers/api/v2/measure_serializer.rb
spec/factories/measure_component_factory.rb
spec/factories/measure_condition_component_factory.rb
spec/factories/measure_condition_factory.rb
spec/factories/measure_factory.rb
spec/models/measure_spec.rb
spec/presenters/api/v2/measures/measure_condition_component_presenter_spec.rb
spec/presenters/api/v2/measures/measure_condition_presenter_spec.rb
spec/presenters/api/v2/measures/measure_presenter_spec.rb

https://transformuk.atlassian.net/browse/HOTT-3639
https://dev.trade-tariff.service.gov.uk/commodities/2203000100?day=21&month=8&year=2023#vat_excise
UK
XI
For ASVX condition components on excise alcohol measures we need to coerce the
first duty amount to be balanced so its no longer making adjustments to handle
liters/hectoliter conversion.
For ASV condition components on excise alcohol measures the ASV part is presenting too small `0.01` instead of `1.00%` and this is incorrect.
- This is required so that the presentation of the duty amount reflects the legislation/intended duty amounts

HOTT-3639: Add presenter to override duty amount on alcohol excise units

---

app/models/measure.rb

BAU: Fix typo in api component

---

app/models/concerns/componentable.rb
app/presenters/api/v2/measures/measure_condition_component_presenter.rb
app/presenters/api/v2/measures/measure_condition_presenter.rb
spec/factories/measure_condition_component_factory.rb
spec/presenters/api/v2/measures/measure_condition_component_presenter_spec.rb
spec/presenters/api/v2/measures/measure_condition_presenter_spec.rb
spec/presenters/api/v2/measures/meursing_measure_component_presenter_spec.rb

https://transformuk.atlassian.net/browse/HOTT-3642
- This is required because the default `SPQ  (SPR * Rate)` is just incorrect

HOTT-3642: Adjust SPQ presentation

---

app/models/measure_condition.rb
app/models/measure_condition_permutations/calculator.rb
spec/models/measure_condition_permutations/calculator_spec.rb
spec/models/measure_condition_spec.rb

https://transformuk.atlassian.net/browse/HOTT-3667
- This is required as part of the alcohol work to make sure users can see when excise does not apply to them

HOTT-3667: Show threshold conditions that are negative

---

app/models/measure.rb

HOTT-3649
- This is causing regression suite failures and is wrong

HOTT-3649: Only surface requirement units after start date

---

app/models/measurement_unit.rb
db/measurement_units.json
spec/models/measurement_unit_spec.rb
spec/services/measure_unit_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-3766
For a bit of context, these types are used to determine the class of measure condition. I realised the types are actually interesting for validation, too, since they indicate how a measurement unit should be treated.
A whole bunch of these were missing/wrong in the measurement unit file (some were classified as a volume when they are in fact a weight. Some were just missing and these needed populating.
I've also opted to memoize and use a set for 0(1) lookup since the iteration happens a lot (for every measure condition on a returned commodity and for every commodity we're loading).
- This will be used in the duty calculator to perform proper measurement unit calculations

HOTT-3766: Extend measurement unit types

---

app/services/certificate_finder_service.rb
spec/services/certificate_finder_service_spec.rb

BAU
- This is causing us to return a list of certificates despite having no measures attached

BAU: Handle no-measure certificates

---

app/controllers/api/admin/headings_controller.rb
app/models/heading.rb
app/serializers/api/admin/chapters/heading_serializer.rb
spec/serializers/api/admin/chapters/heading_serializer_spec.rb

BAU
- This is breaking our integration tests

BAU: Fixes declarable references and adds missing test

---

app/lib/tariff_synchronizer/tariff_updates_requester.rb

BAU
- This is required since the api for setting basic auth on the faraday connection changed. We were being warned but ignored the warnings

BAU: Fixes basic auth api

---

terraform/README.md
terraform/locals.tf
terraform/worker_uk.tf
terraform/worker_xi.tf

- Added worker command
- Bumped worker module versions
- The workers had commands passed as env vars, which is not what we want - we want to use the new module that supports overriding `entrypoint` and providing `command`.

BAU: Run Worker Commands

---

app/services/heading_service/serialization/declarable_service.rb

https://transformuk.atlassian.net/browse/HOTT-3834
- These were missing previously and were noticed by one of our stakeholders

HOTT-3834: Support ancestor measures in declarable headings

---

terraform/README.md
terraform/data.tf
terraform/iam.tf
terraform/locals.tf

[HOTT-3844](https://transformuk.atlassian.net/browse/HOTT-3844)
- Replaced the Redis URL environment variables with new service-specific connection strings.
- The backend services require the new UK and XI specific Redis connection strings, removing a TODO item, as they have changed in the core infra.

HOTT-3844: Split Redis

---

terraform/README.md
terraform/data.tf
terraform/locals.tf
terraform/worker_uk.tf
terraform/worker_xi.tf

- Corrected the bucket names by using the account ID.
- Uncommented worker common vars.
- I noticed that the S3 bucket names were missing the account ID suffix, so I've added a data source to fetch the current account ID.
- There were a couple of vars that were commented out but the worker could use having these.

BAU: Supply account ID to correct bucket names

---

terraform/README.md
terraform/data.tf
terraform/iam.tf
terraform/locals.tf

- Added missing `TARIFF_SYNC_USERNAME`.
- We need this credential so that we can download the CDS/Taric files.

BAU: Add missing sync credential

---

app/models/rules_of_origin/scheme.rb
app/models/rules_of_origin/scheme_set.rb
app/serializers/api/v2/rules_of_origin/full_scheme_serializer.rb
app/serializers/api/v2/rules_of_origin/scheme_serializer.rb
db/rules_of_origin/roo_schemes_uk.json
spec/serializers/api/v2/rules_of_origin/full_scheme_serializer_spec.rb
spec/serializers/api/v2/rules_of_origin/scheme_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-3611
To fix where the DCTS instructions are also showing, the attribute `show_proofs_for_geographical_areas` has been added to the roo scheme uk.
To fix this:

HOTT-3611: Add show_proofs_for_geographical_areas to roo_scheme_uk.

---

config/initializers/spelling_corrector_bucket.rb
terraform/README.md
terraform/backend_uk.tf
terraform/backend_xi.tf
terraform/data.tf
terraform/iam.tf
terraform/locals.tf
terraform/worker_uk.tf
terraform/worker_xi.tf

[HOTT-3858](https://transformuk.atlassian.net/browse/HOTT-3858)
I have:
- Added a check for `ECS_AGENT_URI` to allow the application to know if its running in ECS.
- Updated the initialiser for the spelling corrector bucket to allow it to work in AWS without explicit credential environment variables.
- Added a new IAM policy for access to Spelling Corrector bucket for the backend ECS task role.
- The AWS SDK will automatically search for credentials from the ECS metadata agent and use the generated credentials linked to the ECS task role, so we do not need to supply environment variables for access.
- We need the backend to be able to upload the spelling corrector files for the Search Query Parser to the S3 bucket.

HOTT-3858: Ensure files are created in S3 for the Search Query Parser

---

app/services/search_suggestion_populator_service.rb
db/migrate/20230817135045_adds_primary_key_for_id_and_type.rb
db/structure.sql
spec/controllers/api/v2/headings_controller_spec.rb
spec/controllers/api/v2/search_controller_search_spec.rb
spec/factories/search_suggestion_factory.rb
spec/models/search_suggestion_spec.rb
spec/serializers/api/v2/search_suggestion_serializer_spec.rb
spec/services/search_service_spec.rb
spec/services/search_suggestion_populator_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-3579
We've moved to using an id, type primary key constraint on the search suggestions since these are necessary to identify a unique row in the search suggestions table and to avoid duplication.
- This is needed to fix duplication patches

HOTT-3579: Updates search suggestion primary keys

---

app/models/exchange_rates/period_list.rb
config/routes.rb
spec/models/exchange_rates/period_list_spec.rb
spec/requests/api/v2/exchange_rates/period_lists_controller_spec.rb

BAU
- This simplifies our integration in the frontend and is more canonical with fetching a single resource/is slightly more restful

BAU: Support a restful period list

---

terraform/README.md
terraform/data.tf
terraform/iam.tf
terraform/locals.tf

[HOTT-3922](https://transformuk.atlassian.net/browse/HOTT-3922)
- Amended the S3 policy for the backend task role.
- Fixed the persistence bucket name, and added it to the S3 policy.
- We are getting an `Aws::S3::Errors::AccessDenied` error when the backend attempts to run the spelling model updater.

HOTT-3922: Fix backend S3 access in AWS

---

app/controllers/api/v2/search_references_controller.rb
app/models/concerns/ten_digit_goods_nomenclature.rb
app/models/search_reference.rb

https://transformuk.atlassian.net/browse/HOTT-3520
- The /search_references endpoint was taking 9000 queries to finish (it now takes 2)
- The admin id was just wrong

HOTT-3520: Fixes n+1 in search references

---

terraform/README.md
terraform/backend_uk.tf
terraform/backend_xi.tf
terraform/data.tf
terraform/iam.tf
terraform/locals.tf
terraform/worker_uk.tf
terraform/worker_xi.tf

[HOTT-2789](https://transformuk.atlassian.net/browse/HOTT-2789)
- Upgraded the backend module versions to v1.12.0
See https://github.com/trade-tariff/trade-tariff-platform-terraform-modules/pull/41

HOTT-2789: Run init container for all backends

---

app/models/search_reference.rb

BAU
- This is helpful because goods nomenclature can move whilst retaining the same sid value. We already have handling for goods nomenclature references that get end-dated https://github.com/trade-tariff/trade-tariff-backend/blob/main/app/workers/clear_invalid_search_references.rb

BAU: Handle referenced class getting updated in search references

---

app/workers/monthly_exchange_rates_worker.rb

https://transformuk.atlassian.net/browse/HOTT-3892
- We want to retry the background job if XE API is down

HOTT-3892: Retry job later if XE connection fails

---

app/lib/reporting/differences.rb
app/lib/reporting/differences/quota_exclusion_misalignment.rb
app/models/quota_order_number.rb
app/models/quota_order_number_origin_exclusion.rb
spec/models/quota_order_number_spec.rb

This PR adds the report generator for the quota exclusion misalignment.
https://transformuk.atlassian.net/browse/HOTT-3268
the UK data of measure geographical area exclusions and quota origin exclusions should have the same data.
In case of misalignment, we must report it to HMRC

HOTT-3268: This PR allows to generate the quota exclusion misalignment report

---

app/controllers/api/v2/exchange_rates/files_controller.rb
app/mailers/exchange_rates_mailer.rb
app/models/exchange_rate_file.rb
app/views/exchange_rates_mailer/monthly_files.html.erb
spec/mailers/exchange_rates_mailer_spec.rb
spec/requests/api/v2/exchange_rates/files_controller_spec.rb
spec/views/exchange_rates_mailer/monthly_files.html.erb_spec.rb

https://transformuk.atlassian.net/browse/HOTT-3962
- Filenames needed to match HMRC requirements
- Email should only send HMRC_CSV type

HOTT-3962: Changed file names on download endpoint and updated emails

---

app/controllers/api/v2/exchange_rates/period_lists_controller.rb
spec/models/exchange_rates/period_list_spec.rb
spec/requests/api/v2/exchange_rates/period_lists_controller_spec.rb

HOTT-3910
This should not happen in a real world situation but handles if the user requests a year that has no periods in the exchange rate api

Better handling when no periods exist for exchange rates

---

db/rules_of_origin/roo_schemes_uk.json

https://transformuk.atlassian.net/browse/HOTT-3995
- it is no longer required

HOTT-3995: Removed extended cumulation method from Canada

---

app/lib/trade_tariff_backend.rb

BAU
- This is temporary until the following issue is resolved https://github.com/opensearch-project/opensearch-ruby/issues/205

BAU: Temp fixes opensearch require

---

terraform/backend_uk.tf
terraform/backend_xi.tf

[HOTT-4006](https://transformuk.atlassian.net/browse/HOTT-4006)
- Disabled ECS Exec on non-worker services.
- We only need to be able to exec into the worker services here. To prevent engineers touching the API services, I'm disabling it for them.

HOTT-4006: Disable Exec on API backends

---

app/workers/updates_synchronizer_worker.rb

https://transformuk.atlassian.net/browse/HOTT-4054
- This is required because these files have been arriving later and later

HOTT-4054: Adjust sync cutoff

---

app/lib/reporting/differences.rb
app/lib/reporting/differences/candidate_supplementary_unit.rb

https://transformuk.atlassian.net/browse/HOTT-3271
- This worksheet is used to work out whether there are candidate
supplementary units that could do with being created to highlight the
relevant units for trade.

HOTT-3271: Adds candidate supplementary unit worksheet

---

app/controllers/api/v2/exchange_rates/period_lists_controller.rb
app/models/exchange_rate_currency_rate.rb
app/models/exchange_rate_file.rb
app/models/exchange_rates/period.rb
app/models/exchange_rates/period_list.rb
app/serializers/api/v2/exchange_rates/exchange_rate_period_serializer.rb
spec/models/exchange_rate_currency_rate_spec.rb
spec/models/exchange_rates/period_list_spec.rb
spec/models/exchange_rates/period_spec.rb
spec/requests/api/v2/exchange_rates/period_lists_controller_spec.rb
spec/serializers/api/v2/exchange_rates/exchange_rate_period_serializer_spec.rb

Fix the support for for type `average` on the endpoint 'exchange_rates/period_lists'.
https://transformuk.atlassian.net/browse/HOTT-3976
To simplify/unify FE exchange rate pages.

HOTT-3976: Fix the support for type average 

---

app/controllers/api/v2/exchange_rates/base_controller.rb
app/models/exchange_rate_currency_rate.rb
app/models/exchange_rate_file.rb
app/models/exchange_rates/period_list.rb
app/services/exchange_rates/update_currency_rates_service.rb
app/services/exchange_rates/upload_monthly_file_service.rb
db/data_migrations/20231006122154_scheduled_to_monthly_rate_type.rb
spec/factories/exchange_rate_currency_rate_factory.rb
spec/factories/exchange_rates/exchange_rate_collection_factory.rb
spec/factories/exchange_rates/period_list_factory.rb
spec/models/exchange_rate_currency_rate_spec.rb
spec/models/exchange_rate_file_spec.rb
spec/models/exchange_rates/exchange_rate_collection_spec.rb
spec/models/exchange_rates/period_list_spec.rb
spec/models/exchange_rates/period_spec.rb
spec/requests/api/v2/exchange_rates/period_lists_controller_spec.rb
spec/requests/api/v2/exchange_rates_controller_spec.rb
spec/serializers/api/v2/exchange_rates/exchange_rate_period_list_serializer_spec.rb
spec/services/exchange_rates/create_csv_hmrc_service_spec.rb
spec/services/exchange_rates/create_csv_service_spec.rb
spec/services/exchange_rates/create_xml_service_spec.rb
spec/services/exchange_rates/update_currency_rates_service_spec.rb
spec/services/exchange_rates/upload_monthly_file_service_spec.rb

BAU
- scheduled is meaningless/duplicating and confusing as a type concept

BAU: Rename scheduled -> monthly

---

app/lib/tariff_synchronizer.rb
spec/integration/tariff_synchronizer/rollback_spec.rb
spec/workers/rollback_worker_spec.rb

Speed up rollback_spec, rollback_worker_spec.
Those tests used to run in minutes. They run in seconds now.
https://transformuk.atlassian.net/browse/HOTT-3952
Fast test == Happy developers, Happy QA testers, Higher productivity

Speed up BE tests.

---

app/models/exchange_rate_country_currency.rb
app/models/exchange_rate_currency_rate.rb
app/services/exchange_rates/create_country_currency_history_service.rb
app/services/exchange_rates/create_csv_service.rb
app/services/exchange_rates/create_xml_service.rb
spec/models/exchange_rate_currency_rate_spec.rb

BAU
- The historical country descriptions and country descriptions do not match what HMRC have currently
- The rates also do not match/are associated with the wrong currency codes
- The rounding needed to happen to enable consistency for monthly rates

BAU: Regenerate all monthly data

---

app/services/exchange_rates/monthly_exchange_rates_service.rb
app/services/exchange_rates/update_currency_rates_service.rb
app/workers/monthly_exchange_rates_worker.rb
spec/services/exchange_rates/monthly_exchange_rates_service_spec.rb
spec/services/exchange_rates/update_currency_rates_service_spec.rb
spec/workers/monthly_exchange_rates_worker_spec.rb

BAU
- We have an issue with the delineation between sample date and the validity period date when populating exchange rates The sample date is the date that we sample the api and the validity date is the applicable window that the rates apply for users of the service We need to reflect this difference as currently we're sampling dates from next month (which breaks the XeApi and returns a 400 status)

BAU: Enable sample date override for monthly rates

---

.env.test
app/mailers/exchange_rates_mailer.rb
spec/mailers/exchange_rates_mailer_spec.rb

BAU
- This gives us visibility on whether the mail was successfully sent

BAU: BCC support address on exchange rate email

---

app/lib/reporting/differences.rb
app/lib/reporting/differences/bad_quota_association.rb
app/lib/reporting/differences/candidate_supplementary_unit.rb
app/lib/reporting/differences/endline.rb
app/lib/reporting/differences/goods_nomenclature.rb
app/lib/reporting/differences/goods_nomenclature_end_date.rb
app/lib/reporting/differences/goods_nomenclature_start_date.rb
app/lib/reporting/differences/hierarchy.rb
app/lib/reporting/differences/incomplete_measure_condition.rb
app/lib/reporting/differences/indentation.rb
app/lib/reporting/differences/me16.rb
app/lib/reporting/differences/me32.rb
app/lib/reporting/differences/measure_quota_coverage.rb
app/lib/reporting/differences/mfn_duplicated.rb
app/lib/reporting/differences/mfn_missing.rb
app/lib/reporting/differences/misapplied_action_code.rb
app/lib/reporting/differences/missing_vat_measure.rb
app/lib/reporting/differences/omitted_duty_measures.rb
app/lib/reporting/differences/overview.rb
app/lib/reporting/differences/quota_exclusion_misalignment.rb
app/lib/reporting/differences/quota_missing_origin.rb
app/lib/reporting/differences/supplementary_unit.rb
app/models/quota_order_number.rb

https://transformuk.atlassian.net/browse/HOTT-3360
- This is required to get us to a feature complete differences report

HOTT-3360: Adds an overview worksheet

---

app/controllers/api/api_controller.rb
app/controllers/api/v2/exchange_rates/period_lists_controller.rb
app/controllers/api/v2/exchange_rates_controller.rb
spec/requests/api/v2/exchange_rates/period_lists_controller_spec.rb
spec/requests/api/v2/exchange_rates_controller_spec.rb

BAU
- To avoid passing these to db filters unnecessarily

BAU: Adds basic handling of unsupported ids

---

app/workers/monthly_exchange_rates_worker.rb

BAU
- This was causing random failures in the tests

BAU: Fixes exchange rate date comparison failures

---

app/controllers/api/admin/commodities_controller.rb
spec/requests/api/admin/commodities_controller_spec.rb

https://transformuk.atlassian.net/browse/HOTT-4239
- This was preventing us from subsequently fetching search references for the returned goods nomenclature

HOTT-4239: Fixes reading subheadings with search references

---

app/serializers/api/admin/chapters/chapter_list_serializer.rb
app/serializers/api/admin/chapters/chapter_serializer.rb
app/serializers/api/admin/chapters/heading_serializer.rb
app/serializers/api/admin/headings/chapter_serializer.rb
app/serializers/api/admin/headings/heading_serializer.rb
spec/serializers/api/admin/chapters/chapter_list_serializer_spec.rb
spec/serializers/api/admin/chapters/chapter_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-4238
- This is required for the admin UI to be consistent in its handling of these types of goods nomenclature

HOTT-4238: Surface producline suffix values for chapters/headings

---

app/models/exchange_rate_country_currency.rb
app/models/exchange_rate_currency_rate.rb
app/services/exchange_rates/average_exchange_rates_service.rb
app/services/exchange_rates/create_average_exchange_rates_service.rb
app/services/exchange_rates/create_csv_average_rates_service.rb
app/services/exchange_rates/monthly_exchange_rates_service.rb
app/services/exchange_rates/spot_exchange_rates_service.rb
app/services/exchange_rates/upload_file_service.rb
app/workers/average_exchange_rates_worker.rb
config/sidekiq.yml
docs/exchange_rate_average_rates.md
spec/factories/exchange_rate_country_currency.rb
spec/factories/exchange_rate_currency_rate_factory.rb
spec/models/exchange_rate_country_currency_spec.rb
spec/models/exchange_rate_currency_rate_spec.rb
spec/services/exchange_rates/average_exchange_rates_service_spec.rb
spec/services/exchange_rates/create_average_exchange_rates_service_spec.rb
spec/services/exchange_rates/create_csv_average_rates_service_spec.rb
spec/services/exchange_rates/monthly_exchange_rates_service_spec.rb
spec/services/exchange_rates/spot_exchange_rates_service_spec.rb
spec/services/exchange_rates/upload_file_service_spec.rb
spec/workers/average_exchange_rates_worker_spec.rb

HOTT-3401
See screenshots taken on local env after running `ExchangeRates::AverageExchangeRatesService.call(force_run: true, selected_date: '2023-10-25')`

Create twice-yearly exchange rate AVERAGE rate data: required in CSV and 'view online'

---

docker-compose.yml

HOTT-????
- current config is incompatible with systems using Security Enhanced Linux, ie RedHat/Fedora/Oracle
- Low, just changes the development docker-compose flie

BAU: Fix docker-compose file on SE Linux systems

---

app/lib/reporting/differences/candidate_supplementary_unit.rb
app/models/measurement_unit.rb
db/measurement_units.json
spec/models/measurement_unit_spec.rb

https://transformuk.atlassian.net/browse/HOTT-4323
- This is required to unblock the delivery of the differences report

HOTT-4323: Fixes candidate supplementary units

---

.gitignore
README.md
bin/setup
docker-compose.yml

HOTT-4302
- Developer onboarding is too complicated and wastes valuable developer time
- Low, development focused changes

HOTT-4302 Updated bin/setup and README.md

---

terraform/locals.tf

BAU
- This is what the container exposes

BAU: Adds 8080 to signon links

---

app/lib/trade_tariff_backend.rb
app/workers/report_worker.rb
terraform/README.md
terraform/data.tf
terraform/iam.tf
terraform/locals.tf

https://transformuk.atlassian.net/browse/HOTT-2796
- This is required to avoid special casing features only in production - we can run reports in development or staging and verify they integrate cleanly now

HOTT-2796: Enable reporting in the new world

---

.gitignore
.rspec
spec/spec_helper.rb

This PR will allow devs to use the flag `--only-failures` when running rspec and give more detailed output of the test suite

Add ability for only failures with rspec running

---

app/models/exchange_rate_file.rb
spec/models/exchange_rate_file_spec.rb

Fix bug for the endpoint:
/api/v2/exchange_rates/files/monthly_xml_2023-<??>.xml 
endpoint, which happens only for the months "08" and "09". The reason for the bug is that 08 and 09 are interpreted as not valid octal numbers.
https://transformuk.atlassian.net/browse/HOTT-4350
It is a bug, 
To reproduce it:
This works:
https://www.trade-tariff.service.gov.uk/api/v2/exchange_rates/files/monthly_xml_2023-08.xml
These do not work:
https://www.trade-tariff.service.gov.uk/api/v2/exchange_rates/files/monthly_xml_2023-08.xml
https://www.trade-tariff.service.gov.uk/api/v2/exchange_rates/files/monthly_xml_2023-09.xml
But they should work!

HOTT-4377: Fix bug for the endpoint /api/v2/exchange_rates/files/monthly_xml_2023-<??>.xml

---

app/lib/sequel/plugins/national.rb
spec/models/measure_spec.rb

https://transformuk.atlassian.net/browse/HOTT-4410
- Rubocop isn't sequel aware with predicate method checks and this is breaking taric data loads

HOTT-4410: Fixes national filter after rubocop failure

---

app/controllers/api/v2/green_lanes/subheadings_controller.rb
app/serializers/api/v2/green_lanes/subheading_serializer.rb
config/routes.rb
spec/requests/api/v2/green_lanes/subheadings_controller_spec.rb
spec/serializers/api/v2/green_lanes/subheading_serializer_spec.rb

https://transformuk.atlassian.net/browse/HOTT-4350
Added Green Lanes Subheading Stub API end point
- To start green lanes work
- I should be able to query an end point which will eventually provide 6 digit permutations information but is currently just a stub

HOTT-4350: Green Lanes: Create Stub API end point

---

config/routes.rb

[HOTT-4404](https://transformuk.atlassian.net/browse/HOTT-4404)
- This is an experimental API and I cannot expect the API to remain consistent or supported

HOTT-4404: Move green_lanes API to /api/v2/experimental/green_lanes/subheading/:id

---

.circleci/config.yml

BAU
- This is required to stop Sunday failures since we've now deleted both the dev/staging spaces in the Govuk PaaS

BAU: Removes dead jobs

---

db/rules_of_origin/roo_schemes_uk.json

https://transformuk.atlassian.net/browse/HOTT-4287
Fix to Lebanon trade agreement in the roo_schemes_uk.json
It, mistakenly, points to Albania.

Fix to Lebanon trade agreement in the roo_schemes_uk.json

---

terraform/locals.tf

BAU
Each account is responsible for a main zone:
- dev.trade-tariff.service.gov.uk for development (delegated)
- staging.trade-tariff.service.gov.uk for staging (delegated)
- trade-tariff.service.gov.uk for production
We have verified identities in each account for each zone and need to
reflect that in the from address for the differences emails
- This enables emails to be sent from a verified zone

BAU: Fixes no-reply address

---

terraform/config_development.tfvars

BAU
- These packages got recreated after the development cluster was deleted and this is breaking the smoke tests that run on development

BAU: Fixes package path for development

---

.circleci/config.yml

HOTT-4392
Ensuring we arent wasting processing power when the ruby linting fails early on in the development pipeline.

Block deploying to dev before linting code

---

terraform/locals.tf

[HOTT-4453](https://transformuk.atlassian.net/browse/HOTT-4533)
- Updated signon URL when in production mode
- We don't host this service in production

HOTT-4453: Fix Signon URL in Production

---

lib/tasks/green_lanes.rake

HOTT-4221
- So we can use it in the categorisation of green lanes in the API response
- Low, just adds a rake task

HOTT-4221 Rake task to generate green lanes categories.json

---

.gitignore

HOTT-4564
- it should help prevent accidental inclusion of temporary development data
- Low

HOTT-4564 Ignore green lanes categorisation data

---

.circleci/config.yml

[HOTT-4598](https://transformuk.atlassian.net/browse/HOTT-4598)
- Updated releases context in CircleCi config.
- We now have a new context that we can use for releases, so we'll want to use this.

HOTT-4598: Update Releases Context

---

db/rules_of_origin/roo_schemes_uk/rule_sets/japan.json

https://transformuk.atlassian.net/browse/HOTT-4264
- One of the governing bodies for fish ICCAT should be abbreviated.

HOTT-4264 Fix to Japan rules of origin on fish: any comm code in heading 0301

---

db/data_migrations/20231213154345_fix_publication_date.rb

https://transformuk.atlassian.net/browse/HOTT-4557
- Fixed the ExchangeRateFile publication dates starting from late October
- We were displaying the incorrect date on ExchangeRate pages

HOTT-4557: Publication date data fix

---

app/services/exchange_rates/create_average_exchange_rates_service.rb
app/services/exchange_rates/monthly_exchange_rates_service.rb
app/services/exchange_rates/spot_exchange_rates_service.rb
app/services/exchange_rates/upload_file_service.rb
spec/services/exchange_rates/monthly_exchange_rates_service_spec.rb
spec/services/exchange_rates/spot_exchange_rates_service_spec.rb
spec/services/exchange_rates/upload_file_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-4557
- We were saving/displaying the incorrect date on ExchangeRates

HOTT-4557: Publication date code fix

---

terraform/config_staging.tfvars

https://transformuk.atlassian.net/browse/HOTT-4578
- I'm doing this separately so I can run regression tests against staging before/after reindexing and after enabling the enhancements to simulate production behaviour

HOTT-4578: Enable legacy search enhancements on staging

---

app/controllers/api/v2/green_lanes/categorisations_controller.rb
app/models/green_lanes/categorisation.rb
app/serializers/api/v2/green_lanes/categorisation_serializer.rb
config/routes.rb
spec/models/green_lanes/categorisation_spec.rb
spec/requests/api/v2/green_lanes/categorisation_controller_spec.rb
spec/serializers/api/v2/green_lanes/categorisation_serializer_spec.rb

[HOTT-4561]<https://transformuk.atlassian.net/browse/HOTT-4561>
- This will facilitate service like TSS to implement green lanes if they plan to fully recalculate the logic and use over night scrapes
-
-

HOTT-4561: Categorisation API

---

app/models/exchange_rate_country_currency.rb
app/services/exchange_rates/create_average_exchange_rates_service.rb
spec/models/exchange_rate_country_currency_spec.rb
spec/services/exchange_rates/create_average_exchange_rates_service_spec.rb

HOTT-4754
- Previously the avg rate task would have generated a rate for any countries that had a live rate in the last 12 months
-
-

Fix average rate creation bugs

---

db/migrate/20240110120545_adds_user_privileges.rb
db/structure.sql

BAU
- This was missed and is a tad confusing since previous default privileges were working
- This unblocks feature branches from not being able to deploy to development and will also make a readonly user possible in staging and production envs

BAU: Fixes deployments

---

.circleci/config.yml

HOTT-4822
- Whilst it arguably adds friction to the dev process pre-merge, it makes the dev server QA-able, in turn removing friction around the process post-merge which is where our actual primary contention is
- Low, should only impact dev server

HOTT-4822 Add approval before releasing to dev server

---

terraform/worker_uk.tf
terraform/worker_xi.tf

- Set service count, min and max capacities to `1` for the workers.
- Multiple deployed workers leads to multiple init containers, where the database migrations run, and this leads to concurrent migrations run against the db throwing alerts.

BAU: Only deploy a single worker for each backend

---

app/controllers/api/v2/exchange_rates/base_controller.rb

HOTT-4814
- ExchangeRates API responses are getting cached and should not be
- May increase backend load on server

HOTT-4814 Disable ETag caching for exchange rates

---

app/controllers/api/v2/green_lanes/base_controller.rb
spec/requests/api/v2/green_lanes/categorisation_controller_spec.rb
spec/requests/api/v2/green_lanes/subheadings_controller_spec.rb

[HOTT-4856](https://transformuk.atlassian.net/browse/HOTT-4856)
- This is to avoid api consumers inadvertently consuming the incorrect data
-
-

HOTT-4856: Restrict APIs to XI service only

---

db/rules_of_origin/roo_schemes_uk/articles/iceland-norway/verification.md

https://transformuk.atlassian.net/browse/HOTT-4847
See diff docs from previous PR here:
https://github.com/trade-tariff/trade-tariff-backend/pull/1656/files#diff-42fbea93715ff1a1777ace7aea21f8e73eed3f8bf29f39f6820ee1a16c7034d6 
- Following recent Iceland-Norway Roo updates had a discussion with Chris B to agree that this how it should look to resolve the bug on the page.
**Before Fix**
**After Fix**

HOTT-4847 Combine Article placeholders on one page for Iceland-Norway Origin Proof Verification

---

db/rules_of_origin/roo_schemes_uk/articles/iceland-norway/cumulation-export.md
db/rules_of_origin/roo_schemes_uk/articles/iceland-norway/cumulation-import.md

https://transformuk.atlassian.net/browse/HOTT-4904
- The Article number has changed in the Rules of Origin Reference Document

HOTT-4904 Update Article 9 to 8 for Cumulation For Iceland-Norway

---

terraform/admin_xi.tf
terraform/worker_xi.tf

HOTT-4913
- Admin: It is incorrect an _could_ cause issues if copied to other apps where it does have impact
- Worker: This breaks the sync on XI, and ends up following some unexpected/unintended code paths that seem to have come about as a consequence of separation of CDS and Taric synchronisers
- In general this env var is there to support a scenario we no longer require, is dangerous, and should be removed
- Changes server configuration across all environments

HOTT-4913 XI workers have the CDS variable set to true

---

config/environments/development.rb

This was broken during the Rails 7.1 upgrade
HOTT-????
- It was broken by the Rails 7.1 update
Not entirely convinced by this fix _but_ it appears to work and is better than log output being broken, and only affects the local development environment
- Low, only affects local development environment

HOTT-??? Fixed logging to rails console

---

config/environments/production.rb

HOTT-4690
- To date we've been using GOVUK_APP_DOMAIN for our cache prefix and our workers were configured with this environment variable to match to webapps. This is no longer the case and that means the workers are clearing/modifying different cache keys than the webapps are using resulting in the "clear cache" button being broken
- We have separate Redis instances for different environments so the old approach to namespacing wasn't required and is now actually problematic
- This means all apps for a service will share a common cache - allowing workers or backend admin webapps to modify the cache used by the main readonly webapp
- Changes the Cache prefix, so this will effectively clear the cache on deploy
- It makes sense to deploy …

HOTT-4690 Just use SERVICE for cache namespace

---

app/models/green_lanes/categorisation.rb
lib/tasks/green_lanes.rake
spec/models/green_lanes/categorisation_spec.rb

HOTT-4994
- We will want to expose this in the API
- Low, private API - specs test both with and without key in JSON

HOTT-4994 Added theme to categorisation model

---

app/workers/synchronizer_check_worker.rb
config/sidekiq.yml
spec/workers/synchronizer_check_worker_spec.rb

HOTT-4930
- It should alert us if data is getting out of sync - QuotaBalanceEvent is our most frequently changing table
- None - background job, just checks the data is recent

HOTT-4930 Added simple check that sync is happening

---

terraform/iam.tf

HOTT-5069
I am doing this to allow the rake tasks for rebuilding the exchange rate files to have delete access.

Allow the worker to have access to use the delete object method on the AWS servers for exchange rate path.

---

terraform/worker_uk.tf
terraform/worker_xi.tf

HOTT-5091
- We were running out of memory
- Not the best solution, code is loading a lot of data all at once but lacks tests so this is the safer fix for now
- Low, should just resize worker nodes

HOTT-5091 Increase size of worker nodes

---

config/routes.rb

https://transformuk.atlassian.net/browse/HOTT-4893
Add contraint for numeric values for GET measures API.
To prevent this kind of error: https://engine-le.sentry.io/issues/4874789117/?alert_rule_id=3445710&alert_type=issue&environment=production&notification_uuid=0babcc27-f829-4032-97af-df6eba72c9f3&project=5557005&referrer=slack

HOTT-4893: Add contraint for numeric values for GET measures API.

---

config/routes.rb
spec/rails_helper.rb
spec/requests/api/v2/measures_controller_spec.rb

Previous addition of a numeric constraint on :id only allowed access to measures with sids > 0
HOTT-4893
- we have measures with negative sids and the change to restrict id to numeric values prevented access to measures with negative sids
- Low, minor slackening of routing constraint with additional specs to cover scenario

HOTT-4893 Allow measures API for negative measures

---

.circleci/config.yml

Also allows deploying PR to QA for testing
HOTT-???
- At present dependabot PRs don't get tested at either DEV or Staging steps in the pipeline allowing us to unintentionally merge and deploy a dependabot PR which breaks our code base
- Low, just affects dependabot PRs

Runs specs for dependabot PRs

---

app/controllers/api/v2/green_lanes/goods_nomenclatures_controller.rb
app/services/green_lanes/find_category_assessments_service.rb
spec/requests/api/v2/green_lanes/goods_nomenclatures_controller_spec.rb
spec/services/green_lanes/find_category_assessments_service_spec.rb

https://transformuk.atlassian.net/browse/HOTT-5113
Rename Green Lane filter[origin] to filter[geographical_area_id].
To comply with the design in the API doc

Rename Green Lane origin filter

---

app/controllers/api/v2/green_lanes/category_assessments_controller.rb
app/controllers/api/v2/green_lanes/goods_nomenclatures_controller.rb
app/models/green_lanes/category_assessment.rb
app/presenters/api/v2/green_lanes/category_assessment_presenter.rb
app/presenters/api/v2/green_lanes/goods_nomenclature_presenter.rb
app/presenters/api/v2/green_lanes/measure_presenter.rb
app/serializers/api/v2/green_lanes/category_assessment_serializer.rb
app/serializers/api/v2/green_lanes/measure_serializer.rb
app/services/green_lanes/find_category_assessments_service.rb
spec/factories/green_lanes/category_assessment_factory.rb
spec/models/green_lanes/category_assessment_spec.rb
spec/presenters/api/v2/green_lanes/category_assessment_presenter_spec.rb
spec/presenters/api/v2/green_lanes/goods_nomenclature_presenter_spec.rb
spec/presenters/api/v2/green_lanes/measure_presenter_spec.rb
spec/requests/api/v2/green_lanes/category_assessments_controller_controller_spec.rb
spec/requests/api/v2/green_lanes/goods_nomenclatures_controller_spec.rb
spec/serializers/api/v2/green_lanes/goods_nomenclature_serializer_spec.rb
spec/serializers/api/v2/green_lanes/measure_serializer_spec.rb
spec/services/green_lanes/find_category_assessments_service_spec.rb

HOTT-5114
- Our proposed API needs to serialize out the measures relating to CategoryAssessments
- Low, private (for now) API

HOTT-5114 add measures to category assessments

---

app/serializers/api/v2/green_lanes/category_assessment_serializer.rb
app/serializers/api/v2/green_lanes/goods_nomenclature_serializer.rb
spec/serializers/api/v2/green_lanes/category_assessment_serializer_spec.rb
spec/serializers/api/v2/green_lanes/goods_nomenclature_serializer_spec.rb

Was previously `green_lanes_category_assessment` but thats not the name we've been using in the docs
HOTT-5132
- It brings it inline with the documentation
- Low

HOTT-5132 Rename entity to CategoryAssessment

---

terraform/backend_xi.tf

- Removed `init_container` config from `backend_xi`.
- It has no effect but produces errors because the database connection string is read-only.

BAU: Remove init container config from API app

---

app/models/base_regulation.rb
app/models/green_lanes/category_assessment.rb
app/models/green_lanes/theme.rb
app/models/measure_type.rb
app/models/modification_regulation.rb
spec/factories/green_lanes/category_assessment_factory.rb
spec/factories/green_lanes/theme_factory.rb
spec/models/base_regulation_spec.rb
spec/models/green_lanes/category_assessment_spec.rb
spec/models/green_lanes/theme_spec.rb
spec/models/measure_type_spec.rb
spec/models/modification_regulation_spec.rb

HOTT-4567
- We will need this to implement a database backed version of the green lanes api
- Low, not used anywhere yet

HOTT-4567 add category assessment model

---

db/rules_of_origin/roo_schemes_uk/rule_sets/eu.json

https://transformuk.atlassian.net/browse/HOTT-4684
- There was a copy error in CTH (Chapter & Heading) for 1704 
BEFORE
AFTER

HOTT-4684 EU Rules of Origin PSRs Minor copy change for CTH 1704

---

db/rules_of_origin/roo_schemes_uk/rule_sets/japan.json

https://transformuk.atlassian.net/browse/HOTT-4685
- There was a copy error for Sugar CTH (Chapter & Heading) 1806 for Japan Rules of Origin Product Specific Rules
BEFORE
AFTER

HOTT-4685 Japan RoO PSRs copy error fix

---

db/rules_of_origin/roo_schemes_uk/rule_sets/central-america.json

https://transformuk.atlassian.net/browse/HOTT-4691
- RoO PSRs for Central America are out of date
Testing on commodity 5909001000
BEFORE
AFTER

HOTT-4691 Updated Central America RoO PSRs

---

db/rules_of_origin/roo_schemes_uk/rule_sets/faroe-islands.json

https://transformuk.atlassian.net/browse/HOTT-4697
- The Rules of Origin Product Specific Rules for the Faroe Islands are not in line with the Origin Reference Document
Test results against commodity 5007100010
BEFORE
AFTER

HOTT-4697 Updated Faroe Islands RoO PSRs

---

db/rules_of_origin/roo_schemes_uk/rule_sets/egypt.json

https://transformuk.atlassian.net/browse/HOTT-4700
- Egypt's RoO PSRs formatting was incorrect
Tested on commodity 3006101000
BEFORE
AFTER

HOTT-4700 Updated Egypt RoO PSRs

---

db/rules_of_origin/roo_schemes_uk/rule_sets/north-macedonia.json

https://transformuk.atlassian.net/browse/HOTT-4708
- Formatting changes for North Macedonia RoO PSRs
Tested on commodity 3006101000
BEFORE
AFTER

HOTT-4708 Updated North Macedonia RoO PSRs

---

db/rules_of_origin/roo_schemes_uk/rule_sets/pacific.json

https://transformuk.atlassian.net/browse/HOTT-4710
- To fix errors in Pacific RoO PSRs
Tested on commodity 3205000010 for Fiji (Note hyperlinks have been added to headings references)
BEFORE
AFTER

HOTT-4710 Updated Pacific RoO PSRs

---

app/models/green_lanes/category_assessment.rb
app/models/measure.rb
app/services/green_lanes/permutation_calculator_service.rb
spec/factories/additional_code_factory.rb
spec/factories/green_lanes/category_assessment_factory.rb
spec/factories/measure_factory.rb
spec/models/green_lanes/category_assessment_spec.rb
spec/models/measure_spec.rb
spec/services/green_lanes/permutation_calculator_service_spec.rb

GL-150
- We require this functionality to populate the Green Lanes Category Assessments and Green Lanes Goods Nomenclature APIs
- Low, shouldn't impact existing code at this point

GL-150 Category Assessment Permutation calculator

---

app/controllers/api/v2/green_lanes/category_assessments_controller.rb
app/models/green_lanes/category_assessment.rb
app/presenters/api/v2/green_lanes/category_assessment_presenter.rb
app/presenters/api/v2/green_lanes/measure_presenter.rb
app/services/green_lanes/permutation_calculator_service.rb
spec/models/green_lanes/category_assessment_spec.rb
spec/presenters/api/v2/green_lanes/category_assessment_presenter_spec.rb

GL-148
- We wish to use 'real' data in the API
- The `CategoryAssessmentPresenter` has a Many to One relationship to `CategoryAssessment` it is presenting because it includes additional information not present on the CategoryAssessment record in the database. We serialize a single CategoryAssessment for every combination of measures against a particular db CategoryAssessment
- Will break the GreenLanes GoodsNomenclature API if it is merged separately from the GreenLanes GoodsNomenclature API database conversion
The failing tests are expected and are correctly in a following PR. The intention is to merge to an Epic branch and merge both concurrently once they have been independently reviewed

Gl 148 convert category assessments api to db

---

app/controllers/api/admin/green_lanes/category_assessments_controller.rb
config/routes.rb
spec/requests/api/admin/green_lanes/category_assessments_controller_spec.rb

[GL-102](https://transformuk.atlassian.net/browse/GL-102)
- We need to  build a Green Lanes admin interface to manage green lanes category assessments

GL-102: Add Admin API to backend for CRUD of categorisation data

---

app/models/preference_code.rb
app/presenters/api/v2/commodities/commodity_presenter.rb
app/presenters/api/v2/headings/declarable_heading_presenter.rb
app/presenters/api/v2/special_nature.rb
spec/models/preference_code_spec.rb
spec/presenters/api/v2/commodities/commodity_presenter_spec.rb
spec/presenters/api/v2/headings/declarable_headings_presenter_spec.rb

https://transformuk.atlassian.net/browse/OTT-85
https://transformuk.atlassian.net/browse/OTT-132
- The preference codes displayed were wrong

OTT-85 and OTT-132: Fixed preference codes bug on commodities and declarable headings pages/API

---

app/controllers/api/v2/green_lanes/category_assessments_controller.rb
app/models/green_lanes/theme.rb
app/presenters/api/v2/green_lanes/category_assessment_presenter.rb
app/services/green_lanes/fetch_goods_nomenclature_service.rb
app/services/green_lanes/find_category_assessments_service.rb
spec/factories/geographical_area_factory.rb
spec/factories/green_lanes/category_assessment_factory.rb
spec/factories/measure_factory.rb
spec/models/green_lanes/theme_spec.rb
spec/presenters/api/v2/green_lanes/category_assessment_presenter_spec.rb
spec/presenters/api/v2/green_lanes/goods_nomenclature_presenter_spec.rb
spec/serializers/api/v2/green_lanes/goods_nomenclature_serializer_spec.rb
spec/services/green_lanes/find_category_assessments_service_spec.rb

GL-138
- We want to rely on the database for the Category Assessments data and their measures
- This will allow managing the Category Assessments an api consumer sees
- Low, should only be changing GreenLanes APIs

GL-138 Convert GreenLanes GoodsNomenclature API to use database

---

.env.development
.env.test
app/lib/trade_tariff_backend.rb
config/routes.rb
terraform/admin_uk.tf
terraform/admin_xi.tf

OTT-???
- These routes are inaccessible and so redundant on the other backends
- Should be low

OTT-??? Feature flag admin APIs

---

app/controllers/api/v2/green_lanes/goods_nomenclatures_controller.rb
app/presenters/api/v2/green_lanes/goods_nomenclature_presenter.rb
spec/presenters/api/v2/green_lanes/goods_nomenclature_presenter_spec.rb
spec/requests/api/v2/green_lanes/goods_nomenclatures_controller_spec.rb
spec/serializers/api/v2/green_lanes/goods_nomenclature_serializer_spec.rb

GL-290
- It simplifies the specs
- It is needed to enable filtering measures for ancestors in a later PR
- Low, stacks changes on an Epic branch

GL-290 Refactor GL GN presenter

---

terraform/worker_xi.tf

BAU
- This is required because the HMRC API is broken

BAU: Use the patched downloader

---

app/presenters/api/v2/green_lanes/category_assessment_presenter.rb
app/services/green_lanes/permutation_calculator_service.rb
spec/factories/certificate_factory.rb
spec/presenters/api/v2/green_lanes/category_assessment_presenter_spec.rb
spec/services/green_lanes/permutation_calculator_service_spec.rb

HOTT-388
- We should not be included other certificate types such as licenses
- Low

GL-338 Only include exemption certificates

---

.circleci/config.yml

BAU
- Opensearch 2.11 changed the flag for disabling security in test mode and we were using the old version of opensearch in the tests (bigger issue). I discovered all this chasing the tail of the broken intermittent flaky test workflow

BAU: Fix opensearch configuration issue in tests

---

app/models/quota_blocking_period.rb
app/models/quota_definition.rb
app/models/quota_suspension_period.rb
spec/factories/quota_factory.rb
spec/models/quota_blocking_period_spec.rb
spec/models/quota_definition_spec.rb
spec/models/quota_suspension_period_spec.rb

https://transformuk.atlassian.net/browse/OTT-129
- We need to handle suspended and blocked quota statuses

OTT-129: Quota suspensions and blocking periods bug fix

---

app/models/green_lanes/theme.rb
app/presenters/api/v2/green_lanes/category_assessment_presenter.rb
app/serializers/api/v2/green_lanes/category_assessment_serializer.rb
app/serializers/api/v2/green_lanes/theme_serializer.rb
spec/models/green_lanes/theme_spec.rb
spec/presenters/api/v2/green_lanes/category_assessment_presenter_spec.rb
spec/serializers/api/v2/green_lanes/category_assessment_serializer_spec.rb
spec/serializers/api/v2/green_lanes/theme_serializer_spec.rb

GL-151
- It brings us inline with the upstream API design
- Gives us some where to attach further theme information in the future if so required
- Low, only changes GL APIs

GL-151 Add Theme entity

---

app/controllers/api/v2/green_lanes/goods_nomenclatures_controller.rb
app/presenters/api/v2/green_lanes/goods_nomenclature_presenter.rb
app/serializers/api/v2/green_lanes/goods_nomenclature_serializer.rb
app/services/green_lanes/find_category_assessments_service.rb
spec/presenters/api/v2/green_lanes/goods_nomenclature_presenter_spec.rb
spec/requests/api/v2/green_lanes/goods_nomenclatures_controller_spec.rb
spec/serializers/api/v2/green_lanes/goods_nomenclature_serializer_spec.rb
spec/services/green_lanes/find_category_assessments_service_spec.rb

GL-142
- We want to expose the 'MIGHT' category assessments which apply to goods nomenclatures below the requested GN
- Low, only impacts GL GN API

GL-142 descendant category assessments

---

app/serializers/api/v2/green_lanes/certificate_serializer.rb
spec/serializers/api/v2/green_lanes/certificate_serializer_spec.rb

GL-295
- It standardises the format of exemptions - simplifying things for clients. Both Certificate and AdditionalCode exemptions can be stored by just the `code` and the `description`/`formatted_description`
- Low, only affects green lanes

GL-295 Update certificate serialization

---

app/controllers/api/v2/green_lanes/goods_nomenclatures_controller.rb
app/serializers/api/v2/green_lanes/category_assessment_serializer.rb
spec/serializers/api/v2/green_lanes/category_assessment_serializer_spec.rb

GL-379
- It will end up as a very long list of measure ids, particularly if we implement regulation-less category assessments
- Low, impacts epic branch

GL-379 Drop measures from category assessments endpoint

---

app/models/green_lanes/category_assessment.rb
spec/models/green_lanes/category_assessment_spec.rb

[GL-103](https://transformuk.atlassian.net/browse/GL-103)
- For the current implementation of CategoryAssessment should have regulations.
- Regulation-less CategoryAssessment will be impletemented in the future

GL-103: Add Admin UI for creating category assessment data

---

app/controllers/api/v2/green_lanes/goods_nomenclatures_controller.rb
app/serializers/api/v2/green_lanes/goods_nomenclature_serializer.rb
app/serializers/api/v2/green_lanes/referenced_goods_nomenclature_serializer.rb
spec/serializers/api/v2/green_lanes/goods_nomenclature_serializer_spec.rb
spec/serializers/api/v2/green_lanes/referenced_goods_nomenclature_serializer_spec.rb

GL-442
- There is still some ambiguity around how this information is presented but it is not yet required
- The rest of GL-308 is ready to release and is needed by our partners to make progress
- Removing this allows us to present and updated format to our partners
- Low, for now directly affects epic branch

GL-442 remove measures for now

---

db/rules_of_origin/roo_schemes_uk.json

https://transformuk.atlassian.net/browse/OTT-214 
I have
- The Singapore ORD was out of date
BEFORE 
AFTER

OTT-214 Updated Singapore ORD Details

---

db/rules_of_origin/roo_schemes_uk.json

https://transformuk.atlassian.net/browse/OTT-216
- The Canada ORD was out of date
BEFORE
AFTER

OTT-216 Updated Canada ORD Details

---

db/rules_of_origin/roo_schemes_uk.json

https://transformuk.atlassian.net/browse/OTT-212
- It was wrong
BEFORE
AFTER

OTT-212 Update Reference Date for Iceland ORD

---

db/rules_of_origin/roo_schemes_uk.json
db/rules_of_origin/roo_schemes_uk/articles/south-korea/wholly-obtained.md

https://transformuk.atlassian.net/browse/OTT-215
- The South Korea ORD was out of date and some of the details represented incorrectly.
BEFORE
AFTER

OTT-215 Updated South Korea ORD Details

---

db/rules_of_origin/roo_schemes_uk/articles/cotedivoire/wholly-obtained.md

https://transformuk.atlassian.net/browse/OTT-217
- The Cote D'Ivoire ORD  Wholly Obtained Definition was badly numbered at paragraph (e) 
BEFORE
AFTER

OTT-217 Updated Cote d'Ivoire ORD Details

---

db/rules_of_origin/roo_schemes_uk.json

https://transformuk.atlassian.net/browse/OTT-212
- The Iceland ORD version and date details were out of date
BEFORE
AFTER

OTT-212 Updated Iceland ORD Details

---

app/controllers/api/admin/green_lanes/category_assessments_controller.rb
app/controllers/api/admin/green_lanes/exempting_certificate_overrides_controller.rb
app/controllers/api/admin/green_lanes/themes_controller.rb
app/controllers/concerns/xi_only.rb
app/serializers/api/admin/green_lanes/exempting_certificate_override_serializer.rb
config/routes.rb
spec/requests/api/admin/green_lanes/exempting_certificate_overrides_controller_spec.rb

[GL-366](https://transformuk.atlassian.net/browse/GL-366)
- So that a screen in the Admin area can be built to manage exempting certificate overrides

GL-366: Add admin APIs to list out a page of overrides

---

app/controllers/api/admin/green_lanes/category_assessments_controller.rb
app/controllers/api/admin/green_lanes/exempting_certificate_overrides_controller.rb
app/controllers/api/admin/green_lanes/themes_controller.rb
app/controllers/concerns/xi_only.rb
app/models/measure_condition.rb
app/presenters/api/v2/green_lanes/category_assessment_presenter.rb
app/serializers/api/admin/green_lanes/exempting_certificate_override_serializer.rb
app/services/green_lanes/fetch_goods_nomenclature_service.rb
app/services/green_lanes/permutation_calculator_service.rb
config/routes.rb
spec/factories/certificate_factory.rb
spec/factories/measure_factory.rb
spec/models/measure_condition_spec.rb
spec/presenters/api/v2/green_lanes/category_assessment_presenter_spec.rb
spec/requests/api/admin/green_lanes/exempting_certificate_overrides_controller_spec.rb
spec/services/green_lanes/permutation_calculator_service_spec.rb

[GL-365](https://transformuk.atlassian.net/browse/GL-365)
- We want to override the default exemption behaviour of certificates.

GL-365: Use exempting_certificate_override table to control whether a certificate is treated as an exemption

---

app/models/goods_nomenclature.rb
app/models/green_lanes/category_assessment.rb
app/models/green_lanes/exemption.rb
app/models/green_lanes/measure.rb
spec/factories/green_lanes/category_assessment_factory.rb
spec/factories/green_lanes/exemption_factory.rb
spec/factories/green_lanes/measure_factory.rb
spec/models/goods_nomenclature_spec.rb
spec/models/green_lanes/category_assessment_spec.rb
spec/models/green_lanes/exemption_spec.rb
spec/models/green_lanes/measure_spec.rb

GL-359
- We need to manually associate certain category assessments with certain goods nomenclatures
- We need to manually add exemptions to certain category assessments
- Low, primarily impacts green lanes models

GL-359 Add pseudo measures models

---

app/controllers/api/v2/green_lanes/category_assessments_controller.rb
app/presenters/api/v2/green_lanes/category_assessment_presenter.rb
app/presenters/api/v2/green_lanes/exemption_presenter.rb
app/serializers/api/v2/green_lanes/category_assessment_serializer.rb
app/serializers/api/v2/green_lanes/exemption_serializer.rb
spec/presenters/api/v2/green_lanes/category_assessment_presenter_spec.rb
spec/presenters/api/v2/green_lanes/exemption_presenter_spec.rb
spec/serializers/api/v2/green_lanes/category_assessment_serializer_spec.rb
spec/serializers/api/v2/green_lanes/exemption_serializer_spec.rb
spec/services/green_lanes/permutation_calculator_service_spec.rb

GL-465
- We want to expose pseudo exemptions to our api consumers in a manner consistent with other types of exemptions
- Low, currently targets and epic branch

GL-465 Integrate pseudo exemptions

---

app/controllers/api/v2/green_lanes/category_assessments_controller.rb
app/models/green_lanes/category_assessment.rb
app/models/green_lanes/measure.rb
app/presenters/api/v2/green_lanes/category_assessment_presenter.rb
app/presenters/api/v2/green_lanes/goods_nomenclature_presenter.rb
app/serializers/api/v2/green_lanes/category_assessment_serializer.rb
app/services/green_lanes/fetch_goods_nomenclature_service.rb
spec/factories/measure_factory.rb
spec/models/green_lanes/category_assessment_spec.rb
spec/models/green_lanes/measure_spec.rb
spec/serializers/api/v2/green_lanes/category_assessment_serializer_spec.rb
spec/services/green_lanes/permutation_calculator_service_spec.rb

GL-360
- We want to use pseudo measures to apply certain category assessments to certain goods nomenclatures in a manner not represented within the tariff
- Low, changes a private API and only impacts an epic branch for now

GL-360 Integrate pseudo measures

---

db/data_migrations/20240524143604_remove_zimbabwe_exchange_rate_may24.rb

OTT-299
- so no future runs of the exchange rate task monthly includes the ZWL exchange rate

End date ZWL currency may 24

---

app/controllers/api/admin/green_lanes/category_assessments_controller.rb
app/controllers/api/admin/green_lanes/exemptions_controller.rb
app/controllers/api/admin/green_lanes/measures_controller.rb
app/models/green_lanes/category_assessment.rb
app/models/green_lanes/measure.rb
app/serializers/api/admin/green_lanes/category_assessment_serializer.rb
app/serializers/api/admin/green_lanes/goods_nomenclature_serializer.rb
app/serializers/api/admin/green_lanes/measure_serializer.rb
config/routes.rb
spec/factories/green_lanes/category_assessment_factory.rb
spec/models/green_lanes/category_assessment_spec.rb
spec/models/green_lanes/measure_spec.rb
spec/requests/api/admin/green_lanes/category_assessments_controller_spec.rb
spec/requests/api/admin/green_lanes/measurers_controller_spec.rb
spec/serializers/api/admin/green_lanes/category_assessment_serializer_spec.rb
spec/serializers/api/admin/green_lanes/goods_nomenclature_serializer_spec.rb
spec/serializers/api/admin/green_lanes/measure_serializer_spec.rb

[GL-361](https://transformuk.atlassian.net/browse/GL-361)
- User should be able to manage measures in admin UI

GL-361: Add admin API to list out pseudo measures

---

spec/factories/measure_excluded_geographical_area_factory.rb
spec/factories/measure_factory.rb
spec/models/measure_spec.rb

GL-539
- As part of some GL work I disabled the exclusions code and I found these specs still passed anyway
- Fixing the specs first allows me to do some other refactor work whilst having confidence the code will continue to work as intended
- Low, purely test changes

GL-539 Corrected factories and specs for area exclusions

---

app/models/geographical_area.rb
app/models/measure.rb
app/services/cached_commodity_service.rb
app/services/heading_service/serialization/declarable_service.rb
spec/models/geographical_area_spec.rb

GL-539
- The existing implementation does its own queries, preventing eager loading
- This negatively impacts green lanes but its beneficial to add here, I found even without the eager load changes there was still a significant drop in queries with the existing eager loads already in place
- Some, this changes the internal implementation of key functionality

GL-539 Eager load geo area filtering

---

app/models/rules_of_origin/query.rb
app/models/rules_of_origin/scheme_set.rb
app/presenters/api/v2/rules_of_origin/scheme_presenter.rb
db/rules_of_origin/roo_schemes_uk.json
spec/models/rules_of_origin/query_spec.rb
spec/models/rules_of_origin/scheme_set_spec.rb
spec/presenters/api/v2/rules_of_origin/scheme_presenter_spec.rb

https://transformuk.atlassian.net/browse/OTT-264
I have removed
- This is no longer required following UX changes of Origin tab. The link was used at the bottom of the tab replaced by 'Further information on trade with `[_country_]`'
- 
Deployment risks
Requires frontend PR https://github.com/trade-tariff/trade-tariff-frontend/pull/1921

OTT-264 Origin Tab Update UX

---

app/controllers/api/v2/green_lanes/category_assessments_controller.rb
app/models/green_lanes/category_assessment.rb
app/presenters/api/v2/green_lanes/goods_nomenclature_presenter.rb
app/presenters/api/v2/green_lanes/referenced_goods_nomenclature_presenter.rb
spec/factories/measure_factory.rb
spec/presenters/api/v2/green_lanes/goods_nomenclature_presenter_spec.rb
spec/presenters/api/v2/green_lanes/referenced_goods_nomenclature_presenter_spec.rb

GL-402
- Whilst export measures shouldn't be matched unless we have bad data, we can trivially ensure that they are not
- Low, only affects GL APIs

GL-402 Ignore export measures

---

db/migrate/20240610160146_update_quota_definitions_oplog_volume.rb

https://transformuk.atlassian.net/browse/OTT-324
- Taric data contains Quota Definition Volumes of 11 digits where the table only allowed 10 digits
I have run the fix locally and file 2024-05-19_TGB24114.xml will now commit data to the database.  I have checked the values are in the database too.  See below:

OTT-324 DB Migration Quota Definition oplog volume update

---

app/controllers/api/v2/green_lanes/goods_nomenclatures_controller.rb
app/presenters/api/v2/green_lanes/measure_presenter.rb
app/serializers/api/v2/green_lanes/measure_serializer.rb
spec/presenters/api/v2/green_lanes/measure_presenter_spec.rb
spec/serializers/api/v2/green_lanes/measure_serializer_spec.rb

GL-551
- These were missed by mistake
- Low

GL-551 Small tweaks to API

---

app/controllers/api/v2/green_lanes/category_assessments_controller.rb
app/models/green_lanes/category_assessment.rb
app/models/green_lanes/exempting_certificate_override.rb
app/models/green_lanes/exemption.rb
app/models/green_lanes/measure.rb
app/models/green_lanes/theme.rb
db/migrate/20240530121653_add_index_to_category_assessments_updated_at.rb
db/structure.sql
spec/models/green_lanes/category_assessment_spec.rb
spec/models/green_lanes/exempting_certificate_override_spec.rb
spec/requests/api/v2/green_lanes/category_assessments_controller_spec.rb

GL-373
- This endpoint needs to load _a lot_ of data so can be slow to generate, caching avoids reprocessing all that on repeated calls throughout the day
- Some, adds a DB index as well as the caching changes

GL-373 cache Category assessments endpoint

---

lib/tasks/green_lanes.rake

GL-601
- We should favour ModificationRegulations over BaseRegulations
- Low, means we'll be importing slightly different data into production than staging

GL-601 Fix priorisation of regulations for category assessment imports

---

app/controllers/api/v2/green_lanes/category_assessments_controller.rb
app/models/goods_nomenclature.rb
app/models/green_lanes/category_assessment.rb
app/models/green_lanes/measure.rb
spec/models/green_lanes/category_assessment_spec.rb
spec/models/green_lanes/measure_spec.rb

GL-574
- We should ignore measures (and their associated CAs) when the GN they attach to is not valid for the requested date
- Low, only affects GL APIs

GL-574 Handle pseudo measures against expired goods nomenclatures

---

app/presenters/api/v2/green_lanes/category_assessment_presenter.rb
spec/presenters/api/v2/green_lanes/category_assessment_presenter_spec.rb

GL-562
- We were getting duplicate certificates when there was duplicate measure conditions pointing to the same certificate
- Low, small bugfix

GL-562 Uniq certificates to avoid duplicate certs

---

Gemfile.lock
app/services/exchange_rates/update_currency_rates_service.rb
db/data_migrations/20240606125159_add_new_zimbabwe_gold.rb
spec/services/exchange_rates/update_currency_rates_service_spec.rb

OTT-309
- XE are supplying us with the ZIG rate under the ZWL code

Monkey patch for allowing ZWL rate only be saved as ZIG

---

app/controllers/api/admin/green_lanes/category_assessments_controller.rb
app/controllers/api/admin/green_lanes/measures_controller.rb
app/models/green_lanes/exemption.rb
config/routes.rb

[GL-618](https://transformuk.atlassian.net/browse/GL-618)
- Since there are no forign key constrains in gl data, we need to manually validate pseudo mesures against invalid GN

GL-618: Validate green lanes measures against invalid goods nomenclature codes

---

app/controllers/api/admin/green_lanes/category_assessments_controller.rb
app/controllers/api/admin/green_lanes/measures_controller.rb
config/routes.rb
spec/requests/api/admin/green_lanes/category_assessments_controller_spec.rb
spec/requests/api/admin/green_lanes/measurers_controller_spec.rb

[GL-384](https://transformuk.atlassian.net/browse/GL-384)
- Admin user should be able to manage GL measures

GL-384: Add deleting pseudo measures

---

app/presenters/api/v2/green_lanes/category_assessment_presenter.rb
app/services/green_lanes/find_category_assessments_service.rb
app/services/green_lanes/permutation_calculator_service.rb
spec/presenters/api/v2/green_lanes/category_assessment_presenter_spec.rb
spec/services/green_lanes/permutation_calculator_service_spec.rb

[GL-705](https://transformuk.atlassian.net/browse/GL-705)
- We don't need to create separate CA for each additional codes. Instead, we need to group them into a one CA

GL-705: Remove add code from permutation key

---

app/lib/tariff_synchronizer/cds_update_downloader.rb

BAU
- These were caching failures that got fixed and add little value, really, since this is not a slow api

BAU: Stop caching potentially broken list responses

---

terraform/backend_uk.tf
terraform/backend_xi.tf

BAU
- This was required to debug live issues in staging

BAU: Enable ecs exec

---

app/lib/reporting/differences/omitted_duty_measures.rb

BAU
- This is required to make sure we're sending these reports out
- This was broken after an upgrade of the rubocop gem

BAU: Fixes differences report after lint

---

app/serializers/api/v2/green_lanes/category_assessment_serializer.rb
spec/serializers/api/v2/green_lanes/category_assessment_serializer_spec.rb

BAU
- This is needed by the frontend

BAU: Include the category assessment id in the serialized output

---

db/migrate/20240808113431_update_green_lanes_category_assessments_index.rb
db/structure.sql
lib/tasks/green_lanes.rake
spec/models/green_lanes/category_assessment_spec.rb

[GL-921](https://transformuk.atlassian.net/browse/GL-921)
- We need to add two different CA for same measure_type and regulation quotable and non-quotable items. These CAs created for different category but enforced by same measure type and regulation.

GL-921: Change how CAs uniqueness is calculated to factor in theme

---

app/services/green_lanes/find_category_assessments_service.rb
spec/services/green_lanes/find_category_assessments_service_spec.rb

[GL-909](https://transformuk.atlassian.net/browse/GL-909)
- Trade movements related to GL are always from GB to NI regradless of country of origin of the trade comoddity. So the GB related measures are always applicable for GL categorisation.

GL-909: Extend categorisation function to account for GB specific measures

---

app/controllers/api/v2/green_lanes/base_controller.rb

[GL-914](https://transformuk.atlassian.net/browse/GL-914)
- We need to enable clients that send X-Api-Key header in their request by validating against Api key provided to them.  
- Autherisation header validation also still available for backward compatibility.
- This is tempory solution and api-key validation will be handed over to api-gateway in the future

GL-914: Consume secret in controller & auth with secret in controller

---

app/services/green_lanes/fetch_goods_nomenclature_service.rb
spec/services/green_lanes/fetch_goods_nomenclature_service_spec.rb

[GL-935](https://transformuk.atlassian.net/browse/GL-935)
- As current validation block 4 digit declarables but they need to be allowed for categorisation
-
-

GL-935: Extend API to allow categorization of 4 digit commodities that are end leaves

---

config/routes.rb

[GL-935](https://transformuk.atlassian.net/browse/GL-935)
- To remove the restriction in route file that check CC to min 6 digits

GL-935: Extend API to allow categorization of 4 digit commodities that are end leaves-bug fix

---

app/lib/trade_tariff_backend.rb
terraform/README.md
terraform/data.tf
terraform/iam.tf
terraform/locals.tf

[GL-913](https://transformuk.atlassian.net/browse/GL-913)
- We need to enable clients that send X-Api-Key header in their request by validating against Api key provided to them.
- Autherisation header validation also still available for backward compatibility.
- This is tempory solution and api-key validation will be handed over to api-gateway in the future

GL-913: Create secret & inject in the env of the app

---

Gemfile.lock

BAU
Updated Bundler as our version here is over 2.5 years old
- It being this out of date is fairly risky
- There could potentially be an issue where the target wants to stick to the old version but from what I can see everything should update.

BAU: Update Bundler to 2.5.17

---

config/environments/development.rb

BAU
I have stopped the app from logging in duplicate in development which makes it harder to see what's going on.  This just helps keep the noise down.
I am doing this because we don't need everything twice.
None

BAU - Prevent duplicate logging in development

---

Gemfile
Gemfile.lock

BAU: `csv` is being removed from stdlib as of Ruby 3.4.0.  This change removes the deprecation warning.

Remove csv gem deprecation warning

---

Procfile.dev
README.md
bin/dev

BAU: Dev cleanup
I have added `bin/dev` which will use `Procfile.dev` to spin up web + workers as an option.  Currently the README only demonstrates how to start Rails on it's own.

Add bin/dev to allow dev web+workers

---

app/services/green_lanes/fetch_goods_nomenclature_service.rb

- Only four digit item id need to checked for declarable.
- There is a performance impact of checking the declarable flag for all the item ids
-

BAU: Check declarable flag only for four digit item id.

---

db/rules_of_origin/roo_schemes_uk/articles/iceland-norway/wholly-obtained.md

https://transformuk.atlassian.net/browse/OTT-272
- Govspeak and lettered-list class transforms numbers to letters but numbers were being used in point M.
Before (https://www.trade-tariff.service.gov.uk/rules_of_origin/0409000010/IS/wholly_obtained_definition)
After

OTT-272 Iceland RoO Lettering Fix

---

db/rules_of_origin/roo_schemes_uk/articles/canada/neutral-elements.md
db/rules_of_origin/roo_schemes_uk/articles/canada/packaging.md
db/rules_of_origin/roo_schemes_uk/articles/canada/wholly-obtained-vessels.md

https://transformuk.atlassian.net/browse/OTT-273
I have
- The existing text was wrong
- This requires a front end release from this PR:
https://github.com/trade-tariff/trade-tariff-frontend/pull/2054
BEFORE 
Vessels
Neutral Elements and Packaging
AFTER
Vessels
Neutral Elements and Packaging

OTT-273 Fix Canada RoO inconsistencies

---

app/controllers/application_controller.rb
spec/controllers/application_controller_spec.rb

OTT-326
Added a constraint around date params (as_of) that it must be inside 20 years either side of today
Currently it's possible to pass a date from the frontend such as 202400000-01-01, which is a valid date, but one which is very far in the future.  We already have dates to check that the date is valid, but no check to determine if the date is _reasonable_.
Should the date be unreasonable, todays date is used (which is the same behaviour as an invalid date)

OTT-326 error message encountered if user enters trade date of more than 6 digits

---

db/rules_of_origin/roo_schemes_uk/articles/turkey/wholly-obtained.md

https://transformuk.atlassian.net/browse/OTT-274
- The numbering and lettering was incorrect
BEFORE
AFTER

OTT-274 Changed wholly-obtained to use legislative list

---

app/controllers/api/admin/commodities_controller.rb
config/routes.rb
spec/requests/api/admin/commodities_controller_spec.rb

BAU
- This has been replaced by the static site hosted in s3

BAU: Removes redundant reports endpoint

---

config/routes.rb

BAU
The frontend application needs these routes to be available since it
doesn't have access to both a UK and an XI service running locally on
separate configurations.
We had choices:
1. Run a separate XI/UK service locally and plumb together the routes in
the frontend to point at these running on individual ports
2. Just preserve the current setup for XI runs of the backend but mount
the routes that the frontend service depends on in development
3. Just remove the defensive route conditional and let clients decide
I'm opting for 2 since this has significantly less overhead in terms of
local configuration.
- This makes working with the frontend using the xi service locally (e.g. with green lanes) just work

BAU: Handle development uk-only routes better

---

app/lib/reporting.rb
app/lib/reporting/differences.rb
app/lib/reporting/differences/renderers/bad_quota_association.rb
app/lib/reporting/differences/renderers/candidate_supplementary_unit.rb
app/lib/reporting/differences/renderers/endline.rb
app/lib/reporting/differences/renderers/goods_nomenclature.rb
app/lib/reporting/differences/renderers/goods_nomenclature_end_date.rb
app/lib/reporting/differences/renderers/goods_nomenclature_start_date.rb
app/lib/reporting/differences/renderers/hierarchy.rb
app/lib/reporting/differences/renderers/incomplete_measure_condition.rb
app/lib/reporting/differences/renderers/indentation.rb
app/lib/reporting/differences/renderers/me16.rb
app/lib/reporting/differences/renderers/me32.rb
app/lib/reporting/differences/renderers/measure_quota_coverage.rb
app/lib/reporting/differences/renderers/mfn_duplicated.rb
app/lib/reporting/differences/renderers/mfn_missing.rb
app/lib/reporting/differences/renderers/misapplied_action_code.rb
app/lib/reporting/differences/renderers/missing_vat_measure.rb
app/lib/reporting/differences/renderers/omitted_duty_measures.rb
app/lib/reporting/differences/renderers/overview.rb
app/lib/reporting/differences/renderers/quota_missing_origin.rb
app/lib/reporting/differences/renderers/seasonal.rb
app/lib/reporting/differences/renderers/supplementary_unit.rb

OTT-502
This removes the manual counting of items in the Excel spreadsheet, and replaces them with Excel functions meaning that the numbers will always correlate with the contents of each sheet.
Previously it was wrong

OTT-502 Remove item counts and rely on Excel

---

config/sidekiq.yml

BAU
Changed the time the ReportWorker is triggered from 0800 to 1030 UTC.
Whilst the UpdatesSynchronizers run at 0500, they re-try every 20 minutes until the file appear.  This continues until 1000, at which point it give us.
Meanwhile, over in reporting land, the ReportsWorker runs at 0800.
However, from the timestamps of files in S3 it seems that files are not appearing until around 0800 so the ReportsWorker is often missing the most recent files.
This change ensures that the ReportsWorker has either received the new files, or has given up trying.

BAU: Change time ReportWorker runs

---

app/services/measure_service/council_regulation_url_generator.rb
spec/helpers/application_helper_spec.rb
spec/presenters/api/v2/green_lanes/regulation_presenter_spec.rb
spec/presenters/api/v2/measures/measure_legal_act_presenter_spec.rb
spec/services/measure_service/council_regulation_url_generator_spec.rb

https://transformuk.atlassian.net/browse/OTT-307
I have 
- Links using existing methods were not working
More info on generating links here:
https://eur-lex.europa.eu/content/help/data-reuse/linking.html
https://eur-lex.europa.eu/content/help/eurlex-content/celex-number.html

OTT-307 Updated the way Legal Basis Links are generated from BaseRegulation

---

app/controllers/api/admin/green_lanes/category_assessments_controller.rb
spec/requests/api/admin/green_lanes/category_assessments_controller_spec.rb

[GL-1065](https://transformuk.atlassian.net/browse/GL-1065)
- User needs to sort the result table by different attributes

GL-1065: Implement Sorting Functionality on Category Assessments Page

---

app/workers/differences_report_check_worker.rb
spec/workers/differences_report_check_worker_spec.rb

BAU
We check if the differences report has run, but we don't need to do it outside prod as that's giving us false alarms.  This fixes that.

BAU: Don't run differences check outside production

---

app/lib/reporting/differences/loaders/supplementary_unit.rb

HMRC-337
Added a missing key for the supplementary units reports as it was not overridden correctly to include the `uk` and `xi` params

HMRC-337 FIx key for supp units report

---

.circleci/config.yml

BAU: Disable the `smoke-test-staging` test suite
This suite runs on every `deploy-to-staging` aka merge.  However it is clearly adding no value whatsoever as it has been failing on multiple tests at a rate of 65% yet there are no apparent negative side effects.  This suite has also been failing at 100% rate 
Before reinstating the test suite needs review as to:
a) why it's failing
b) if it's even useful given the world has kept spinning even with it failing two times out of three.

BAU: Disable smoke-test-staging

---

app/controllers/api/v2/goods_nomenclatures_controller.rb
config/routes.rb
spec/controllers/api/v2/goods_nomenclatures_controller_spec.rb

[GL-1079](https://transformuk.atlassian.net/browse/GL-1079)
- Front end GL screen need to validate if given GN is a declarable

GL-1079: Validation for only allowing declarable commodities is not working

---

Gemfile
Gemfile.lock
config/initializers/sentry.rb

HMRC-385
It transpires that Sentry can do APM tracing so it's worth trying that first.  This PR enables that.

HMRC-385 Enable tracing in Senty

---

app/lib/trade_tariff_backend.rb
app/workers/populate_changes_table_worker.rb
terraform/README.md
terraform/config_staging.tfvars
terraform/locals.tf
terraform/variables.tf

https://transformuk.atlassian.net/browse/HMRC-434
I have added
- TGP have requested adhoc Change data to be added for 1-1-2022 and 1-1-2024 to staging and want to test it over a period of days.
- When the staging daily DB refresh occurs and when populate changes Cron runs as normal that data would be deleted and we want to retain it for TGP in staging
- Note Terraform files have the env var set to false in all environments other than staging
- This change will be reverted following TGP successful testing

HMRC-434 Changed Changes process for Staging for TGP

---

app/controllers/application_controller.rb

Added regex check for correct date format, returns today if date is completely wrong
https://transformuk.atlassian.net/browse/HMRC-423
- returning a date >20 years in the past caused a bug in the front end making a commodity look active when it isn't
- Dates thousands of years in the future are unacceptable however we don't want the app to error as trade dates can be in the future
- possible UX constraint for front end required to restrict date input

HMRC-423 Fix 20 Year Problem

---

db/rules_of_origin/roo_schemes_uk.json

https://transformuk.atlassian.net/browse/HMRC-351
I have:
- CPTPP FTA needs to be active for all ratified countries bar Australia.

HMRC-351 Adjust CPTPP to exclude Australia

---

db/rules_of_origin/roo_schemes_uk.json
db/rules_of_origin/roo_schemes_uk/articles/cptpp/accessories.md
db/rules_of_origin/roo_schemes_uk/articles/cptpp/cumulation-export.md
db/rules_of_origin/roo_schemes_uk/articles/cptpp/cumulation-import.md
db/rules_of_origin/roo_schemes_uk/articles/cptpp/direct-transport.md
db/rules_of_origin/roo_schemes_uk/articles/cptpp/insufficient-processing.md
db/rules_of_origin/roo_schemes_uk/articles/cptpp/neutral-elements.md
db/rules_of_origin/roo_schemes_uk/articles/cptpp/origin_processes.md
db/rules_of_origin/roo_schemes_uk/articles/cptpp/packaging_retail.md
db/rules_of_origin/roo_schemes_uk/articles/cptpp/sets.md
db/rules_of_origin/roo_schemes_uk/articles/cptpp/tolerances.md
db/rules_of_origin/roo_schemes_uk/articles/cptpp/verification.md
db/rules_of_origin/roo_schemes_uk/articles/cptpp/wholly-obtained.md
db/rules_of_origin/roo_schemes_uk/introductory_notes/cptpp_intro.md
db/rules_of_origin/roo_schemes_uk/proofs/cptpp/origin-declaration.md

https://transformuk.atlassian.net/browse/HMRC-351
I have added asterisks to legislativelists in markdown docs and updated the scheme name in the schemes file
- the formatting was incorrect and the scheme name was wrong
Example:
BEFORE:
AFTER:

HMRC-351 - Updated Articles Legislative Lists with Asterisks

---

app/lib/custom_regex.rb
app/services/search_service/exact_search.rb

BAU
I am doing this because: Parameter is populated with "undiefined" when the param is empty.

Ignore default 'undefined' resource_id in search to used in sql query.

---

app/lib/trade_tariff_backend.rb
app/workers/populate_changes_table_worker.rb
terraform/README.md
terraform/config_staging.tfvars
terraform/locals.tf
terraform/variables.tf

https://transformuk.atlassian.net/browse/HMRC-511
I have reverted commits 
[658f19329f582839c9c6ce241ff06fe3ab0551fc](https://github.com/trade-tariff/trade-tariff-backend/commit/658f19329f582839c9c6ce241ff06fe3ab0551fc) 
And
[65b718728165aa613f405925d55910d31414a470](https://github.com/trade-tariff/trade-tariff-backend/commit/65b718728165aa613f405925d55910d31414a470)
- Jira [HMRC-434](https://transformuk.atlassian.net/browse/HMRC-434) must be completely backed out. 
- These were both merge commits for PRs: 
- https://github.com/trade-tariff/trade-tariff-backend/pull/2030 (Didn't work in staging)
- https://github.com/trade-tariff/trade-tariff-backend/pull/2033 (Did work in staging)
- The reason there were two merges to be backed out is that the code in the first PR …

HMRC-511 - Revert HMRC-434-Toggle-Delete-Changes

---

terraform/admin_uk.tf
terraform/admin_xi.tf

BAU
- This is required to debug a live issue with these services

BAU: Adds ecs exec capability to admin API boxes

---

config/initializers/rack_attack.rb

HMRC-635
This PR adds a rule to Rack::Attack to throttle users to 10k requests every 10 mins on a leaky bucket system.  
There are only a couple of users way above this amount which we are looking to cut.  Whilst this is a limit, it's still way about what should be considered reasonable.
[logs-insights-results.csv](https://github.com/user-attachments/files/18655891/logs-insights-results.csv)

HMRC-635 Add throttle on worst abusers

---

config/initializers/rack_timeout.rb
terraform/locals.tf

HMRC-635
Rack timeout is set way too high to be useful.  This PR sets this to a more realistic level to provide the protection it's intended to

HMRC-635 Fix Rack Timeout timeouts to protect app

---

config/initializers/rack_attack.rb

HMRC-635
Move from 10min bucket to 1min bucket (same limit, just a smaller sample)

HMRC-635 Reduce rack-attack bucket size

---

.circleci/config.yml
app/controllers/api/admin/admin_controller.rb
app/controllers/api/api_controller.rb
app/lib/trade_tariff_backend.rb
terraform/README.md
terraform/config_development.tfvars
terraform/config_production.tfvars
terraform/config_staging.tfvars
terraform/locals.tf
terraform/variables.tf

[HMRC-573](https://transformuk.atlassian.net/browse/HMRC-573)
- This only affects authentication between the admin frontend app and the
backend apis and does not impact the need to authenticate users with
signon currently.
- We're doing this to reflect that development/staging hosted signon applications are currently in a broken state and need fixing separately
- Moved the GDS::SSO configuration because it is specific to admin
- Removed deploy for QA as the team is smaller now and not required

HMRC-573: Adds environment configuration to disable admin api auth

---

app/lib/cds_importer.rb
app/lib/cds_importer/xml_parser.rb
app/lib/taric_importer/xml_parser.rb

HMRC-649
- This should cap the memory overhead of using the SAX parsers
- This actually speeds up file loading for me (1.5 hours down to about 40 minutes for the annual file)

HMRC-649: Stop holding excessive objects in SAX parser stacks

---

db/migrate/20250120112727_update_currency_vef_to_ved.rb
db/migrate/20250207141527_update_currency_vef_end_date.rb

https://transformuk.atlassian.net/browse/HMRC-577
I have:
- The VEF end date must supersede the VED start date in January 2025 for the January 2025 rate for VEF to show
- The previous migration wouldn't run due to duplicate key table constraints

HMRC-577 Update VEF Currency Exchange Rate Code End Date

---

app/elastic_search_indexes/search/goods_nomenclature_index.rb
app/lib/sequel/plugins/elasticsearch.rb
app/models/full_chemical.rb
app/serializers/search/goods_nomenclature_serializer.rb
app/services/elastic_search/elastic_search_service.rb
app/services/elastic_search/query/search_suggestion_query.rb
db/structure.sql
spec/integration/sequel/plugins/elasticsearch_spec.rb
spec/services/elastic_search/elastic_search_service_spec.rb

[HMRC-439](https://transformuk.atlassian.net/browse/HMRC-439)

HMRC-439: Include CAS Codes in the Standard Search Index

---

terraform/README.md
terraform/backend_uk.tf
terraform/backend_xi.tf
terraform/data.tf

HMRC-657
- These need to be deployed behind an ALB target group to route traffic
properly

HMRC-657: Register backend_uk and backend_xi

---

app/models/measure.rb
app/models/measure_type.rb
spec/models/measure_spec.rb

https://transformuk.atlassian.net/browse/HMRC-633
- Client has asked for VAT in XI to be shown in commodity tree

HMRC-633 Add VAT column to /headings and /subheadings pages on XI

---

app/controllers/api/v2/green_lanes/faq_feedback_controller.rb
app/engines/v2_api.rb
app/serializers/api/v2/green_lanes/faq_feedback_serializer.rb
config/routes.rb
spec/requests/api/v2/green_lanes/faq_feedback_controller_spec.rb
spec/serializers/api/v2/green_lanes/faq_feedback_serializer_spec.rb
terraform/backend_uk.tf
terraform/backend_xi.tf
terraform/locals.tf

HMRC-715
- This is so that we can generate feedback in V2

HMRC-715: Migrate feedback to V2 Namespace

---

terraform/admin_uk.tf
terraform/admin_xi.tf

HMRC-683
Scaled down the `backend-admin-*` services to zero as they should no longer be required.  Should we require them we can manually scale up and revert this PR.
Should we prove they are not required after a few days we will decommission the services.

 HMRC-683 Scale down backend-admin-uk & backend-admin-xi

---

app/controllers/api/v2/goods_nomenclatures_controller.rb
app/helpers/application_helper.rb
app/lib/api_constraints.rb
app/views/api/v1/chapters/show.json.rabl
app/views/api/v1/commodities/show.json.rabl
app/views/api/v1/headings/show.json.rabl
app/views/api/v1/sections/show.json.rabl
config/routes.rb
spec/controllers/api/v2/measure_types_controller_spec.rb
spec/requests/api/v2/exchange_rates/period_lists_controller_spec.rb
spec/requests/api/v2/exchange_rates_controller_spec.rb
spec/serializers/api/v2/csv/goods_nomenclature_serializer_spec.rb
spec/serializers/api/v2/goods_nomenclatures/goods_nomenclature_extended_serializer_spec.rb
spec/serializers/api/v2/goods_nomenclatures/goods_nomenclature_list_serializer_spec.rb

BAU
Occasionally but not consistently the legacy routes are being hit and failing because the Accept header isn't being set. We only saw this in [production](https://engine-le.sentry.io/issues/6294252303/events/?end=2025-02-17T23%3A59%3A59&environment=production&project=5557005&referrer=issue-stream&start=2025-02-17T00%3A00%3A00&stream_index=0&utc=true)
This change moves us to match the more specific routes first (e.g. /api/v1 /api/v2) to avoid this problem. It also fixes the missing Accept header error by calling to_s on the result of fetching the header before we call `include?` against nil.
When you put the most specific mounts first there's an unwanted side effect of clobbering the previously defined helpers. This mostly affected the tests (controller specs use helpers implicitly and …

BAU: Put more specific routes first

---

app/models/appendix_5a.rb
app/services/appendix_5a_populator_service.rb
spec/factories/appendix_5a_factory.rb
spec/services/appendix5a_populator_service_spec.rb
spec/support/shared_contexts/with_a_stubbed_appendix_5a_guidance_s3_bucket.rb

https://transformuk.atlassian.net/browse/HMRC-670
I have removed CHIEF Guidance from Appendix5a Populator Service
- HMRC do not need CHIEF Guidance anymore and has been deprecated from the front end and in this [PR](https://github.com/trade-tariff/process-appendix-5a/pull/79) for the process-appendix-5a python script
- NOTE following successfuly merge to main, AWS `ci-appendix5a-persistence-readwrite-policy`  must be updated to allow `appendix-5a` user to `PUT` into S3 `config/cds_guidance.json` in Staging and Prod.

HMRC-670 Remove 'appendix 5a' jobs and infrastructure for CHIEF guidance

---

terraform/README.md
terraform/backend_uk.tf
terraform/backend_xi.tf
terraform/data.tf
terraform/iam.tf
terraform/locals.tf
terraform/versions.tf
terraform/worker_uk.tf
terraform/worker_xi.tf

- Switched over to RDS Aurora cluster in production.
- We have proven this in staging, and now it's time to move this to production.
- Changes database to new RDS Aurora cluster. This will impact performance initially as the database reacts to usage.

BAU: Switch to Aurora cluster

---

db/data_migrations/20230522102427_kill_broken_balance_events.rb

HMRC-668
- Data migrations should run cleanly

HMRC-668: Fixes broken data migration

---

config/environments/development.rb

BAU
Noticed that the default mailer options were hardcoded to `host.docker.internal`.  This allows you to override that in .env

Allow override of default mailer url in dev

---

.devcontainer/Dockerfile
Gemfile.lock

https://transformuk.atlassian.net/browse/HMRC-854
I have added yaml-dev to dockerfile so psych would bundle and updated bundler
- App wasn't bundling in DevContainer due to psych missing yaml gem in container environment

HMRC-854 Fix Psych Gem in Backend DevContainer

---

.circleci/config.yml

[HMRC-725](https://transformuk.atlassian.net/browse/HMRC-725)
I have updated the circleCI config to use Postgres 16 for testing

HMRC-725 Update CircleCI config for Postgres version

---

db/rules_of_origin/roo_schemes_uk/articles/dcts-general-enhanced/origin_processes.md

[HMRC-662](https://transformuk.atlassian.net/browse/HMRC-662)
I have removed triple hash titles from markdown and replaced with double hash titles to work with front end parser in rules_of_origin/article.rb
proof requirements weren't rendering due to the formatting in the .md document
BEFORE
AFTER

HMRC-662 Missing data on Origin tool for Algeria

---

lib/tasks/green_lanes.rake

[HMRC-840](https://transformuk.atlassian.net/browse/HMRC-840)
- We should not control for the ‘regulation role’ at all, and any Measure of these given Measure Types should be a CA no matter what the ‘regulation role’ is
- Need to run this task in all the environemtns manually

HMRC-840: Add new Trade Defence CAs 'regulation role' types and Measure Types

---

db/migrate/20250324091812_alter_column_nullable_path_in_goods_nomenclatures_oplog.rb
db/structure.sql

[HMRC-869](https://transformuk.atlassian.net/browse/HMRC-869)
- Fixes updates to goods nomenclatures oplog in the xi service
- This path got removed from updates in the code in a proxy object since its not used. It was missed that this path value was not nullable at the database level so updates to these rows was broken in a daily file (see https://github.com/trade-tariff/trade-tariff-backend/pull/2144)

HMRC-869: Sets the path to nullable on goods_nomenclatures_oplog

---

Gemfile
Gemfile.lock
app/workers/cds_updates_synchronizer_worker.rb
app/workers/invalidate_cache_worker.rb
app/workers/taric_updates_synchronizer_worker.rb
spec/workers/invalidate_cache_worker_spec.rb
terraform/.terraform.lock.hcl
terraform/README.md
terraform/backend_uk.tf
terraform/backend_xi.tf
terraform/iam.tf
terraform/worker_uk.tf
terraform/worker_xi.tf

HMRC-693
I have added a job that will invalidate the entire CloudFront cache each time we do a file import.  We can probably refine this further.  
Before this can ship though we need some extra configuration setup for AWS Authentication:
```
ENV['AWS_REGION']
ENV['AWS_ACCESS_KEY_ID']
ENV['AWS_SECRET_ACCESS_KEY']
ENV['AWS_SESSION_TOKEN']
```

HMRC-693 Invalidate CF cache on import

---

db/migrate/20250331102817_update_view_indexes.rb
db/structure.sql

[HMRC-811](https://transformuk.atlassian.net/browse/HMRC-811)
I have updated:
- Index on quota_definitions_oplog
- Index on quota_balance_events_oplog
In both cases an oid in descending order has been to an existing index which is mainly used to create the related view.
Speeds up queries on 3 views (old and new time to count all rows):
- quota_definitions (9 seconds -> 0.35 seconds)
- bad_quota_associations (10 seconds -> 1.5 seconds)
- quota_balance_events (300 seconds -> 12 seconds)
In particular this should help to speed up quota search

Add indexes to speed up views

---

.circleci/config.yml

[HMRC-945](https://transformuk.atlassian.net/browse/HMRC-945)
- I'm about to migrate the backend to Github Actions and rather than fix this its simpler to just remove it

HMRC-945: Removes broken e2e tests for now

---

spec/lib/reporting/basic_spec.rb

BAU
- This is blocking builds with false negatives

BAU: Mark tests as flaky for now

---

.github/workflows/deploy-to-production.yml

[HMRC-968](https://transformuk.atlassian.net/browse/HMRC-968)
I have added a post production deployment step to send the commit ID to New Relic
So New Relic can track deployments

HMRC-968 Mark deployments in New Relic 

---

.rspec
spec/lib/reporting/basic_spec.rb
spec/support/shared_contexts/with_a_stubbed_reporting_s3_bucket.rb

[HMRC-972](https://transformuk.atlassian.net/browse/HMRC-972)
I have:
- Re-enabled tests
- Removed RSpec documentation formatting
- Clears api requests between tests
Fixes tests and makes output less verbose

HMRC-972 Fix flaky S3 tests

---

app/middleware/clear_cache_control.rb
config/application.rb
spec/requests/api/api_controller_spec.rb

[HMRC-971](https://transformuk.atlassian.net/browse/HMRC-971)
- This is required to prevent instructions to cache responses in the CDN for a very short lifetime.
- Without this the API requests have the same duration as the etagged requests from the frontend which are purposely short lived because verifying etags is a lightweight request
[cache-control]: https://datatracker.ietf.org/doc/html/rfc5861#:~:text=RFC%205861%20%2D%20HTTP%20Cache%2DControl%20Extensions%20for%20Stale%20Content

HMRC-971: Clear Cache-Control header on non-frontend requests

---

app/services/search_instrumentation_service.rb
spec/services/search_instrumentation_service_spec.rb

[HMRC-998](https://transformuk.atlassian.net/browse/HMRC-998)
When total results were being counted for logging purposes, some potential results were not being assigned and not being added to the total.
The code has been refactored to loop through all possible combinations.
it fixes a bug

HMRC-998 Refactor and fix bug where not all results are counted

---

app/controllers/api/v2/search_controller.rb
app/services/search_instrumentation_service.rb
spec/services/search_instrumentation_service_spec.rb

[HMRC-997](https://transformuk.atlassian.net/browse/HMRC-997)
- Refactored the service
- When logging details of an exact search, an override has been added to set the result count to be 1
- Exact search results currently log as having no results

HMRC-997 Set result count for exact searches and refactor SearchInstrumentationService

---

app/controllers/api/admin/news/items_controller.rb
app/models/news/item.rb
app/serializers/api/admin/news/item_serializer.rb
app/serializers/api/v2/news/item_serializer.rb
db/migrate/20250425145123_add_chapters_to_news_item.rb
db/structure.sql
spec/models/news/item_spec.rb
spec/serializers/api/admin/news/item_serializer_spec.rb
spec/serializers/api/v2/news/item_serializer_spec.rb

[HMRC-1023](https://transformuk.atlassian.net/browse/HMRC-1023)
Adds chapters attribute for news items
- This is required for stop press subscription feature

HMRC-1023 Add chapters to news items

---

.github/workflows/ci.yml
.github/workflows/deploy-to-development.yml
app/models/public_users/user.rb
db/data_migrations/20250429110718_set_news_item_1_show_on_home_page_false.rb
spec/factories/public_users/subscription.rb
spec/factories/public_users/user.rb
spec/factories/subscriptions/type.rb
spec/models/measure_spec.rb

[HMRC-986](https://transformuk.atlassian.net/browse/HMRC-986)
I have added migration script to hide GL news item from home page for UK 
- A specifc banner with a CTA (call to action) button replaces it see front end PR https://github.com/trade-tariff/trade-tariff-frontend/pull/2276
- 

HMRC-986 Add CTA Link for SPIMM from OTT Homepage

---

.github/workflows/deploy-to-production.yml
.github/workflows/replicate-db-development.yml
.github/workflows/replicate-db-staging.yml

[HOTT-962](https://transformuk.atlassian.net/browse/HMRC-962)
- When deploying to production, we’re notifying in production alerts

HMRC-962: Notify in production-alerts

---

.github/workflows/deploy-to-development.yml
app/models/search_suggestion.rb
app/services/search_suggestion_populator_service.rb
spec/models/measure_spec.rb
spec/services/search_suggestion_populator_service_spec.rb

[HMRC-1115](https://transformuk.atlassian.net/browse/HMRC-1115)
- This adds handling for search references that were deleted from the search references table and were causing issues recently

HMRC-1115: Adds handling for expired search reference search suggestions

---

db/migrate/20250516154516_add_notify_subscribers_to_news_item.rb
db/structure.sql

[HMRC-1067](https://transformuk.atlassian.net/browse/HMRC-1067)
I have Added migration to add email subscribers column to news item
- Admin users can decide whether subscribers should be emailed with new/updated news items.

HMRC-1067 Add Notify Subscribers Migration

---

terraform/config_development.tfvars

BAU: Dev is running 5x instances for backend, so 10x total across uk/xi. 
We don't need this.

Reduce dev service scale

---

app/controllers/api/admin/news/collections_controller.rb
app/serializers/api/admin/news/collection_serializer.rb
db/migrate/20250522141643_add_subscribable_to_news_collection.rb
db/structure.sql
spec/factories/news_factory.rb
spec/serializers/api/admin/news/collection_serializer_spec.rb

[HMRC-1074](https://transformuk.atlassian.net/browse/HMRC-1074)
- Added a new field to news collections called `subscribable`
- Added to the serializer and made updateable
- Only subscribable news items should be sent to subscribers

HMRC-1074 Add subscribable attribute to News Collections

---

.github/workflows/ci.yml

Turn of slack notifications after CI tests/linting are run on a PR
Notifications are meant for deploys

Don't notify about tests

---

.rubocop.yml
app/models/news/item.rb
app/models/public_users/user.rb
app/workers/stop_press_subscription_worker.rb
spec/factories/public_users/user.rb
spec/models/news/item_spec.rb
spec/models/public_users/user_spec.rb
spec/rails_helper.rb
spec/workers/stop_press_subscription_worker_spec.rb

[HMRC-1074](https://transformuk.atlassian.net/browse/HMRC-1074)
Triggers worker after news item is saved that identifies users whose subscription matches the news item.
Matching is based on:
- The user having an active subscription
- The news item being emailable
- The news item relating to chapters that the user set a preference for
- Part of MyOTT subscriptions.

HMRC-1074 Subscription matcher worker

---

app/controllers/api/admin/green_lanes/measure_type_mappings_controller.rb
app/lib/green_lanes_updates_publisher/green_lanes_update.rb
app/serializers/api/admin/green_lanes/measure_type_mapping_serializer.rb
app/serializers/api/admin/green_lanes/update_notification_serializer.rb
app/workers/green_lanes_updates_worker.rb
config/routes/admin.rb
spec/models/green_lanes/update_notification_spec.rb
spec/requests/api/admin/green_lanes/measure_type_mappings_controller_spec.rb
spec/serializers/api/admin/green_lanes/measure_type_mapping_serializer_spec.rb
spec/workers/green_lanes_updates_worker_spec.rb

[HMRC-1141](https://transformuk.atlassian.net/browse/HMRC-1141)
- Admin Ui should facilitate to manage measure type mapping

HMRC-1141: Create Admin UI element to allow MTypes to be added for automation

---

app/workers/stop_press_email_worker.rb
spec/workers/stop_press_email_worker_spec.rb

Verifies the user is still active before sending a subscriber email
Handles edge case where sending email was delayed and in the meantime the user has unsubscribed.

Check user is active before emailing

---

app/controllers/api/user/public_users_controller.rb
spec/controllers/api/user/public_users_controller_spec.rb

When the myott user is loaded, first filter out deleted users. 
If there are no matches then create a new user
- Deleted users can not be loaded

Only match active users

---

app/controllers/api/user/public_users_controller.rb
app/controllers/api/user/subscriptions_controller.rb

- API has per user authentication so can't be cached

Disable caching on user API

---

app/lib/identity_api_client.rb
app/models/public_users/user.rb
app/workers/external_user_deletion_worker.rb
db/migrate/20250612150328_allow_null_external_id_on_users.rb
db/structure.sql
spec/lib/identity_api_client_spec.rb
spec/models/public_users/user_spec.rb
spec/workers/external_user_deletion_worker_spec.rb

[HMRC-1224](https://transformuk.atlassian.net/browse/HMRC-1224)
- Added worker to request users are deleted from Identity service
- To remove users personal details when they are no longer required

Delete external user worker

---

app/workers/stop_press_subscription_worker.rb
spec/models/public_users/user_spec.rb
spec/workers/stop_press_subscription_worker_spec.rb

`matching_chapters` method expects chapters to be an array or single string value

Fix: convert chapters to array

---

app/services/govuk_notifier.rb
app/workers/stop_press_email_worker.rb
spec/services/govuk_notifier_spec.rb
spec/workers/stop_press_email_worker_spec.rb

[HMRC-1192](https://transformuk.atlassian.net/browse/HMRC-1192)
- Updated Notify template ID to use live account
- Added email reply ID
- Getting ready for production

HMRC-1192 Add reply email ID and change template ID

---

app/models/news/item.rb
app/workers/stop_press_subscription_worker.rb
spec/models/news/item_spec.rb
spec/workers/stop_press_subscription_worker_spec.rb

[HMRC-1285](https://transformuk.atlassian.net/browse/HMRC-1285)
- Moved check for whether a stop press object is emailable to the after_save
- Ensure that we don't trigger the worker incorrectly

HMRC-1285 Move emailable check

---

app/lib/trade_tariff_backend.rb
app/mailers/action_log_mailer.rb
app/views/action_log_mailer/daily_report.text.erb
app/workers/action_log_report_worker.rb
config/sidekiq.yml
spec/factories/public_users/action_logs.rb
spec/mailers/action_log_mailer_spec.rb
spec/workers/action_log_report_worker_spec.rb

[HMRC-1290](https://transformuk.atlassian.net/browse/HMRC-1290)
- Added a task that emails CSV of myott action logs records for the previous day
- So we can keep track of actions during private beta

HMRC-1290 Schedule email of myott action log report

---

.github/workflows/deploy-to-development.yml

[HMRC-1306](https://transformuk.atlassian.net/browse/HMRC-1306)
- This is needed as a simpler solution than making sure the backend and admin appsare also deployed via workflow calls (something to solve later)

HMRC-1306: Disable tests in development deployment

---

app/lib/sequel/plugins/oplog.rb
db/migrate/20250613170053_add_geographical_area_materialized_views.rb
db/migrate/20250619131935_add_base_geographical_area_materialized_views.rb
db/migrate/20250620150030_add_geographical_area_materialized_views_fix.rb

HMRC-1360
- Enables dynamically rolling forward and backwards after creating duplicate indexes
- The duplicate indexes were misapplied in some production environments but worked in others and rather than manually rolling back and forward to fix these we created additional migrations.
- This gets us into a steady state

HMRC-1360: More rollback fixes

---

.github/workflows/deploy-to-development.yml
app/lib/sequel/plugins/oplog.rb

[HMRC-1317](https://transformuk.atlassian.net/browse/HMRC-1317)
- Refreshing during materialized oplog inserts is insanely wasteful and we actually just do these at the end of an apply anyway for all of the update files

HMRC-1317: Do a materialized refresh only during testing

---

app/workers/cds_updates_synchronizer_worker.rb
app/workers/clear_cache_worker.rb
app/workers/taric_updates_synchronizer_worker.rb
spec/workers/clear_cache_worker_spec.rb

[HMRC-1402](https://transformuk.atlassian.net/browse/HMRC-1402)
- This makes sure we're doing this everywhere where cache invalidation makes sense

HMRC-1402: Make sure we're invalidating CDN caches where relevant

---

app/helpers/materialize_view_helper.rb
app/workers/apply_worker.rb
app/workers/clear_cache_worker.rb
app/workers/clear_invalid_search_references.rb
app/workers/download_worker.rb
app/workers/healthcheck_worker.rb
app/workers/precache_headings_worker.rb
app/workers/prewarm_quota_order_numbers_worker.rb
app/workers/reindex_models_worker.rb
app/workers/rollback_worker.rb
app/workers/tree_integrity_check_worker.rb
config/sidekiq.yml
lib/tasks/tariff.rake
spec/workers/clear_cache_worker_spec.rb

[HMRC-1317](https://transformuk.atlassian.net/browse/HMRC-1317)
- There is a performace drawback in running all those job asynchronously

HMRC-1317: Move views to materialized views - refresh task

---

app/engines/user_api.rb
config/routes.rb

[MYOTT-45](https://transformuk.atlassian.net/browse/MYOTT-45)
Recent changes to the api paths in backend and frontend meant that the route being used for the user api from the frontend was no longer valid.
This updates the route so the frontend will work again for the myott subscriptions.

Update to work with frontend

---

config/routes.rb

BAU
```
I, [2025-07-24T10:31:01.910358 #1232636]  INFO -- : Started GET "/api/v2/commodities/0101210000?filter[geographical_area_id]=KP" for ::1 at 2025-07-24 10:31:01 +0100
I, [2025-07-24T10:31:01.960376 #1232636]  INFO -- : Redirected to http://localhost:3000/uk/api/v2/commodities/0101210000?filter[geographical_area_id]=KP
I, [2025-07-24T10:31:01.960722 #1232636]  INFO -- : Completed 301 Moved Permanently in 2ms
I, [2025-07-24T10:31:01.966138 #1232636]  INFO -- : Started GET "/uk/api/v2/commodities/0101210000?filter[geographical_area_id]=KP" for ::1 at 2025-07-24 10:31:01 +0100
I, [2025-07-24T10:31:01.995094 #1232636]  INFO -- : Started GET "/uk/api/commodities/0101210000?filter[geographical_area_id]=KP" for ::1 at 2025-07-24 10:31:01 +0100
I, [2025-07-24T10:31:02.047649 #1232636]  INFO …
```

BAU: Fixes redirects with a query

---

.github/workflows/ci.yml
.tool-versions
terraform/.terraform.lock.hcl
terraform/README.md
terraform/backends/production.tfbackend
terraform/backends/staging.tfbackend
terraform/versions.tf

[HMRC-1446](https://transformuk.atlassian.net/browse/HMRC-1446)
- Terraform has deprecated dynamodb_table in favour of use_lockfile
[Terraform S3 backend documentation](https://developer.hashicorp.com/terraform/language/settings/backends/s3)

HMRC-1446: Migrate terraform backend to use_lockfile and update terraform version

---

app/lib/versioned_forwarder.rb
config/routes.rb
spec/lib/versioned_forwarder_spec.rb

BAU
- This is just to be ready depending on a decision from HMRC/OTT team

BAU: Move to transparent redirects

---

.github/workflows/deploy-to-development-full.yml

[HMRC-1362](https://transformuk.atlassian.net/browse/HMRC-1362)
I have a...
- Enabled identity service when running the e2e tests
I am doing this because...
- This is required to make sure the e2e tests pass

HMRC-1362: Start identity service when running e2e tests

---

.pre-commit-config.yaml
app/lib/green_lanes_updates_publisher/data_updates_finder.rb
app/workers/cds_updates_synchronizer_worker.rb
app/workers/green_lanes_updates_worker.rb
app/workers/taric_updates_synchronizer_worker.rb
config/sidekiq.yml
spec/workers/green_lanes_updates_worker_spec.rb

[HMRC-1477](https://transformuk.atlassian.net/browse/HMRC-1477)
When a new measure, regulation and measure type permutation comes in via
a daily file we update the category assessments that are interesting to
users of the Green Lanes SPIMM APIs.
If the daily file happens late then this process will miss these updates
and therefore the permutations for these new categories won't show up in
the API.

HMRC-1477: Refactor and fix automatic category assessments

---

app/lib/changes_table_populator/descendant_populator.rb

[HMRC-1472](https://transformuk.atlassian.net/browse/HMRC-1472)
- Measures with goods_nomenclature_sid causing error in generating change report

HMRC-1472: Generate Changes API response for 1/1/2022 (XI and UK)

---

app/controllers/api/admin/admin_controller.rb
app/lib/trade_tariff_backend.rb

[HMRC-1404](https://transformuk.atlassian.net/browse/HMRC-1404)
- Admin use long living auth token for request auth in backend, it is not related to the logged in user in admin api. So the token can be used regardless of GDS SSO or Basic user auth use in prod and lower env. Token is set up in admin secrets of BEARER_TOKEN

HMRC-1404: Basic auth to admin backends when auth disabled

---

.env.development
.env.test
.rubocop.yml
Gemfile
app/controllers/api/v2/enquiry_form/submissions_controller.rb
app/engines/v2_api.rb
app/helpers/enquiry_form/submission_helper.rb
app/serializers/api/v2/enquiry_form/submission_serializer.rb
app/services/enquiry_form/csv_generator_service.rb
app/services/govuk_notifier.rb
app/workers/enquiry_form/send_submission_email_worker.rb
app/workers/stop_press_email_worker.rb
spec/helpers/enquiry_form/submission_helper_spec.rb
spec/requests/api/v2/enquiry_form/submissions_controller_spec.rb
spec/services/enquiry_form/csv_generator_service_spec.rb
spec/services/govuk_notifier_spec.rb
spec/workers/enquiry_form/send_submission_email_worker_spec.rb
spec/workers/stop_press_email_worker_spec.rb

[PEX-18](https://transformuk.atlassian.net/browse/HMRC-18)
[PEX-130](https://transformuk.atlassian.net/browse/HMRC-130)
- It's a requirement for the product experience workflow
Front End [PR](https://github.com/trade-tariff/trade-tariff-frontend/pull/2491) for this requirement

PEX-18 & PEX-130 Enquiry From API

---

app/services/quota_search_service.rb

[HMRC-1442](https://transformuk.atlassian.net/browse/HMRC-1442)
- Currently quota search count takes lots of time as measure table merge join with quota deffinition. As we have much small quota_order table compared to measures, we can use exist instead of join. So I changed the count query accordingly.

HMRC-1442: Improve quota search - merge count query

---

app/services/delta_report_service.rb
app/services/delta_report_service/footnote_changes.rb
spec/services/delta_report_service/footnote_changes_spec.rb
spec/services/delta_report_service_spec.rb

Added Footnote oplog changes to the delta report.
Footnote changes are linked directly to Goods Nomenclatures or via Measures.

Add footnote changes to delta report

---

app/services/delta_report_service.rb
app/services/delta_report_service/base_changes.rb
app/services/delta_report_service/measure_condition_changes.rb
spec/services/delta_report_service/base_changes_spec.rb
spec/services/delta_report_service/certificate_changes_spec.rb
spec/services/delta_report_service/measure_condition_changes_spec.rb
spec/services/delta_report_service_spec.rb

Effect date is now based on the validity start date + 1 day, the validity end date, or the change date + 1 day.
This better reflects when the listed change actually comes into effect.
More details have been added for changes to Certificates and MeasureConditions to give more context to users.
Changes to certificates that happen on the same day as a related MeasureCondition change are now ignored to prevent duplication.

Fix effect date in delta report

---

spec/controllers/api/user/public_users_controller_spec.rb

[MyOTT-117](https://transformuk.atlassian.net/browse/MyOTT-117)
I have :
- There is currently no requirement for CC validation

MyOTT-117 Replace irrelevant spec

---

app/services/delta_report_service.rb
app/services/delta_report_service/additional_code_changes.rb
app/services/delta_report_service/base_changes.rb
app/services/delta_report_service/certificate_changes.rb
app/services/delta_report_service/commodity_changes.rb
app/services/delta_report_service/excel_generator.rb
app/services/delta_report_service/excluded_geographical_area_changes.rb
app/services/delta_report_service/footnote_association_goods_nomenclature_changes.rb
app/services/delta_report_service/footnote_association_measure_changes.rb
app/services/delta_report_service/footnote_changes.rb
app/services/delta_report_service/geographical_area_changes.rb
app/services/delta_report_service/measure_changes.rb
app/services/delta_report_service/measure_component_changes.rb
app/services/delta_report_service/measure_condition_changes.rb
app/services/delta_report_service/measure_presenter.rb
spec/services/delta_report_service/excel_generator_spec.rb
spec/services/delta_report_service/excluded_geographical_area_changes_spec.rb
spec/services/delta_report_service/footnote_association_goods_nomenclature_changes_spec.rb
spec/services/delta_report_service/footnote_association_measure_changes_spec.rb
spec/services/delta_report_service/footnote_changes_spec.rb
spec/services/delta_report_service/measure_changes_spec.rb
spec/services/delta_report_service/measure_component_changes_spec.rb
spec/services/delta_report_service/measure_condition_changes_spec.rb
spec/services/delta_report_service/measure_presenter_spec.rb
spec/services/delta_report_service_spec.rb

- Added error logging
- Formatted start and end dates with just the date
- If a end date is being removed, show as "Removed"
- Use TimeMachine to get details about Certificates and Footnotes at the time of the change
- Remove duty expression from the report
- On some records we make checks for changes to related models on the same day so we don't duplicate the changes in the report. This now uses the raw oplogs as this avoids an issue looking at old dates where subsequent changes mean the views have filtered out the original change so there was no match.
- Use better descriptions for MeasureComponent changes that will be recognisable to users ("Tariff Duty" or "Supplementary Unit")

Various delta report changes

---

app/services/delta_report_service/base_changes.rb
app/services/delta_report_service/certificate_changes.rb
spec/services/delta_report_service/base_changes_spec.rb
spec/services/delta_report_service/certificate_changes_spec.rb

New certificates are linked to a commodity by Measure Condition. The change to a Measure Condition will be shown on the delta report.
Also fixes the use of the validity start date to be the actual date.

Ignore new certificates for delta report

---

terraform/README.md
terraform/backend_job.tf
terraform/backend_uk.tf
terraform/backend_xi.tf
terraform/worker_uk.tf
terraform/worker_xi.tf

[HMRC-1581](https://transformuk.atlassian.net/browse/HMRC-1581)
- A new release of the trade-tariff-platform-terraform-modules (v1.18.0) was created following changes made to the main branch.

HMRC-1581: Update ecs module source reference

---

terraform/README.md
terraform/backend_job.tf
terraform/backend_uk.tf
terraform/backend_xi.tf
terraform/worker_uk.tf
terraform/worker_xi.tf

[HMRC-1581](https://transformuk.atlassian.net/browse/HMRC-1581)
- A new release of the trade-tariff-platform-terraform-modules (v1.18.1) was created following changes made to the main branch.

HMRC-1581: Bump terraform modules to the latest version

---

app/workers/cds_updates_synchronizer_worker.rb
app/workers/taric_updates_synchronizer_worker.rb
config/sidekiq.yml
spec/workers/cds_updates_synchronizer_worker_spec.rb
spec/workers/taric_updates_synchronizer_worker_spec.rb

BAU
- Using a schedule was brittle when we control the event that would drive the changes

BAU: Move to populating changes after changes are available

---

app/models/quota_event.rb
spec/models/quota_event_spec.rb

- Refactored `for_quota_definition`
- Added `event_class_for` method
- Added some tests
Existing `for_quota_definition` method was a bit confusing with its use of inject with `EVENTS.from(1)`

Refactor QuotaEvent

---

app/services/delta_report_service.rb
app/services/delta_report_service/quota_event_changes.rb
spec/services/delta_report_service/quota_event_changes_spec.rb
spec/services/delta_report_service_spec.rb

Finds all `QuotaExhaustionEvent` and `QuotaExhaustionEvent` updates and then checks the status for related `QuotaDefinition` from the previous day. If the status has not changed then they are discarded.
Uses formatting to display quota balance to match frontend.

Ensure quota events cause a change in status in the delta report

---

app/lib/cds_importer.rb
app/lib/cds_importer/entity_mapper.rb
app/lib/cds_importer/excel_writer.rb
app/lib/cds_importer/excel_writer/base_mapper.rb
app/lib/cds_importer/excel_writer/quota_definition.rb
app/lib/cds_importer/record_inserter.rb
app/lib/trade_tariff_backend.rb
spec/factories/measure_factory.rb
spec/integration/cds_importer/cds_importer_spec.rb
spec/integration/cds_importer/record_inserter_spec.rb
spec/lib/cds_importer/excel_writer/quota_definition_spec.rb
spec/lib/cds_importer/excel_writer_spec.rb

[HMRC-987](https://transformuk.atlassian.net/browse/HMRC-987)
- We need to migrate CDS Updates report from python app to ruby
-
-
- We don't need to switch on this in any env until finalise the whole feature

HMRC-987: Migrate Download-CDS-Files to Ruby - Quota Definitions Sheet

---

app/services/search_service.rb
app/services/search_service/base_search.rb
app/services/search_service/null_search.rb
spec/services/search_service_spec.rb

BAU
- Previously we were using a custom implementation of the as_of handling that duplicates the existing implementation in the application controller
- This change also fixes a bug where the date is nil if the as_of isn't supplied as a query param since we were relying on the query parameter to be present in order to set even a default date.

BAU: Consolidate TimeMachine in search service

---

app/workers/cds_updates_synchronizer_worker.rb
app/workers/taric_updates_synchronizer_worker.rb
spec/workers/cds_updates_synchronizer_worker_spec.rb
spec/workers/taric_updates_synchronizer_worker_spec.rb

[HMRC-1651](https://transformuk.atlassian.net/browse/HMRC-1651)
I have added a bit of delay to various sync follow on jobs.  This is intended to alleviate some of the alerting we get overnight.  There's no guarantees this will work so can be reverted if no improvement is made.

HMRC-1651 Delay follow-up jobs on data syncs
