trade-tariff/trade-tariff-backend

- lib/tasks/tariff.rake
HOTT-<TODO>
- This is needed to make sure the rollback functionality works for CDS
> Fix broken rake task for rollback

- app/models/concerns/declarable.rb
- app/models/measure_type.rb
- spec/models/commodity_spec.rb
- spec/models/heading_spec.rb
- spec/models/measure_type_spec.rb
HOTT-<TODO>
-  to avoid noisy output in tests
> Removes constant reload in tests

- app/models/quota_order_number.rb
- spec/models/quota_order_number_spec.rb
HOTT-368
Extend the list of licensed quotas
Since HMRC wants to start sending 07* in as prefixes
for licensed quotas, we better add all possible
cases.
> Extend the list of licensed quotas

- .github/workflows/ci.yml
HOTT-<TODO>
- Shave some minutes off of the build
> Optimise gem cache

- spec/integration/cds_importer/entity_mapper_spec.rb
HOTT-<TODO>
Add back removed unit tests for EntityMapper
Due to a bad rebase some of the unit tests for the entity mapper
were removed.
> Add back removed unit tests for EntityMapper

- app/controllers/application_controller.rb
> Require clearable to make sure the module behaviour is loaded on the

- Gemfile
- Gemfile.lock
> Bumps uktt

- db/measurement_units.json
HOTT-<TODO>
- This is the correct unit
> Fixes annotations

- .circleci/config.yml
HOTT-<TODO>
- This is simpler and avoids duplication
> Use orb command to run tests

- README.md
> Update Read.me indentation

- Gemfile
- Gemfile.lock
- app/models/additional_code.rb
- app/models/additional_code_type.rb
- app/presenters/api/v2/commodities/commodity_presenter.rb
- app/presenters/measure_presenter.rb
- app/serializers/api/v2/commodities/commodity_serializer.rb
- app/services/applicable_additional_code_service.rb
- db/additional_codes.json
- spec/controllers/api/v2/commodities_controller_spec.rb
- spec/factories/additional_code_factory.rb
- spec/factories/measure_factory.rb
- spec/models/additional_code_spec.rb
- spec/services/applicable_additional_code_service_spec.rb
https://transformuk.atlassian.net/browse/HOTT-581
https://transformuk.atlassian.net/browse/HOTT-658
The structure of the surfaced codes is:
```json
{
"meta": {
"applicable_additional_codes": {
"552": {
"heading": {
"overlay": "Describe your goods in more detail",
"hint": "To trade this commodity, you need to specify an additional 4 digits, known as an additional code"
},
"additional_codes": [
{
"code": "B999",
"overlay": "Other",
"hint": ""
},
{
"code": "B349",
"overlay": "Hunan Hualian China Industry Co., Ltd; Hunan Hualian Ebillion China Industry Co., Ltd; Hunan Liling Hongguanyao China Industry Co., Ltd; Hunan Hualian Yuxiang China Industry Co., Ltd.",
"hint": ""
}
]
}
}
}
}
```
Here are four interesting variants of additional codes: …
> Surface additional codes for the duty calculator

- .circleci/config.yml
HOTT-n/a
- We want to correlate issues with the release history.
-
-
> Track releases in sentry

- app/services/quota_search_service.rb
- spec/services/quota_search_service_spec.rb
Search quotas by full date
https://transformuk.atlassian.net/browse/HOTT-659
I am doing this because HOTT-659 changes to the quote search form included moving from a plain year field to a full date search, and the related backend service was lacking this option.
No known risk: the service has been extended by adding a new filter by full date functionality, but the old search by years is still in place.
> HOTT-659: Search quotas by full date

- app/controllers/api/v2/goods_nomenclatures_controller.rb
> Eager load indents

- .circleci/config.yml
- Gemfile.lock
- app/controllers/api/v2/goods_nomenclatures_controller.rb
> Fix more n + 1 issues in goods_nomenclature controller

- app/services/applicable_vat_options_service.rb
- spec/services/applicable_vat_options_service_spec.rb
> Tweak presented vat measures

- .solargraph.yml
- Gemfile
- Gemfile.lock
> Adds solargraph to project

- app/controllers/api/v2/changes_controller.rb
- app/serializers/api/v2/changes_serializer.rb
- config/routes.rb
- spec/controllers/api/v2/changes_controller_spec.rb
Reverts trade-tariff/trade-tariff-backend#106
> Revert "Revert "HOTT-726: create changes API""

- app/workers/populate_changes_table_worker.rb
- spec/workers/populate_changes_table_worker_spec.rb
- spec/workers/rollback_worker_spec.rb
HOTT-<TODO>
- https://sentry.io/organizations/engine-le/issues/2498388253/?project=5557005&referrer=slack
> Fix integration in the populate_changes_table_worker

- CHANGELOG.md
- CHANGELOG.old.md
- Gemfile
- Gemfile.lock
- Rakefile
HOTT-<TODO>
- This is needed to get better visibility on releases. The surrounding processes for deploying need to include a snippet of CHANGELOG so that all stakeholders have better visibility
> Adds automatically generated CHANGELOG.md

- app/serializers/api/v2/measures/measure_condition_serializer.rb
- spec/serializers/api/v2/measures/measure_condition_serializer_spec.rb
https://transformuk.atlassian.net/browse/HOTT-840
- Required for codifying the behaviour of specific measure conditions in the duty calculator
> Surface action code for the duty calculator

- README.md
- lib/tariff_importer/logger.rb
- lib/tariff_synchronizer.rb
- lib/tariff_synchronizer/logger.rb
- lib/tariff_synchronizer/tariff_downloader.rb
- lib/tariff_synchronizer/tariff_updates_requester.rb
- lib/tasks/tariff.rake
- lib/trade_tariff_backend.rb
> Tidy up some outstanding chief stuff

- Rakefile
- app/serializers/api/v2/measures/measure_component_serializer.rb
- app/serializers/api/v2/measures/measure_condition_component_serializer.rb
- app/services/cached_commodity_service.rb
- spec/serializers/api/v2/measures/measure_component_serializer_spec.rb
- spec/serializers/api/v2/measures/measure_condition_component_serializer_spec.rb
HOTT-<TODO>
- This will give the measure condition components the same signature as the measure components
> Surface description and abbreviation for consistency

- CHANGELOG.md
> Bumps changelog

- app/presenters/api/v2/measures/measure_legal_act_presenter.rb
Difference in behaviour between &. and #try(:)
> HOTFIX for Sentry issue 2568513150

- app/presenters/api/v2/measures/measure_legal_act_presenter.rb
Don't assume regulation has #information_text
> Don't assume regulation has #information_text

- app/presenters/api/v2/measures/measure_legal_act_presenter.rb
Incorrect call to information_text
> Fix for incorrect method call

- spec/presenters/api/v2/measures/measure_legal_act_presenter_spec.rb
???
Because my specs should have picked it up.
- None - spec only changes
> Added specs for Regulations which don't follow base regulations schema

- db/data_migrations/20210817124456_create_table_flibble.rb
- db/data_migrations/20210817124456_update_validity_end_date.rb
https://transformuk.atlassian.net/browse/HOTT-901
> Adds migration for measure with missing validity end date

- Gemfile
- Gemfile.lock
> Bumps gems

- app/elastic_search_indexes/search/chapter_index.rb
- app/elastic_search_indexes/search/heading_index.rb
- app/elastic_search_indexes/search/section_index.rb
- app/models/export_refund_nomenclature.rb
- app/models/footnote.rb
- app/models/geographical_area.rb
- app/models/goods_nomenclature_description.rb
- app/presenters/api/v2/exact_search_presenter.rb
- app/presenters/api/v2/fuzzy_search_presenter.rb
- app/presenters/api/v2/suggestion_presenter.rb
- app/serializers/api/admin/search_references/heading_serializer.rb
- app/serializers/api/admin/search_references/search_reference_list_serializer.rb
- app/serializers/api/admin/search_references/search_reference_serializer.rb
- app/serializers/api/admin/search_references/section_serializer.rb
- app/serializers/api/v2/chapters/heading_leaf_serializer.rb
- app/serializers/api/v2/exact_search_serializer.rb
- app/serializers/api/v2/search_suggestion_serializer.rb
- app/serializers/search/chapter_serializer.rb
- app/serializers/search/heading_serializer.rb
- app/serializers/search/search_reference_serializer.rb
- app/services/api/v1/error_serialization_service.rb
- app/services/api/v1/search_serialization_service.rb
- app/services/api/v2/search_serialization_service.rb
- app/services/api/v2/suggestions_service.rb
- app/services/base_suggestions_service.rb
- app/services/search_service/exact_search.rb
- config/environments/production.rb
- config/initializers/redis_lock_db.rb
- lib/tasks/chemical_import.rake
>  bundle exec rubocop -a --only Layout/TrailingWhitespace

- .circleci/config.yml
HOTT-755
- We need to manually change the manifest in Gov PaaS before we can merge this.
> Use docker deploys for staging

- .circleci/config.yml
> enable docker deployment in production

- config/application.rb
- config/initializers/global_requires.rb
- lib/taric_importer/record_processor.rb
- lib/taric_importer/record_processor/attribute_mutator_overrides/measure_attribute_mutator.rb
- lib/taric_importer/record_processor/operation_overrides/goods_nomenclature_destroy_operation.rb
- lib/taric_importer/record_processor/operation_overrides/goods_nomenclature_update_operation.rb
- lib/taric_importer/record_processor/record.rb
- spec/unit/core_ext/object_spec.rb
- spec/unit/taric_importer/record_processor/record_spec.rb
- spec/unit/taric_importer/record_processor_spec.rb
[HOTT-926](https://transformuk.atlassian.net/browse/HOTT-926)
- We need CDS sync more urgently than the switch to Zeitwerk
> HOTT-926 - Revert PR 157

- .circleci/config.yml
- Dockerfile
HOTT-n/a
- (migration) tasks were just being submitted and actual execution status was not checked.
-
-
> wait for migrations to complete

- app/services/search_service.rb
- app/services/search_service/exact_search.rb
Jira: https://transformuk.atlassian.net/browse/HOTT-810
Include search for singular/plural forms of the term.
This gives the user more flexibility, allowing us to search using either the singular or the plural form of the term.
> HOTT-810 Include search for singular/plural forms of the term.

- app/models/rules_of_origin/scheme.rb
- db/rules_of_origin/roo_schemes_uk.json
- db/rules_of_origin/roo_schemes_xi.json
- spec/models/rules_of_origin/scheme_spec.rb
[HOTT-949](https://transformuk.atlassian.net/browse/HOTT-949)
- We now have updated scheme files and there are additional attributes present in them
> HOTT-949: Updated RoO schemes files

- .circleci/config.yml
- app/presenters/api/v2/headings/declarable_heading_presenter.rb
- app/serializers/api/v2/headings/declarable_heading_serializer.rb
- spec/controllers/api/v2/headings_controller_spec.rb
- spec/factories/measure_factory.rb
- spec/presenters/api/v2/headings/declarable_headings_presenter_spec.rb
- spec/serializers/api/v2/headings/declarable_heading_serializer_spec.rb
https://transformuk.atlassian.net/browse/HOTT-947
- This is needed to make declarable headings work for the STW team
> Surface duty calculator meta attributes

- spec/controllers/api/v2/headings_controller_spec.rb
- spec/factories/measure_factory.rb
https://transformuk.atlassian.net/browse/HOTT-947
- It was expedient to do this separately since we had to get that feature out for the STW team
> Linting after changes to the declarable headings

- app/serializers/api/v2/measures/measure_serializer.rb
- spec/serializers/api/v2/measures/measure_serializer_spec.rb
Reverts trade-tariff/trade-tariff-backend#228
> Revert "Lazy load all measure v2 relationships"

- app/models/rules_of_origin/scheme.rb
[HOTT-956](https://transformuk.atlassian.net/browse/HOTT-956)
- It improves readability and addresses review comments raised after merge of original code
> HOTT-956: Address review comments

- spec/controllers/api/admin/chapters/chapter_notes_controller_spec.rb
- spec/controllers/api/admin/footnotes_controller_spec.rb
- spec/controllers/api/admin/measure_types_controller_spec.rb
- spec/controllers/api/admin/rollbacks_controller_spec.rb
- spec/controllers/api/admin/sections/section_notes_controller_spec.rb
- spec/controllers/api/admin/updates_controller_spec.rb
- spec/controllers/api/v2/additional_code_types_controller_spec.rb
- spec/controllers/api/v2/additional_codes_controller_spec.rb
- spec/controllers/api/v2/certificate_types_controller_spec.rb
- spec/controllers/api/v2/certificates_controller_spec.rb
- spec/controllers/api/v2/chapters_controller_spec.rb
- spec/controllers/api/v2/commodities_controller_spec.rb
- spec/controllers/api/v2/footnote_types_controller_spec.rb
- spec/controllers/api/v2/footnotes_controller_spec.rb
- spec/controllers/api/v2/goods_nomenclatures_controller_spec.rb
- spec/controllers/api/v2/monetary_exchange_rates_controller_spec.rb
- spec/controllers/api/v2/search_references_controller_spec.rb
- spec/controllers/api/v2/sections_controller_spec.rb
- spec/controllers/api/v2/updates_controller_spec.rb
- spec/support/shared_examples/v2_search_reference_controller_examples.rb
> Removes unused render_views and lint touched files

- app/models/rules_of_origin/heading_mappings.rb
- app/models/rules_of_origin/rule_set.rb
[HOTT-985](https://transformuk.atlassian.net/browse/HOTT-985)
- There were duplicates in the earlier copies of the files
> HOTT-985: Updated rules of origin data

- app/formatters/duty_expression_formatter.rb
- app/models/duty_expression.rb
- app/models/geographical_area.rb
- app/models/measure_type_exclusion.rb
- app/services/cached_commodity_service.rb
- app/services/cached_geographical_area_service.rb
- app/services/meursing_measure_finder_service.rb
- spec/models/duty_expression_spec.rb
- spec/models/measure_type_exclusion_spec.rb
- spec/services/cached_commodity_service_spec.rb
- spec/services/meursing_measure_finder_service_spec.rb
https://transformuk.atlassian.net/browse/HOTT-801
- This is required to return different responses depending on the meursing additional code
- There is a small performance hit (all requests need to recache) since I've changed the key but I think this is acceptable/will repopulate quickly
> Adds caching on meursing code and handle geographical area exclusions

- .circleci/config.yml
- CONTRIBUTING.md
- README.md
https://transformuk.atlassian.net/browse/HOTT-1090
> Remove master references

- app/presenters/api/v2/measures/measure_presenter.rb
> Refactor measure presenter

- app/models/measurement_unit.rb
- spec/models/measurement_unit_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1105
Measurement units are used by the duty calculator to record inputs that
can later be used in different types of measure component to do a duty
calculation and work out the duties a trader needs to pay.
We have been seeing some components that refer to measurement units that
do not even exist in the db and these should be handled more gracefully
to avoid the backend response causing failed journeys for the user.
Even if these units do not exist in the database we can still do duty
calculations against them - they just won't be semantically enriched for
the user in the duty calculator measure amount input step.
- More graceful user experience
> HOTT-1105: Gracefully fail on missing measure units

- spec/controllers/api/admin/news_items_controller_spec.rb
- spec/services/find_ancestors_service_spec.rb
- spec/services/quota_search_service_spec.rb
- spec/unit/core_ext/object_spec.rb
- spec/unit/taric_importer/record_processor/record_spec.rb
- spec/unit/taric_importer/record_processor_spec.rb
> Namespace all describes

- app/models/measurement_unit.rb
- app/services/measure_unit_service.rb
- db/measurement_units.json
- spec/factories/measure_factory.rb
- spec/models/measurement_unit_spec.rb
- spec/services/measure_unit_service_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1182
- ASVX measurement units are currently calculated incorrectly and we do not ask for all the units that apply in this case.
> HOTT-1182: Surface compound measurement units

- app/controllers/api/v2/chapters_controller.rb
- app/serializers/api/v2/chapters/chapter_list_serializer.rb
- spec/controllers/api/v2/chapters_controller_spec.rb
- spec/serializers/api/v2/chapters/chapter_list_serializer_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1186
- This is to reduce the overhead of pulling out chapter descriptions as part of the goods nomenclature work
> Surface chapter descriptions when listing all chapters

- app/lib/goods_nomenclature_mapper.rb
[HOTT-1150](https://transformuk.atlassian.net/browse/HOTT-1150)
This Patch fixes the bug "comparison of Integer with nil failed" on the goods_nomenclature_mapper.
Bug on Sentry: https://sentry.io/organizations/engine-le/issues/2732997178/events/ea7919efbaa443a299ee0db53622cb32/?project=5557005&statsPeriod=24h
We do not like bugs
> Bugfix comparison of Integer with nil failed

- README.md
- docker-compose.yml
[HOTT-927](https://transformuk.atlassian.net/browse/HOTT-927)
To make it easier to work with TT backend.
> Hott 927 Update README

- app/lib/tariff_synchronizer.rb
- app/lib/tasks/tariff.rake
- app/workers/rollback_worker.rb
- spec/integration/tariff_synchronizer_spec.rb
- spec/unit/tariff_synchronizer/logger_spec.rb
- spec/workers/rollback_worker_spec.rb
Rubocop suggested using hash params, which makes sense,
so I did it in a different PR to keep the feature branch cleaner.
> Convert param to hash param. Code smell suggested by Rubocop.

- .circleci/config.yml
- Dockerfile
Reverts trade-tariff/trade-tariff-backend#372
> Revert "HOTT-1294: Fix Alpine docker updates"

- .rubocop.yml
- app/lib/tariff_synchronizer.rb
- app/lib/tariff_synchronizer/cds_update.rb
- app/workers/updates_synchronizer_worker.rb
- spec/unit/tariff_synchronizer/cds_update_spec.rb
- spec/unit/tariff_synchronizer_spec.rb
- spec/workers/updates_synchronizer_worker_spec.rb
Reverts trade-tariff/trade-tariff-backend#354
> Revert "HOTT-1260 Retry data loads"

- .circleci/config.yml
- Dockerfile
Reverts trade-tariff/trade-tariff-backend#373
> Revert "Revert "HOTT-1294: Fix Alpine docker updates""

- app/controllers/api/admin/measure_types_controller.rb
- app/controllers/api/v2/measure_types_controller.rb
- app/models/measure_type.rb
- app/serializers/api/v2/measures/measure_type_serializer.rb
- config/routes.rb
- spec/controllers/api/v2/measure_types_controller_spec.rb
- spec/factories/measure_factory.rb
- spec/serializers/api/v2/measures/measure_types_serializer_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1297
Add a new endpoint to list all the measure_types and relevant measure_type_series_description
The members of the trade consider useful this endpoint.
> Hott 1297 Add measures types api endpoint

- app/controllers/api/v2/measure_types_controller.rb
- spec/controllers/api/v2/certificates_controller_index_spec.rb
- spec/controllers/api/v2/measure_types_controller_spec.rb
HOTT-1297
Add support for ?as_of param, and fix eagerloading on measure_type_series_description.
> Add support for ?as_of param + eagerloading fix

- app/controllers/api/v2/measure_condition_codes_controller.rb
- app/serializers/api/v2/measure_condition_code_serializer.rb
- config/routes.rb
- spec/controllers/api/v2/measure_condition_codes_controller_spec.rb
- spec/factories/measure_condition_code_factory.rb
- spec/serializers/api/v2/measure_condition_codes_serializer_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1299
- This is a feature request
> HOTT-1299: Surface measure condition codes

- app/controllers/api/v2/measure_actions_controller.rb
- app/serializers/api/v2/measure_action_serializer.rb
- config/routes.rb
- spec/controllers/api/v2/measure_actions_controller_spec.rb
- spec/factories/measure_action_description.rb
- spec/factories/measure_action_factory.rb
- spec/serializers/api/v2/measure_action_serializer_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1301
- This is a feature request
> HOTT-1301: Surface measure actions

- app/models/measure.rb
- spec/models/commodity_spec.rb
- spec/models/measure_spec.rb
Reverts trade-tariff/trade-tariff-backend#388
> Revert "HOTT-1318: Fix broken measure filtering"

- app/services/meursing_measure_finder_service.rb
- spec/services/meursing_measure_finder_service_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1334
> HOTT-1334: Surface measures around the measure finder

- db/rules_of_origin/roo_schemes_uk/introductory_notes/gsp_intro.md
- db/rules_of_origin/roo_schemes_xi/introductory_notes/gsp_intro.md
[HOTT-1218](https://transformuk.atlassian.net/browse/HOTT-1218)
Update the GSP introductory notes for UK and XI.
> Update the GSP introductory notes for UK and XI.

- .circleci/config.yml
- app/lib/tasks/tariff.rake
https://transformuk.atlassian.net/browse/HOTT-1283
- We want to make sure staging looks/acts like production when we integrate/validate changes before they go live
> HOTT-1293: Refresh staging database

- .circleci/config.yml
Reverts trade-tariff/trade-tariff-backend#347
> Revert "HOTT-1104 Run database migrations on own tasks app"

- .circleci/config.yml
- db/seeds/staging.sql
https://transformuk.atlassian.net/browse/HOTT-1377
- This is needed to make sure Madhu's e2e tests of subheading functionality work
> HOTT-1377: Populate staging search references

- app/presenters/api/v2/measures/measure_presenter.rb
- spec/factories/measure_factory.rb
- spec/serializers/api/v2/measures/measure_serializer_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1359
- I'm working on extending this presenter and it needed cleaning/side effects removing
> HOTT-1359: Simplify and tidy measure presenter

- spec/services/meursing_measure_finder_service_spec.rb
> Temporarily silence meursing finder service failures

- app/models/measure_action.rb
- app/models/measure_condition.rb
- app/presenters/api/v2/measures/measure_condition_presenter.rb
- app/presenters/api/v2/measures/measure_presenter.rb
- app/serializers/api/v2/measures/measure_condition_serializer.rb
- spec/controllers/api/v2/commodities_controller_spec.rb
- spec/factories/goods_nomenclature_factory.rb
- spec/factories/measure_condition_component_factory.rb
- spec/factories/measure_condition_factory.rb
- spec/factories/measure_factory.rb
- spec/models/measure_action_spec.rb
- spec/presenters/api/v2/measures/measure_condition_presenter_spec.rb
- spec/presenters/api/v2/measures/measure_presenter_spec.rb
- spec/serializers/api/v2/measures/measure_condition_serializer_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1360
- This is required so we can more easily work with complex measure conditions in the frontend later
> HOTT-1360: Surface measure condition class

- app/controllers/api/v2/quotas_controller.rb
- app/models/commodity.rb
- app/models/goods_nomenclature.rb
- app/serializers/api/v2/quotas/definition/chapter_serializer.rb
- app/serializers/api/v2/quotas/definition/commodity_serializer.rb
- app/serializers/api/v2/quotas/definition/goods_nomenclature_serializer.rb
- app/serializers/api/v2/quotas/definition/heading_serializer.rb
- app/serializers/api/v2/quotas/definition/measure_serializer.rb
- app/serializers/api/v2/quotas/definition/subheading_serializer.rb
- app/services/quota_search_service.rb
- spec/controllers/api/v2/quotas_controller_spec.rb
- spec/models/commodity_spec.rb
- spec/models/goods_nomenclature_spec.rb
- spec/serializers/api/v2/quotas/definition/chapter_serializer_spec.rb
- spec/serializers/api/v2/quotas/definition/commodity_serializer_spec.rb
- spec/serializers/api/v2/quotas/definition/goods_nomenclature_serializer_spec.rb
- spec/serializers/api/v2/quotas/definition/heading_serializer_spec.rb
- spec/serializers/api/v2/quotas/definition/measure_serializer_spec.rb
- spec/serializers/api/v2/quotas/definition/subheading_serializer_spec.rb
- spec/support/shared_examples/a_serialized_goods_nomenclature.rb
https://transformuk.atlassian.net/browse/HOTT-1411
- This is required so that we can make commodities, subheadings, headings and chapters that are attached to a measure
link to the correct thing in the frontend
> HOTT-1411: Surface polymorphic goods nomenclature for quota search

- app/controllers/api/v2/quotas_controller.rb
- spec/controllers/api/v2/quotas_controller_spec.rb
- This is required to serialize quotas correctly
> HOTT-1414: Use shared quota serializers

- app/models/measure_condition.rb
- app/serializers/api/v2/certificates/certificate_list_serializer.rb
- app/serializers/api/v2/certificates/certificates_serializer.rb
- spec/models/measure_condition_spec.rb
- spec/serializers/api/v2/certificates/certificate_list_serializer_spec.rb
- spec/serializers/api/v2/certificates/certificates_serializer_spec.rb
Reverts trade-tariff/trade-tariff-backend#518
> Revert "HOTT-1468: Disable guidance on XI"

- app/controllers/api/v2/chapters_controller.rb
- app/serializers/api/v2/csv/chapter_serializer.rb
- spec/requests/api/v2/chapters_controller_spec.rb
- spec/serializers/api/v2/csv/chapter_serializer_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1488
Add support for CSV for /chapters
> HOTT-1487: Add support for CSV for /chapters

- config/routes.rb
- spec/requests/api/v2/chapters_controller_spec.rb
- spec/requests/api/v2/sections_controller_spec.rb
- spec/support/shared_examples/api_request_examples.rb
Reverts trade-tariff/trade-tariff-backend#538
> Revert "HOTT-1518: Support text/csv in ACCEPT header"

- app/controllers/api/v2/sections_controller.rb
- app/models/section.rb
- config/routes.rb
- spec/factories/section_factory.rb
https://transformuk.atlassian.net/browse/HOTT-1543
- This combination of incorrect configuration led me down a bit of a rabbit hole recently with intermittently failing specs
> HOTT-1543: Fix misuse of section id/position

- app/models/measurement_unit.rb
- db/measurement_units_20220428.json
- spec/services/measure_unit_service_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1540
- So we can present them to the user on the duty calculator screen
> HOTT-1540: Adds original unit to the measurement_units file

- app/lib/cds_importer/entity_mapper.rb
- app/lib/cds_importer/entity_mapper/base_mapper.rb
- app/lib/cds_importer/xml_parser.rb
- spec/integration/cds_importer/entity_mapper_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1582
- This is to simplify management of the entity mappers and to make sure mapping roots are loading properly
> HOTT-1582: Dynamic entity mapper loading

- app/controllers/api/admin/search_references_controller.rb
- app/controllers/api/v2/search_references_controller.rb
- app/models/search_reference.rb
- spec/controllers/api/v2/search_references_controller_spec.rb
- spec/requests/api/admin/search_references_controller_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1545
Return all the search ref when the letter param is not provided.
> HOTT-1545 Return all the search ref when query letter is not provided.

- app/lib/cds_importer/entity_mapper.rb
- app/lib/cds_importer/entity_mapper/base_mapper.rb
- app/lib/cds_importer/entity_mapper/footnote_mapper.rb
- spec/lib/cds_importer/entity_mapper/footnote_mapper_spec.rb
- spec/support/shared_examples/an_entity_mapper_missing_entity_destroy_operation.rb
https://transformuk.atlassian.net/browse/HOTT-1583
- CDS send us files that do not explicitly indicate that resources should be deleted and instead are expecting us to work out what needs removing and to remove them.
> HOTT-1583: Enable soft deletion of missing footnoteDescriptionPeriod entities

- app/lib/cds_importer/entity_mapper/base_mapper.rb
- app/lib/cds_importer/entity_mapper/footnote_association_measure_mapper.rb
- app/lib/cds_importer/entity_mapper/measure_component_mapper.rb
- app/lib/cds_importer/entity_mapper/measure_condition_component_mapper.rb
- app/lib/cds_importer/entity_mapper/measure_condition_mapper.rb
- app/lib/cds_importer/entity_mapper/measure_excluded_geographical_area_mapper.rb
- app/lib/cds_importer/entity_mapper/measure_mapper.rb
- app/lib/cds_importer/entity_mapper/measure_partial_temporary_stop_mapper.rb
- spec/factories/measure_condition_factory.rb
- spec/factories/measure_excluded_geographical_area_factory.rb
- spec/factories/measure_factory.rb
- spec/lib/cds_importer/entity_mapper/footnote_mapper_spec.rb
- spec/lib/cds_importer/entity_mapper/measure_condition_mapper_spec.rb
- spec/lib/cds_importer/entity_mapper/measure_mapper_spec.rb
- spec/models/measure_spec.rb
- spec/support/shared_examples/an_entity_mapper_missing_entity_destroy_operation.rb
https://transformuk.atlassian.net/browse/HOTT-1586
- This is required so we can reflect the changes that come from the CDS files properly
> HOTT-1599: Handle deletions on the measure mapper

- app/lib/cds_importer/entity_mapper/additional_code_description_period_mapper.rb
- app/lib/cds_importer/entity_mapper/additional_code_mapper.rb
- app/lib/cds_importer/entity_mapper/footnote_association_additional_code_mapper.rb
- app/lib/cds_importer/entity_mapper/footnote_association_measure_mapper.rb
- app/lib/cds_importer/entity_mapper/footnote_description_period_mapper.rb
- app/lib/cds_importer/entity_mapper/measure_component_mapper.rb
- app/lib/cds_importer/entity_mapper/measure_condition_component_mapper.rb
- app/lib/cds_importer/entity_mapper/measure_condition_mapper.rb
- app/lib/cds_importer/entity_mapper/measure_excluded_geographical_area_mapper.rb
- app/lib/cds_importer/entity_mapper/measure_partial_temporary_stop_mapper.rb
- app/models/additional_code_description_period.rb
- spec/factories/additional_code_factory.rb
- spec/lib/cds_importer/entity_mapper/additional_code_mapper_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1585
- This is required so we can reflect the changes that come from the CDS files properly
> HOTT-1585: Handle additional code primary soft deletes

- app/lib/cds_importer.rb
- app/lib/cds_importer/entity_mapper.rb
- app/lib/cds_importer/entity_mapper/additional_code_mapper.rb
- app/lib/cds_importer/entity_mapper/additional_code_type_mapper.rb
- app/lib/cds_importer/entity_mapper/base_mapper.rb
- app/lib/cds_importer/entity_mapper/footnote_mapper.rb
- app/lib/cds_importer/entity_mapper/measure_mapper.rb
- app/lib/sequel/plugins/oplog.rb
- app/lib/tariff_synchronizer/cds_update.rb
- spec/integration/cds_importer/cds_importer_spec.rb
- spec/unit/tariff_synchronizer/cds_update_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1586
- This will make it easier to understand which kind of operations resulted from a CDS file in the admin UI
> HOTT-1586: Instrument oplog operations

- app/lib/cds_importer.rb
- spec/integration/cds_importer/cds_importer_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1584
- These are all coming back as 0
> HOTT-1586: Removes allocations

- app/controllers/api/admin/updates_controller.rb
- app/lib/tariff_synchronizer/base_update.rb
- app/lib/tariff_synchronizer/cds_update.rb
- app/lib/tariff_synchronizer/taric_update.rb
- config/routes.rb
- spec/controllers/api/admin/updates_controller_spec.rb
- spec/unit/tariff_synchronizer/base_update_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1585
- This is required so we can show the inserts of a specific update
> HOTT-1585: Adds show endpoint to admin updates controller

- app/lib/cds_importer/entity_mapper/certificate_description_period_mapper.rb
- app/lib/cds_importer/entity_mapper/certificate_mapper.rb
- spec/lib/cds_importer/entity_mapper/certificate_mapper_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1584
- This is part of a wider rollout for handling missing xml nodes
> HOTT-1584: Handle missing deletion for certificates

- app/workers/reindex_models_worker.rb
- spec/workers/recache_models_worker_spec.rb
- spec/workers/reindex_models_worker_spec.rb
And added missing specs
HOTT-1676
- Reindexing is broken on `main` and the specs didn't catch it
> HOTT-1676 Fixed model reindexing bug

- spec/factories/base_update_factory.rb
- spec/integration/tariff_synchronizer/rollback_cds_spec.rb
- spec/integration/tariff_synchronizer/rollback_spec.rb
- spec/support/matchers/have_rolled_back.rb
https://transformuk.atlassian.net/browse/HOTT-1662
- This needs to be in place before I can optimise and simplify the CDS rollbacks
> HOTT-1662: Adds specs for rollback behaviour

- .circleci/config.yml
[HOTT-1403](https://transformuk.atlassian.net/browse/HOTT-1403)
- We want to be able to redeploy releases without rebuilding
- We want to build a record of what we have released and when
- We want to notify the team when changes are released, and what was changed
- Makes changes to the deployment process
> HOTT-1404 Use tagged releases

- app/controllers/api/admin/search_references_base_controller.rb
- app/lib/taric_importer/record_processor/operation.rb
- app/lib/tariff_synchronizer/base_update_importer.rb
- app/lib/tariff_synchronizer/cds_update_downloader.rb
- app/models/commodity.rb
- app/models/concerns/declarable.rb
- app/services/search_service/fuzzy_search/fuzzy_search_result.rb
- lib/tasks/national_data.rake
> Lint multiline commas

- app/elastic_search_indexes/search_index.rb
- app/lib/sequel/plugins/elasticsearch.rb
- app/lib/trade_tariff_backend.rb
- app/lib/trade_tariff_backend/search_client.rb
- app/services/search_service/fuzzy_search/fuzzy_search_result.rb
- app/workers/build_index_page_worker.rb
- config/environments/test.rb
- spec/controllers/api/v2/additional_codes_controller_spec.rb
- spec/controllers/api/v2/certificates_controller_search_spec.rb
- spec/controllers/api/v2/footnotes_controller_spec.rb
- spec/elastic_search_indexes/cache/additional_code_index_spec.rb
- spec/elastic_search_indexes/cache/certificate_index_spec.rb
- spec/elastic_search_indexes/cache/footnote_index_spec.rb
- spec/elastic_search_indexes/cache/heading_index_spec.rb
- spec/elastic_search_indexes/search/chapter_index_spec.rb
- spec/elastic_search_indexes/search/commodity_index_spec.rb
- spec/elastic_search_indexes/search/heading_index_spec.rb
- spec/elastic_search_indexes/search/search_reference_index_spec.rb
- spec/elastic_search_indexes/search/section_index_spec.rb
- spec/lib/trade_tariff_backend/search_client_spec.rb
- spec/services/additional_code_search_service_spec.rb
- spec/services/certificate_search_service_spec.rb
- spec/workers/build_index_page_worker_spec.rb
Reverts trade-tariff/trade-tariff-backend#643
> Revert "HOTT-1676 allow multiple indexes per model"

- app/elastic_search_indexes/search_index.rb
- app/lib/sequel/plugins/elasticsearch.rb
- app/lib/trade_tariff_backend.rb
- app/lib/trade_tariff_backend/search_client.rb
- app/services/search_service/fuzzy_search/fuzzy_search_result.rb
- app/workers/build_index_page_worker.rb
- config/environments/test.rb
- spec/controllers/api/v2/additional_codes_controller_spec.rb
- spec/controllers/api/v2/certificates_controller_search_spec.rb
- spec/controllers/api/v2/footnotes_controller_spec.rb
- spec/elastic_search_indexes/cache/additional_code_index_spec.rb
- spec/elastic_search_indexes/cache/certificate_index_spec.rb
- spec/elastic_search_indexes/cache/footnote_index_spec.rb
- spec/elastic_search_indexes/cache/heading_index_spec.rb
- spec/elastic_search_indexes/search/chapter_index_spec.rb
- spec/elastic_search_indexes/search/commodity_index_spec.rb
- spec/elastic_search_indexes/search/heading_index_spec.rb
- spec/elastic_search_indexes/search/search_reference_index_spec.rb
- spec/elastic_search_indexes/search/section_index_spec.rb
- spec/lib/trade_tariff_backend/search_client_spec.rb
- spec/services/additional_code_search_service_spec.rb
- spec/services/certificate_search_service_spec.rb
- spec/workers/build_index_page_worker_spec.rb
Reverts trade-tariff/trade-tariff-backend#660
> Revert "Revert "HOTT-1676 allow multiple indexes per model""

- app/lib/tariff_synchronizer.rb
https://transformuk.atlassian.net/browse/HOTT-1662
- These run incredibly inefficiently (for every date we execute 157 queries to delete oplog rows that match our filename). Now we just run 1 query per oplog table
> HOTT-1662: Optimise CDS rollbacks

- app/models/quota_definition.rb
- app/models/quota_reopening_event.rb
- app/models/quota_unblocking_event.rb
- app/models/quota_unsuspension_event.rb
- spec/models/quota_definition_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1688
- This is to correct the returned status in the UI for the active definition
> HOTT-1688: Update statuses of open events

- spec/serializers/search/goods_nomenclature_serializer_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1702
> HOTT-1702: Fixes flaky spec

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- config/routes.rb
- lib/routing_filter/service_path_prefix.rb
- spec/requests/api/beta/search_controller_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1751
- This is required so that we can expose the beta scope
> HOTT-1751: Enable routing to the new beta scope

- app/elastic_search_indexes/search/goods_nomenclature_index.rb
- config/opensearch/synonyms_generic.txt
- docker-compose.yml
https://transformuk.atlassian.net/browse/HOTT-1763
- This will soon be plumbed together to pull config files into AWS as part of our deployment pipeline
> HOTT-1763: Adds synonym config file for opensearch beta index

- app/workers/clear_cache_worker.rb
- app/workers/updates_synchronizer_worker.rb
HOTT-<TODO>
- It's 12:00 and (because we're behind the unreasonably slow heading cache job) we still haven't generated our search index which should have started around 5am and finished in under half an hour
> Adjusts the sequencing for goods nomenclature index population

- app/workers/reindex_models_worker.rb
- spec/workers/reindex_models_worker_spec.rb
HOTT-<TODO>
- The beta indexes are finally in a steady state of structure
> Stop dropping beta index

- db/data_migrations/2022080530154709_fix_broken_comm_code_descriptions.rb
- db/data_migrations/20220805304709_fix_broken_comm_code_descriptions.rb
[HOTT-1795](https://transformuk.atlassian.net/browse/HOTT-1795)
> HOTT-1759 - Adds a migration to fix description for a couple of comm codes

- app/serializers/api/beta/goods_nomenclature_serializer.rb
- spec/fixtures/beta/search/goods_nomenclatures/serialized_result.json
- spec/serializers/api/beta/chapter_serializer_spec.rb
- spec/serializers/api/beta/commodity_serializer_spec.rb
- spec/serializers/api/beta/heading_serializer_spec.rb
- spec/serializers/api/beta/subheading_serializer_spec.rb
[HOTT-1833](https://transformuk.atlassian.net/browse/HOTT-1833)
> HOTT-1833 adds endline and declarable status to goods nomen clature

- app/serializers/api/beta/commodity_serializer.rb
[HOTT-1829](https://transformuk.atlassian.net/browse/HOTT-1829)
> HOTT-1829 adds validity start date and validity end date to commodity api

- db/data_migrations/20220815100048_fix_broken_comm_code_descriptions.rb
[HOTT-1795](https://transformuk.atlassian.net/browse/HOTT-1795)
> HOTT-1795 Fix broken comm codes

- .rubocop.yml
- app/models/chief_cds_guidance.rb
- app/models/rules_of_origin/article.rb
- app/models/rules_of_origin/explainer.rb
- app/models/rules_of_origin/heading_mappings.rb
- app/models/rules_of_origin/link.rb
- app/models/rules_of_origin/query.rb
- app/models/rules_of_origin/rule.rb
- app/models/rules_of_origin/rule_set.rb
- app/models/rules_of_origin/scheme.rb
- app/models/rules_of_origin/scheme_set.rb
- app/models/rules_of_origin/v2/rule.rb
- app/models/rules_of_origin/v2/rule_set.rb
- db/migrate/20210915112121_add_news_items.rb
- db/migrate/20220107134210_add_productline_suffix_to_search_references.rb
- db/migrate/20220223091956_add_oplog_inserts_to_tariff_updates.rb
- db/migrate/20220328091515_add_show_on_banner_to_news_items.rb
- db/migrate/20220526155444_add_language_to_additional_code_type_description_view.rb
- db/migrate/20220609140555_add_path_to_goods_nomenclatures_oplog.rb
- db/migrate/20220614130523_drop_function_fetch_chapter_commodities_for_date.rb
- db/migrate/20220713145800_add_strapline_to_guides.rb
- db/migrate/20220714165446_create_guides_goods_nomenclatures.rb
> Removes dead frozen string literal instruction

- app/controllers/api/v2/headings_controller.rb
- app/models/measure_collection.rb
- app/presenters/api/v2/commodities/commodity_presenter.rb
- app/presenters/api/v2/headings/declarable_heading_presenter.rb
- app/services/cached_commodity_service.rb
- app/services/heading_service/heading_serialization_service.rb
- spec/models/measure_collection_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1943
- This is required to make sure we support the same behaviour between headings and commodities
> HOTT-1943: Filter countries consistently

- app/lib/trade_tariff_backend.rb
- Getting documents that are bigger than what is support by ES and need to make sure this runs fine by Monday
> HOTT-1658: Reduce batch size

- config/routes.rb
HOTT-<TODO>
- Section ids go past 2 digits and the routes fail
> Fixes intermittent test failures

- config/locales/en.yml
- spec/models/beta/search/intercept_message_spec.rb
- spec/serializers/api/beta/intercept_message_serializer_spec.rb
- spec/serializers/api/beta/search_result_serializer_spec.rb
[HOTT-<1906>](https://transformuk.atlassian.net/browse/HOTT-1906)
- we need the new intercept messaging data
> HOTT-1906: Replace en.yml file

- app/lib/roman_numerals/converter.rb
- app/models/beta/search/intercept_message.rb
- spec/factories/intercept_message_factory.rb
- spec/lib/roman_numerals/converter_spec.rb
- spec/models/beta/search/intercept_message_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1990
To dynamically include hyperlinks to SECTIONS of the tariff in the search intercepts messages
> HOTT-1990 Add support for section on intercept_message.

- app/services/api/beta/search_service.rb
- spec/services/api/beta/search_service_spec.rb
> Fix broken reference to goods_nomenclatures

- Gemfile.lock
- config/puma.rb
Reverts trade-tariff/trade-tariff-backend#826
> Revert "Revert "Bump puma from 5.6.5 to 6.0.0""

- app/controllers/api/beta/search_controller.rb
- app/services/api/beta/search_query_parser_service.rb
- app/services/api/beta/search_service.rb
- spec/services/api/beta/search_query_parser_service_spec.rb
- spec/services/api/beta/search_service_spec.rb
https://transformuk.atlassian.net/browse/HOTT-2162
- This is required to avoid spelling corrections in the frontend
> HOTT-2162: Support spell option and pass it on

- app/models/full_temporary_stop_regulation.rb
- app/models/measure_partial_temporary_stop.rb
- app/models/prorogation_regulation.rb
- spec/factories/full_temporary_stop_regulation_factory.rb
- spec/models/full_temporary_stop_regulation_spec.rb
- spec/models/measure_partial_temporary_stop_spec.rb
HOTT-2029
This PR fixes the undefined `role` method.
Because we are  🐛 🐛🐛 fighters!  🐛🔫
> Fix for undefined method role.

- app/workers/updates_synchronizer_worker.rb
- spec/workers/updates_synchronizer_worker_spec.rb
HOTT-2212
- We were missing a file from sunday even, and only realised sync didn't happen yesterday when todays file showed up but was rejected for being out of order
- Impacts overnight sync - should be seen to work DEV before merging, then should be seen to work on staging before release
> HOTT-2212 Alert slack when missing CDS file

- app/controllers/api/admin/news/collections_controller.rb
- app/controllers/api/v2/news/collections_controller.rb
- app/controllers/api/v2/news/items_controller.rb
- app/models/news/collection.rb
- app/models/news/item.rb
- app/serializers/api/v2/news/collection_serializer.rb
- db/migrate/20221127173137_add_description_and_priority_to_news_collections.rb
- db/structure.sql
- spec/factories/news_factory.rb
- spec/models/news/collection_spec.rb
- spec/models/news/item_spec.rb
- spec/serializers/api/v2/news/collection_serializer_spec.rb
HOTT-2136
- We need to sort some collections above others
- We need to show additional content in the footer of the news stories relating to the collection
- Includes a database schema change
> HOTT-2136 update news item api

- config/locales/en.yml
https://transformuk.atlassian.net/browse/HOTT-2320
- This is required to work with the intercept message builder which only works iwth lower case search query strings
> HOTT-2320: Downcase keys for intercept messages

- app/controllers/api/v2/quotas_controller.rb
- app/models/quota_closed_and_transferred_event.rb
- app/serializers/api/v2/quotas/order_number/quota_definition_serializer.rb
- app/serializers/api/v2/quotas/quota_closed_and_transferred_event_serializer.rb
- app/services/concerns/declarable_serialization.rb
- spec/factories/quota_factory.rb
- spec/serializers/api/v2/quotas/quota_closed_and_transferred_event_serializer_spec.rb
https://transformuk.atlassian.net/browse/HOTT-2297
> HOTT-2297: Adds new transfer events to quota definition

- app/services/api/beta/search_service.rb
- app/services/base_suggestions_service.rb
- spec/controllers/api/v2/search_controller_search_spec.rb
- spec/factories/goods_nomenclature_factory.rb
- spec/services/api/beta/search_service_spec.rb
https://transformuk.atlassian.net/browse/HOTT-2377
https://transformuk.atlassian.net/browse/HOTT-2378
- This is required to handle duplicate title search references better
> HOTT-2378: Search reference duplication enhancements

- db/import_guides.rb
https://transformuk.atlassian.net/browse/HOTT-2394
- This will unblock running the rake task
> HOTT-2394: Adjustments for new guides files

- spec/factories/measure_factory.rb
- spec/serializers/api/v2/subheadings/commodity_serializer_spec.rb
HOTT-???
- The duplicate trait I spotted whilst looking at that file and a potential source of confusion to a future developer
- The second triggers a warning when we start up the test suite
> Minor cleanups

- app/models/measure_condition.rb
- app/models/measure_condition_code.rb
- app/serializers/api/v2/measures/measure_condition_serializer.rb
- app/services/concerns/declarable_serialization.rb
- spec/factories/measure_condition_factory.rb
- spec/models/measure_condition_code_spec.rb
- spec/serializers/api/v2/measures/measure_condition_serializer_spec.rb
https://transformuk.atlassian.net/browse/HOTT-2484
- This is required to correctly override requirement texts in the frontend
> HOTT-2484: Surface measure condition requirement operator

- .circleci/config.yml
HOTT-2171
- Its erroring out on the missing file and never re-running migrations
- Low
> HOTT-2171 Fix missing seeds file

- .circleci/config.yml
- .rspec
- spec/models/goods_nomenclature_spec.rb
- spec/serializers/search/goods_nomenclature_serializer_spec.rb
- spec/spec_helper.rb
- spec/unit/changes_table_populator/measure_started_spec.rb
- spec/workers/generate_materialized_paths_worker_spec.rb
https://transformuk.atlassian.net/browse/HOTT-2574
> HOTT-2574: Adds dedicated workflow to run flaky tests

- app/lib/cds_importer/entity_mapper/quota_association_mapper.rb
- app/lib/cds_importer/entity_mapper/quota_balance_event_mapper.rb
- app/lib/cds_importer/entity_mapper/quota_blocking_period_mapper.rb
- app/lib/cds_importer/entity_mapper/quota_critical_event_mapper.rb
- app/lib/cds_importer/entity_mapper/quota_definition_mapper.rb
- app/lib/cds_importer/entity_mapper/quota_exhaustion_event_mapper.rb
- app/lib/cds_importer/entity_mapper/quota_reopening_event_mapper.rb
- app/lib/cds_importer/entity_mapper/quota_suspension_period_mapper.rb
- app/lib/cds_importer/entity_mapper/quota_unblocking_event_mapper.rb
- app/lib/cds_importer/entity_mapper/quota_unsuspension_event_mapper.rb
- db/migrate/20230127151505_fixes_quota_critical_events_view.rb
- db/migrate/20230127153630_fixes_quota_exhaustion_events_view.rb
- db/migrate/20230127154210_fixes_quota_reopening_events_view.rb
- db/migrate/20230127155444_fixes_quota_unsuspension_events_view.rb
- db/structure.sql
- spec/factories/quota_factory.rb
- spec/lib/cds_importer/entity_mapper/quota_definition_mapper_spec.rb
- spec/support/shared_examples/an_entity_mapper_update_operation.rb
https://transformuk.atlassian.net/browse/HOTT-1612
- This is required to enable clearing out missing rows in quota definitions
- The views were broken and it took writing unit tests to highlight this
> HOTT-1612: Adds quota definition missing deletes behaviour

- db/rules_of_origin/roo_schemes_uk/rule_sets/central-america.json
HOTT-2535
- We have an updated version of the data set
- Low
> HOTT-2535 Update central america RoO rulesets

- app/lib/cds_importer/entity_mapper/additional_code_description_mapper.rb
- app/lib/cds_importer/entity_mapper/additional_code_description_period_mapper.rb
- app/lib/cds_importer/entity_mapper/certificate_description_mapper.rb
- app/lib/cds_importer/entity_mapper/certificate_description_period_mapper.rb
- app/lib/cds_importer/entity_mapper/footnote_description_mapper.rb
- app/lib/cds_importer/entity_mapper/footnote_description_period_mapper.rb
- app/lib/cds_importer/entity_mapper/goods_nomenclature_description_mapper.rb
- app/lib/cds_importer/entity_mapper/goods_nomenclature_description_period_mapper.rb
- spec/lib/cds_importer/entity_mapper/additional_code_description_period_mapper_spec.rb
- spec/lib/cds_importer/entity_mapper/certificate_description_period_mapper_spec.rb
- spec/lib/cds_importer/entity_mapper/footnote_description_period_mapper_spec.rb
- spec/lib/cds_importer/entity_mapper/goods_nomenclature_description_period_mapper_spec.rb
https://transformuk.atlassian.net/browse/HOTT-2596
- This is mainly for completeness and is part of the protocol that have designed
- The real life implications are not super relevant/a bit edge casey and we already only pull out periods with a description present as a defensive measure
> HOTT-2596: Clearout missing descriptions

- db/migrate/20230202142148_adds_fields_to_search_references.rb
- db/structure.sql
https://transformuk.atlassian.net/browse/HOTT-2381
- This will be used to simplify the relationships between the search references and the goods nomenclature
> HOTT-2381: Adds goods nomenclature item id and sid to search references

- db/migrate/20230203090107_tweak_footnote_type_id_field_length.rb
- db/structure.sql
https://transformuk.atlassian.net/browse/HOTT-2623
- You can't alter the underlying table of a view so we needed to drop and recreate these
> HOTT-2623: Alter footnote type id field to support 3 chars

- app/controllers/api/admin/headings_controller.rb
- app/models/commodity.rb
- app/models/goods_nomenclature.rb
- app/models/search_reference.rb
- app/presenters/api/admin/headings/commodity_presenter.rb
- app/presenters/api/admin/headings/heading_presenter.rb
- app/serializers/api/admin/headings/commodity_serializer.rb
- app/serializers/api/admin/headings/heading_serializer.rb
- app/serializers/api/admin/search_references/chapter_serializer.rb
- app/serializers/api/admin/search_references/commodity_serializer.rb
- app/serializers/api/admin/search_references/heading_serializer.rb
- app/serializers/api/admin/search_references/subheading_serializer.rb
- db/migrate/20230202192506_adds_index_to_search_references.rb
- db/structure.sql
- spec/factories/goods_nomenclature_factory.rb
- spec/models/goods_nomenclature_spec.rb
- spec/models/search_reference_spec.rb
- spec/presenters/api/admin/headings/commodity_presenter_spec.rb
- spec/presenters/api/admin/headings/heading_presenter_spec.rb
- spec/serializers/api/admin/headings/commodity_serializer_spec.rb
- spec/serializers/api/admin/headings/heading_serializer_spec.rb
https://transformuk.atlassian.net/browse/HOTT-2381
- This was previously taking 10 or more seconds on some headings
> HOTT-2381: Use populated goods nomenclature sid values

- app/presenters/api/v2/measures/measure_presenter.rb
- app/serializers/api/v2/measures/duty_expression_serializer.rb
- spec/presenters/api/v2/measures/measure_presenter_spec.rb
- spec/serializers/api/v2/duty_expression_serializer_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1945
- This is required to fix a bug in the serialization of measures noticed by the regression suite
> HOTT-1945: Fix handling of duty expression

- app/models/beta/search/open_search_result.rb
- app/models/search_reference.rb
- app/serializers/api/beta/search_result_serializer.rb
- spec/factories/search_result_factory.rb
- spec/fixtures/beta/search/goods_nomenclatures/serialized_result.json
- spec/models/beta/search/open_search_result_spec.rb
- spec/models/search_reference_spec.rb
- spec/requests/api/beta/search_controller_spec.rb
- spec/serializers/api/beta/search_result_serializer_spec.rb
https://github.com/trade-tariff/trade-tariff-backend/pull/1067
- This is no longer how we do redirecting
> HOTT-2393: Cleanup old redirecting behaviour

- app/lib/custom_regex.rb
- app/services/chemical_search_service.rb
- app/services/search_service.rb
- spec/lib/custom_regex_spec.rb
- spec/serializers/search/goods_nomenclature_serializer_spec.rb
- spec/services/heading_service/cached_heading_service_spec.rb
https://transformuk.atlassian.net/browse/HOTT-2687
https://transformuk.atlassian.net/browse/HOTT-2693
- These tests were failing
> HOTT-2687: Fixes flaky tests after updates to factories

- app/services/cached_subheading_service.rb
- spec/fixtures/cached_subheading_exhaustive_annotated.json
- spec/serializers/api/v2/subheadings/subheading_serializer_spec.rb
https://transformuk.atlassian.net/browse/HOTT-2719
- This is a cause of a live issue in the subheadings UI
> HOTT-2719: Surface additional codes for overview measures on subheadings

- db/data_migrations/20230227101311_nan_fix.rb
https://transformuk.atlassian.net/browse/HOTT-2704
> HOTT-2704: Update descriptions from nan to the EU description

- app/models/goods_nomenclature_group.rb
- app/models/goods_nomenclature_group_description.rb
- app/models/nomenclature_group_membership.rb
https://transformuk.atlassian.net/browse/HOTT-2744
- This was missed and was a mistake
> HOTT-2744: Fix missing entities for the EU service

- config/opensearch/synonyms_all.txt
https://transformuk.atlassian.net/browse/HOTT-2746
- To prove multiword support
> HOTT-2746: Fixes cherry tomatoes once and for all

- config/sidekiq.yml
https://transformuk.atlassian.net/browse/HOTT-2703
- This is stopping this worker from running
> HOTT-2703: Fixes typo in worker schedule

- bin/sync_opensearch_packages
https://transformuk.atlassian.net/browse/HOTT-2775
- This sometimes leads to a failure condition when associating packages
> HOTT-2775: Handle delay in package becoming active

- app/elastic_search_indexes/search/goods_nomenclature_index.rb
- spec/elastic_search_indexes/search/goods_nomenclature_index_spec.rb
https://transformuk.atlassian.net/browse/HOTT-2775
- This fixes a bug with the synonym filters handling of the filter chain
> HOTT-2775: Promote the synonym positioning in the filter chain

- app/services/heading_service/heading_serialization_service.rb
- app/services/heading_service/serialization/declarable_service.rb
- app/services/heading_service/serialization/nondeclarable_service.rb
HOTT-2643
- I'll be adding a separate serialization service for the non-declarable nested set path and this change is an extraction from that branch to ease code review.
- Changes implementation of a key endpoint
> HOTT-2643 Refactor Heading serializers

- app/controllers/api/v2/goods_nomenclatures_controller.rb
HOTT-2941
- It will allow effeciently determining things like `declarable?` values which is needed for later tickets
- Changes headings output to not include the 'grouping' parent heading - this appears to be a bug in the existing implementation though
> HOTT-2941 Use nested set for GoodsNomenclature CSV endpoints

- db/migrate/20230411105850_create_table_full_chemicals.rb
- db/migrate/20230411140112_adds_type_and_priority_to_search_suggestions.rb
- db/structure.sql
https://transformuk.atlassian.net/browse/HOTT-3031
- These are needed to augment search
> HOTT-3031: Migrations: adds full chemicals and search suggestion adjustments

- config/initializers/use_search_path_to_dump_structure_sql.rb
https://transformuk.atlassian.net/browse/HOTT-3031
- This is required to fix an issue running this initializer in development
> HOTT-3031: Fixes issue with initializer requires

- db/data_migrations/20230417130051_show_98.rb
https://transformuk.atlassian.net/browse/HOTT-3041
- This is an urgent requirement that has just come in
> HOTT-3041: Show all of chapter 98

- app/services/search_service/exact_search.rb
- spec/services/search_service_spec.rb
https://transformuk.atlassian.net/browse/HOTT-3044
- This is required so that suggestions redirect the user properly to the right goods nomenclature for new chemicals
> HOTT-3044: Enable legacy search to lookup all known CAS numbers

- app/elastic_search_indexes/search/goods_nomenclature_index.rb
- app/models/goods_nomenclature.rb
- app/models/search_suggestion.rb
https://transformuk.atlassian.net/browse/HOTT-3095
- This was missed in previous review
> HOTT-3095: Improve goods nomenclature querying on suggestions

- spec/support/elasticsearch.rb
HOTT-????
- Personal frustation - ElasticSearch is slow to open its socket after being started - this change allows rspec to retry the connection for 30 seconds rather then me swapping to another screen, coming back 5 minutes later only to find yet again ES wasn't ready and RSpec crashed out right at the start :wink: 
- Safe, only changes how test suite starts
> Fix elasticsearch connection issues

- app/controllers/api/v2/chemicals_controller.rb
HOTT-???
- Drops query count from 1600 to 2
- Low
> Eager load chemicals

- app/models/goods_nomenclatures/nested_set.rb
- docs/goods-nomenclature-nested-set.md
HOTT-2926
- So other developers can benefit from this functionality
- None, pure documentation change
> HOTT-2926 Added docs for working with Nested Set

- app/workers/report_worker.rb
- spec/workers/report_worker_spec.rb
https://transformuk.atlassian.net/browse/HOTT-3177
> HOTT-3177: Enable trade groups report

- app/lib/reporting/prohibitions.rb
- app/workers/report_worker.rb
- spec/lib/reporting/prohibitions_spec.rb
- spec/workers/report_worker_spec.rb
https://transformuk.atlassian.net/browse/HOTT-3175
- This is part of a new suite of reports that Matt produces locally and that need to be productionised
> HOTT-3175: Generate a prohibitions report

- db/data_migrations/20230522102427_kill_broken_balance_events.rb
https://transformuk.atlassian.net/browse/HOTT-3149
> HOTT-3149: Fixes quota definition initial volumes

- app/models/measure_component.rb
- app/serializers/api/v2/measures/measure_component_serializer.rb
- app/serializers/api/v2/measures/measurement_unit_qualifier_serializer.rb
- app/services/cached_commodity_service.rb
- app/services/concerns/declarable_serialization.rb
- app/services/heading_service/serialization/declarable_service.rb
- spec/factories/measurement_unit_qualifier_factory.rb
- spec/serializers/api/v2/measures/measure_component_serializer_spec.rb
- spec/serializers/api/v2/measures/measurement_unit_qualifier_serializer_spec.rb
https://transformuk.atlassian.net/browse/HOTT-3238
- This is needed to properly present measure components in the frontend
> HOTT-3238: Surface measure component qualifiers

- db/rules_of_origin/roo_schemes_uk/fta_intro/dcts-general-enhanced.md
- db/rules_of_origin/roo_schemes_uk/fta_intro/dcts-ldcs.md
HOTT-3242
- We'll need these when we add the DCTS scheme in the next couple of weeks
- Low
> HOTT-3242 Added DCTS FTA Intro files

- app/lib/reporting/differences.rb
- app/lib/reporting/differences/indentation.rb
https://transformuk.atlassian.net/browse/HOTT-3253
- this is one of many worksheets needed for differences report
> HOTT-3253: Indentation worksheet

- app/lib/reporting/differences.rb
- app/lib/reporting/differences/endline.rb
- app/lib/reporting/differences/goods_nomenclature.rb
https://transformuk.atlassian.net/browse/HOTT-3255
- This is part of ongoing work to produce the workbook for differences
- These styles are common to all worksheets
> HOTT-3255: Adds endline differences worksheet

- app/lib/reporting/differences.rb
- app/lib/reporting/differences/endline.rb
- app/lib/reporting/differences/goods_nomenclature.rb
- app/lib/reporting/differences/goods_nomenclature_end_date.rb
- app/lib/reporting/differences/goods_nomenclature_start_date.rb
https://transformuk.atlassian.net/browse/HOTT-3256
https://transformuk.atlassian.net/browse/HOTT-3257
> HOTT-3255: Adds start date and end date differences worksheets

- db/rules_of_origin/roo_schemes_uk/introductory_notes/dcts-general-enhanced_intro.md
- db/rules_of_origin/roo_schemes_uk/introductory_notes/dcts-ldcs_intro.md
HOTT-3243
- We will require them when we add the DCTS markdown scheme in the next couple of weeks
- None
> HOTT-3243 Add DCTS introductory notes

- app/lib/reporting/differences.rb
- app/lib/reporting/differences/goods_nomenclature_end_date.rb
- app/lib/reporting/differences/goods_nomenclature_start_date.rb
- app/lib/reporting/differences/mfn_missing.rb
https://transformuk.atlassian.net/browse/HOTT-3258
> HOTT-3258: Adds missing mfns worksheet

- app/lib/reporting/differences.rb
https://transformuk.atlassian.net/browse/HOTT-3258
- This was missed in the previous code review
> HOTT-3258: Enhance differences mfn worksheet

- app/lib/reporting/differences.rb
- app/lib/reporting/differences/mfn_duplicated.rb
https://transformuk.atlassian.net/browse/HOTT-3259
> HOTT-3259: Adds duplicated mfn worksheet

- db/rules_of_origin/roo_schemes_uk/articles/dcts-general-enhanced/accessories.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-general-enhanced/cumulation-export.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-general-enhanced/cumulation-import.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-general-enhanced/insufficient-processing.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-general-enhanced/neutral-elements.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-general-enhanced/non-alteration.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-general-enhanced/origin_processes.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-general-enhanced/originating_export.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-general-enhanced/originating_import.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-general-enhanced/packaging.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-general-enhanced/sets.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-general-enhanced/tolerances.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-general-enhanced/verification.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-general-enhanced/wholly-obtained.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-ldcs/accessories.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-ldcs/cumulation-export.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-ldcs/cumulation-import.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-ldcs/insufficient-processing.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-ldcs/neutral-elements.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-ldcs/non-alteration.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-ldcs/origin_processes.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-ldcs/originating_export.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-ldcs/originating_import.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-ldcs/packaging.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-ldcs/sets.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-ldcs/tolerances.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-ldcs/verification.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-ldcs/wholly-obtained.md
https://transformuk.atlassian.net/browse/HOTT-3290
- We need to display these in rules of origin journeys on the frontend
> HOTT-3290: Articles for DCTS

- db/rules_of_origin/roo_schemes_uk/rule_sets/dcts-general-enhanced.json
- db/rules_of_origin/roo_schemes_uk/rule_sets/dcts-ldcs.json
https://transformuk.atlassian.net/browse/HOTT-3279
- We need to access the data in these files on the backend API and frontend
> HOTT-3279: Added rule set documents

- app/workers/generate_goods_nomenclatures_csv_report_worker.rb
https://transformuk.atlassian.net/browse/HOTT-3301
- This is required to make sure that we are showing chapter differences in other reports
> HOTT-3301: Adds chapters to commodities csv

- app/lib/reporting/differences.rb
- app/lib/reporting/differences/misapplied_action_code.rb
https://transformuk.atlassian.net/browse/HOTT-3260
> HOTT-3260: Adds misapplied action codes worksheet

- app/lib/reporting/differences.rb
- app/lib/reporting/differences/incomplete_measure_condition.rb
https://transformuk.atlassian.net/browse/HOTT-3261
> HOTT-3261: Adds incomplete measure conditions worksheet

- db/rules_of_origin/roo_schemes_uk/articles/dcts-general-enhanced/verification.md
- db/rules_of_origin/roo_schemes_uk/articles/dcts-ldcs/verification.md
https://transformuk.atlassian.net/browse/HOTT-3290
- articles were displaying incorrectly
> HOTT-3290: Fixed bullets in RoO articles

- app/lib/time_machine.rb
- app/models/goods_nomenclatures/nested_set.rb
- spec/models/commodity_spec.rb
- spec/models/goods_nomenclatures/nested_set_spec.rb
- spec/models/goods_nomenclatures/tree_node_spec.rb
- spec/models/measure_spec.rb
- spec/models/meursing_measure_spec.rb
- spec/models/quota_definition_spec.rb
- spec/rails_helper.rb
- spec/services/search_service_spec.rb
- spec/unit/time_machine_spec.rb
Reverts trade-tariff/trade-tariff-backend#1279
Turns out search is using these methods outside of time machine
> Revert "HOTT-3284 Raise if using NestedSet outside TimeMachine"

- app/lib/reporting/differences.rb
- app/lib/reporting/differences/omitted_duty_measures.rb
https://transformuk.atlassian.net/browse/HOTT-3263
> HOTT-3263: Adds omitted duties worksheet

- app/lib/reporting/differences.rb
- app/lib/reporting/differences/missing_vat_measure.rb
https://transformuk.atlassian.net/browse/HOTT-3264
> HOTT-3264: Adds missing vat measure worksheet

- app/models/rules_of_origin/scheme.rb
- app/serializers/api/v2/rules_of_origin/full_scheme_serializer.rb
- db/rules_of_origin/roo_schemes_uk.json
- spec/models/rules_of_origin/scheme_spec.rb
- spec/serializers/api/v2/rules_of_origin/full_scheme_serializer_spec.rb
HOTT-3305
- We want to expose this information on the frontend
- Low
> HOTT-3305 CDS proof rules on Rules of Origin schemes

- app/elastic_search_indexes/search/goods_nomenclature_index.rb
- app/models/goods_nomenclature.rb
- app/serializers/search/goods_nomenclature_serializer.rb
- spec/elastic_search_indexes/search/goods_nomenclature_index_spec.rb
https://transformuk.atlassian.net/browse/HOTT-3372
- This speeds up the implementation significantly (c 280 seconds to c 40 seconds) and reduces the impact of a reindex on the postgres service
> HOTT-3372: Refactor beta search indexer

- app/models/geographical_area.rb
- app/models/measure.rb
- app/models/preference_code.rb
- spec/factories/geographical_area_factory.rb
- spec/models/geographical_area_spec.rb
https://transformuk.atlassian.net/browse/HOTT-3344
- We need to use these to calculate preference codes
> HOTT-3344: Preference codes DCTS

- app/models/chapter.rb
- app/models/concerns/declarable.rb
- app/models/goods_nomenclature.rb
- app/models/section.rb
- app/serializers/api/v2/chapters/chapter_serializer.rb
- app/serializers/api/v2/sections/section_serializer.rb
- app/serializers/api/v2/subheadings/subheading_serializer.rb
- spec/controllers/api/v2/chapters_controller_spec.rb
- spec/controllers/api/v2/sections_controller_spec.rb
- spec/fixtures/cached_subheading_exhaustive_annotated.json
- spec/serializers/api/v2/subheadings/subheading_serializer_spec.rb
https://transformuk.atlassian.net/browse/HOTT-3319
- page titles contained unwanted characters
> HOTT-3319: XI title bug fix BE

- db/rules_of_origin/roo_schemes_uk.json
HOTT-<TODO>
- We want to provide this additional information to our users
- Low
> HOTT-3421 Updated Rules of Origin UK schemes file

- db/rules_of_origin/roo_schemes_uk/proofs/dcts-general-enhanced/gsp-form-a.md
- db/rules_of_origin/roo_schemes_uk/proofs/dcts-general-enhanced/origin-declaration.md
- db/rules_of_origin/roo_schemes_uk/proofs/dcts-ldc/gsp-form-a.md
- db/rules_of_origin/roo_schemes_uk/proofs/dcts-ldc/origin-declaration.md
HOTT-3428
- We wish to show this additional content to our users
- Low
> HOTT-3428 Added proofs documents for dcts schemes

- app/lib/time_machine.rb
- app/models/goods_nomenclatures/nested_set.rb
- spec/models/commodity_spec.rb
- spec/models/goods_nomenclatures/nested_set_spec.rb
- spec/models/goods_nomenclatures/tree_node_spec.rb
- spec/models/measure_spec.rb
- spec/models/meursing_measure_spec.rb
- spec/models/quota_definition_spec.rb
- spec/rails_helper.rb
- spec/services/search_service_spec.rb
- spec/unit/time_machine_spec.rb
Reverts trade-tariff/trade-tariff-backend#1293
> Revert "Revert "HOTT-3284 Raise if using NestedSet outside TimeMachine""

- db/rules_of_origin/roo_schemes_uk/fta_intro/dcts-general-enhanced.md
- db/rules_of_origin/roo_schemes_uk/fta_intro/dcts-ldcs.md
HOTT-3425
- There is additional information available which will be beneficial to our users
- Low
> HOTT-3425 Added replacment fta intro files

- app/lib/changes_table_populator/commodity_code_description_changed.rb
- app/lib/changes_table_populator/commodity_code_end_dated.rb
- app/lib/changes_table_populator/commodity_code_started.rb
- app/lib/changes_table_populator/descendant_populator.rb
- app/lib/changes_table_populator/importer.rb
- app/lib/changes_table_populator/measure_created_or_updated.rb
- app/lib/changes_table_populator/measure_deleted.rb
- app/lib/changes_table_populator/measure_end_dated.rb
- app/lib/changes_table_populator/measure_started.rb
HOTT-2913
- The logic was overly complicated and could be simplified.
- The new implementation handles querying future goods nomenclatures better
- Reduce code duplication and improve readability to aid future development
- Modifies logic for the changes api
> HOTT-2913 Amend dates used for calculating descendants

- lib/tasks/exchange_rates.rake
https://transformuk.atlassian.net/browse/HOTT-3472
- This will make it easier to run the exchange rates tasks
> HOTT-3472: Added exchange rates rake tasks

- app/lib/trade_tariff_backend.rb
- config/sidekiq.yml
BAU
- Try to fix worker deployment issues
> BAU: Debug rails constant

- app/lib/reporting/bulk_search.rb
- app/services/bulk_search/report_generator_service.rb
https://transformuk.atlassian.net/browse/HOTT-3447
- This is required to handover to HMRC a worksheet for review.
> HOTT-3447: Bulk search reporting

- app/elastic_search_indexes/concerns/point_in_time_index.rb
- app/elastic_search_indexes/search/bulk_search_index.rb
- app/workers/build_index_by_heading_worker.rb
https://transformuk.atlassian.net/browse/HOTT-3532
- This is required to divide the work to construct bulk indexes
> HOTT-3547: Adds by heading async worker

- app/models/goods_nomenclature.rb
- app/models/goods_nomenclature_description.rb
- app/serializers/api/v2/headings/heading_serializer.rb
- spec/models/goods_nomenclature_description_spec.rb
- spec/serializers/api/v2/csv/commodity_serializer_spec.rb
- spec/serializers/api/v2/headings/heading_serializer_spec.rb
[HOTT-3521](https://transformuk.atlassian.net/browse/HOTT-3521)
> Ensure description_plain is capitalized and heading serializer has description_plain

- app/services/search_service/exact_search.rb
HOTT-3571
- The last date valid if it is historical
- The first date valid if it is in the future
- The as_of search date if it is current
- Previously this would look for any children at all points in time, this meant if a GoodsNomenclature had ever been a Subheading the it would always be treated as a Subheading. This was true even if a the point of search it was now a Commodity
- Changes behaviour of the ExactSearch class
> HOTT-3571 Check for Commodity vs Subheading using appropriate date

- docs/rules_of_origin.md
HOTT-3522
- It did not cover many of the more recent changes
- It will aid new developers working on these areas
- None, purely documentation change
> HOTT-3522 Updated Rules Of Origin documentation

- app/controllers/healthcheck_controller.rb
- app/models/healthcheck.rb
- config/routes.rb
BAU
- This is for ECS to essentially bring up the new tasks
> BAU: Adds healthcheckz for ECS

- app/models/concerns/componentable.rb
- app/models/measure_component.rb
- app/models/measure_condition_component.rb
https://transformuk.atlassian.net/browse/HOTT-3641
- This is required to make changes in one place and to simplify a duplicated api
- **This is a non-functional refactor**
> HOTT-3641: Extract shared component behaviour into concern

- app/models/concerns/componentable.rb
- app/models/measure_component.rb
- app/models/measure_condition_component.rb
- app/serializers/api/v2/measures/measure_condition_component_serializer.rb
- db/measurement_units_20220825.json
HOTT-3641
- SPQ is required to show SPQ units in measure conditions
> HOTT-3641: Adds missing SPQ unit and simplify components

- app/models/measure_condition.rb
- app/models/measurement_unit.rb
- db/measurement_units.json
- spec/factories/measure_condition_factory.rb
- spec/models/measure_condition_spec.rb
- spec/models/measurement_unit_spec.rb
- spec/services/measure_unit_service_spec.rb
https://transformuk.atlassian.net/browse/HOTT-3698
- This is needed for the presentation of excise condition requirements in the frontend
> HOTT-3698: Support presentation of percentage ABV requirement

- .env.test
- app/models/measure.rb
- app/presenters/api/v2/measures/measure_condition_component_presenter.rb
- app/presenters/api/v2/measures/measure_condition_presenter.rb
- spec/factories/measure_factory.rb
- spec/models/measure_spec.rb
- spec/presenters/api/v2/measures/measure_condition_component_presenter_spec.rb
- spec/presenters/api/v2/measures/measure_condition_presenter_spec.rb
BAU
- This is required since we're not showing these display adjustments in production and we should be
> BAU: Fixes bug in conditional display of alcohol duties

- app/controllers/api/admin/chapters_controller.rb
- app/services/find_ancestors_service.rb
- app/services/validity_period_serializer_service.rb
- spec/controllers/api/v2/chapters_controller_spec.rb
- spec/models/commodity_spec.rb
- spec/models/heading_spec.rb
- spec/services/find_ancestors_service_spec.rb
BAU
- This is required as part of the nested set migration
> BAU: Fixes broken admin chapter id reference

- app/services/certificate_finder_service.rb
- spec/services/certificate_finder_service_spec.rb
> BAU: Fixes code/type ordering in test

- db/migrate/20230808103253_adds_footnote_indexes.rb
- db/structure.sql
https://transformuk.atlassian.net/browse/HOTT-3755
- This is required to enable efficient filtering on these fields
> HOTT-3755: Adds footnote search indexes

- .circleci/config.yml
BAU
- These were commented out to speed up workflows when creating ECS task definitions
> BAU: Reinstate tests

- terraform/worker_uk.tf
- terraform/worker_xi.tf
HOTT-3788
I have added:
- Migration off gov.uk PaaS
> HOTT-3788 - Create ECS Service (worker)

- db/structure.sql
- docker-compose.yml
> *DEV-TASK* Update docker-compose file

- app/services/exchange_rates/create_old_files_service.rb
- lib/tasks/exchange_rates.rake
- spec/services/exchange_rates/create_old_files_service_spec.rb
> HOTT-3705: Create rake task to create old files for previous data

- app/formatters/spq_duty_expression_formatter.rb
- app/presenters/api/v2/measures/measure_condition_presenter.rb
- spec/formatters/spq_duty_expression_formatter_spec.rb
- spec/presenters/api/v2/measures/measure_condition_presenter_spec.rb
https://transformuk.atlassian.net/browse/HOTT-3795
- This is required as a special case which only applies to SPQ/excise measures
> HOTT-3795: Adjust SPQ presentation in our api

- .circleci/config.yml
- db/migrate/20230824155416_add_unique_key_for_files.rb
- db/structure.sql
- spec/models/exchange_rates/period_spec.rb
BAU
- This is required to make sure we're not creating duplicate file records
> BAU: Adds unique file index

- app/controllers/api/v2/bulk_searches_controller.rb
- spec/requests/api/v2/bulk_searches_controller_spec.rb
https://transformuk.atlassian.net/browse/HOTT-3672
- This is required to match the frontend routing
> HOTT-3672: Resolve location to be via frontend

- app/mailers/exchange_rates_mailer.rb
https://transformuk.atlassian.net/browse/HOTT-3947
-  We sometimes need to call the mailer manually and need to pass a date
> HOTT-3947: Make date passable for manual running and testing

- terraform/README.md
- terraform/backend_uk.tf
- terraform/backend_xi.tf
- terraform/data.tf
- terraform/iam.tf
- terraform/locals.tf
- terraform/worker_uk.tf
- terraform/worker_xi.tf
BAU
- This is needed to be able to persist files as part of daily updates
> BAU: Fixes task role kms key permissions

- app/lib/reporting/differences/quota_exclusion_misalignment.rb
BAU
- This helps us load all mismatched quotas and measures
> BAU: Fixes differences report

- db/rules_of_origin/roo_schemes_uk.json
https://transformuk.atlassian.net/browse/HOTT-3963
- they were missing
> HOTT-3963: Added Rules of origin documents to schemes file on backend

- app/lib/reporting/differences.rb
- app/lib/reporting/differences/bad_quota_association.rb
- app/lib/reporting/differences/quota_exclusion_misalignment.rb
- app/models/bad_quota_association.rb
- db/migrate/20230921124623_adds_bad_quota_associations.rb
- db/structure.sql
https://transformuk.atlassian.net/browse/HOTT-3267
> HOTT-3267: Adds bad quota associations worksheet

- app/lib/reporting/differences.rb
- app/lib/reporting/differences/measure_quota_coverage.rb
- app/lib/sequel/plugins/time_machine.rb
- app/models/measure.rb
- app/models/quota_definition.rb
- config/initializers/date.rb
- spec/models/measure_spec.rb
- spec/models/quota_definition_spec.rb
https://transformuk.atlassian.net/browse/HOTT-4054
- This is required as part of the differences and anomalies reporting
> HOTT-3266: Adds measure quota coverage worksheet

- app/lib/reporting/differences.rb
- app/lib/reporting/differences/supplementary_unit.rb
- app/lib/reporting/supplementary_units.rb
- app/workers/report_worker.rb
- spec/workers/report_worker_spec.rb
https://transformuk.atlassian.net/browse/HOTT-3269
https://transformuk.atlassian.net/browse/HOTT-3270
- This is part of the differences and anomalies reporting
> HOTT-3269: Adds supplementary source and worksheet

- app/lib/reporting/differences.rb
- app/lib/reporting/differences/me16.rb
https://transformuk.atlassian.net/browse/HOTT-3273
- This is used to determine when there are duplicate measures of the same type/geographical area with and without additional codes
> HOTT-3273: Adds me16 worksheet

- app/models/exchange_rate_country_currency.rb
- db/data_migrations/20231004142615_populate_country_currencies.rb
https://transformuk.atlassian.net/browse/HOTT-4023
- This is needed to make sure we can surface exchange rates
> HOTT-4023: Populate day zero exchange_rate_countries_currencies

- app/controllers/api/v2/exchange_rates/period_lists_controller.rb
- spec/requests/api/v2/exchange_rates/period_lists_controller_spec.rb
> BAU: Handle missing periods

- db/data_migrations/20231025075701_quota_critical_fix.rb
https://transformuk.atlassian.net/browse/HOTT-4228
> HOTT-4228: Quota critical fix

- app/lib/reporting/differences.rb
- app/lib/reporting/differences/bad_quota_association.rb
- app/lib/reporting/differences/candidate_supplementary_unit.rb
- app/lib/reporting/differences/endline.rb
- app/lib/reporting/differences/goods_nomenclature.rb
- app/lib/reporting/differences/goods_nomenclature_end_date.rb
- app/lib/reporting/differences/goods_nomenclature_start_date.rb
- app/lib/reporting/differences/hierarchy.rb
- app/lib/reporting/differences/incomplete_measure_condition.rb
- app/lib/reporting/differences/indentation.rb
- app/lib/reporting/differences/me16.rb
- app/lib/reporting/differences/me32.rb
- app/lib/reporting/differences/mfn_duplicated.rb
- app/lib/reporting/differences/mfn_missing.rb
- app/lib/reporting/differences/misapplied_action_code.rb
- app/lib/reporting/differences/missing_vat_measure.rb
- app/lib/reporting/differences/omitted_duty_measures.rb
- app/lib/reporting/differences/quota_exclusion_misalignment.rb
- app/lib/reporting/differences/quota_missing_origin.rb
- app/lib/reporting/differences/supplementary_unit.rb
- app/models/goods_nomenclature.rb
- spec/models/goods_nomenclature_spec.rb
BAU
- This is a result of a review/comparison with the files Matt automatically generates
> BAU: Differences reporting tweaks

- config/database.yml
- terraform/locals.tf
> BAU: Removes merged databases feature flag

- docs/exchange_rate_average_rates.md
No ticket just a very quick docs update for the exchange rates as the class name changed
> Update docs for the average exchange rate

- app/lib/reporting.rb
BAU
- This is required to make sure that the reporting links work
> BAU: Tweak reporting CDN linkage

- terraform/config_development.tfvars
- terraform/config_staging.tfvars
BAU
[x] Altered the base domain for dev
[x] Altered the base domain for staging
• This is to reflect the settled state of the trade-tariff.service.gov.uk
> BAU: Fixes the base domain for dev and staging

- terraform/locals.tf
BAU
- This should enable integration with the admin api
> BAU: Fixes private network communications to signon

- config/initializers/reporting_bucket.rb
BAU
- This is leading to an uninitialised bucket
> BAU: Fixes reporting credentials when running in ECS

- app/services/exchange_rates/update_currency_rates_service.rb
- db/structure.sql
BAU
- This is required for average rates
> BAU: Only sample country currencies that are active

- terraform/README.md
- terraform/backend_uk.tf
- terraform/iam.tf
- terraform/worker_uk.tf
- terraform/worker_xi.tf
https://transformuk.atlassian.net/browse/HOTT-4326
- This is required for various templated messages
> HOTT-4326: Enable SES permissions

- .circleci/config.yml
- spec/presenters/api/v2/headings/declarable_headings_presenter_spec.rb
Add back in the rubocop step removed in previous PR
> Rubocop all files

- app/controllers/api/v2/search_controller.rb
- app/services/search_service.rb
- app/services/search_service/rogue_search_service.rb
This PR avoids searching for certain terms that we dont want to show to the user and currently returns a nill search for for iterations of gifts.
> Add simple class for avoiding searching for eroneous terms

- app/services/search_service/rogue_search_service.rb
- spec/services/search_service/rogue_search_service_spec.rb
> Add support for lowercase terms and tests

- app/controllers/api/admin/search_references_base_controller.rb
- spec/support/shared_examples/v2_search_reference_controller_examples.rb
https://transformuk.atlassian.net/browse/HOTT-4436
> HOTT-4436: Adds handling for XLS formulas

- terraform/backend_uk.tf
- terraform/backend_xi.tf
- terraform/config_production.tfvars
- terraform/data.tf
- terraform/iam.tf
- terraform/locals.tf
- terraform/worker_uk.tf
- terraform/worker_xi.tf
BAU
- This is currently incorrect/pointing to the old test domain
> BAU: Update base domain

- terraform/README.md
- terraform/data.tf
- terraform/iam.tf
- terraform/locals.tf
BAU
- This is required to enable exchange rate automation in the new world
> BAU: Adds XE api configuration

- terraform/README.md
- terraform/config_development.tfvars
- terraform/config_production.tfvars
- terraform/config_staging.tfvars
- terraform/locals.tf
- terraform/variables.tf
BAU
- This now reflects current production/supports a different frontend host (e.g. www)
- It also adds a missing email address needed to send CSV files of exchange rates to HMRC
> BAU: Fix production configuration

- config/initializers/appendix_5a_guidance_bucket.rb
> BAU: Fixes appendix 5a configuration in ECS

- terraform/config_production.tfvars
> BAU: Adds final production base domain

- .circleci/config.yml
https://transformuk.atlassian.net/browse/HOTT-4597
> HOTT-4597: Update smoketest context

- .circleci/config.yml
https://transformuk.atlassian.net/browse/HOTT-4597
- This isn't needed
> HOTT-4597: Remove trade-tariff context

- spec/services/exchange_rates/upload_file_service_spec.rb
- terraform/config_production.tfvars
BAU
- Chris has validated/is comfortable with this behaviour now and we want to go live with these enhancements
> BAU: Enable legacy search in production

- app/models/green_lanes/categorisation.rb
- spec/models/green_lanes/categorisation_spec.rb
https://transformuk.atlassian.net/browse/HOTT-4351
Add filter for GreenLanes::Categorisation.
> Add filter for GreenLanes::Categorisation.

- .env.development
- Dockerfile
- Makefile
- terraform/locals.tf
https://transformuk.atlassian.net/browse/HOTT-4449
ECS healthchecks are managed separately:
https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_HealthCheck.html
- This is remediation work from our pentest report
> HOTT-4446: Adds HEALTHCHECK

- app/serializers/search/goods_nomenclature_serializer.rb
- spec/serializers/search/goods_nomenclature_serializer_spec.rb
https://transformuk.atlassian.net/browse/HOTT-4949
Fix tests and remove the "flaky" flag from rspec serializers/search/goods_nomenclature_serializer_spec.rb.
> HOTT-4949: Fix tests and remove the "flaky" flag from rspec.

- docs/caching.md
HOTT-4962
- It came up during a retro that there is limited information on this within the team
- Non, just a document
> HOTT-4962 Added document describing our caching

- .pre-commit-config.yaml
- terraform/README.md
- terraform/admin_uk.tf
- terraform/admin_xi.tf
- terraform/backend_uk.tf
- terraform/backend_xi.tf
- terraform/worker_uk.tf
- terraform/worker_xi.tf
Reverts trade-tariff/trade-tariff-backend#1720
> Revert "HOTT-4852: Make deployments depend on workers"

- db/rules_of_origin/roo_schemes_uk/rule_sets/turkey.json
https://transformuk.atlassian.net/browse/HOTT-4686
- Turkey RoO PSRs needed updating
BEFORE
AFTER
> HOTT-4686 Updated Turkey Rule of Origin Product Specific Rules

- db/rules_of_origin/roo_schemes_uk/rule_sets/cameroon.json
https://transformuk.atlassian.net/browse/HOTT-4689
- Cameroon RoO PSRs were incorrect
Test results:
BEFORE
AFTER
> HOTT-4689 Updated Cameroon RoO PSRs

- db/rules_of_origin/roo_schemes_uk/rule_sets/albania.json
https://transformuk.atlassian.net/browse/HOTT-4687
- Albania RoO rules were out of date.
Test results:
BEFORE
AFTER
> HOTT-4687 Updated RoO PSRs for Albania

- db/rules_of_origin/roo_schemes_uk/rule_sets/cariforum.json
https://transformuk.atlassian.net/browse/HOTT-4690
- Cariforum RoO PSRs were out of date
Test results:
BEFORE
AFTER
> HOTT-4690 Update Cariforum RoO PSRs

- db/rules_of_origin/roo_schemes_uk/rule_sets/chile.json
https://transformuk.atlassian.net/browse/HOTT-4692
- Chile Rules of Origin Product Specific Rules are out of date.
Test results with commodity 5208111000
BEFORE
AFTER
> HOTT-4692 Updated Chile RoO PSRs

- db/rules_of_origin/roo_schemes_uk/rule_sets/ghana.json
https://transformuk.atlassian.net/browse/HOTT-4699
- There are some minor changes for the Ghana RoO PSRs
Tested on commodity 9403105100
BEFORE
AFTER
> HOTT-4699 Updated Ghana RoO PSRs

- db/rules_of_origin/roo_schemes_uk/rule_sets/moldova.json
https://transformuk.atlassian.net/browse/HOTT-4706
- There are some minor changes to Moldovas RoO PSRs
Tested on Commodity 3006101000
BEFORE
AFTER
> HOTT-4706 Updated Moldova RoO PSRs

- db/rules_of_origin/roo_schemes_uk/rule_sets/lebanon.json
https://transformuk.atlassian.net/browse/HOTT-4705
- There some formatting errors in Lebanon RoO PSRs
Tested on commodity 3006101000
BEFORE
AFTER
> HOTT-4705 Updated Lebanon RoO PSRs

- db/rules_of_origin/roo_schemes_uk/rule_sets/israel.json
- db/rules_of_origin/roo_schemes_uk/rule_sets/jordan.json
https://transformuk.atlassian.net/browse/HOTT-4702
- Jordan RoO Product Specific Rules had some errors.
Tested on commodity 5208111000
BEFORE
AFTER
> HOTT-4702 Jordan RoO PSRs update

- db/rules_of_origin/roo_schemes_uk/rule_sets/georgia.json
https://transformuk.atlassian.net/browse/HOTT-4698
- There are some formatting changes for Georgia RoO PSRs
Tested on commodity 5007100010
BEFORE
AFTER
> HOTT-4698 Updated Georgia RoO PSRs

- db/rules_of_origin/roo_schemes_uk/rule_sets/morocco.json
https://transformuk.atlassian.net/browse/OTT-56
-  Morocco PSRs need to be updated
> OTT-56: Morocco PSRs

- lib/tasks/green_lanes.rake
GL-145
- We need to import the CategoryAssessments data into the database prior to switching to the database backed version
- Low, just adds a rake task
> GL-145 Added Category Assessment importer

- app/controllers/api/v2/green_lanes/goods_nomenclatures_controller.rb
- app/presenters/api/v2/green_lanes/goods_nomenclature_presenter.rb
- app/serializers/api/v2/green_lanes/goods_nomenclature_serializer.rb
- app/services/green_lanes/fetch_goods_nomenclature_service.rb
- spec/presenters/api/v2/green_lanes/goods_nomenclature_presenter_spec.rb
- spec/serializers/api/v2/green_lanes/goods_nomenclature_serializer_spec.rb
GL-289
- This information may be needed as part of the declaration process
- Low, modifies API on an Epic branch for now
> GL-289 Add descendants to API

- app/controllers/api/v2/green_lanes/goods_nomenclatures_controller.rb
- app/serializers/api/v2/green_lanes/measure_serializer.rb
- spec/serializers/api/v2/green_lanes/measure_serializer_spec.rb
GL-442
- Avoid making breaking changes until we've sought clarification
- Low
> GL-442 Removed entities hanging off CA measures

- db/rules_of_origin/roo_schemes_uk.json
https://transformuk.atlassian.net/browse/OTT-213
I have 
- The Mexico ORD was out of date
BEFORE
AFTER
> OTT-213 Updated Mexico ORD Details

- db/migrate/20240429125446_change_title_limit_in_sections.rb
- db/structure.sql
https://transformuk.atlassian.net/browse/OTT-248
- We need to update a title that is more than 255 characters in length
> OTT-248: Increase section title limit

- db/data_migrations/20240429092532_update_section_iv_title.rb
https://transformuk.atlassian.net/browse/OTT-204
Warning: Do not merge. This must go out in the release after https://transformuk.atlassian.net/browse/OTT-248
- It's outdated
> OTT-204: Updated section IV title

- db/rules_of_origin/roo_schemes_uk.json
https://transformuk.atlassian.net/browse/OTT-217
- The Cote D'Ivoire ORD was out of date
BEFORE
AFTER
> OTT-217 Updated Cote d'Ivoire ORD Details

- db/rules_of_origin/roo_schemes_uk.json
https://transformuk.atlassian.net/browse/OTT-220
- The Albania ORD was out of date
BEFORE
AFTER
> OTT-220 Updated Albania ORD Details

- db/rules_of_origin/roo_schemes_xi.json
https://transformuk.atlassian.net/browse/OTT-45
- it was wrong
> OTT-45 Fix link for EU-Chile Association Link

- db/rules_of_origin/roo_schemes_uk.json
https://transformuk.atlassian.net/browse/OTT-218
- The Ghana ORD was out of date
BEFORE
AFTER
> OTT-218 Updated Ghana ORD Details

- db/rules_of_origin/roo_schemes_uk.json
- db/rules_of_origin/roo_schemes_uk/articles/eu/accessories.md
- db/rules_of_origin/roo_schemes_uk/articles/eu/cumulation-export.md
- db/rules_of_origin/roo_schemes_uk/articles/eu/cumulation-import.md
- db/rules_of_origin/roo_schemes_uk/articles/eu/insufficient-processing.md
- db/rules_of_origin/roo_schemes_uk/articles/eu/neutral-elements.md
- db/rules_of_origin/roo_schemes_uk/articles/eu/non-alteration.md
- db/rules_of_origin/roo_schemes_uk/articles/eu/origin_processes.md
- db/rules_of_origin/roo_schemes_uk/articles/eu/packaging.md
- db/rules_of_origin/roo_schemes_uk/articles/eu/sets.md
- db/rules_of_origin/roo_schemes_uk/articles/eu/tolerances.md
- db/rules_of_origin/roo_schemes_uk/articles/eu/verification.md
- db/rules_of_origin/roo_schemes_uk/articles/eu/wholly-obtained-verbatim.md
- db/rules_of_origin/roo_schemes_uk/articles/eu/wholly-obtained.md
https://transformuk.atlassian.net/browse/OTT-222
- The EU ORD was out of date
- The EU ORD article references were incorrect.
BEFORE
AFTER
> OTT-222 Updated EU ORD Details

- .circleci/config.yml
- .github/pull_request_template.md
BAU
- This is required to consolidate how we do pre-commit stuff
> BAU: Use orb command for pre-commit

- spec/services/green_lanes/permutation_calculator_service_spec.rb
GL-491 
- The code already behaves as expected but added specs to ensure this continues to be the case
- None, just spec changes
> GL-491 Specs verifying tickets described behaviour

- docs/green-lanes.md
GL-481 
- So future developers have some explanation of how this works
- None - only docs changes
> GL-481 Added Green Lanes docs

- db/migrate/20240610160146_update_quota_definitions_oplog_volume.rb
- db/structure.sql
BAU
- This is required to make sure the broken data files can be loaded
- We rely on implicit schema choices set by hierarchical search paths as part of our migration process.
> BAU: Fixes borked migration

- app/models/healthcheck.rb
> BAU: Removes dependency on SQP

- spec/models/healthcheck_spec.rb
> BAU: Revise healthcheck

- app/workers/green_lanes_update_notifications_worker.rb
- terraform/config_development.tfvars
- terraform/config_staging.tfvars
BAU
- We only need this in prod env
> BAU: Switch off GL update email on staging and dev environment

- Gemfile
- Gemfile.lock
- README.md
- config/initializers/rack_attack.rb
- docs/green_lanes_api_keys.md
[GL-919](https://transformuk.atlassian.net/browse/GL-919)
- API need to be protected from heavy load, hence it needs a throtteling mechanism
> GL-919: Implement throttling GL api

- app/lib/reporting/differences.rb
- app/lib/reporting/differences/loaders.rb
- app/lib/reporting/differences/renderers/overview.rb
https://transformuk.atlassian.net/browse/OTT-510
Fixes an issue where data wouldn't show on first run, and also resolves a problem with intersheet linking being in the wrong column
> OTT-510 Solve issue with rendering and fix "View Issues" links

- db/rules_of_origin/roo_schemes_uk/articles/iceland-norway/wholly-obtained.md
https://transformuk.atlassian.net/browse/OTT-272
I have
- to get around the govspeak and css constraints without affecting other FTA’s wholly obtained definitions
NB. This PR is dependant on Front End PR: https://github.com/trade-tariff/trade-tariff-frontend/pull/2054
Before
After
> OTT-272 Fix Numbering for Iceland RoO Wholly Obtained Definition

- db/rules_of_origin/roo_schemes_uk/articles/turkey/accessories.md
- db/rules_of_origin/roo_schemes_uk/articles/turkey/wholly-obtained-vessels.md
https://transformuk.atlassian.net/browse/OTT-274
- it was incorrect
Vessels BEFORE
Accessories BEFORE
Vessels AFTER
Accessories AFTER
> OTT-274 Turkey RoO Numbering Fix

- db/rules_of_origin/roo_schemes_uk/articles/canada/wholly-obtained.md
https://transformuk.atlassian.net/browse/OTT-273
- The numbering and lettering was incorrect
BEFORE
AFTER
> OTT-273 Bullet points inconsistency in ROO - OTT 216 ( Canada)

- db/rules_of_origin/roo_schemes_uk/articles/georgia/cumulation-export.md
- db/rules_of_origin/roo_schemes_uk/articles/georgia/cumulation-import.md
https://transformuk.atlassian.net/browse/OTT-302
Fixes formatting/numbering of Georgia Cumulation ROO
Depends on https://github.com/trade-tariff/trade-tariff-frontend/pull/2059
> OTT-302 Correct Bulleting

- db/rules_of_origin/roo_schemes_uk/articles/dcts-ldcs/origin_processes.md
https://transformuk.atlassian.net/browse/OTT-400
- nothing was showing and HMRC have emailed new guidelines to OTT team
BEFORE
AFTER
> OTT-400 Missing Origin content for DCTS - Comprehensive Preferences.

- .github/pull_request_template.md
BAU: Tickets now start with HMRC instead of OTT
> BAU Update PR template

- Gemfile
- Gemfile.lock
- config/initializers/aws_xray.rb
HMRC-385
I have added AWS X-Ray which should give us plenty more tracing opportunities in production.  No effect on other environments outside AWS.
> HMRC-385  Add AWS X-Ray

- Gemfile
- Gemfile.lock
- config/initializers/sentry.rb
Reverts trade-tariff/trade-tariff-backend#2023
We don't want this anymore
> Revert "HMRC-385 Enable tracing in Senty"

- config/environment.rb
HMRC-398
I have added a clarification on an object path to fix this:
> HMRC-398 Bug Fix

- db/migrate/20241210100900_add_green_lanes_faq_feedback_table.rb
- db/structure.sql
https://transformuk.atlassian.net/browse/HMRC-447
I have added a data migration for Green Lanes FAQ Feedback
I am doing this because migration must be added before the code (see PR https://github.com/trade-tariff/trade-tariff-backend/pull/2047)
> HMRC-447-Green-Lanes-FAQ-Migration

- db/migrate/20250120112727_update_currency_vef_to_ved.rb
HMRC-556
Added the new VED currency
Updated the VEF currency to end validity on the 15th
Added a relationship between VED and Venezuela starting on the 22nd
> HMRC-556 Move VE from VEF to VED currency

- config/database.yml
> Add PGHOST env variable to database configuration

- db/migrate/20250128110215_update_diacritics_in_currencies.rb
HMRC-614
Updated currencies with diacritics as per ticket.
> HMRC-614 Remove diacritics from VED

- config/initializers/rack_timeout.rb
- terraform/locals.tf
Reverts trade-tariff/trade-tariff-backend#2096
> Revert "HMRC-635 Fix Rack Timeout timeouts to protect app"

- Gemfile
- Gemfile.lock
> BAU: Explicitly add ses gem

- app/engines/v2_api.rb
- config/routes.rb
BAU
- This enables devs to know what has been deployed in our environments
> BAU: Make healthcheck globally accessible

- Gemfile
- Gemfile.lock
- config/environments/production.rb
BAU
- Adds aws-actionmailer-ses
- Configure ses provider
- SES stopped working after aws-sdk-rails separated out specific subparts into separate gems
> BAU: SES V2 configuration

- app/middleware/handle_goods_nomenclature.rb
- config/application.rb
- spec/middleware/handle_goods_nomenclature_spec.rb
BAU
- This is needed to fix some of the 404 responses we were getting in the backend sentry alerts and was discovered when I was investigating the failing paths
> BAU: Handle path rewrites on chapters/headings hitting the commodities

- Gemfile
- Gemfile.lock
- config/initializers/aws_xray.rb
BAU
- This is logging 1000s of warnings and makes debugging a smidge harder in ECS
> BAU: Removes xray

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/lib/cds_importer/record_inserter.rb
- app/lib/green_lanes_updates_publisher/mailer.rb
- app/lib/roman_numerals/converter.rb
- app/lib/sequel/plugins/oplog.rb
- app/lib/taric_synchronizer.rb
- app/models/data_migration.rb
- app/models/tradeset_description.rb
- app/serializers/api/v2/search_suggestion_serializer.rb
- app/services/search_service/exact_search.rb
- config/environments/development.rb
- lib/generators/data_migration_generator.rb
- lib/sentry/rails/background_worker.rb
- spec/factories/change_factory.rb
- spec/factories/export_refund_nomenclature_factory.rb
- spec/factories/goods_nomenclature_factory.rb
- spec/factories/hidden_goods_nomenclature_factory.rb
- spec/factories/measure_factory.rb
- spec/models/measure_spec.rb
BAU
- Adds rubocop performance
- Lint with new rules
- I noticed another government project using this and it seems like an easy win
> BAU: Adds rubocop-performance

- .github/pull_request_template.md
> BAU: Update pull_request_template.md

- app/services/elastic_search/query/search_suggestion_query.rb
[HMRC-742](https://transformuk.atlassian.net/browse/HMRC-742)
- Need exact match suggestions over partial match.
> HMRC-742: Suggestions iteration: 'horse' best match is 010121

- app/lib/trade_tariff_backend.rb
- app/services/search_service/fuzzy_search/goods_nomenclature_query.rb
- app/services/search_service/fuzzy_search/reference_query.rb
- config/routes.rb
- spec/services/search_service/fuzzy_search/goods_nomenclature_query_spec.rb
- spec/services/search_service/fuzzy_search/reference_query_spec.rb
- terraform/README.md
- terraform/backend_uk.tf
- terraform/config_development.tfvars
- terraform/config_production.tfvars
- terraform/config_staging.tfvars
- terraform/data.tf
- terraform/iam.tf
- terraform/locals.tf
- terraform/variables.tf
[HMRC-793](https://transformuk.atlassian.net/browse/HMRC-793)
- This has not really been used until we started doing rollbacks to long
long ago
- These feature flags are just unused now
> HMRC-793: Adjust cutoff date of implicit deletes

- .circleci/config.yml
- .pre-commit-config.yaml
- flake.nix
- terraform/.terraform.lock.hcl
[HMRC-765](https://transformuk.atlassian.net/browse/HMRC-765)
- To get value out of these tests early
> HMRC-765: Integrate e2e-tests github workflow

- app/lib/reporting/basic.rb
https://transformuk.atlassian.net/browse/HMRC-265
I have added code to replace whitespace unicode with whitespace in GN description to fix csv to excel conversion
> HMRC-265 Check all reports work

- app/lib/reporting/basic.rb
- app/lib/reporting/commodities.rb
- app/lib/reporting/declarable_duties.rb
- app/lib/reporting/geographical_area_groups.rb
- app/lib/reporting/prohibitions.rb
- app/lib/reporting/supplementary_units.rb
- spec/lib/reporting/basic_spec.rb
- spec/lib/reporting/declarable_duties_spec.rb
- spec/lib/reporting/geographical_area_groups_spec.rb
- spec/lib/reporting/prohibitions_spec.rb
https://transformuk.atlassian.net/browse/HMRC-813
- Reporting classes only currently output to s3
> HMRC-813 Add functionality for local file output for Reporting classes

- app/lib/sequel/plugins/elasticsearch.rb
[HMRC-869](https://transformuk.atlassian.net/browse/HMRC-869)
- This is essentially to speed up loading of the annual file which currently calls out to opensearch 1.0 million times for every-single change to goods nomenclature, etc.
- The cadence for updates doesn't warrant this plugin given we receive this stuff on a daily basis and then do a full reindex.
> HMRC-869: Disable elasticsearch plugin

- config/sidekiq.yml
[HMRC-919](https://transformuk.atlassian.net/browse/HMRC-919)
- Avoid running this job on the weekends for no reason since the cds_guidance.json will be the Friday one.
> HMRC-919 Update RefreshAppendix5a worker

- .github/workflows/deploy-to-staging.yml
> BAU: Fixes missing needs section on the post-deploy step of staging

- flake.nix
- spec/models/goods_nomenclature_spec.rb
- spec/models/measure_spec.rb
BAU
- Fixes flaky order-independent tests
- Bumps my local database version to 17 to match the CI env
> BAU: Fixes some flaky tests

- app/workers/invalidate_cache_worker.rb
[HMRC-979](https://transformuk.atlassian.net/browse/HMRC-979)
- This preserves caches for very very long cached things
> HMRC-979: Invalidate paths that are short medium and long duration

- app/workers/invalidate_cache_worker.rb
BAU
- This is a prerequistite for invalidations
> BAU: Make invalidation reference unique

- db/migrate/20250411114556_create_govuk_notifier_audit.rb
[HMRC-<TODO>](https://transformuk.atlassian.net/browse/HMRC-<TODO>)
-
-
-
> Fix migration to be schema aware

- .github/workflows/ci.yml
- .github/workflows/deploy-to-development.yml
[HMRC-1008](https://transformuk.atlassian.net/browse/HMRC-1008)
- CI HAS to run so tests/linting run before a PR can be merged
> Separated out CI and build/deploy workflows for development

- app/models/public_users/user.rb
- spec/factories/public_users/subscription.rb
- spec/factories/public_users/user.rb
- spec/factories/subscriptions/type.rb
[HMRC-<TODO>](https://transformuk.atlassian.net/browse/HMRC-<TODO>)
-
-
-
> Fix subscription factories

- .github/workflows/deploy-to-production.yml
- .github/workflows/deploy-to-staging.yml
- app/models/exchange_rate_currency_rate.rb
BAU
- We've agreed collectively we're ready for this
> BAU: Enable continuous deployment of the backend

- .github/workflows/ci.yml
BAU
- To simplify our workflow/properly apply hooks
> BAU: Fixes skipped pre-commit hooks

- .github/workflows/ci.yml
- .github/workflows/deploy-to-production.yml
BAU
- This is noise not signal
> BAU: Silence skipped production notifications

- app/workers/stop_press_email_worker.rb
- spec/workers/stop_press_email_worker_spec.rb
[HMRC-1222](https://transformuk.atlassian.net/browse/HMRC-1222)
- Added unsubscribe link to stop press email
To make it easy for subscribers to unsubscribe
> Add unsubscribe link

- app/models/news/item.rb
- spec/models/news/item_spec.rb
Changing format of chapters from space delimited to comma delimited
This is consistent with how they will be written in the Stop Press
> HMRC-1277 Change expected format of chapters

- .github/workflows/replicate-db-development.yml
- .github/workflows/replicate-db-staging.yml
[HMRC-1282](https://transformuk.atlassian.net/browse/HMRC-1282)
- We need to keep staing data changes for MyOTT testing
> HMRC-1282: Temporarily stop replicating the DB from prod to staging

- app/lib/cds_importer.rb
- app/lib/cds_importer/record_inserter.rb
- app/lib/taric_importer.rb
- app/lib/taric_importer/record_processor.rb
- app/lib/tariff_synchronizer/taric_update.rb
- spec/integration/cds_importer/record_inserter_spec.rb
- spec/unit/taric_importer/record_processor_spec.rb
[HMRC-1169](https://transformuk.atlassian.net/browse/HMRC-1169)
- These data not been added for adming UI
> HMRC-1169: Enable insert review in XI

- app/models/search_suggestion.rb
- db/migrate/20250617113942_add_search_suggestion_indexes.rb
- db/structure.sql
[HMRC-1265](https://transformuk.atlassian.net/browse/HMRC-1265)
Add a more efficient query for search suggestions, and add indexes that will help
> HMRC-1265 Optimise search suggestions

- app/views/action_log_mailer/daily_report.text.erb
- app/workers/action_log_report_worker.rb
- spec/workers/action_log_report_worker_spec.rb
[HMRC-1290](https://transformuk.atlassian.net/browse/HMRC-1290)
- Updated date range so that it includes all events from the start of private beta
- Change of requirements
> HMRC-1290 Email all events up to date

- db/migrate/20250620150030_add_geographical_area_materialized_views_fix.rb
- db/structure.sql
[BAU_]
- With UK prefix in sql script for creating materialised view, it doesn't work in XI
> BAU_ : fix geographical area materialised view issue in xi

- .github/workflows/replicate-db-development.yml
- .github/workflows/replicate-db-staging.yml
Reverts trade-tariff/trade-tariff-backend#2323
> Revert "HMRC-1282: Temporarily stop replicating the DB from prod to staging"

- app/helpers/materialize_view_helper.rb
- app/lib/sequel/plugins/oplog.rb
- app/models/additional_code.rb
- app/models/additional_code_description.rb
- app/models/additional_code_description_period.rb
- app/models/additional_code_type.rb
- app/models/additional_code_type_description.rb
- app/models/additional_code_type_measure_type.rb
- app/models/geographical_area.rb
- app/models/geographical_area_description.rb
- app/models/geographical_area_description_period.rb
- app/models/geographical_area_membership.rb
- app/models/measure_excluded_geographical_area.rb
- db/migrate/20250623123926_add_additional_codes_materialized_views.rb
- db/structure.sql
- spec/rails_helper.rb
[HMRC-1317](https://transformuk.atlassian.net/browse/HMRC-1317)
- The change will improve the performance as the base tables hardly ever updated.
> HMRC-1317: Move views to materialized views

- app/models/base_regulation.rb
- app/models/measure.rb
- app/models/modification_regulation.rb
- db/migrate/20250625101149_add_measure_and_regulation_materialized_views.rb
- db/structure.sql
- spec/integration/taric_synchronizer_spec.rb
- spec/models/green_lanes/category_assessment_spec.rb
- spec/presenters/api/v2/green_lanes/category_assessment_presenter_spec.rb
- spec/rails_helper.rb
- spec/services/quota_search_service_spec.rb
- spec/support/matchers/have_rolled_back.rb
- spec/unit/changes_table_populator/measure_created_or_updated_spec.rb
- spec/unit/changes_table_populator/measure_deleted_spec.rb
- spec/unit/changes_table_populator/measure_end_dated_spec.rb
- spec/unit/changes_table_populator/measure_started_spec.rb
- spec/unit/changes_table_populator_spec.rb
[HMRC-1317](https://transformuk.atlassian.net/browse/HMRC-1317)
- The change will improve the performance as the base tables hardly ever updated.
> HMRC-1317: Move views to materialized views - measures and regulations

- .github/workflows/deploy-to-development-full.yml
- .github/workflows/deploy-to-development.yml
[HMRC-1380](https://transformuk.atlassian.net/browse/HMRC-1380)
See https://github.com/trade-tariff/trade-tariff-tools/pull/61
- This enables us to validate a full e2e deployment in development
> HMRC-1380: Adds deploy-full-stack job for e2e validation

- .github/workflows/deploy-to-development-full.yml
[HMRC-1380](https://transformuk.atlassian.net/browse/HMRC-1380)
> HMRC-1380: Simplify references

- app/engines/user_api.rb
- config/routes.rb
- config/routes/user.rb
- spec/controllers/api/user/public_users_controller_spec.rb
- spec/controllers/api/user/subscriptions_controller_spec.rb
[HMRC-1406](https://transformuk.atlassian.net/browse/HMRC-1406)
> HMRC-1406: Small route adjustments

- app/controllers/api/v2/exchange_rates/files_controller.rb
- spec/requests/api/v2/exchange_rates/files_controller_spec.rb
BAU
- 10 shouldn't become 1
- 07 should become 7
> BAU: Fixes bug in month handling

- app/lib/versioned_forwarder.rb
- spec/lib/versioned_forwarder_spec.rb
BAU
- This was getting dropped in the routing regex and needs adding back in
to match the file endpoints correctly
> BAU: Fixes handling of extensions in requests

- app/controllers/api/v2/green_lanes/base_controller.rb
- app/lib/trade_tariff_backend.rb
- config/environments/production.rb
- config/initializers/rack_attack.rb
[HMRC-1489](https://transformuk.atlassian.net/browse/HMRC-1489)
- This gives us an indication of how people are using these APIs
> HMRC-1489: Adds logging of authenticated requests kind

- app/controllers/api/v2/quotas_controller.rb
- app/services/quota_search_service.rb
- spec/services/quota_search_service_spec.rb
[HMRC-1442](https://transformuk.atlassian.net/browse/HMRC-1442)
- Currently quota search count takes lots of time as measure table merge join with quota deffinition. As we have much small quota_order table compared to measures, we can use exist instead of join. So I changed the count query accordingly.
> HMRC-1442: Improve quota search

- app/services/quota_search_service.rb
[HMRC-1442](https://transformuk.atlassian.net/browse/HMRC-1442)
- We changed quota search countquery to use exist instead of joinning quota_definition table. It shows improvement of query time. So I changed the search query as well to addopt the same method.
> HMRC-1442: Improve quota search - update search query

- app/services/delta_report_service.rb
- app/services/delta_report_service/excel_generator.rb
- spec/services/delta_report_service/excel_generator_spec.rb
- spec/services/delta_report_service_spec.rb
- Adds caching of commodity code objects to speed up processing.
- Refactors excel generation to be more organised and use less memory
- Uses date of effect in OTT URL
> Optimize delta report
